### ISSUE TITLE
Lxde reverts back to default icon theme and widget theme after a reboot

### ISSUE THREAD

**Issue by T4P4N** [sdrausty/TermuxArch#101]
![screenshot_2018-07-29-19-53-41-384_com realvnc viewer android](https://user-images.githubusercontent.com/32695903/43367431-5623dd3e-936a-11e8-83e5-6259d214fab5.png)
Before ^
![screenshot_2018-07-29-19-55-42-141_com realvnc viewer android](https://user-images.githubusercontent.com/32695903/43367445-9758bfa4-936a-11e8-9bab-1f38f0a45a1f.png)
After a reboot the lxde reverts back to default icon theme and widget(theme)
I searched for this on Google but didn't found anything useful.

**Comment by T4P4N** [comment]
https://forum.lxde.org/viewtopic.php?t=36652
i found this but it is not working -_-

**Comment by T4P4N** [comment]
![screenshot_2018-07-30-00-04-01-792_com realvnc viewer android](https://user-images.githubusercontent.com/32695903/43369595-b66ba8ba-938e-11e8-8d6a-61ce2f3fd094.png)
Now^ 😊

**Comment by sdrausty** [comment]
@T4P4N Thanks for sharing this information 🔩🔧
