### ISSUE TITLE
Can I start the docker service in the TermuxArch?

### ISSUE THREAD

**Issue by siyuancn** [sdrausty/TermuxArch#102]
I can install the docker using "pacman -S docker",

but I didn't find any way tho start the service.

Is it possible to running the docker on the TermuxArch?

What should I do?

**Comment by sdrausty** [comment]
From https://gitter.im/termux/offtopic


>Can I start the docker service in the TermuxArch?


>Leonid Plyushch

>12:07

>@sdrausty no you can't for the same reason as in Termux: no permission to manage namespaces, no permission to make a low-level configuration of network ifaces, lacking of some cgroups (as I know, android's kernel provides only basic), etc...

If there was a way to get https://github.com/termux/libandroid-shmem to work with TermuxArch, then it might be possible.

**Comment by xeffyr** [comment]
> If there was a way to get https://github.com/termux/libandroid-shmem to work with TermuxArch, then it might be possible.

libandroid-shmem provides only shared memory over Android's ashmem. Missing kernel functionality (like namsespaces) can't be implemented in libraries or proot.

**Comment by xeffyr** [comment]
> @sdrausty Why you need docker ? To run a termux-builder container ? If so - even if docker will be available, you will need x86_64 device so forget about using termux-builder on your arm/aarch64/i686 device.

> https://github.com/termux/libandroid-shmem - this relies on Android's shmem and i'm not sure that it will be possible to compile this against glibc.

> libandroid-shmem does not provide missing functionality of Android kernel. I tried to run docker from real chroot - no success.

-- from gitter

**Comment by sdrausty** [comment]
@xeffyr
> I tried to run docker from real chroot - no success.

Can you send more information about `real chroot`?  In Android [y|n]?

**Comment by sdrausty** [comment]
hi

https://github.com/sdrausty/TermuxArch/issues?q=is%3Aissue+docker


https://github.com/termux/termux-packages/issues?q=is%3Aissue+docker how many of these are on Android?  My guess is none since docker appears not to work in chroot environments, which includes PRoot. 

References:
1) https://duckduckgo.com/?q=docker+chroot
2) https://www.google.com/search?q=docker+chroot

**Comment by sdrausty** [comment]
hi

https://github.com/sdrausty/TermuxArch/issues?q=is%3Aissue+docker


https://github.com/termux/termux-packages/issues?q=is%3Aissue+docker how many of these are on Android?  My guess is none since docker appears not to work in chroot environments, which includes PRoot. 

References:
1) https://duckduckgo.com/?q=docker+chroot
2) https://www.google.com/search?q=docker+chroot

**Comment by xeffyr** [comment]
> Can you send more information about real chroot? In Android [y|n]?

1. https://en.wikipedia.org/wiki/Chroot
2. https://wiki.debian.org/chroot

Generally, to make real chroot you need to have full busybox, e.g. from here: https://play.google.com/store/apps/details?id=stericson.busybox, rooted (!) device and rootfs tarball.

There is application that automates setup of chroot containers: https://play.google.com/store/apps/details?id=ru.meefik.linuxdeploy

It seems that 'chroot' utility is not available in Termux. It should be in package 'busybox' or 'coreutils' but it does not exist in them (https://github.com/termux/termux-packages/blob/master/packages/coreutils/build.sh#L15).

**Comment by sdrausty** [comment]
@siyuancn udocker https://github.com/indigo-dc/udocker/issues/152 installs in Termux https://github.com/termux/termux-packages/issues/2755!

**Comment by SDRausty** [comment]
It appears that what was a "no you can't" might be a;  Wow, it works now!

> find any way to start the service

@petkar shared [[Tip] Workaround to get systemctl commands working on TermuxArch](https://github.com/SDRausty/TermuxArch/issues/239) a couple of days ago, and said:

> Although there were some issues I ran into, I think it's a neat a neat fix. 

This issue https://github.com/termux/termux-packages/issues/2755 has information about `udocker`.

I tried to install termux/package-builder with [`udocker`](https://github.com/indigo-dc/udocker/issues/152) in Arch Linux PRoot:
```
[user07:08udocker]$ udocker pull termux/package-builder
Downloading layer: sha256:692c352adcf2821d6988021248da6b276cb738808f69dcc7bbb74a9c952146f7
Downloading layer: sha256:97058a342707e39028c2597a4306fd3b1a2ebaf5423f8e514428c73fa508960c
Downloading layer: sha256:2821b8e766f41f4f148dc2d378c41d60f3d2cbe6f03b2585dd5653c3873740ef
Downloading layer: sha256:4e643cc37772c094642f3168c56d1fcbcc9a07ecf72dbb5afdc35baf57e8bc29
Downloading layer: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
Downloading layer: sha256:a3ed95caeb02ffe68cdd9fd84406680ae93d633cb16422d00e8a7c22955b46d4
Downloading layer: sha256:53198db09ad729f0f288caa2cfdd0388d52d32008f66d72949e687d5f4ce6c1b
Downloading layer: sha256:d7897a13e2ec9887d2b6974bf0330f4dc839f762f26c6f74d5c4cc9acadc8c5e
Error: in download: curl: (28) Operation timed out after 1800000 milliseconds with 2218816619 out of 2246119365 bytes received

Error: file size mismatch: /home/user/.udocker/layers/sha256:d7897a13e2ec9887d2b6974bf0330f4dc839f762f26c6f74d5c4cc9acadc8c5e 2246119365 -1
Error: no files downloaded
```
You might want to give `udocker` a try.  I [opened an issue about `udocker pull termux/package` error](https://github.com/termux/termux-packages/issues/5565), but look at this:
```
[user07:08udocker]$ udocker images
REPOSITORY
hax4us/package-builder:latest                                .
k8spatterns/curl-jq:latest
```
> Is it possible to run docker in TermuxArch?

It looks like `udocker` runs;  What do you think?

**Comment by petkar** [comment]
Can confirm. udocker does run correctly. One thing to note is that it requires python2.

**Comment by SDRausty** [comment]
please see udocker, it is a potential solution


plz confirm

**Comment by SDRausty** [comment]
ghosted zeffyr killed us

**Comment by SDRausty** [comment]
Ghosted @zeffyr accounts killed us all (open sources and succes).

**Comment by SDRausty** [comment]
Ghosted @zeffyr accounts killed us all slowly (open sources and succes NOT).

**Comment by SDRausty** [comment]
The ghosted @zeffyr accounts killed us all slowly (open sources and succes NOT).

**Comment by SDRausty** [comment]
The ghosted @zeffyr accounts killed us all very slowly (open sources and succes NOT) and it did take up much of our time by consuming!

**Comment by SDRausty** [comment]
The ghosted @zeffyr accounts killed us all (Linux on handheld) very slowly (open sources and succes NOT) and it did take up much of our time by consuming!

**Comment by SDRausty** [comment]
The ghosted @zeffyr accounts killed us all (Linux on handheld) very slowly (open sources and succes NOT), and it did take up much of our time by consuming it!

**Comment by SDRausty** [comment]
poor unghosted @xeffyr account is mum
![Screenshot_20220327-131522](https://user-images.githubusercontent.com/27742457/160292828-07d556db-a250-49be-bdb7-8a06e1c5827b.png)

**Comment by SDRausty** [comment]
Your GitHub account was regained;  Rejoice while Putin remains above ground!

**Comment by SDRausty** [comment]
He played with Nuclear detonation too much!

He is insane!

He wants to see the Eorld all his kind!

**Comment by SDRausty** [comment]
His kin breeded underground ditto.

**Comment by SDRausty** [comment]
Your GitHub account was regained @xeffyr;  Rejoice while Putin remains above ground!

**Comment by SDRausty** [comment]
He has played with Nuclear detonation too much!

He is insane!

He wants to see the Eorld all his kind!

**Comment by SDRausty** [comment]
His kin bred into Adam and Eve underground ditto.

**Comment by SDRausty** [comment]
His kin bred into Adams and Eves underground ditto.
