### ISSUE TITLE
Issues on aarch64

### ISSUE THREAD

**Issue by nxd84** [sdrausty/TermuxArch#105]
Hello sir,
I am user of aarch64, android 7.1.2 .
When I going to install ArchLinux on termux, at the stage of "🕚 Uncompressing ArchLinuxARM-aarch64-latest.tar.gz" an error comes displaying this massage " TermuxArch warning: Script signal 1 generated! "
" SetupTermuxArch.sh v1.6: DONE "
Please solve this issue.
Note that, I used ArchLinux in the same device 5 days ago. But today after uninstalling termux when I reinstalled it (termux) and going to install ArchLinux on it (termux) the error came. Now I request, please fix this problem as soon as possible.
Thanks in advance.
![screenshot_20180814-095158](https://user-images.githubusercontent.com/42072272/44071596-ba34ce70-9fa7-11e8-83a5-e6808c5f644f.png)

**Comment by sdrausty** [comment]
The most recent version takes this error into account.  Use `setupTermuxArch.sh refresh` to update your Arch Linux in Termux PRoot.  Should refresh not accomplish its' task, reinstall.

**Comment by nxd84** [comment]
Thanks its working. Also for your quick response.

**Comment by sdrausty** [comment]
You are welcome; Thank you for confirming.
