### ISSUE TITLE
Help error id.so: object

### ISSUE THREAD

**Issue by mjskoneg** [sdrausty/TermuxArch#11]
╭─@ Mr_/bon'007@localhost  ~
╰─➤  ./arch/startArch
ERROR: ld.so: object '/data/data/com.termux/files/usr/lib/libtermux-exec.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.

**Comment by Soph1a7** [comment]
try installing `termux-exec` with `pkg install termux-exec`

**Comment by mjskoneg** [comment]
Still not able :'(

**Comment by sdrausty** [comment]
@mjskoneg the more clues you provide the better are your chances for success. Try bash shell please. 

Include as much information as possible.

**Comment by sdrausty** [comment]
Please use the bash shell. Thank you for your time and input. It was very helpful in modifying [setupTermuxArch.sh](https://raw.githubusercontent.com/sdrausty/TermuxArch/master/setupTermuxArch.sh) accordingly; Help pages such as https://sdrausty.github.io/TermuxArchPlus/install were added. If this doesn't resolve your issue, then reopen it please👷
