### ISSUE TITLE
$ bash setupTermuxArch.sh not working

### ISSUE THREAD

**Issue by djrivington** [sdrausty/TermuxArch#112]
```
setupTermuxArch.sh: line 392: /proc/sys/kernel/random/uuid: Permission denied
TermuxArch warning:  Script signal 1 generated!
setupTermuxArch.sh: line 232: tmpdir: unbound variable
```

I reinstalled Termux today on both my aarch64 phone and armv8 chromebook and now I'm facing this issue on both devices.

**Comment by sdrausty** [comment]
Can you `$ ls -al /proc/sys/kernel/random/`?  What does `$ cat /proc/sys/kernel/random/*` give?  Are the ROMs stock? A little bit more information is requested.  Use `setupTermuxArch.sh sysinfo`.

**Comment by djrivington** [comment]
Sorry about that. I wasn't sure where to start. I'm primarily focused on the phone. It's a galaxy s8 active running stock Android 8 without root. Until I reinstalled Termux, TermuxArch had been running flawlessly.

```
> ls -al /proc/sys/kernel/random/ > 
```
shows:

```
ls: /proc/sys/kernel/random/boot_id: Permission denied
ls: /proc/sys/kernel/random/entropy_avail: Permission denied
ls: /proc/sys/kernel/random/poolsize: Permission denied
ls: /proc/sys/kernel/random/read_wakeup_threshold: Permission denied
ls: /proc/sys/kernel/random/urandom_min_reseed_secs: Permission denied
ls: /proc/sys/kernel/random/uuid: Permission denied
ls: /proc/sys/kernel/random/write_wakeup_threshold: Permission denied
total 0
dr-xr-xr-x    1 root     root             0 Aug 19 11:06 .
dr-xr-xr-x    1 root     root             0 Aug 19 11:06 ..
```

```
cat /proc/sys/kernel/random/*
```

shows:

```
cat: can't open '/proc/sys/kernel/random/boot_id': Permission denied
cat: can't open '/proc/sys/kernel/random/entropy_avail': Permission denied
cat: can't open '/proc/sys/kernel/random/poolsize': Permission denied
cat: can't open '/proc/sys/kernel/random/read_wakeup_threshold': Permission denied
cat: can't open '/proc/sys/kernel/random/urandom_min_reseed_secs': Permission denied
cat: can't open '/proc/sys/kernel/random/uuid': Permission denied
cat: can't open '/proc/sys/kernel/random/write_wakeup_threshold': Permission denied
```

and ```bash setupTermuxArch.sh sysinfo``` returns:

```
setupTermuxArch.sh: line 392: /proc/sys/kernel/random/uuid: Permission denied
TermuxArch warning:  Script signal 1 generated!
setupTermuxArch.sh: line 232: tmpdir: unbound variable```

**Comment by s73obrien** [comment]
I'm having the same issue. Looks like it is related to termux/termux-app/#299, as I am running Oreo.

**Comment by s73obrien** [comment]
Changed the path in preptmpdir() to avoid using /proc/sys/kernel/random/uuid and it ran past that, but hangs up with some illegal character errors from curl down the line.

**Comment by djrivington** [comment]
Studying that issue now, I passed over it last night because I mistook it to be unrelated.

**Comment by sdrausty** [comment]
@s73obrien This is related to a new function: preptmpdir()  It's supposed to be a major improvement, and it appears that we have run into a hiccup on certain devices.  More information regarding proc random is requested.  

Can you `$ ls -al /proc/sys/kernel/random/`?  What does `$ cat /proc/sys/kernel/random/*` give?  Are the ROMs stock? A little bit more information is requested, including `uname -a`:

**Comment by s73obrien** [comment]
Sure thing! 
```
$ ls -al /proc/sys/kernel/random
ls: cannot access '/proc/sys/kernel/random/boot_id': Permission denied
ls: cannot access '/proc/sys/kernel/random/entropy_avail': Permission denied
ls: cannot access '/proc/sys/kernel/random/poolsize': Permission denied
ls: cannot access '/proc/sys/kernel/random/read_wakeup_threshold': Permission denied
ls: cannot access '/proc/sys/kernel/random/urandom_min_reseed_secs': Permission denied
ls: cannot access '/proc/sys/kernel/random/uuid': Permission denied
ls: cannot access '/proc/sys/kernel/random/write_wakeup_threshold': Permission denied
total 0
dr-xr-xr-x 1 root root 0 Aug 19 12:36 .
dr-xr-xr-x 1 root root 0 Aug 19 12:36 ..
-????????? ? ?    ?    ?            ? boot_id
-????????? ? ?    ?    ?            ? entropy_avail
-????????? ? ?    ?    ?            ? poolsize
-????????? ? ?    ?    ?            ? read_wakeup_threshold
-????????? ? ?    ?    ?            ? urandom_min_reseed_secs
-????????? ? ?    ?    ?            ? uuid
-????????? ? ?    ?    ?            ? write_wakeup_threshold
```
```
$ cat /proc/sys/kernel/random/*
cat: /proc/sys/kernel/random/boot_id: Permission denied
cat: /proc/sys/kernel/random/entropy_avail: Permission denied
cat: /proc/sys/kernel/random/poolsize: Permission denied
cat: /proc/sys/kernel/random/read_wakeup_threshold: Permission denied
cat: /proc/sys/kernel/random/urandom_min_reseed_secs: Permission denied
cat: /proc/sys/kernel/random/uuid: Permission denied
cat: /proc/sys/kernel/random/write_wakeup_threshold: Permission denied
```
Stock Android 8 on Galaxy S9

```
$ uname -a
Linux localhost 4.9.65-13087505 #1 SMP PREEMPT Wed Feb 28 18:50:17 KST 2018 aarch64 Android
```

**Comment by s73obrien** [comment]
So I uninstalled curl in order to force the script to use wget, and it downloaded with no issues. Unpacking now....

**Comment by s73obrien** [comment]
Aside from a handful of download errors from updating the pacman database, it seems to have installed correctly. (well, I got a prompt, anyway)

**Comment by sdrausty** [comment]
This issue is resolved.  `tmp="$(date +%s)"` tmp is now set to date, not uuid.  Thank you for your time and help.  Any idea why uuid is not readable on some devices?  I am curious about the rationale.

**Comment by djrivington** [comment]
Working like a charm now after a refresh. Thank you!

**Comment by sdrausty** [comment]
You are welcome; thank you for confirming 🏌

**Comment by s73obrien** [comment]
I don't really know, but according to the conversation on termux/termux-app#299, sounds like Oreo brought tighter permissions around information related to currently running processes. I suppose that uuid generation can be considered a part of that.
