### ISSUE TITLE
Hostname resolving not working after setting up

### ISSUE THREAD

**Issue by SteelTitanium** [sdrausty/TermuxArch#113]
After setting up the arch proot, hostname resolving fails to work. Causing some required packages to fail when installing. Would the fact systemd isn't used be part of the problem?

**Comment by SteelTitanium** [comment]
No idea what changed, but everything suddenly works after running  `setupTermuxArch.sh refresh`

**Comment by sdrausty** [comment]
Glad to hear that it's working for you?
