### ISSUE TITLE
Installation Issue - unbound variable

### ISSUE THREAD

**Issue by isrgish** [sdrausty/TermuxArch#117]
In middle of setup I get the following error.
"printoutstatements.sh: line 142: NLCMIRROR: unbound variable"

After this the setup script stops with Exit Signal 1.

I'm new at this and would appreciate any help on how to proceed.

![screenshot_20180907-010634](https://user-images.githubusercontent.com/35469435/45199949-783f5b00-b23c-11e8-8795-a4807d302072.png)

**Comment by sdrausty** [comment]
@isrgish an option that should be a quick fix for you is: `setupTermuxArch.sh b[loom]`; cd TermuxArchBloom; next comment out `
set -Eeuo pipefail` so it reads `# 
set -Eeuo pipefail`; run `setupTermuxArch.sh` in TermuxArchBloom.  Good luck!

I will get back to the code as soon as I can; In the meantime this should get through.

**Comment by sdrausty** [comment]
This message should be resolved.

**Comment by gauloics** [comment]
no solved yet

**Comment by sdrausty** [comment]
Yes.  It's solved.

**Comment by isrgish** [comment]
I used the TermuxArchBloom and it worked but was the regular TermuxArch resolved?

**Comment by gauloics** [comment]
let see, what wrong?
![screenshot_2018-09-14-09-51-25](https://user-images.githubusercontent.com/742131/45527093-1feff680-b804-11e8-95f1-8f3e4f35e050.jpg)

**Comment by isrgish** [comment]
I'm not sure what you are saying.

**Comment by gauloics** [comment]
> @isrgish an option that should be a quick fix for you is: `setupTermuxArch.sh b[loom]`; cd TermuxArchBloom; next comment out `set -Eeuo pipefail` so it reads `# set -Eeuo pipefail`; run `setupTermuxArch.sh` in TermuxArchBloom. Good luck!
> 
> I will get back to the code as soon as I can; In the meantime this should get through.

I have already run the suggested command as above, as seen in my terminal, but the error still occurs

**Comment by sdrausty** [comment]
setupTermuxArch.sh v1.6.id0647 should no longer contain this error.  Thank you for calling it to my attention.  This https://github.com/sdrausty/TermuxArch/commit/221c0d08b0d8bc3a3442d3cff957bf544020cc29 commit should resolve the issue.

**Comment by gauloics** [comment]
Let me ask, after installing archlinux, in archlinux do I have to reinstall the package that has been installed in Termux? or can it be used together directly?

**Comment by gauloics** [comment]
i think my installation not successfully. this after i run
$ startarch c df
/etc/locale.conf: line 5: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8): No such file or directory
/etc/locale.conf: line 6: warning: setlocale: LC_CTYPE: cannot change locale (en_US.UTF-8): No such file or directory
/etc/locale.conf: line 9: warning: setlocale: LC_MESSAGES: cannot change locale (en_US.UTF-8): No such file or directory
/etc/locale.conf: line 12: warning: setlocale: LC_NUMERIC: cannot change locale (en_US.UTF-8): No such file or directory
/etc/locale.conf: line 15: warning: setlocale: LC_TIME: cannot change locale (en_US.UTF-8): No such file or directory
/root/.bash_profile: line 15: warning: setlocale: LC_COLLATE: cannot change locale (en_US.UTF-8)
/root/.bash_profile: line 16: warning: setlocale: LC_CTYPE: cannot change locale (en_US.UTF-8)
/root/.bash_profile: line 19: warning: setlocale: LC_MESSAGES: cannot change locale (en_US.UTF-8)
/root/.bash_profile: line 22: warning: setlocale: LC_NUMERIC: cannot change locale (en_US.UTF-8)
/root/.bash_profile: line 25: warning: setlocale: LC_TIME: cannot change locale (en_US.UTF-8)
Filesystem              1K-blocks     Used Available Use% Mounted on
/dev/block/mmcblk1p2      3723200  1596772   1920912  46% /data/sdext2
tmpfs                     2000720       68   2000652   1% /dev
none                      2000720        0   2000720   0% /sys/fs/cgroup
/dev/block/by-name/data  26772500 22336140   4419976  84% /data
tmpfs                     2000720        0   2000720   0% /storage/emulated
/dev/fuse                 3781152   498144   3283008  14% /storage/MicroSD
proot error: trying to remove a directory outside of '/data/data/com.termux/files/usr/tmp/', please report this error.

**Comment by isrgish** [comment]
I just ran the setup and I got a few errors and warnings here are the screenshots.

![screenshot_20180914-083835](https://user-images.githubusercontent.com/35469435/45550814-0944a200-b7fa-11e8-99e9-c26b0f7f861a.png)

![screenshot_20180914-083858](https://user-images.githubusercontent.com/35469435/45550821-0d70bf80-b7fa-11e8-8fd7-a07b8f8a2d3b.png)

**Comment by sdrausty** [comment]
@isrgish these two files should look similar to this:  
```
[root09:21home]$cat /root/.bash_profile
if [ ! -e "$HOME"/.hushlogin ] && [ ! -e "$HOME"/.chushlogin ] ; then
. /etc/motd
fi
if [ -e "$HOME"/.chushlogin ] ; then
rm "$HOME"/.chushlogin
fi
PATH="$HOME/bin:$PATH"
. "$HOME"/.bashrc
PS1="[\e[38;5;148m\]\u\[\e[1;0m\]\A\[\e[1;38;5;112m\]\W\[\e[0m\]]\$"
# PS1="[\A\[\033[0;32m\] \W \[\033[0m\]]\$ "
export TZ="America/New_York"
export LANG="en_US.UTF-8"
export LANGUAGE="en_US.UTF-8"
export LC_ADDRESS="en_US.UTF-8"
export LC_COLLATE="en_US.UTF-8"
export LC_CTYPE="en_US.UTF-8"
export LC_IDENTIFICATION="en_US.UTF-8"
export LC_MEASUREMENT="en_US.UTF-8"
export LC_MESSAGES="en_US.UTF-8"
export LC_MONETARY="en_US.UTF-8"
export LC_NAME="en_US.UTF-8"
export LC_NUMERIC="en_US.UTF-8"
export LC_PAPER="en_US.UTF-8"
export LC_TELEPHONE="en_US.UTF-8"
export LC_TIME="en_US.UTF-8"

[root09:23home]$cat /etc/locale.conf
##  File locale.conf generated by setupTermuxArch.sh at 20180913205526.
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_ADDRESS=en_US.UTF-8
LC_COLLATE=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
LC_IDENTIFICATION=en_US.UTF-8
LC_MEASUREMENT=en_US.UTF-8
LC_MESSAGES=en_US.UTF-8
LC_MONETARY=en_US.UTF-8
LC_NAME=en_US.UTF-8
LC_NUMERIC=en_US.UTF-8
LC_PAPER=en_US.UTF-8
LC_TELEPHONE=en_US.UTF-8
LC_TIME=en_US.UTF-8
```
We are currently discussing locales in issue,  "Warning setlocal on start 
https://github.com/sdrausty/TermuxArch/issues/121".  You are welcome to contribute;  Can you post the output of `getprop` too?

**Comment by MrHackingEx** [comment]
> 



> @isrgish an option that should be a quick fix for you is: `setupTermuxArch.sh b[loom]`; cd TermuxArchBloom; next comment out ` set -Eeuo pipefail` so it reads `# set -Eeuo pipefail`; run `setupTermuxArch.sh` in TermuxArchBloom. Good luck!
> 
> I will get back to the code as soon as I can; In the meantime this should get through.

It says command not found

**Comment by SDRausty** [comment]
>setupTermuxArch.shb[loom]

Please note the space `setupTermuxArch.sh b[loom]`.  Brackets mean optional.  They are not ment to be typed.
