### ISSUE TITLE
Missing `setupbin1.sh` and no internet after

### ISSUE THREAD

**Issue by ConorIA** [sdrausty/TermuxArch#118]
`necessaryfunctions.sh` is throwing an error about a missing `.sh` file at line 326.

```
🕛 > 🕘 Cleaning up installation files: DONE

 🕛 > 🕤 Arch Linux in Termux PRoot is installed.  Configuring and updating Arch Linux 📲
necessaryfunctions.sh: line 326: /data/data/com.termux/files/home/arch/root/bin/setupbin1.sh: No such file or directory

To generate locales in a preferred language use Settings > Language & Keyboard > Language in Android; Then run setupTermuxArch.sh r for a quick system refresh.
```
I'm not sure if this is related, but all internet-requiring commands afterward fail, and I can't get connectivity. Does `setupbin1.sh` configure internet connectivity? 

[setupTermuxArchSysInfo1839.log.txt](https://github.com/sdrausty/TermuxArch/files/2361756/setupTermuxArchSysInfo1839.log.txt)

**Comment by sdrausty** [comment]
@ConorIA it looks like it went well, except for the error; Try `setupTermuxArch.sh re[fresh]`.  

This should complete the installation by running a full system refresh.  I will get back to the code as soon as I can and take a closer look at this matter.

**Comment by sdrausty** [comment]
You are welcome @ConorIA, and thanks for bringing this topic to my attention.  This https://github.com/sdrausty/TermuxArch/commit/af1800ad0daf7c4d7a4a8db15a94c59b085d6419 commit resolves this issue.
