### ISSUE TITLE
MD5 Errors (x86_64)

### ISSUE THREAD

**Issue by Seriell** [sdrausty/TermuxArch#12]
I'm getting the following error when trying to run the setup script:
It could be that the md5 actually is mismatched, but the errors surrounding the check hints that that might not be the case.
![screenshot_2017-10-31-19-56-57](https://user-images.githubusercontent.com/14004943/32246147-f36d3f42-be75-11e7-8ef4-f376db9d6dee.png)

<br>

Some system info:
![screenshot_2017-10-31-20-00-07](https://user-images.githubusercontent.com/14004943/32246295-70c3b642-be76-11e7-97ec-e83a6edf424d.png)
![screenshot_2017-10-31-20-00-12](https://user-images.githubusercontent.com/14004943/32246297-70f16236-be76-11e7-93a6-027d94fc4ffa.png)
</details>

**Comment by sdrausty** [comment]
@Seriell thank you for posting. This should be fixed now with https://github.com/sdrausty/TermuxArch/commit/12b931590fc94aeadd1384a72d21505821911b79 this commit. I have tested, and installation seems to work fine now. However, I do not have an x86_64 to do a complete test with login. Image download, md5 check and extraction should work for you fine now. Enjoy.

**Comment by Seriell** [comment]
Sorry, I haven’t had a chance to try it again lately, I’ll see if it works
when I can

**Comment by Seriell** [comment]
It's not an md5 issue anymore, now I get this:
![screenshot_2017-11-05-10-15-45](https://user-images.githubusercontent.com/14004943/32411979-a5c6a8a2-c224-11e7-93a8-b4cb8733a538.png)
![screenshot_2017-11-05-10-27-53](https://user-images.githubusercontent.com/14004943/32411980-afa3c332-c224-11e7-8ecb-a29ea21b804a.png)

**Comment by sdrausty** [comment]
@Seriell sorry to hear that you are still having trouble. Make sure termux-exec is installed. This should take care of any script startup issues. See ["Why do I keep getting '/bin/sh bad interpreter' error?"](https://wiki.termux.com/wiki/FAQ#Why_do_I_keep_getting_.27.2Fbin.2Fsh_bad_interpreter.27_error.3F) for more information. Rerunning setupTermuxArch.sh should do this for you. You may have ran an older version that didn't. 

Either way, the script is now self-updating, so see if running it again helps. Your version might not have the self-updating code, so grab a fresh one from [here](https://raw.githubusercontent.com/sdrausty/TermuxArch/master/setupTermuxArch.sh) and try again. You should have gotten a login in your first screenshot, but for some reason you got a startArch.sh not found! How did you do that? `setupTermuxArch.sh` is supposed to create `startArch.sh`.

![screenshot_20171105-035921](https://user-images.githubusercontent.com/27742457/32413354-df21b4f8-c1dd-11e7-95a9-1204d5fc2ed4.png)

I have not a clue why PRoot says it only runs on 32bit. This might be x86_64 specific in as far as it doesn't work, but it should work. This screenshot is from an aarch64 device and PRoot does not complain.  Your PRoot error confirms the startup script is setup correctly on your device. It found `env`, but why it says it will not run on 64bit is beyond scope here. This is a PRoot issue. Please reference this issue if you post at https://github.com/termux/proot/issues There is active development at termux-proot and new versions of PRoot are being published and tested. Good luck.
