### ISSUE TITLE
blackarch error signature

### ISSUE THREAD

**Issue by gauloics** [sdrausty/TermuxArch#120]
error: failed to update blackarch (invalid or corrupted database (PGP signature))
error: database 'blackarch' is not valid (invalid or corrupted database (PGP signature))

![screenshot_2018-09-14-12-49-54](https://user-images.githubusercontent.com/742131/45532070-cba54080-b81c-11e8-84f7-084d21b69614.jpg)

**Comment by sdrausty** [comment]
Have you run `keys`?

**Comment by gauloics** [comment]
not sure, for a while i just comment out it on pacman.conf
like this

#[blackarch]

#Server = http://blackarch.org/blackarch/$repo/os/$arch

**Comment by sdrausty** [comment]
@gauloics this https://github.com/sdrausty/TermuxArch/commit/8cff900d521ce08f1b0182f138555a3a3912af79 commit resolves this issue.  The error has been found and corrected.
