### ISSUE TITLE
download speed is slow

### ISSUE THREAD

**Issue by apersonlikesc** [sdrausty/TermuxArch#122]
i am downloading archlinuxarm-armv7.tar.gz, but the speed  under 10kb/s  :(
i am in china.Is that the reason for my network? how to solve it？

**Comment by sdrausty** [comment]
@apersonlikesc does configuring this https://mirrors.tuna.tsinghua.edu.cn/archlinuxarm/ mirror help?

**Comment by apersonlikesc** [comment]
@sdrausty how to configure it

**Comment by apersonlikesc** [comment]
maybe i need to git the repo, I just bash the sh file :)

**Comment by sdrausty** [comment]
Edit /etc/pacman.d/mirrorlist.

**Comment by apersonlikesc** [comment]
sad :(
the kernel is too old  :(
