### ISSUE TITLE
PRoot can't sanitize binding warning

### ISSUE THREAD

**Issue by s0urc3d3v3l0pm3nt** [sdrausty/TermuxArch#123]
proot warning: can't sanitize binding "/data/data/com.termux/files/home/arch/var/binds/fbindprocstat": No such file or directory

**Comment by sdrausty** [comment]
@s0urc3d3v3l0pm3nt see if `mkdir /data/data/com.termux/files/home/arch/var/binds/` helps.  If that does not help, try `setupTermuxArch.sh r` for a quick system refresh.

**Comment by gauloics** [comment]
as I explained on another issue, I tried to reinstall termuxarch, but found a proot error `/root/bin/finishsetup.sh: line 53: ./root/bin/keys: No such file or directory`

what wrong?

**Comment by sdrausty** [comment]
@gauloics in addition to https://github.com/sdrausty/TermuxArch/issues/121#issuecomment-422045415 run `pc sed`.  All these should be set up correctly on the kind of device you are using (i686).  We have covered and tackled similar https://github.com/sdrausty/TermuxArch/issues?q=is%3Aissue+i686 https://github.com/sdrausty/TermuxArch/issues?q=is%3Aissue+x86 issues recently.   See whether any of these topics related to your device can help you out as well.

**Comment by sdrausty** [comment]
@s0urc3d3v3l0pm3nt @gauloics this https://github.com/sdrausty/TermuxArch/commit/8cff900d521ce08f1b0182f138555a3a3912af79 commit resolves this issue.  The error has been found and corrected.
