### ISSUE TITLE
"Permission denied" during installation

### ISSUE THREAD

**Issue by memoir** [sdrausty/TermuxArch#127]
I'm getting the following error right after the installer script starts unpacking:
`tar: can't create symlink './etc/ca-certificates/extracted/cadir/d7746a63.0' to 'D-TRUST_Root_Class_3_CA_2_EV_2009.pem': Permission denied`.
This is followed by ``TermuxArch WARNING: Generated script signal 1 near or at line number 598 by `trap`!`` and the script exits with signal 201.
Any ideas what could cause this?

**Comment by sdrausty** [comment]
@memoir try running `keys` in Arch Linux; Does this resolve the error?

**Comment by memoir** [comment]
Thanks for the suggestion!
But as I said, Arch isn't even extracted, so I'm not sure how I'm supposed to run something in it.

**Comment by sdrausty** [comment]
@memoir `setupTermuxArch.sh sysinfo` is requested.

**Comment by sdrausty** [comment]
@memoir try using the current version which is v1.6.id3554.  Also make sure your packages are up to date with https://sdrausty.github.io/au/ or `pkg up`.

**Comment by memoir** [comment]
same :(

**Comment by sdrausty** [comment]
@memoir you should not be having any issues since your architecture is aarch64 and TermuxArch is thoroughly tested on aarch64.  Can you dump the information the install?

**Comment by memoir** [comment]
[setupTermuxArchTranscript.txt](https://github.com/sdrausty/TermuxArch/files/2420511/setupTermuxArchTranscript.txt)
I don't think there's a lot to see beyond what I already wrote, but here you go.

**Comment by sdrausty** [comment]
@memoir thanks, now can you post an updated sysinfo?

**Comment by memoir** [comment]
[setupTermuxArchSysInfo5539.log](https://github.com/sdrausty/TermuxArch/files/2420759/setupTermuxArchSysInfo5539.log)

**Comment by sdrausty** [comment]
@memoir here is the status of your TermuxArch installation:

Downloaded, verified, but not unpacked yet.  


> I don't think there's a lot to see beyond what I already wrote, but here you go.

As you can see there was enough see to state your installation is downloaded and verified.  I am interested as to why it is not installed and configured on your device.  Can you please provide some more information about the install;  Run:
```
$ setupTermuxArch.sh bloom
$ cd ~/TermuxArchBloom
```
Edit setupTermuxArch.sh and change `set -Eeuo pipefail` to `set -Eeuxo pipefail`. Then run `./setupTermuxArch.sh` in the TermuxArchBloom directory. You will see every command echoed.  There will be a lot of  output.  Share the output from before the error, ~12 lines until the end of results.

**Comment by memoir** [comment]
This is everything after "Be patient…":

+ printf '\e[0;32m'                          + _PREPROOT_                                 + [[ arm64-v8a = \x\8\6 ]]                   + [[ arm64-v8a = \x\8\6\_\6\4 ]]             + proot --link2symlink -0 /data/data/com.termux/files/usr/bin/applets/tar -xpf ArchLinuxARM-aarch64-latest.tar.gz
tar: can't create symlink './etc/ca-certificates/extracted/cadir/d7746a63.0' to 'D-TRUST_Root_Class_3_CA_2_EV_2009.pem': Permission denied                                          ++ _STRPERROR_ 602 trap '_STRPERROR_ 324 proot --link2symlink -0 "$PREFIX"/bin/applets/tar -xpf "$file" 1' ERR 0                       ++ local RV=1                                ++ printf '\e[?25h\n\e[1;48;5;138m %s\e[0m\n' 'TermuxArch WARNING:  Generated script signal 1 near or at line number 602 by `trap`!'                                                 TermuxArch WARNING:  Generated script signal 1 near or at line number 602 by `trap`!     ++ [[ 1 = 4 ]]
++ printf '\n'                                                                            ++ exit 201                                  + _STRPEXIT_
+ local RV=201                               + rm -rf /data/data/com.termux/files/home/arch/tmp/setupTermuxArch22125                   + sleep 0.04
+ [[ 201 = 0 ]]                              + printf '\a\e[0;32m%s %s \a\e[0mv1.6.1.id4321\e[1;34m: \a\e[1;32m%s %s\e[0m\n\n\a\e[0m' setupTermuxArch.sh '' '[Exit Signal 201]' 'DONE 🏁 '
setupTermuxArch.sh  v1.6.1.id4321: [Exit Signal 201] DONE 🏁

+ printf '\033]2; %s: %s %s \007' 'setupTermuxArch.sh ' '[Exit Signal 201]' 'DONE 🏁 '    + printf '\e[?25h\e[0m'                      + set +Eeuo pipefail                         + exit                                       $

**Comment by memoir** [comment]
[bloom.txt](https://github.com/sdrausty/TermuxArch/files/2426084/bloom.txt)
OK, maybe it works better in an attachment.

**Comment by sdrausty** [comment]
@memoir install bsdtar (pkg install bsdtar), then `proot --link2symlink -0 bsdtar -xpf ArchLinuxARM-aarch64-latest.tar.gz`. This will use bsdtar to unpack the image file.  Hopefully, bsdtar shall overcome the symlink error encountered by busybox tar.

**Comment by memoir** [comment]
🎉 Yaay, that worked. You're awesome, @sdrausty. 

Now I'm only getting this error when I start Arch, but it does start:
`proot warning: can't sanitize binding "/data/data/com.termux/files/home/arch/var/binds/fbindprocstat": No such file or directory`

**Comment by sdrausty** [comment]
@memoir good news🌈  
> proot warning: can't sanitize binding "/data/data/com.termux/files/home/arch/var/binds/fbindprocstat": No such file or directory

Try `setupTermuxArch.sh refresh` for a full system refresh.  Both `setupTermuxArch.sh help` and `startarch help` have additional information.  This appears to be a busybox tar error.  You might want to submit an issue at https://github.com/termux/termux-packages/issues.

**Comment by texasbruce** [comment]
@sdrausty I ran with bsdtar, and it emitted even more errors like `Can't create 'etc/ca-certificates/extracted/cadir/certSIGN_ROOT_CA.pem'` and same for other pem files like `QuoVadis_Root_CA_2.pem`, `DigiCert_Assured_ID_Root_G3.pem` etc.

**Comment by texasbruce** [comment]
Looks like a simple permission error. Somehow /etc/ca-certificate/extracted/cadir has permission of 555. I used `proot chmod 755 /etc/ca-certificate/extracted/cadir` and untar again, and it worked. (Still have some problem with locale but that is minor)

For this image http://os.archlinuxarm.org/os/ArchLinuxARM-aarch64-latest.tar.gz it appears that only the folder above has the wrong permission. All other folders have permission of 775 but that one has 555. Do you think they intend to have a 555 permisson or can you relax it in the command?

**Comment by sdrausty** [comment]
I am taking a close look at this issue, and cannot find much at all but successful installation with configuration on aarch64 time and time again. Example output: https://sdrausty.github.io/docsTermuxArch/outputaarch6420181002install.txt 

> Looks like a simple permission error. 

@texasbruce possibly, however both your issue and @memoir's are related in a number of different ways.  Can you share `setupTermuxArch.sh sysinfo` information so we can get more details about this topic?

**Comment by texasbruce** [comment]
Here 
[sysinfo.txt](https://github.com/sdrausty/TermuxArch/files/2451345/sysinfo.txt)

**Comment by sdrausty** [comment]
@memoir @texasbruce here's a comparison of your devices:
```
[user13:59sysinfo]$ grep 'Android' setupTermuxArchSysInfo55*
setupTermuxArchSysInfo5539.log:Linux localhost 4.4.103+ #1 SMP PREEMPT Fri Aug 3 03:52:13 CST 2018 aarch64 Android
setupTermuxArchSysInfo5539.log:[getprop net.bt.name]: [Android]
setupTermuxArchSysInfo5547.log:Linux localhost 4.4.103+ #1 SMP PREEMPT Tue Aug 14 12:55:49 CST 2018 aarch64 Android
setupTermuxArchSysInfo5547.log:[getprop net.bt.name]: [Android]
[user13:59sysinfo]$ grep 'version.[r,s]' setupTermuxArchSysInfo55*
setupTermuxArchSysInfo5539.log:[getprop ro.build.version.release]: [8.1.0]
setupTermuxArchSysInfo5539.log:[getprop ro.build.version.sdk]: [27]
setupTermuxArchSysInfo5547.log:[getprop ro.build.version.release]: [8.1.0]
setupTermuxArchSysInfo5547.log:[getprop ro.build.version.sdk]: [27]
[user14:22sysinfo]$ grep 'huawei' setupTermuxArchSysInfo55*
setupTermuxArchSysInfo5539.log:[getprop ro.com.google.clientidbase]: [android-huawei]
setupTermuxArchSysInfo5539.log:[getprop ro.com.google.clientidbase.am]: [android-huawei]
setupTermuxArchSysInfo5539.log:[getprop ro.com.google.clientidbase.ms]: [android-huawei-rev1]
setupTermuxArchSysInfo5547.log:[getprop ro.com.google.clientidbase]: [android-huawei]
setupTermuxArchSysInfo5547.log:[getprop ro.com.google.clientidbase.am]: [android-huawei]
setupTermuxArchSysInfo5547.log:[getprop ro.com.google.clientidbase.ms]: [android-huawei-rev1]
```
This issue is **Android 8 Termux PRoot** related.  Here they are labelled A26+.  Feel free to seek a resolution upstream https://github.com/termux/proot/issues?q=is%3Aissue+Android+8 at this link, and https://github.com/termux/termux-packages/issues?q=is%3Aissue+Android+8 this one.
