### ISSUE TITLE
How to fix `makepkg` without reinstalling TermuxArch?

### ISSUE THREAD

**Issue by dlintw** [sdrausty/TermuxArch#129]
I want to fix makepkg issues, there are two major issues, it seems has solved. But I can not do it by exist makepkg.

1. sudo - seems nosudo can replace it, but it is not the same as sudo, it require type in root password.
2. fakeroot - seems fakeroot-tcp can replace it, but it failed compile I got no selinux issue

Why not provide a workable script to build the replacement packcakage just during the TermuxArchSetup.sh? 

Or, if it has contains in the TermuxArchSetup.sh, How can I redo it without reinstall the archlinux(I've setup many packages, it is a hardwork for re-setup all).

**Comment by dlintw** [comment]
@sdrausty I just try to do 'r' again.  And it doesn't let the 'makepkg' workable.
I try to run 'makepkg' on nosudo package. It failed on call fakeroot: lack of SYSV IPC

**Comment by sdrausty** [comment]
@dlintw did you use a user account in Arch Linux, i.e., `startarch l user`?

**Comment by sdrausty** [comment]
```
[user13:37~]$ sudo whoami

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for root:
root
[user13:38~]$ whoami
user
```

@dlintw did you use a user account in Arch Linux, i.e., `startarch l user`?

**Comment by sdrausty** [comment]
Are you familiar with this https://github.com/sdrausty/TermuxArch/issues/38 issue?

**Comment by dlintw** [comment]
yes, I use normal user to do this. I wish there is a setupMakepkg.sh to provide what #38 said to build fakeroot-tcp

**Comment by sdrausty** [comment]
@dlintw I have added labels for this topic as markers, a bit like guides. 
> I think it will also install base-devel 
```
[e23:27working]$ f base-devel *
archlinuxconfig.sh:     pacman --noconfirm --color=always -S base base-devel "\${@:2}"
archlinuxconfig.sh:     pacman --noconfirm --color=always -S base base-devel emacs "\${@:2}"
archlinuxconfig.sh:     pacman --noconfirm --color=always -S base base-devel emacs jdk8-openjdk "\${@:2}"
archlinuxconfig.sh:     pacman --noconfirm --color=always -Syu base base-devel emacs "\${@:2}"
archlinuxconfig.sh:     pacman --noconfirm --color=always -Syu base base-devel emacs jdk8-openjdk "\${@:2}"
archlinuxconfig.sh:     pacman --noconfirm --color=always -Syu base base-devel emacs jdk10-openjdk "\${@:2}"
```
Can you outline a little more what you are working on?  This way I can follow along.

**Comment by dlintw** [comment]
I have not do it. I was misunderstand is is already included in setup.sh.

**Comment by sdrausty** [comment]
What are you trying to build with `makepkg` @dlintw?

**Comment by dlintw** [comment]
In fact, I want to use yay for any AUR packages.  So, the first fakeroot-tcp, than nosudo. When makepkg work, maybe bvi

**Comment by sdrausty** [comment]
> I want to use yay for any AUR packages. 

I tried building yay:
```
[user16:09yay]$ makepkg -si
==> Making package: yay 8.1139-1 (Sun 30 Sep 2018 04:10:01 PM EDT)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading yay-8.1139.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   118    0   118    0     0    203      0 --:--:-- --:--:-- --:--:--   204
100  340k  100  340k    0     0   114k      0  0:00:02  0:00:02 --:--:--  173k
==> Validating source files with sha1sums...
    yay-8.1139.tar.gz ... Passed
==> Extracting sources...
  -> Extracting yay-8.1139.tar.gz with bsdtar
==> Starting build()...
go build -v -ldflags '-s -w -X main.version=8.1139' -o yay
github.com/jguer/go-alpm
github.com/Morganamilo/go-srcinfo
github.com/Morganamilo/go-pacmanconf/ini
github.com/Morganamilo/go-pacmanconf
github.com/mikkeloscar/aur
_/home/user/yay/src/yay-8.1139
==> Entering fakeroot environment...
fakeroot, while creating message channels: Function not implemented
This may be due to a lack of SYSV IPC support.
fakeroot: error while starting the `faked' daemon.
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
[user16:11yay]$
```
Do you get a similar result @dlintw?

**Comment by dlintw** [comment]
yes, so, I guess use fakeroot-tcp may let it work.  But I can't use makepkg directly because fakeroot can't work.

**Comment by sdrausty** [comment]
> use fakeroot-tcp may let it work. 

```
[user16:11yay]$ sudo pc fakeroot-tcp
[sudo] password for root:

==> Running TermuxArch pc fakeroot-tcp v1.6.2.id3957…

error: target not found: fakeroot-tcp
error: no operation specified (use -h for help)

 pc WARNING:  Generated script signal 1 near or at line number 78 by !


TermuxArch pc fakeroot-tcp v1.6.2.id3957: DONE 🏁

[user17:56yay]$
```

> But I can't use makepkg directly because fakeroot can't work.

Ditto, I cannot get it to run correctly.

**Comment by sdrausty** [comment]
> One way to do it would be to build a separate copy of fakeroot-tcp from source  http://ftp.debian.org/debian/pool/main/f/fakeroot/
open up the PKGBUILD, install the dependencies (arch packages):
depends=('glibc' 'filesystem' 'sed' 'util-linux' 'sh')
makedepends=('po4a')
follow the commands in PKGBUILD
install it to a temporary prefix (say, /opt/fakeroot), 
add said prefix to $PATH, 
 use that to bootstrap fakeroot-tcp from makepkg.

Reference https://www.reddit.com/r/archlinux/comments/7rycmu/cannot_build_fakeroottcp_without_fakeroot/

Let's see whether this method works well with our setup.

**Comment by dlintw** [comment]
https://gist.github.com/10da0d331d7fccee77c2a9062a2617dc

Here is my work script, it is still in draft.  And I found another issue in this Proot env, the 'patch' can NOT work well, it complaint no selinux permission.

**Comment by sdrausty** [comment]
I am curious how far our thread shall go.  Hopefully, we will build some more interesting projects with these tools in the near future.  Here is the output of nosudo on Android smartphone:
```
[user13:21~]$ ./nosudo/src/nosudo
usage: ./nosudo/src/nosudo [-u username|#uid] [-bEHi] [VAR=value] command
usage: ./nosudo/src/nosudo [-u username|#uid] -l [-n] [command]
usage: ./nosudo/src/nosudo [-u username|#uid] -e [file ...]

Options:
  -b       run command in the background
  -E       preserve user environment when executing command
  -e       edit files instead of running a command
  -H       set HOME variable to target user's home dir
  -h       display help message and exit
  -i       run a login shell as target user
  -l       list user's available commands (dummy)
  -n       non-interactive mode, will not prompt user
  -u user  run command (or edit file) as specified user
  --       stop processing command line arguments
```

Thank you for the details that you provided.  They helped greatly.

**Comment by dlintw** [comment]
I do not think nosudo is necessary for makepkg. but patch is required.

**Comment by sdrausty** [comment]
`pacman -S patch` will install patch.

**Comment by dlintw** [comment]
It installed, but contained selinux issue when build chroot-tcp. I mean it's native PkGBUILD.

**Comment by dlintw** [comment]
To let makepkg build, just remove sudo and it will work without nosudo.

**Comment by weitongdao** [comment]
I am a newer and like this archlinux in termux.
however.i relay on the yaourt much.
recently when i am trytoinstall yaourt manually.
the pkgbuild goes wrong.
------output such as
/usr/share/makepkg/util/pkgbuild.sh: line 69: /dev/fd/62: No such file or directory                         /usr/share/makepkg/util/pkgbuild.sh: line 69: /dev/fd/62: No such file or directory                         /usr/share/makepkg/util/pkgbuild.sh: line 69: /dev/fd/62: No such file or directory                         /usr/share/makepkg/util/pkgbuild.sh: line 69: /dev/fd/62: No such file or directory                         /usr/share/makepkg/util/pkgbuild.sh: line 69: /dev/fd/62: No such file or directory                         /usr/share/makepkg/util/pkgbuild.sh: line 69: /dev/fd/62: No such file or directory                         /usr/share/makepkg/util/pkgbuild.sh: line 69: /dev/fd/62: No such file or directory                         /usr/share/makepkg/util/pkgbuild.sh: line 69: /dev/fd/62: No such file or directory                         /usr/share/makepkg/util/pkgbuild.sh: line 69: /dev/fd/62: No such file or directory                         /usr/bin/makepkg: line 1025: /dev/fd/62: No such file or directory                                          ==> Making package: package-query 1.9-3 (Sat 01 Dec 2018 07:39:40 PM CST)                                   ==> Checking runtime dependencies...                  ==> Checking buildtime dependencies...                ==> Retrieving sources...                             /usr/share/makepkg/source/file.sh: line 44: /dev/fd/62: No such file or directory
---
i have no idea butask for help here.

thanks for reply.
My Android phone Z9max .system version 5.1

**Comment by sdrausty** [comment]
@takov751 you can try:
```
for lib in $(find /system/framework -type f -iname \*.jar); do
    BOOTCLASSPATH=${lib}:${BOOTCLASSPATH};
done
BOOTCLASSPATH=${BOOTCLASSPATH%%:}
export BOOTCLASSPATH
```

**Comment by mambiux** [comment]
Hey guys im having the same issue installing yay==> Entering fakeroot environment...
fakeroot, while creating message channels: Function not implemented
This may be due to a lack of SYSV IPC support

Also tried to install fakeroot-tcp, but it failed, did you found a workaround?, thanks for the help, im loving the arch in my pocket, thanks SDRausty

**Comment by sobaee** [comment]
@mambiux 
Were you working  on root in the first steps then log out or what?

**Comment by xnn403** [comment]
> ```
> 
> [user13:37~]$ sudo whoami
> 
> 
> 
> We trust you have received the usual lecture from the local System
> 
> Administrator. It usually boils down to these three things:
> 
> 
> 
>     #1) Respect the privacy of others.
> 
>     #2) Think before you type.
> 
>     #3) With great power comes great responsibility.
> 
> 
> 
> [sudo] password for root:
> 
> root
> 
> [user13:38~]$ whoami
> 
> user
> 
> ```
> 
> 
> 
> @dlintw did you use a user account in Arch Linux, i.e., `startarch l user`?
