### ISSUE TITLE
BLACKARCH INSTALLATION

### ISSUE THREAD

**Issue by sudeeprku** [sdrausty/TermuxArch#13]
How to get blackarch in arch linux(termux)
Plz help

**Comment by sdrausty** [comment]
I would like to try to include BlackArch. But without boot images, it is a no go. I checked at https://www.mirrorservice.org/sites/blackarch.org/blackarch/ but couldn't find the rootimage.tar.gz file. Do you know where they are?

**Comment by sudeeprku** [comment]
i am unable to use makepkg

**Comment by sdrausty** [comment]
@sudeeprku are you getting something like this?
```
[root@localhost home]# makepkg
==> ERROR: Running makepkg as root is not allowed as it can cause permanent,
catastrophic damage to your system.

==> ERROR: An unknown error has occurred. Exiting...
```

**Comment by sudeeprku** [comment]
No it showing......wait I will tell👇
Can u give it WhatsApp number
Bcoz there is much to discuss
Thank you

**Comment by Soph1a7** [comment]
@sudeeprku this isn't really the place to discuss blackarch, rather the arch install script for termux and its issues.
Regarding your issue,  check https://blackarch.org/downloads.html#install-repo and try it from there.
If you want to reach us in a more direct and open way, use the gitter linked in our README, instead of something like WhatsApp.

**Comment by sudeeprku** [comment]
Hello sir 
Is there any way that I can arch Linux chrooted on android 
Other than termux (on internal sdcard)

**Comment by sdrausty** [comment]
@sudeeprku Arch Linux needs to be installed in $HOME or similar Termux user space. You cannot install it on the external SD card at present. Hopefully this will change in the future.

**Comment by sdrausty** [comment]
@sudeeprku to install https://blackarch.org do the following:
1) Install, update and configure Arch Linux using [`setupTermuxArch.sh`](https://sdrausty.github.io/TermuxArch/setupTermuxArch.sh).
2) Add the next lines to the end of the /etc/pacman.conf file:  
```
[blackarch]
Server = http://blackarch.org/blackarch/$repo/os/$arch
```
3) Run `pacman -Syu`. 
4) Run `pacman -S archstrike --needed`.
