### ISSUE TITLE
proot handles 32bit programs only

### ISSUE THREAD

**Issue by samprasannaj** [sdrausty/TermuxArch#131]
Hi sdrausty,

I installed termuxarch in my amazon fire tablet hd 10 7th gen. This is the error I received
proot error: '~/arch/usr/bin/env' is a 64 bit program whereas this version of proot handles 32 bit programs only.

proot info : vpid 1: terminated with signal 11

Please let me know what can I do to fix it?

**Comment by sdrausty** [comment]
> Please let me know what can I do to fix it?

@samprasannaj can you provide information from `setupTermuxArch.sh sysinfo`?

**Comment by sdrausty** [comment]
@samprasannaj are you familiar with this, "dpkg for Termux doesn't correctly supports x86-64 Android devices - x86_64 vs x86-64 vs amd64 name of architecture for packages and repo paths dispute" https://github.com/termux/termux-app/issues/853 issue?

**Comment by samprasannaj** [comment]
> > Please let me know what can I do to fix it?
> 
> @samprasannaj can you provide information from `setupTermuxArch.sh sysinfo`?


Setting mode to sysinfo.
]2;bash setupTermuxArch.sh sysinfo 📲
[0;34m 🕛 > 🕛 [1;34mＴｅｒｍｕｘＡｒｃｈ v1.6.5.id4616 shall create a system information file.  Ensure background data is not restricted.  Run [0;32mbash setupTermuxArch.sh help [1;34mfor additional information.  Check the wireless connection if you do not see one o'clock 🕐 below.  [1;34mChecking prerequisites…
[1;32m
Found download tool: curl; Continuing…

Using curl to manage downloads.

[0;34m 🕛 > 🕧 [1;34mPrerequisites: [1;32mOK  [1;34mDownloading ＴｅｒｍｕｘＡｒｃｈ…

[0;32m
[1;32m[0;34m 🕛 > 🕐 [1;34mＴｅｒｍｕｘＡｒｃｈ download: [1;32mOK

[0;34m 🕛 > 🕜 [1;34mＴｅｒｍｕｘＡｒｃｈ v1.6.5.id4616 integrity: [1;32mOK[0m

[1;32mGenerating TermuxArch system information; Please wait…

[38;5;76mBegin TermuxArch v1.6.5.id4616 system information.

dpkg --print-architecture result:

arm

uname -a results:

Linux localhost 3.18.19+ #1 SMP PREEMPT Fri Aug 10 03:07:50 UTC 2018 armv8l Android

BASH_VERSINFO[0] = 4
BASH_VERSINFO[1] = 4
BASH_VERSINFO[2] = 23
BASH_VERSINFO[3] = 1
BASH_VERSINFO[4] = release
BASH_VERSINFO[5] = arm-unknown-linux-androideabi

cat /proc/cpuinfo results:

Processor	: AArch64 Processor rev 2 (aarch64)
processor	: 0
model name	: AArch64 Processor rev 2 (aarch64)
BogoMIPS	: 26.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 2

processor	: 1
model name	: AArch64 Processor rev 2 (aarch64)
BogoMIPS	: 26.00
Features	: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt lpae evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 2

Hardware	: MT8173
Serial		: bc3975569fcc424d

Download directory information results:

/sdcard/Download exists
/storage/emulated/0/Download exists
~/downloads not found
/data/data/com.termux/files/home/storage/downloads exists

Device information results:

/dev/ashmem exists
/dev/ashmem is readable
/dev/shm exists
/dev/shm is not readable
/proc/stat exits
/proc/stat is readable

getprop results:

[getprop gsm.sim.operator.iso-country]: []
[getprop net.bt.name]: [Android]
[getprop net.dns1]: [192.168.1.1]
[getprop net.dns2]: [8.8.8.8]
[getprop net.dns3]: []
[getprop net.dns4]: []
[getprop persist.sys.locale]: []
[getprop ro.build.target_country]: []
[getprop ro.build.version.release]: [5.1.1]
[getprop ro.build.version.preview_sdk]: []
[getprop ro.build.version.sdk]: [22]
[getprop ro.com.google.clientidbase]: []
[getprop ro.com.google.clientidbase.am]: []
[getprop ro.com.google.clientidbase.ms]: []
[getprop ro.product.device]: [suez]
[getprop ro.product.cpu.abi]: [arm64-v8a]
[getprop ro.product.first_api_level]: []
[getprop ro.product.locale]: []
[getprop ro.product.manufacturer]: [Amazon]
[getprop ro.product.model]: [KFSUWI]

Disk report 13.7G on /data Tue Oct  9 17:18:58 EDT 2018

df /data/data/com.termux/files/home/arch results:

Filesystem               Size     Used     Free   Blksize
/data/data/com.termux/files/home/arch    26.6G    12.9G    13.7G   4096

df results:

Filesystem               Size     Used     Free   Blksize
/dev                   907.9M    68.0K   907.8M   4096
/sys/fs/cgroup         907.9M    12.0K   907.9M   4096
/mnt/asec              907.9M     0.0K   907.9M   4096
/mnt/obb               907.9M     0.0K   907.9M   4096
/system                  1.5G     1.4G   121.1M   4096
/data                   26.6G    12.9G    13.7G   4096
/data/metrics            5.8M   260.0K     5.6M   4096
/cache                 410.7M     2.9M   407.8M   4096
/mnt/sqfs               80.9M    80.9M     0.0K   32768
/mnt/cd-rom              1.2M     1.2M     0.0K   2048
/storage/emulated      907.9M     0.0K   907.9M   4096
/storage/sdcard1        29.0G    11.1G    17.9G   16384
/storage/emulated/0     26.6G    12.9G    13.7G   4096
/storage/emulated/legacy    26.6G    12.9G    13.7G   4096

du -hs /data/data/com.termux/files/home/arch results:

1009.9M	/data/data/com.termux/files/home/arch

ls -al /data/data/com.termux/files/home/arch results:

total 80
drwx------   16 u0_a32   u0_a32        4096 Oct  9 17:18 .
drwx------    6 u0_a32   u0_a32        4096 Oct  9 16:15 ..
lrwxrwxrwx    1 u0_a32   u0_a32           7 Oct  9 16:22 bin -> usr/bin
drwxr-xr-x    4 u0_a32   u0_a32        4096 Oct  9 16:22 boot
drwxr-xr-x    2 u0_a32   u0_a32        4096 Oct  5 09:46 dev
drwxr-xr-x   39 u0_a32   u0_a32        4096 Oct  9 16:26 etc
drwxr-xr-x    3 u0_a32   u0_a32        4096 Oct  9 16:22 home
lrwxrwxrwx    1 u0_a32   u0_a32           7 Oct  9 16:22 lib -> usr/lib
drwxr-xr-x    2 u0_a32   u0_a32        4096 Aug 23 14:03 mnt
drwxr-xr-x    2 u0_a32   u0_a32        4096 Aug 23 14:03 opt
dr-xr-xr-x    2 u0_a32   u0_a32        4096 Oct  5 09:46 proc
drwxr-x---    4 u0_a32   u0_a32        4096 Oct  9 16:22 root
drwxr-xr-x    3 u0_a32   u0_a32        4096 Oct  5 09:46 run
lrwxrwxrwx    1 u0_a32   u0_a32           7 Oct  9 16:22 sbin -> usr/bin
-rw-------    1 u0_a32   u0_a32        3391 Oct  9 17:19 setupTermuxArchSysInfo63cb.log
drwxr-xr-x    4 u0_a32   u0_a32        4096 Oct  9 16:22 srv
-rwx------    1 u0_a32   u0_a32        5959 Oct  9 16:21 startarch
dr-xr-xr-x    2 u0_a32   u0_a32        4096 Oct  5 09:46 sys
-rw-------    1 u0_a32   u0_a32         853 Oct  9 17:18 sysinfo.txt
drwxrwxrwt    3 u0_a32   u0_a32        4096 Oct  9 17:18 tmp
drwxr-xr-x    8 u0_a32   u0_a32        4096 Oct  9 16:22 usr
drwxr-xr-x   13 u0_a32   u0_a32        4096 Oct  9 16:26 var

End `setupTermuxArchSysInfo63cb.log` v1.6.5.id4616 system information.
[0m
Share this information along with your issue at https://github.com/sdrausty/TermuxArch/issues; include input and output.  This file is found in `/data/data/com.termux/files/home/arch/setupTermuxArchSysInfo63cb.log`.  If you think screenshots will help in a quicker resolution, include them in the post as well.  

[1mThis information may be quite important when planning issue(s) at https://github.com/sdrausty/TermuxArch/issues with the hope of improving `setupTermuxArch.sh`;  Include input and output, along with screenshot(s) relavent to X, and similar.

]2;setupTermuxArch.sh sysinfo: DONE 🏁 [?25h[0;32msetupTermuxArch.sh sysinfo [0mv1.6.5.id4616[1;34m: [1;32mDONE 🏁 [0m

[0m

**Comment by sdrausty** [comment]
@samprasannaj it appears that getprop isn't installed on your device.
> getprop results:

Can you run `getprop` and share the output?

**Comment by samprasannaj** [comment]
[camera.disable_zsl_mode]: [1]
[curlockscreen]: [1]
[dalvik.vm.dex2oat-Xms]: [64m]
[dalvik.vm.dex2oat-Xmx]: [512m]
[dalvik.vm.heapgrowthlimit]: [128m]
[dalvik.vm.heapsize]: [256m]
[dalvik.vm.image-dex2oat-Xms]: [64m]
[dalvik.vm.image-dex2oat-Xmx]: [64m]
[dalvik.vm.isa.arm.features]: [div]
[dalvik.vm.isa.arm64.features]: [default]
[dalvik.vm.mtk-stack-trace-file]: [/data/anr/mtk_traces.txt]
[dalvik.vm.stack-trace-file]: [/data/anr/traces.txt]
[debug.force_rtl]: [0]
[debug.hwc.bq_count]: [3]
[debug.hwc.compose_level]: [0]
[debug.log.base.path]: [/data/debug_service]
[debug.log.battery.enable]: [n]
[debug.log.battery.sleep]: [60]
[debug.log.coredump.enable]: [n]
[debug.log.dmesg.enable]: [n]
[debug.log.dmesg.wakeup]: [0]
[debug.log.gpu_mem.enable]: [n]
[debug.log.logcat.enable]: [n]
[debug.log.temperature.enable]: [n]
[debug.log.temperature.sleep]: [10]
[debug.log.thermal_qa.enable]: [n]
[debug.service.log]: [1]
[dev.bootcomplete]: [1]
[dev.fireos.bootstatus]: [0]
[dhcp.wlan0.dns1]: [192.168.1.1]
[dhcp.wlan0.dns2]: []
[dhcp.wlan0.dns3]: []
[dhcp.wlan0.dns4]: []
[dhcp.wlan0.domain]: []
[dhcp.wlan0.gateway]: [192.168.1.1]
[dhcp.wlan0.ipaddress]: [192.168.1.61]
[dhcp.wlan0.leasetime]: [86400]
[dhcp.wlan0.mask]: [255.255.255.0]
[dhcp.wlan0.mtu]: []
[dhcp.wlan0.netchange]: [false]
[dhcp.wlan0.pid]: [16852]
[dhcp.wlan0.reason]: [RENEW]
[dhcp.wlan0.result]: [ok]
[dhcp.wlan0.server]: [192.168.1.1]
[dhcp.wlan0.vendorInfo]: []
[dolby.audio.sink.info]: [speaker]
[dolby.ds.dialogenhancer.state]: [on]
[dolby.ds.graphiceq.state]: [off]
[dolby.ds.hpvirtualizer.state]: [on]
[dolby.ds.intelligenteq.preset]: [Focused]
[dolby.ds.intelligenteq.state]: [on]
[dolby.ds.profile.name]: [Movie]
[dolby.ds.settings.filename]: [ds1-0028.xml]
[dolby.ds.spkvirtualizer.state]: [on]
[dolby.ds.state]: [off]
[dolby.ds.volumeleveler.state]: [on]
[drm.service.enabled]: [true]
[fmradio.driver.enable]: [0]
[init.svc.66xx_launcher]: [running]
[init.svc.adbd]: [running]
[init.svc.amzn_dha_hmac]: [stopped]
[init.svc.amzn_drmprov]: [stopped]
[init.svc.autokd]: [running]
[init.svc.bat_logging]: [running]
[init.svc.bootanim]: [stopped]
[init.svc.debuggerd64]: [running]
[init.svc.debuggerd]: [running]
[init.svc.devicetype]: [stopped]
[init.svc.dhcpcd_wlan0]: [running]
[init.svc.drm]: [running]
[init.svc.enableswap]: [stopped]
[init.svc.factoryadb]: [stopped]
[init.svc.flash_recovery]: [stopped]
[init.svc.fosflags]: [stopped]
[init.svc.fuse_sdcard1]: [running]
[init.svc.guiext-server]: [running]
[init.svc.healthd]: [running]
[init.svc.installd]: [running]
[init.svc.iprenew_wlan0]: [stopped]
[init.svc.keystore]: [running]
[init.svc.kisd]: [running]
[init.svc.lmkd]: [running]
[init.svc.logd]: [running]
[init.svc.media]: [running]
[init.svc.msensord]: [stopped]
[init.svc.netd]: [running]
[init.svc.nvram_daemon]: [stopped]
[init.svc.p2p_supplicant]: [running]
[init.svc.post-recovery]: [stopped]
[init.svc.pq]: [stopped]
[init.svc.pvrsrvctl]: [stopped]
[init.svc.rpmb_svc]: [running]
[init.svc.sdcard]: [running]
[init.svc.servicemanager]: [running]
[init.svc.surfaceflinger]: [running]
[init.svc.thermal_manager]: [stopped]
[init.svc.ueventd]: [running]
[init.svc.ufsd]: [stopped]
[init.svc.vitals_service]: [running]
[init.svc.vold]: [running]
[init.svc.vp_metrics]: [stopped]
[init.svc.wifi_log_levels]: [running]
[init.svc.wmtLoader]: [stopped]
[init.svc.zygote]: [running]
[mediatek.wlan.chip]: [MT6630]
[mediatek.wlan.ctia]: [0]
[mediatek.wlan.module.postfix]: [_mt6630]
[mtk_in_house_tee_support]: [true]
[mtk_sec_enable]: [svp_mode]
[net.bt.name]: [Android]
[net.change]: [net.dns2]
[net.dns1]: [192.168.1.1]
[net.dns2]: [8.8.8.8]
[net.dns3]: []
[net.dns4]: []
[net.dns5]: []
[net.hostname]: [amazon-f53999399]
[net.netid]: [149]
[net.qtaguid_enabled]: [1]
[net.tcp.default_init_rwnd]: [60]
[persist.gemini.sim_num]: [1]
[persist.meta.dumpdata]: [0]
[persist.mtk.wcn.combo.chipid]: [0x6630]
[persist.radio.fd.counter]: [15]
[persist.radio.fd.off.counter]: [5]
[persist.radio.fd.off.r8.counter]: [5]
[persist.radio.fd.r8.counter]: [15]
[persist.radio.mobile.data]: [0,0]
[persist.radio.multisim.config]: [ss]
[persist.radio.reset_on_switch]: [true]
[persist.service.acm.enable]: [0]
[persist.service.bdroid.bdaddr]: [22:22:6f:68:7f:67]
[persist.service.dropbox.seq]: [5088]
[persist.sys.DaysFromOTA_V390]: [8000]
[persist.sys.DaysFromOTA_V395]: [8000]
[persist.sys.DaysFromOTA_V400]: [8000]
[persist.sys.DaysFromOTA_V410]: [8000]
[persist.sys.amazon-account-cor]: [US]
[persist.sys.country]: [US]
[persist.sys.dalvik.vm.lib.2]: [libart.so]
[persist.sys.ecs.SCREEN_IDLE]: [1]
[persist.sys.language]: [en]
[persist.sys.last_synced_time]: [1539120481000]
[persist.sys.last_verified_build]: [Amazon/suez/suez:5.1.1/LVY48F/40.6.1.2_user_612496620:user/release-keys]
[persist.sys.localevar]: []
[persist.sys.ota.silent]: [false]
[persist.sys.ota.verified]: [success]
[persist.sys.otaAtPowerDown]: [0]
[persist.sys.pq.shp.idx]: [2]
[persist.sys.profiler_ms]: [0]
[persist.sys.recovery.batt_level]: [25]
[persist.sys.timezone]: [America/New_York]
[persist.sys.usb.config]: [mtp,adb]
[persist.sys.wifi.country_code]: [US]
[persist.vpartition.metrics]: [ok]
[persist.wifi.rssi.thresholds]: [-81,-72,-66,-63]
[qemu.hw.mainkeys]: [0]
[ril.current.share_modem]: [1]
[ril.first.md]: [1]
[ril.flightmode.poweroffMD]: [0]
[ril.radiooff.poweroffMD]: [0]
[ril.specific.sm_cause]: [0]
[ril.telephony.mode]: [0]
[rild.libargs]: [-d /dev/ttyC0]
[rild.libpath]: [mtk-ril.so]
[rild.mark_switchuser]: [0]
[ro.adb.secure]: [1]
[ro.allow.mock.location]: [0]
[ro.amazon.fosflags]: [1]
[ro.amzn_dha.hmac]: [99e8e0e8838bd1af906b83a871b56ed7fbccf9f71e9840062664b6c355a58fdd]
[ro.amzn_drm.amzn_dha]: [yes]
[ro.amzn_drm.lek]: [yes]
[ro.amzn_drm.pek]: [yes]
[ro.amzn_drm.playready]: [yes]
[ro.amzn_drm.widevine]: [yes]
[ro.audio.hw_vol_devices]: [0x0C]
[ro.audio.monitorRotation]: [true]
[ro.audio.silent]: [0]
[ro.baseband]: [unknown]
[ro.board.platform]: [mt8173]
[ro.boot.barg_size_pair]: [440_440]
[ro.boot.bootreason]: [wdt]
[ro.boot.hardware]: [mt8173]
[ro.boot.lk_build_desc]: [a693e3d-20180321_221907]
[ro.boot.lk_version]: [0x0002]
[ro.boot.pl_build_desc]: [7fa1049-20180321_192352]
[ro.boot.pl_version]: [0x0004]
[ro.boot.prod]: [1]
[ro.boot.rpmb_state]: [1]
[ro.boot.secure_cpu]: [1]
[ro.boot.selinux]: [enforcing]
[ro.boot.serialno]: [G000N607821300B5]
[ro.boot.tee_version]: [0x0107]
[ro.boot.unlocked_kernel]: [false]
[ro.bootloader]: [unknown]
[ro.bootmode]: [unknown]
[ro.build.characteristics]: [tablet]
[ro.build.configuration]: [tablet]
[ro.build.date.utc]: [1533870199]
[ro.build.date]: [Fri Aug 10 03:03:19 UTC 2018]
[ro.build.description]: [suez-user 5.1.1 LVY48F 40.6.1.2_user_612496620 release-keys]
[ro.build.display.id]: [LVY48F]
[ro.build.fingerprint]: [Amazon/suez/suez:5.1.1/LVY48F/40.6.1.2_user_612496620:user/release-keys]
[ro.build.flavor]: [suez-user]
[ro.build.host]: [i3-ri-14-use1a-b-7]
[ro.build.id]: [LVY48F]
[ro.build.lab126.build]: [4966]
[ro.build.lab126.buildtype]: [Nightly]
[ro.build.lab126.project]: [suez_ship_5363]
[ro.build.lab126.sign.type]: [release]
[ro.build.mktg.fireos]: [Fire OS 5.6.2.0]
[ro.build.platform.version]: []
[ro.build.product]: [suez]
[ro.build.tags]: [release-keys]
[ro.build.type]: [user]
[ro.build.user]: [build]
[ro.build.version.all_codenames]: [REL]
[ro.build.version.base_os]: []
[ro.build.version.codename]: [REL]
[ro.build.version.fireos.sdk]: [4]
[ro.build.version.fireos]: [5.3.6.3]
[ro.build.version.incremental]: [40.6.1.2_user_612496620]
[ro.build.version.name]: [Fire OS 5.3.6.3 (612496620)]
[ro.build.version.number]: [612496620]
[ro.build.version.release]: [5.1.1]
[ro.build.version.sdk]: [22]
[ro.build.version.security_patch]: [2018-02-01]
[ro.camera.sound.forced]: [0]
[ro.carrier]: [unknown]
[ro.com.android.dateformat]: [MM-dd-yyyy]
[ro.com.android.mobiledata]: [false]
[ro.config.alarm_alert]: [Alarm_Classic.ogg]
[ro.config.notification_sound]: [Verso.ogg]
[ro.config.ringtone]: [Ring_Synth_04.ogg]
[ro.crypto.fuse_sdcard]: [true]
[ro.crypto.state]: [unencrypted]
[ro.dalvik.vm.native.bridge]: [0]
[ro.debuggable]: [0]
[ro.factorytest]: [0]
[ro.fireos.target.extension]: [default]
[ro.fireos.target.product]: [suez]
[ro.gemini.smart_sim_switch]: [false]
[ro.hardware.gralloc]: [mt8173.img]
[ro.hardware]: [mt8173]
[ro.have_aacencode_feature]: [1]
[ro.hwui.drop_shadow_cache_size]: [6]
[ro.hwui.layer_cache_size]: [48]
[ro.hwui.path_cache_size]: [16]
[ro.hwui.r_buffer_cache_size]: [8]
[ro.hwui.shape_cache_size]: [2]
[ro.hwui.text_small_cache_height]: [1024]
[ro.hwui.texture_cache_flushrate]: [0.4]
[ro.hwui.texture_cache_size]: [48]
[ro.kernel.zio]: [38,108,105,16]
[ro.logd.size.metrics]: [128000]
[ro.logd.size.vitals]: [128000]
[ro.mediatek.chip_ver]: [S01]
[ro.mediatek.gemini_support]: [false]
[ro.mediatek.platform]: [MT8173]
[ro.mediatek.project.path]: [device/amazon/suez]
[ro.mediatek.version.branch]: [alps-mp-l1.mp13.tc6sp]
[ro.mediatek.version.release]: [alps-mp-l1.mp13.tc6sp]
[ro.mediatek.version.sdk]: [4]
[ro.mediatek.wlan.p2p]: [1]
[ro.mediatek.wlan.wsc]: [1]
[ro.mount.fs]: [EXT4]
[ro.mtk_antibricking_level]: [2]
[ro.mtk_audio_profiles]: [1]
[ro.mtk_audio_tuning_tool_ver]: [V1]
[ro.mtk_besloudness_support]: [1]
[ro.mtk_bg_power_saving_support]: [1]
[ro.mtk_bg_power_saving_ui]: [1]
[ro.mtk_bip_scws]: [1]
[ro.mtk_bt_support]: [1]
[ro.mtk_cam_mfb_support]: [0]
[ro.mtk_cta_drm_support]: [1]
[ro.mtk_cta_set]: [1]
[ro.mtk_dhcpv6c_wifi]: [1]
[ro.mtk_dual_mic_support]: [0]
[ro.mtk_eap_sim_aka]: [1]
[ro.mtk_emmc_support]: [1]
[ro.mtk_fd_support]: [1]
[ro.mtk_flv_playback_support]: [1]
[ro.mtk_hdmi_4k_support]: [1]
[ro.mtk_is_tablet]: [0]
[ro.mtk_key_manager_kb_path]: [1]
[ro.mtk_key_manager_support]: [1]
[ro.mtk_miravision_image_dc]: [1]
[ro.mtk_oma_drm_support]: [1]
[ro.mtk_omacp_support]: [1]
[ro.mtk_perf_response_time]: [1]
[ro.mtk_perf_simple_start_win]: [1]
[ro.mtk_perfservice_support]: [1]
[ro.mtk_pq_support]: [2]
[ro.mtk_privacy_protection_lock]: [1]
[ro.mtk_safemedia_support]: [1]
[ro.mtk_sec_video_path_support]: [1]
[ro.mtk_send_rr_support]: [1]
[ro.mtk_shared_sdcard]: [1]
[ro.mtk_sim_hot_swap]: [1]
[ro.mtk_tetheringipv6_support]: [1]
[ro.mtk_thumbnail_play_support]: [1]
[ro.mtk_uipq_support]: [1]
[ro.mtk_wappush_support]: [1]
[ro.mtk_widevine_drm_l1_support]: [1]
[ro.mtk_wifi_mcc_support]: [1]
[ro.mtk_wlan_support]: [1]
[ro.mtk_wmv_playback_support]: [1]
[ro.mtk_world_phone_policy]: [0]
[ro.opengles.version]: [196609]
[ro.product.board]: [suez]
[ro.product.brand]: [Amazon]
[ro.product.config.type]: [A3R9S4ZZECZ6YL]
[ro.product.cpu.abi]: [arm64-v8a]
[ro.product.cpu.abilist32]: [armeabi-v7a,armeabi]
[ro.product.cpu.abilist64]: []
[ro.product.cpu.abilist]: [armeabi-v7a,armeabi]
[ro.product.device]: [suez]
[ro.product.locale.language]: [en]
[ro.product.locale.region]: [US]
[ro.product.manufacturer]: [Amazon]
[ro.product.model]: [KFSUWI]
[ro.product.name]: [suez]
[ro.product.package_name]: [com.amazon.suez.android.os]
[ro.recovery.wl.maxstore]: [524288]
[ro.revision]: [0]
[ro.runtime.firstboot]: [1538877108833]
[ro.secure]: [1]
[ro.serialno]: [G000N607821300B5]
[ro.sf.hwrotation]: [0]
[ro.sf.lcd_density]: [240]
[ro.sim_me_lock_mode]: [0]
[ro.slimport.colorado3]: [0]
[ro.smartvolume.config]: [/system/vendor/smartvolume/suez/]
[ro.sys.usb.bicr]: [yes]
[ro.sys.usb.charging.only]: [yes]
[ro.sys.usb.mtp.whql.enable]: [0]
[ro.sys.usb.storage.type]: [mtp,mass_storage]
[ro.usb.pid.adb]: [0288]
[ro.usb.pid.mtp.adb]: [0282]
[ro.usb.pid.mtp]: [0281]
[ro.usb.pid.ptp.adb]: [0284]
[ro.usb.pid.ptp]: [0283]
[ro.usb.vid]: [1949]
[ro.wifi.channels]: []
[ro.wlan.mtk.wifi.5g]: [1]
[ro.zygote.preload.enable]: [0]
[ro.zygote]: [zygote32]
[selinux.reload_policy]: [1]
[service.bootanim.exit]: [1]
[service.nvram_init]: [Ready]
[service.wcn.coredump.mode]: [0]
[service.wcn.driver.ready]: [yes]
[supolicy.loaded]: [1]
[sys.audio_init]: [true]
[sys.boot_completed]: [1]
[sys.captive_portal]: [0]
[sys.hwc.video_mode]: [0]
[sys.ipo.pwrdncap]: [2]
[sys.lab126.hasDeviceTime]: [true]
[sys.mtk.no.factoryimage]: [1]
[sys.rpmb.ready]: [1]
[sys.settings_global_version]: [443]
[sys.settings_secure_version]: [14]
[sys.settings_system_version]: [11]
[sys.sysctl.extra_free_kbytes]: [27000]
[sys.sysctl.tcp_def_init_rwnd]: [60]
[sys.usb.config]: [mtp,adb]
[sys.usb.state]: [mtp,adb]
[sys.usb.vid]: [1949]
[vold.pfe]: [deactivated]
[vold.post_fs_data_done]: [1]
[wfd.dummy.enable]: [1]
[wifi.direct.interface]: [p2p0]
[wifi.interface]: [wlan0]
[wifi.tethering.interface]: [ap0]
[wlan.driver.status]: [ok]

**Comment by sdrausty** [comment]
Thank you for your output 😙

Are you familiar with https://developer.amazon.com/docs/fire-tv/identify-amazon-fire-tv-devices.html?  Do any of those commands work on your tablet? 

From the output, it appears that the device should be using aarch64.  Can you also share `termux-info` results?

**Comment by samprasannaj** [comment]
[getprops.txt](https://github.com/sdrausty/TermuxArch/files/2462601/getprops.txt)

**Comment by samprasannaj** [comment]
Updatable packages:
All packages up to date
System information:
Linux localhost 3.18.19+ #1 SMP PREEMPT Fri Aug 10 03:07:50 UTC 2018 armv8l Android
Termux-packages arch:
arm
Android version:
5.1.1
Device manufacturer:
Amazon
Device model:
KFSUWI

**Comment by sdrausty** [comment]
This https://github.com/sdrausty/TermuxArch/commit/a510f9aeeec471fea569d9124e5589c757ea2176 commit rewrites the detection functions.  Use `setupTermuxArch.sh purge` to remove the current installation followed by a fresh install.  Hopefully, everything will go as intended.

**Comment by samprasannaj** [comment]
Thanks sdrausty. It worked finally.

**Comment by sdrausty** [comment]
@samprasannaj you are welcome.  Thank you for confirming 🎷🎶

**Comment by jtitley** [comment]
I'm getting the same error on S7 Edge running Oreo. I downloaded the latest setupTermuxArch.sh script and it still happens. Anything needed to troubleshoot or a hack to force a work around?

**Comment by DragonFire1024** [comment]
I have the same tablet. So I ran 'setupTermuxArch.sh purge' to no avail.
