### ISSUE TITLE
useradd: PAM: Authentication service cannot retrieve authentication info

### ISSUE THREAD

**Issue by developer787** [sdrausty/TermuxArch#132]
Fresh install TermuxArch. Getting that error when trying to add a user. Thanks

**Comment by sdrausty** [comment]
@developer787 this https://github.com/sdrausty/TermuxArch/commit/5b63e220f099e4eb1e5b2b56c18aad310687846d commit resolves, "useradd: PAM: Authentication service cannot retrieve authentication info".  I tried using `# PROOTSTMNT+="-i $UID:$GROUPS` in `/var/binds/additional _proot_binds.prs`, and changed knownconfigurations.sh:
```
PROOTSTMNTT="${PROOTSTMNT//--link2symlink }"
PROOTSTMNTU="${PROOTSTMNTT/-S /-R }"
```
After running `setupTermuxArch.sh re`, I could not get passwords to authenticate for user accounts.
