### ISSUE TITLE
systemd problem

### ISSUE THREAD

**Issue by gauloics** [sdrausty/TermuxArch#134]
`$ systemctl status`
>System has not been booted with systemd as init system (PID 1). Can't operate.                                                Failed to connect to bus: Host is down

**Comment by sdrausty** [comment]
> Are this 122cffb can fix ?
Considering I installed with the version before this committing

I do not understand.  Ask this question again in an easy to understand manner.  Are you also using https://gitter.im/termux to find help?

**Comment by gauloics** [comment]
https://github.com/systemd/systemd/issues/10396
**Arch inside Termux not using systemd and can't use systemctl.**

**Comment by SDRausty** [comment]
The TermuxArch command `csystemctl` installs a `systemctl` replacement that seems to work as expected.
