### ISSUE TITLE
Issues with TermuxArch in a virtualbox emulated Android environment.

### ISSUE THREAD

**Issue by den1z3n** [sdrausty/TermuxArch#136]
I'm currently attempting to install TermuxArch in an Android Mobile (Nougat 7.1) and Android Desktop (Remix OS 3.0.207) emulated environment in Virtualbox. I am experiencing identical issues discussed in https://github.com/sdrausty/TermuxArch/issues/121 and https://github.com/sdrausty/TermuxArch/issues/107. I have tried all suggestions to remedy the issue in those discussions as well as others, but have not been able to solve the issue. Here  are some screenshots of the installation for troubleshooting:
![1](https://user-images.githubusercontent.com/25859700/48316418-aa549c80-e5a0-11e8-8840-f75835a24991.png)
![2](https://user-images.githubusercontent.com/25859700/48316419-aa549c80-e5a0-11e8-80d2-d9e5206c4078.png)
![3](https://user-images.githubusercontent.com/25859700/48316420-aa549c80-e5a0-11e8-8a2c-9dab2fcf3bac.png)
![4](https://user-images.githubusercontent.com/25859700/48316421-aaed3300-e5a0-11e8-9c2c-c1e9518f8428.png)
![5](https://user-images.githubusercontent.com/25859700/48316422-aaed3300-e5a0-11e8-8b78-9b42af79fa11.png)
![6](https://user-images.githubusercontent.com/25859700/48316423-aaed3300-e5a0-11e8-83b2-376ded2f7e3b.png)
![7](https://user-images.githubusercontent.com/25859700/48316424-aaed3300-e5a0-11e8-88ae-471f84004b9d.png)

**Comment by sdrausty** [comment]
Read https://raw.githubusercontent.com/sdrausty/TermuxArch/master/setupTermuxArch.sh and `./setupTermuxArch.sh help`, including `startarch help`.

Closed: beyond scope.
