### ISSUE TITLE
How to start services?

### ISSUE THREAD

**Issue by xzarabotok** [sdrausty/TermuxArch#138]
Hello, I am delighted with your creation, do not abandon the project, please tell me how to start services, for example tor? systemctl and systemd do not work. I did not find a similar question here ... Thanks for the earlier thanks for the answer.

**Comment by xzarabotok** [comment]
Is the project dead? (

**Comment by sdrausty** [comment]
Read https://raw.githubusercontent.com/sdrausty/TermuxArch/master/setupTermuxArch.sh and `./setupTermuxArch.sh help`, including `startarch help`.

**Comment by SDRausty** [comment]
The TermuxArch command `csystemctl` installs a `systemctl` replacement that seems to work as expected.
