### ISSUE TITLE
How to start termux arch ?

### ISSUE THREAD

**Issue by MrNobodyTharusha** [sdrausty/TermuxArch#139]
TermuxArch WARNING!  The root directory structure is correct; Cannot continue setupTermuxArch.sh install!  See `setupTermuxArch.sh help` and `startarch help` for more information.

setupTermuxArch.sh  v1.6.7.id5677: [Exit Signal 205] DONE 🏁

 ✘  ~ 

But when I type setupTermuxArch.sh ,

~  setupTermuxArch.sh
setupTermuxArch.sh: command not found
 ✘  ~ 

**Comment by SDRausty** [comment]
Please read these documents: https://raw.githubusercontent.com/sdrausty/TermuxArch/master/setupTermuxArch and `bash setupTermuxArch help` and also `startarch help`.

**Comment by ahartikainen** [comment]
Hi, could you add instructions how to start the container at least to README.md? This infornation was a bit hard to find.

**Comment by sdrausty** [comment]
> add instructions on how to

You are welcome to submit pulls (pull requests) here https://github.com/sdrausty/TermuxArch/pulls
also here
https://github.com/sdrausty/docsTermuxArch/pulls

Pulls are simple:
a) fork repository
b) make change
=

**Comment by sdrausty** [comment]
Hello,
> add instructions on how to

You are welcome to submit pulls (pull requests) here https://github.com/sdrausty/TermuxArch/pulls
also here
https://github.com/sdrausty/docsTermuxArch/pulls

Pulls are simple:
a) fork repository
b) make change
=

**Comment by sdrausty** [comment]
Hello,
> add instructions on how to

You are welcome to submit pulls (pull requests) here https://github.com/sdrausty/TermuxArch/pulls
also here
https://github.com/sdrausty/docsTermuxArch/pulls

Pulls are simple:
a) fork repository
b) make change
=

**Comment by sdrausty** [comment]
https://github.com/sdrausty/TermuxArch/pulls/148: merged

Nice work @ahartikainen 🏩

**Comment by sdrausty** [comment]
@ahartikainen thank you for submitting https://github.com/sdrausty/TermuxArch/pull/148: merged
