### ISSUE TITLE
ERROR: /dev must be mounted!

### ISSUE THREAD

**Issue by Arif-Tech** [sdrausty/TermuxArch#14]
after load this i m use this coman  
pacman -Syu

ERROR: /dev must be mounted!
error: command failed to execute correctly
(2/5) Updating system user accounts...
(3/5) Creating temporary files...
(4/5) Arming ConditionNeedsUpdate...
(5/5) Updating the info directory file...
[root@localhost home]# echo $0
/bin/bash
[root@localhost home]#

my device not rooted

**Comment by Soph1a7** [comment]
The script should automatically mount /dev.
Try restarting the script or the pacman command.

**Comment by Arif-Tech** [comment]
./arch/startArch.sh
[root@localhost home]# pacman
error: no operation specified (use -h for help)
[root@localhost home]#

**Comment by Soph1a7** [comment]
Any issue with pacman?
Your comment is pretty vague.

**Comment by T3CHNOLOG1C** [comment]
can confirm that exiting the proot env and using the script fixes /dev not being mounted

**Comment by sdrausty** [comment]
On aarch64
```
[root@localhost tmp]# !g
git clone https://github.com/sdrausty/TermuxArch
Cloning into 'TermuxArch'...
remote: Counting objects: 848, done.
remote: Compressing objects: 100% (61/61), done.
remote: Total 848 (delta 49), reused 54 (delta 21), pack-reused 766
Receiving objects: 100% (848/848), 122.46 KiB | 526.00 KiB/s, done.
Resolving deltas: 100% (576/576), done.
[root@localhost tmp]# du -hs TermuxArch/
668K    TermuxArch/
[root@localhost tmp]# du -hs TermuxArch/.git/
612K    TermuxArch/.git/
```

**Comment by Arif-Tech** [comment]
tellme pkg install code i m new in Arch how to install python2  or git clone  repo install in Arch

**Comment by sdrausty** [comment]
@Arif-Tech "The pacman package manager is one of the major distinguishing features of Arch Linux. It combines a simple binary package format with an easy-to-use build system. The goal of pacman is to make it possible to easily manage packages, whether they are from the official repositories or the user's own builds."

https://wiki.archlinux.org/index.php/Pacman

**Comment by sdrausty** [comment]
```$ gcl https://github.com/sdrausty/TermuxArch
Cloning into 'TermuxArch'...
remote: Counting objects: 21, done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 21 (delta 6), reused 15 (delta 4), pack-reused 2
Unpacking objects: 100% (21/21), done.
$ d TermuxArch/
380K    TermuxArch/
$ d TermuxArch/.git
324K    TermuxArch/.git``` 🌞
