### ISSUE TITLE
Change Home Directory?

### ISSUE THREAD

**Issue by neo-expert** [sdrausty/TermuxArch#141]
I did not fiind anything related to this:
How can I change the Home Directory elegantly?
For now HOME is set to /root
But I would like to set it to termux home:

/data/data/com.termux/files/home/

**Comment by sdrausty** [comment]
Read https://raw.githubusercontent.com/sdrausty/TermuxArch/master/setupTermuxArch.sh and `./setupTermuxArch.sh help`, including `startarch help`.
