### ISSUE TITLE
I accidentally overwrote my /etc/pacman.conf file.

### ISSUE THREAD

**Issue by JacobTDC** [sdrausty/TermuxArch#142]
How do I regenerate pacman.conf with the same stuff ArchTermux had in it?
(I accidentally used `>` instead of `>>`)

I have found the ArchLinux default and am using it plus alarm and aur, but it would be nice to have the default for TermuxArch.

**Comment by JacobTDC** [comment]
I know they are the same, (functionality-wise), it's just the idea of it and the comments that exist in the TermuxArch that bothers me.

**Comment by cbrt64** [comment]
This appears to be the [pacman.conf](https://archlinuxarm.org/packages/arm/pacman/files/pacman.conf) installed by ArchTermux.
