### ISSUE TITLE
error metasploit

### ISSUE THREAD

**Issue by kel12345678** [sdrausty/TermuxArch#143]
hello i have one error after install metasploit .
msfconsole
Could not find rake-12.1.0 in any of the sources
Run `bundle install` to install missing gems.
[root14:59~]$ bundle install
Don't run Bundler as root. Bundler can ask for
sudo if it is needed, and installing your bundle
as root will break this application for all
non-root users on this machine.
Could not locate Gemfile.

and who update last metasploit?

thanks for help

**Comment by sdrausty** [comment]
Closed: beyond scope.
