### ISSUE TITLE
could not change the root directory (Function not implemented) 

### ISSUE THREAD

**Issue by Frostbyrne** [SDRausty/TermuxArch#145]
"could not change the root directory (Function not implemented)
error: command failed to execute correctly"

I've been getting this error when running the setupTermuxArch.sh script and installing any packages after it completes. I'm on a oneplus 6t with OOS 9.0.9 (Pie) and have granted termux the storage permission as well as run the storage setup command.

**Comment by takahirom** [comment]
I have the same issue

**Comment by Frostbyrne** [comment]
![termux](https://user-images.githubusercontent.com/660819/50426072-cfe4ef00-084a-11e9-8b64-397416551bf9.jpg)
![termux1](https://user-images.githubusercontent.com/660819/50426073-cfe4ef00-084a-11e9-9189-9337098c66cc.jpg)

**Comment by sdrausty** [comment]
@Frostbyrne can you elaborate on this part of the log:
```
du -hs /data/data/com.termux/files/home/arch results:

316.0K  /data/data/com.termux/files/home/arch

ls -al /data/data/com.termux/files/home/arch results:

total 24
drwx------    3 u0_a133  u0_a133       4096 Dec 25 13:23 .
drwx------    3 u0_a133  u0_a133       4096 Dec 25 13:23 ..
drwxrwxrwt    3 u0_a133  u0_a133       4096 Dec 25 13:23 tmp
                                                                                                      End `setupTermuxArchSysInfo66c1.log` v1.6.7.id5677 system information.
```
Is Arch Linux installed in a different folder?

**Comment by Frostbyrne** [comment]
It appears to be installed there, (/data/data/com.termux/files/home/arch)I've been digging through my storage and don't see any other references to it.  Where is it supposed to be installing to?

**Comment by abicorios** [comment]
+1 I have this issue to on `pacman -Syu` I have the old instalation.

**Comment by abicorios** [comment]
![screenshot_2018-12-27-12-29-44-265_com termux](https://user-images.githubusercontent.com/33332953/50477028-3f85e600-09d3-11e9-878f-bc6d58de1c9a.png)

**Comment by sdrausty** [comment]
Did Arch Linux ever perform correctly on Android 9 Pie?  Is this a newly arisen error?

**Comment by sdrausty** [comment]
I cannot assist much at present due to lack of an Android 9, the following channels are recommended in seeking resolution:
a) https://gitter.im/termux
b) https://github.com/termux/proot/issues
c) See https://wiki.archlinux.org/index.php/IRC_channel for available Arch Linux IRC channels.

Share Arch Linux in Termux PRoot Android 9 Pie accomplishments here.

**Comment by CorvetteCole** [comment]
I also have this issue on a Google Pixel running Android 9

**Comment by Frostbyrne** [comment]
@sdrausty if having a device to troubleshoot on would help I could give you remote access to my device but I will also look at the channels you listed.

**Comment by CorvetteCole** [comment]
@sdrausty @Frostbyrne you could also test on the Android emulator included in Android studio. It is an emulator so it will help you troubleshoot this error

**Comment by abicorios** [comment]
It is not the important error. The Pacman show the error, but you can install the new program with the error, and this program is working.

**Comment by abicorios** [comment]
`pacman -Syu` break the updated software. And the reinstalled software do not work too. We can only reinstall the TermuxArch and install the new soft.

**Comment by sdrausty** [comment]
@abicorios can you share the output of a simple command:
```
$ startarch c pc tree

==> Running TermuxArch pc tree v1.6.7.id5677…

warning: tree-1.8.0-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) tree-1.8.0-1

Total Installed Size:  0.12 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n]
(1/1) checking keys in keyring                                   [####################################] 100%
(1/1) checking package integrity                                 [####################################] 100%
(1/1) loading package files                                      [####################################] 100%
(1/1) checking for file conflicts                                [####################################] 100%
(1/1) checking available disk space                              [####################################] 100%
:: Processing package changes...
(1/1) reinstalling tree                                          [####################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...

TermuxArch pc tree v1.6.7.id5677: DONE 🏁
```
Sa in the one above in the example above.

**Comment by ExtraHash** [comment]
```startarch c pc tree

==> Running TermuxArch pc tree v1.6.7.id5677…

warning: tree-1.8.0-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) tree-1.8.0-1

Total Installed Size:  0.13 MiB
Net Upgrade Size:      0.00 MiB

:: Proceed with installation? [Y/n]
(1/1) checking keys in keyring                     [#########] 100%
(1/1) checking package integrity                   [#########] 100%
(1/1) loading package files                        [#########] 100%
(1/1) checking for file conflicts                  [#########] 100%
(1/1) checking available disk space                [#########] 100%
:: Processing package changes...
(1/1) reinstalling tree                            [#########] 100%
could not change the root directory (Function not implemented)
error: command failed to execute correctly
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
could not change the root directory (Function not implemented)
error: command failed to execute correctly

TermuxArch pc tree v1.6.7.id5677: DONE 🏁
```

**Comment by sdrausty** [comment]
@ExtraHash can you share `setupTermuxArch.sh sysinfo` information?

**Comment by sdrausty** [comment]
Here is a map of similar A26+ issues:

a) https://github.com/sdrausty/TermuxArch/issues/59#issuecomment-379564041 resolved by https://github.com/termux/proot/issues/13#issuecomment-379533612

b) https://github.com/termux/proot/issues?q=is%3Aissue+function+not+implemented 

c) https://github.com/sdrausty/termux-archlinux/issues?q=is%3Aissue+function+not+implemented

d) https://github.com/sdrausty/TermuxArch/issues?q=is%3Aissue+function+not+implemented

Consider sharing at https://github.com/termux/proot/issues/ as this is how A26+ was resolved https://github.com/sdrausty/termuxarch/issues?q=is%3Aissue+label%3AA26%2B for the most part.bb

**Comment by qianbaiducode** [comment]
I have the same issue
Phone model: xiaomi 8se
Android version: 9.0 (MIUI10)
Linux kernel version: 4.9.112
 
Previous Android 8.0 can be used normally, kernel version 4.9.80，So this is a problem with the new kernel?

**Comment by sdrausty** [comment]
@qianbaiducode the best places to ask:
> So this is a problem with the new kernel?

Are:
https://github.com/termux/proot
https://github.com/termux/termux-packages

I cannot as I was banned in September, 2018.

**Comment by SDRausty** [comment]
https://github.com/termux/proot/issues?q=is%3Aissue+%22root+directory%22

**Comment by SDRausty** [comment]
@CorvetteCole @Frostbyrne Android Studio is easily available as of last month on smartphone with the latest commits:
```
[user21:33~]$ makeyay
Building and installing 'yay':
When this message:
libtool: warning: remember to run 'libtool --finish /usr/lib/libfakeroot'
When this message is displayed on the screen 'makeyay' will deal with it a little bit later in the build proccess, and there will be a short pause when this message is displayed:
"Libraries have been installed in:"
A difficult part of any build process can be choosing the correct answers.  Here are the correct answers:
:: fakeroot-tcp and fakeroot are in conflict. Remove fakeroot? [y/N] y
Tap the 'y' key first, then enter.  For the first question, the 'y' key must be tapped first, then enter.  Yes will be chosen when enter is tapped in all of the questions after the first question:
:: Proceed with installation? [Y/n]
Tap enter x4 as this build proccess continues.  If everything goes well, you will see these messages:
Libraries have been installed in:
makefakeroottcp  2.0.476: DONE 🏁
and then this will go on to make 'yay' which is much simpler.  It is simply tapping enter which chooses the yes answer.
⋮
Paths that can be followed after building 'yay' are 'yay cmatrix' which builds matrix screensavers.  The commands 'yay pikaur|pikaur-git|tpac' build more aur installers thst can also be used to download aur repositories and build packages like with 'yay' in your smartphone, tablet, wearable and more...  Did you know that 'android-studio' is available with the command 'yay android'?
If you have trouble importing keys, this command 'gpg --keyserver keyserver.ubuntu.com --recv-keys 71A1D0EFCFEB6281FD0437C71A1D0EFCFEB6281F' might help.  Change the number to the number of the key being imported.
Building and installing yay: DONE 🏁
makeyay  2.0.489: DONE 🏁
[user21:42~]$ yay android studio
8 aur/php-android-cli-git 3937963d3bde24a3dcfe99325242e3cfc7f905e0-1 (+0 0.00)
    PHP Android Clit to create/generate Scaffold Android-Studio Gradle project
7 aur/android-studio-dummy 2.2.3.0-1 (+3 0.00)
    The official Android IDE, dummy package
6 aur/android-studio-launcher 1:1.0.3-1 (+6 0.92)
    Wrap android-sdk directory in UnionFS to be "writeable" for Android Studio
5 aur/tuxjdk 8.152.03-2 (+6 0.02)
    Enhanced Open Java Development Kit for developers on Linux. Contains series of patched to OpenJDK to enhance user experience with Java-based and Swing-based tools (NetBeans, Idea, Android Studio, etc)
4 aur/android-studio-beta 4.1.0.15-1 (+9 0.00)
    The Official Android IDE (Beta branch)
3 aur/apkstudio-git 1:r211.5b6f115-1 (+21 0.00) (Out-of-date: 2019-09-15)
    An IDE for decompiling/editing & then recompiling of android application binaries.
2 aur/android-studio-canary 4.2.0.9-1 (+53 0.00)
    The Official Android IDE (Canary branch)
1 aur/android-studio 4.0.1.0-1 (+925 7.90)
    The official Android IDE (Stable branch)
==> Packages to install (eg: 1 2 3, 1-3 or ^4)
==>
```

**Comment by CorvetteCole** [comment]
Awesome, great to hear

**Comment by SDRausty** [comment]
Glad that you like the news.

**Comment by qaiu** [comment]
nice
