### ISSUE TITLE
docs/proot: inaccurate information regarding Linux distributions

### ISSUE THREAD

**Issue by oxr463** [SDRausty/TermuxArch#146]
> Benefits of PRoot include running Linux operating systems in Termux on a smartphone and tablet in Android and Chrome. Termux offers Linux operating system software for your device in the following flavors: --[PRoot.md](https://github.com/sdrausty/docsTermuxArch/blob/master/PRoot.md)

**BSD != Linux**

While running a BSD userland under Linux is possible, it is highly unlikely that the following UNIX-like operating systems will run in PRoot:

- FreeBSD
- GhostBSD
- OpenBSD

The PRoot website (<https://proot-me.github.io/#rootfs>), lists root file systems that can
be downloaded and are expected to work in PRoot.

Also, Gentoo Linux support varies due to miscellaneous privilege issues (See instead: http://wiki.gentoo.org/wiki/Project:Android).

See also: https://github.com/proot-me/PRoot/issues/155

**Comment by sdrausty** [comment]
@oxr463 you are welcome to submit a pull request https://github.com/sdrausty/docsTermuxArch/pulls here.

**Comment by SDRausty** [comment]
@oxr463 [e.g.|for example]
https://github.com/TermuxArch/docsTermuxArch/pulls

**Comment by oxr463** [comment]
Unfortunately, I do not have time for this right now.

Also, I think the label is incorrect, since this information is incorrect.

**Comment by SDRausty** [comment]
@oxr463 thank you for updating;  The https://us.images.linuxcontainers.org/images/ link is captivating.

**Comment by SDRausty** [comment]
@oxr463 do you know why *BSD has errors like:
`proot error: execve("/usr/bin/env"): Function not implemented` and similar.  You mentioned:
> While running a BSD userland under Linux is possible, it is highly unlikely that the following UNIX-like operating systems will run in PRoot:

To reproduce:
```
$ mkdir arch
$ cd arch
$ curl -O https://cloudflare.cdn.openbsd.org/pub/OpenBSD/6.6/arm64/base66.tgz
$ proot --link2symlink -0 bsdtar -xf xbase66.tgz
$ touch bin/we
$ mkdir root/bin
$ mkdir var/binds
$ bash ../setupTermuxArch.bash re
.
.
.
$ startarch
proot error: execve("/usr/bin/env"): Function not implemented
proot info: possible causes:
  * the program is a script but its interpreter (eg. /bin/sh) was not found;
  * the program is an ELF but its interpreter (eg. ld-linux.so) was not found;
  * the program is a foreign binary but qemu was not specified;
  * qemu does not work correctly (if specified);
  * the loader was not found or doesn't work.
fatal error: see `proot --help`.
proot error: can't chmod '/data/data/com.termux/files/usr/tmp/proot-28238-4YnzMQ': No such file or directory
$ l usr/bin/env
-r-xr-xr-x 1 133600 Oct 12 20:00 usr/bin/env

```
Why are errors like the one above occuring in *BSD?

**Comment by oxr463** [comment]
> What causes errors like this one in *BSD?

The answer is in the log:

```sh
  * the program is an ELF but its interpreter (eg. ld-linux.so) was not found;
```
