### ISSUE TITLE
Problem when cloning any git repository

### ISSUE THREAD

**Issue by MortadhaAlaa** [sdrausty/TermuxArch#15]
`[root@localhost /]# git clone https://github.com/robbyrussell/oh-my-zsh.git
Cloning into 'oh-my-zsh'...
fatal: unable to access '/root/.config/git/config': Invalid argument`

**Comment by Soph1a7** [comment]
Your directory seems to be on root (/)
Try changing it to your home directory (cd ~) and cloning there.
If it still doesn't work try reinstalling git.

**Comment by MortadhaAlaa** [comment]
hoem directory is setup to /root
Problem persists after reinstalling and cd'ing there

**Comment by Soph1a7** [comment]
I just setup a fresh install of git and did some user config to it on ~/.config/git/config and with/without the configuration the oh-my-zsh clone worked. Other repositories work too.
And this issue doesn't really belong to this repository as this script is designed to install arch.
