### ISSUE TITLE
bash: warning: setlocale: LC_COLLATE: cannot change locale (en_IN.UTF-8): No such file or directory

### ISSUE THREAD

**Issue by remo7777** [sdrausty/TermuxArch#151]
# Begin TermuxArch v1.6.2.id7525 system information.

`dpkg --print-architecture result:

aarch64

uname -a results:

Linux localhost 3.18.31-perf-gdedd3c8 #1 SMP PREEMPT Tue Nov 14 15:00:16 CST 2017 aarch64 Android

BASH_VERSINFO[0] = 4
BASH_VERSINFO[1] = 4
BASH_VERSINFO[2] = 23
BASH_VERSINFO[3] = 1
BASH_VERSINFO[4] = release
BASH_VERSINFO[5] = aarch64-unknown-linux-android

cat /proc/cpuinfo results:

Processor	: AArch64 Processor rev 4 (aarch64)
processor	: 0
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 1
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 2
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 3
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 4
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 5
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 6
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

processor	: 7
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Hardware	: Qualcomm Technologies, Inc MSM8937

Download directory information results:

/sdcard/Download exists
/storage/emulated/0/Download exists
/data/data/com.termux/files/home/downloads exists
/data/data/com.termux/files/home/storage/downloads exists

Device information results:

/dev/ashmem exists
/dev/ashmem is readable
/dev/shm does not exist
/dev/shm is not readable
/proc/stat exits
/proc/stat is readable

getprop results:

[getprop gsm.sim.operator.iso-country]: [in]
[getprop net.bt.name]: [Android]
[getprop net.dns1]: [49.45.0.1]
[getprop net.dns2]: [2405:200:800::1]
[getprop net.dns3]: []
[getprop net.dns4]: []
[getprop persist.sys.locale]: [en-IN]
[getprop ro.build.target_country]: []
[getprop ro.build.version.release]: [7.0]
[getprop ro.build.version.preview_sdk]: [0]
[getprop ro.build.version.sdk]: [24]
[getprop ro.com.google.clientidbase]: [android-lenovo]
[getprop ro.com.google.clientidbase.am]: [android-lenovo]
[getprop ro.com.google.clientidbase.ms]: [android-lenovo]
[getprop ro.product.device]: [K53a48]
[getprop ro.product.cpu.abi]: [arm64-v8a]
[getprop ro.product.first_api_level]: []
[getprop ro.product.locale]: [en-US]
[getprop ro.product.manufacturer]: [LENOVO]
[getprop ro.product.model]: [Lenovo K53a48]

Disk report 4120280 on /data Tue Jan 29 19:43:49 IST 2019

df /data/data/com.termux/files/home/arch results:

Filesystem      1K-blocks     Used Available Use% Mounted on
/dev/block/dm-0  25150792 20997748   4120276  84% /data

df results:

Filesystem                            1K-blocks     Used Available Use% Mounted on
rootfs                                  1756068     5560   1750508   1% /
tmpfs                                   1837436      620   1836816   1% /dev
tmpfs                                   1837436        0   1837436   0% /mnt
/dev/block/bootdevice/by-name/system    3499436  2806260    676792  81% /system
/dev/block/bootdevice/by-name/preload    396744   128592    259960  34% /preload
/dev/block/bootdevice/by-name/cache      253920     1596    247084   1% /cache
/dev/block/bootdevice/by-name/dsp         12016     5052      6640  44% /dsp
/dev/block/bootdevice/by-name/modem       80560    62648     16192  80% /firmware
/dev/block/dm-0                        25150792 20997748   4120276  84% /data
/dev/fuse                              25150792 20997748   4120276  84% /storage/emulated
/dev/fuse                              31248384 16424096  14824288  53% /storage/9016-4EF8

du -hs /data/data/com.termux/files/home/arch results:

912M	/data/data/com.termux/files/home/arch

ls -al /data/data/com.termux/files/home/arch results:

total 72
drwx------ 16 u0_a123 u0_a123 4096 Jan 29 19:41 .
drwx------ 22 u0_a123 u0_a123 4096 Jan 29 19:43 ..
lrwxrwxrwx  1 u0_a123 u0_a123    7 Jan 29 19:08 bin -> usr/bin
drwxr-xr-x  3 u0_a123 u0_a123 4096 Jan 29 19:19 boot
drwxr-xr-x  2 u0_a123 u0_a123 4096 Jan 21 01:41 dev
drwxr-xr-x 39 u0_a123 u0_a123 4096 Jan 29 19:27 etc
drwxr-xr-x  3 u0_a123 u0_a123 4096 Jan 29 19:08 home
lrwxrwxrwx  1 u0_a123 u0_a123    7 Jan 29 19:08 lib -> usr/lib
drwxr-xr-x  2 u0_a123 u0_a123 4096 Dec 26 20:26 mnt
drwxr-xr-x  2 u0_a123 u0_a123 4096 Dec 26 20:26 opt
dr-xr-xr-x  2 u0_a123 u0_a123 4096 Jan 21 01:41 proc
drwxr-x---  4 u0_a123 u0_a123 4096 Jan 29 19:23 root
drwxr-xr-x  3 u0_a123 u0_a123 4096 Jan 21 01:41 run
lrwxrwxrwx  1 u0_a123 u0_a123    7 Jan 29 19:08 sbin -> usr/bin
drwxr-xr-x  4 u0_a123 u0_a123 4096 Jan 29 19:08 srv
-rwx------  1 u0_a123 u0_a123 6504 Jan 29 19:27 startarch
dr-xr-xr-x  2 u0_a123 u0_a123 4096 Jan 21 01:41 sys
drwxrwxrwt  3 u0_a123 u0_a123 4096 Jan 29 19:43 tmp
drwxr-xr-x  8 u0_a123 u0_a123 4096 Jan 29 19:21 usr
drwxr-xr-x 13 u0_a123 u0_a123 4096 Jan 29 19:19 var`

# End `setupTermuxArchSysInfo82bd.log` v1.6.2.id7525 system information.

**Comment by sdrausty** [comment]
@remo7777 see whether this search "locale.gen site:archlinux.org" helps out with the LC error.  Removing the corresponding export lines from `bash_profile` might fix the error cosmetically, too.

**Comment by remo7777** [comment]
> @remo7777 see whether this search "locale.gen site:archlinux.org" helps out with the LC error. Removing the corresponding export lines from `bash_profile` might fix the error cosmetically, too.

your right `/etc/locale.gen` need to manually edit according to locale then execute `locale.gen`
