### ISSUE TITLE
No install "proot info: vpid 1: terminated with signal 9"

### ISSUE THREAD

**Issue by sorryusernameisalreadytaken** [sdrausty/TermuxArch#152]
Hey.

I try to run the setupTermuxArch.sh and it download the necessary arch files but at the end there is a message:

`proot info: vpid 1: terminated with signal 9`

` TermuxArch WARNING:    Generated script signal 255 near or at line number 600 by 'trap'!`

`setupTemuxArch.sh v1.6.7.id5677:  [Exit Signal 201] DONE`

Here is my attached sysinfo:
[setupTermuxArchSysInfo3d79.log](https://github.com/sdrausty/TermuxArch/files/2818015/setupTermuxArchSysInfo3d79.log)

<br>

**Comment by sorryusernameisalreadytaken** [comment]
I already purge it twice the last time with the **purge** command.

But I did the following now to get a clear termux:
-uninstall termux
-get sure that the folder /data/data/com.termux is removed
-install termux again from play:store
-I follow step 2 from this link https://sdrausty.github.io/TermuxArch/docs/install
-> ### ls -al /data/data/com.termux/files/home/arch
results are the same as you mentioned above.

Here is the output from the installer:
[setup-script.txt](https://github.com/sdrausty/TermuxArch/files/2825391/setup-script.txt)

The same message.

GReetings by Uniat

**Comment by sdrausty** [comment]
@sorryusernameisalreadytaken change `set -Eeuo pipefail` to `set -Eexuo pipefail` in setupTermuxArch.sh and see whether the script will reveal where it fails.

**Comment by sdrausty** [comment]
Also see whether changing:
```
necessaryfunctions.sh:          proot --link2symlink -0 "$PREFIX"/bin/applets/tar -xpf "$file"
setupTermuxArch.sh:             proot --link2symlink -0 "$PREFIX"/bin/applets/tar xf 
```
To:
```
necessaryfunctions.sh:          proot --link2symlink -0 "$PREFIX"/bin/bsdtar -xpf "$file"
setupTermuxArch.sh:             proot --link2symlink -0 "$PREFIX"/bin/bsdtar xf 
```
Will help; install `bsdtar` to see if this method works.

**Comment by sorryusernameisalreadytaken** [comment]
Seems to be something with the proot cmd:
`
While waiting, you can use df, du -hs, htop, ps, top and watch in a new Termux session to watch the unpacking while the session completes.  Use info query and man query to learn more about your Linux system in the palm of your hand.  See The Linux Documentation Project http://tldp.org to learn more about Linux and CLI commands.  Unpacking ArchLinuxARM-armv7-latest.tar.gz will take a long time; Be patient…                                        
+ printf '\e[0;32m'
+ _PREPROOT_
+ [[ armeabi-v7a = \x\8\6 ]]
+ [[ armeabi-v7a = \x\8\6\_\6\4 ]]                      + proot --link2symlink -0                               proot error: '/bin/sh' not found (root = /, cwd = /data/data/com.termux/files/home/arch, $PATH=(null))
fatal error: see `proot --help`.
++ _STRPERROR_ 601 trap '_STRPERROR_ 331 proot --link2symlink -0 1' ERR 0
++ local RV=1                                           ++ printf '\e[?25h\n\e[1;48;5;138m %s\e[0m\n' 'TermuxArch WARNING:  Generated script signal 1 near or at line number 601 by `trap`!'                                    
 TermuxArch WARNING:  Generated script signal 1 near or at line number 601 by `trap`!
++ [[ 1 = 4 ]] 
++ printf '\n'`

**Comment by sdrausty** [comment]
@sorryusernameisalreadytaken from your system information log:

`[getprop ro.build.version.sdk]: [25]`
a) There should not be issues with this sdk version.

`/dev/block/loop0          96724     4764     91960   5% /su`
b) Is your device rooted?

> Seems to be something with the proot cmd:

c) You might want to touch the issues https://github.com/termux/proot/issues here.
