### ISSUE TITLE
Instructions for newbies

### ISSUE THREAD

**Issue by jdnichollsc** [sdrausty/TermuxArch#153]
How can we execute TermuxArch after install the first time?
Also, what's the best way to install Java with JDK?

Thanks in advance!

**Comment by sdrausty** [comment]
@jdnichollsc I see that you found the answer to your first question.  `startarch` information was just added https://github.com/sdrausty/TermuxArch/pull/148 here.

> Also, what's the best way to install Java with JDK?

The TermuxArch command [`pci`](https://github.com/sdrausty/TermuxArch/blob/master/archlinuxconfig.sh#L479) has options for installing Java with a development environment.  More information: search install java site:archlinux.org

You can can add to the documentation if you like here:
a) https://github.com/sdrausty/TermuxArch/pulls
b) https://github.com/sdrausty/docsTermuxArch/pulls

## pull requests are simple:
#### a) fork repository
#### b) make change
#### c) push change

**Comment by jdnichollsc** [comment]
@sdrausty thanks for your help. 
The command is:
pacman -Syy; pacman -Su; pacman -S jdk8-openjdk

But what's the recommended way to set the **ANDROID_HOME** variable in TermuxArch?
