### ISSUE TITLE
How to use VSCode in TermuxArch?

### ISSUE THREAD

**Issue by jdnichollsc** [SDRausty/TermuxArch#154]
Hi guys,
Thanks for this project! Is it possible to install VSCode from TermuxArch?

Thanks in advance!

**Comment by sdrausty** [comment]
@jdnichollsc try this search: VSCode site:archlinux.org

**Comment by sdrausty** [comment]
This link https://wiki.archlinux.org/index.php/Visual_Studio_Code looks promising.  You are welcome.

**Comment by jdnichollsc** [comment]
I downloaded the snapshot but it doesn't work
ˋˋˋ
[root19:30downloads]$ tar -xzvf visual-studio-code-bin.tar.gz
visual-studio-code-bin/
visual-studio-code-bin/.SRCINFO                                                visual-studio-code-bin/PKGBUILD
visual-studio-code-bin/visual-studio-code-url-handler.desktop
visual-studio-code-bin/visual-studio-code.desktop                              [root19:31downloads]$ cd visual-studio-code-bin
[root19:31visual-studio-code-bin]$ makepkg -s
==> ERROR: Running makepkg as root is not allowed as it can cause permanent,
catastrophic damage to your system.
[root19:31visual-studio-code-bin]$ su jdnichollsc
[jdnichollsc@localhost visual-studio-code-bin]$ makepkg -s
==> ERROR: visual-studio-code-bin is not available for the 'aarch64' architecture.
ˋˋˋ
Thanks for your help

**Comment by jdnichollsc** [comment]
As you can see I've already searched from Google before to ask here but nothing works
I was asking if it's possible, sorry for my newbie question

**Comment by sdrausty** [comment]
> ERROR: Running makepkg as root is not allowed as it can cause permanent,
catastrophic damage to your system.

See these https://github.com/sdrausty/TermuxArch/issues?q=label%3Amakepkg regarding the makepkg error.  Consider a https://github.com/sdrausty/docsTermuxArch/pulls request to share with users.

**Comment by jdnichollsc** [comment]
I would love to create a pull request from the documentation of this project like "How can you run React Native Apps from your cellphone using TermuxArch", but after fix my issues to have the list of the commands required to do that :)

**Comment by top1Ashier** [comment]
vscodium is what u need ，and u can install it from aur which called vscodium-bin-mutliarch

**Comment by johndoehack** [comment]
error with ./setuptermuxarch:  the script download the tar file but after decripting tar files and running and self configuring mirror-servers i get error 416
