### ISSUE TITLE
How to run React Native Apps in TermuxArch?

### ISSUE THREAD

**Issue by jdnichollsc** [SDRausty/TermuxArch#156]
Hi S D Rausty,
This is the list with the instructions to run react native apps from x86_64 devices and running in a Linux chroot https://gist.github.com/jdnichollsc/08a0d6a1b27962c4c4dd78ffbbfe768c

@sdrausty can you confirm please? I want to share this solution and create a pull request to include from the documentation of this project 👍

**Comment by sdrausty** [comment]
@jdnichollsc try it; I got stuck at the last step...

If you run into any problems with fakeroot and makepkg:
https://github.com/sdrausty/TermuxArch/issues?q=is%3Aissue+fakeroot
https://github.com/sdrausty/TermuxArch/issues?q=is%3Aissue+makepkg

https://github.com/sdrausty/TermuxArch/issues/129

Good luck🍀

**Comment by jdnichollsc** [comment]
Let me try docsBuildAPKs solution, I don't have a x86_64 device to try these commands ^^

**Comment by sdrausty** [comment]
>  don't have a x86_64

You don't need one for React Native.  As far as I know, it should work on all architectures.
