### ISSUE TITLE
issues when a program instslls configs in /etc

### ISSUE THREAD

**Issue by Merith-TK** [sdrausty/TermuxArch#158]
``[/usr/lib/tmpfiles.d/journal-nocow.conf:26] Failed to resolve specifier: uninitialized /etc detected, skipping``

when i try to install sudo or openssh (no root access on tablet) so i can use the AUR

**Comment by sdrausty** [comment]
> can use the AUR

Y PLZ SEARCH

**Comment by sdrausty** [comment]
https://github.com/sdrausty/TermuxArch/issues?utf8=✓&q=is%3Aissue+aur

**Comment by sdrausty** [comment]
https://github.com/sdrausty/TermuxArch/issues?utf8=✓&q=is%3Aissue+aur+makepkg

**Comment by Merith-TK** [comment]
Dude. The simple fact is, (for me anyways) when something uses permissions and writes config files to said permissions. It fails with this error.

This is program breaking bug for me
