### ISSUE TITLE
Install in ~/storage/external-1

### ISSUE THREAD

**Issue by craftersmine** [sdrausty/TermuxArch#159]
Hello everyone! I have an issue with installation, I have my old phone and want to install TermuxArch on it but it is low on internal storage, can I install TermuxArch into ~/storage/external-1. Thanks

**Comment by sdrausty** [comment]
Share your progress @craftersmine for if this feature were to be available...

**Comment by craftersmine** [comment]
Oh, wait, I forgot a question mark, this is a question, can I install TermuxArch into ~/storage/external-1 or not?

**Comment by sdrausty** [comment]
Hi @craftersmine this feature can be added like https://github.com/sdrausty/TermuxArch/blob/master/archlinuxconfig.sh#L588 trim was added before the ban...

**Comment by sdrausty** [comment]
Much of the system CAN BE moved to external, and then symlinked, etc...
