### ISSUE TITLE
Cannot access termux root/

### ISSUE THREAD

**Issue by Harshiv-Patel** [sdrausty/TermuxArch#16]
while it's wonderful to have a full fledged Linux distro in our phones, I think there is plenty of room there for improvement.
I'm running on Lollipop 5.1.1 armv7l, 
For some reason output of 'ls' command has been set to b/w  and needs "--color=always"
Also once logged, user is sort of locked in to "~/arch/" directory, this one is a harsh limitation that combined with Interpreted environment feels less flexible compared to default Termux environment. 
I think you must have seen it coming that, for a distribution like this, the default internal space of device storage will quickly fill up. Support for external SD cards would be great.
Vim 8.x seems to look for VIMRUNTIME files in "/share/vim/vim80" whereas actual files reside in "/usr/share/vim/vim80"

**Comment by Soph1a7** [comment]
First of all, the goal is to sort lock you out to ~/arch since that's exactly how a chroot works (feel free to search further onto it).
Second, it would not be possible to move it to an external location, or any location outside of termux's directory since you cannot set permissions/ownership on external media storage locations. Both of these issues aren't in any way related to this script.
Regarding the last, vim seems functional on this install; try reinstalling it.

**Comment by Harshiv-Patel** [comment]
Regarding external storage, if one were to create an extra partition (ext 2/3/4) on the Micro SD card, would it be possible to mount it in archLinux environment ?  It is rather hackish way to go, but limited device storage gets filled very quickly. I still wish that I could access sdcard/extSD card, even if as Read only storage.

**Comment by Soph1a7** [comment]
even if the partition were extx, I don't think you can set ownership/permissions correctly on external media storage on android, it's a limitation of the system (if you consider it one).
Again, not an issue of the script.

**Comment by sdrausty** [comment]
See https://wiki.termux.com/wiki/Termux-setup-storage for information how to access the external SD card on your device. Also add "--color=always" to your ls command customisation in `.bashrc` to colorize your screen output.

**Comment by sdrausty** [comment]
@Harshiv-Patel regarding storage, see Feature Request: `mount loopback device` #376 https://github.com/termux/termux-app/issues/376 and Does Anyone Want to Have More Native Space on Device? #1176 https://github.com/termux/termux-packages/issues/1176 for more information.
