### ISSUE TITLE
in China

### ISSUE THREAD

**Issue by zaoqi-unsafe** [SDRausty/TermuxArch#164]
===============================================
[#4aeffd 1.4MiB/464MiB(0%) CN:1 DL:26KiB ETA:4h59m58s]
FILE: /data/data/com.termux/files/home/arch/ArchLinuxARM-aarch64-latest.tar.gz
-----------------------------------------------

**Comment by zaoqi** [comment]
`aria2c -s 10 -j 10 -x 10 -k 1M` may be faster

**Comment by echizenryoma** [comment]
你可以使用中国科技大学的源http://mirrors.ustc.edu.cn/archlinuxarm/

**Comment by Sparky-14145** [comment]
@echizenryoma 如何修改下载源（安装时）

再就是怎么解决 'termux tar: can't create symlink '': Permission denied'的 的问题？

**Comment by sdrausty** [comment]
@Sparky-14145 use `ln -s` to create symbolic links.

**Comment by SDRausty** [comment]
https://github.com/SDRausty/TermuxArch/issues/179#issuecomment-517108066 : you can create the symbolic links manually by symlinking to `$PREFIX/bin/busybox`:
```
cd $PREFIX/bin/applets/
ln -s ../busybox awk
ln -s ../busybox sha512sum
ln -s ../busybox rev
ln -s ../busybox tar
ln -s ../busybox uname
```
Run `setupTermuxArch.sh` again.
```
cd
bash setupTermuxArch.sh h # for more information
```

**Comment by ZenithalHourlyRate** [comment]
> 如何修改下载源（安装时）

As for changing download mirror, you can run `bash setupTermuxArch.sh manual` instead of `bash setupTermuxArch.sh`, and change all 
```
CMIRROR=os.archlinuxarm.org
PATH=/os/
```
to (or any other mirror)
```
CMIRROR=mirrors.tuna.tsinghua.edu.cn
PATH=/archlinuxarm/os/
```
