### ISSUE TITLE
Glibc implementation

### ISSUE THREAD

**Issue by allanrps** [SDRausty/TermuxArch#167]
I am wondering how glibc was implemented into TermuxArch. My understanding is that Termux itself uses Bionic libc and the Termux API to communicate with the kernel. Where does Termux arch get the kernel headers and API? I'm trying to compile an application for Termux from within TermuxArch and am playing with how I could implement glibc how you have or get the compiled application to play with bionic.

Thanks for the help, feel free to email me at allanrpsx@gmail.com if this doesn't belong here.

**Comment by SDRausty** [comment]
> I am wondering how glibc was implemented into TermuxArch. 

@allanrps https://github.com/termux/proot/issues?q=is%3Aissue+glibc
