### ISSUE TITLE
makepkg & groups do not function

### ISSUE THREAD

**Issue by IamPARANOID** [sdrausty/TermuxArch#171]
Use case is to be able to install packages from the AUR.

Logical starting point: Install ``yay``.
The PKGBUILD is downloaded, but ``makepkg -s`` can't be run as root (though it does require a password to act as root).
Next move, add a user that isn't root: ``startarch c adduser user username``
Result: ``/bin/bash: adduser: command not found``
``adduser`` does not exist in either Termux or Arch apparently, in Arch they want you to use ``useradd`` as ``adduser`` is _[not real](https://bbs.archlinux.org/viewtopic.php?id=156386)_ in the Arch ecosystem.
Recourse: Add a user manually using ``useradd username`` inside the proot, then add to group wheel (``usermod -aG wheel username``), and uncomment `` %wheel ALL=(ALL) NOPASSWD: ALL`` in visudo:
``groups username`` run as root or username show username as being in wheel, but if just ``groups`` is run as username then it does not show as being in wheel.
Wheel group is set not to ask for a password, yet ``sudo`` requires ones and then fails with "user is not in the sudoers file", further proving it is not in the wheel group.

What do?

**Comment by sdrausty** [comment]
https://github.com/sdrausty/TermuxArch/issues?q=is%3Aissue+makepkg

**Comment by sdrausty** [comment]
https://github.com/sdrausty/termux-archlinux/issues?q=is%3Aissue+makepkg

**Comment by IamPARANOID** [comment]
So after _further_ reading it would seem:

1. ``addauser`` and ``adduser`` are not to be confused, ``addauser``, or more specifically ``startarch c addauser user username`` works (confusion because ``adduser`` is real command in some distros).
2. Even after patching ``makepkg`` as in #38, ``/dev/fd/62`` becomes an issue, apparently only on older Android versions (I'm on 5.1.1).

I do however have root access if that could be of any help at all.

**Comment by IamPARANOID** [comment]
As root doing ``ln -s /proc/self/fd /dev/fd`` fixed the ``/dev/fd/62`` issue.
See: http://www.ducea.com/2009/02/18/linux-tips-bash-completion-devfd62-no-such-file-or-directory/

To enable root (in LineageOS 12.1 anyway) go to Developer Options -> Root access and set to at least "Apps only".

However, the patch did not work correctly I believe, and only partially patched it, so now I have this error:
``Do not use the '-F' option. This option is only for internal use by makepkg.``.

**Comment by IamPARANOID** [comment]
Reinstalling the pacman package (which contains makepkg), ``pacman -S pacman``, fixes the issue, by undoing the patch.

``yay`` still requires a sudo password however, and will not run as root.

**Comment by sdrausty** [comment]
> have root access if that could be of any help at all.

Root access to Android is not required.

> requires a sudo password

https://duckduckgo.com/html?q=add+user+to+sudo+Arch+Linux

**Comment by sdrausty** [comment]
> Add a user manually

Use `startarch command addauser user` first to create a user and user's home directory.

```
$ startarch help

startarch: Start Arch Linux as root.  This account is reserved for system administration.

startarch c[md] cmd: Run Arch Linux command from Termux as root user.

startarch u[ser]|l[ogin] user: Login as user.  Use startarch c addauser user first to create this user and user's home directory.

startarch r[aw]: Construct the startarch proot statement from exec.../bin/.  For example startarch r su will exec su in Arch Linux.

startarch s[u] user cmd: Login as user and execute command.  Use startarch c addauser user first to create this user and user's home directory.`
```

**Comment by IamPARANOID** [comment]
https://aur.archlinux.org/packages/nosudo/ is your friend.
Manually installing nosudo, then setting a password for root (Arch's root), will get you as far as ``Password: su: Authentication token manipulation errorexit status 1``, unless you log out & log back in.
Then ``yay`` works.

https://askubuntu.com/questions/57620/getting-an-authentication-token-manipulation-error-when-trying-to-change-my-us

> Root access to Android is not required.

It is required for creating the symlink for ``/dev/fd/62``.

>https://duckduckgo.com/html?q=add+user+to+sudo+Arch+Linux

I did add the user to wheel (the sudo group on Arch), but as I stated in the OP, it _does not actually set_.

**Comment by sdrausty** [comment]
> creating the symlink for...

Try creating like [`PROOTSTMNT+="-b /proc/self/fd/1:/dev/stdout "`](https://github.com/sdrausty/TermuxArch/blob/master/knownconfigurations.sh#L86) this, instead of symlink.

>[To regenerate the start script use \`setupTermuxArch.sh re[fresh]\`.  An example is included for convenience.  Usage: PROOTSTMNT+=\"-b host_path:guest_path \" The space before the last double quote is necessary.  Appending to the PRoot statement can be accomplished on the fly by creating a *.prs file in /var/binds.  The format is straightforward, `PROOTSTMNT+="option command "`.  The space is required before the last double quote.  `info proot` and `man proot` have more information about what can be configured in a proot init statement.  `setupTermuxArch.sh manual refresh` will refresh the installation globally.  If more suitable configurations are found, share them at https://github.com/sdrausty/TermuxArch/issues to improve TermuxArch.](https://github.com/sdrausty/TermuxArch/blob/master/knownconfigurations.sh#L59)

**Comment by sdrausty** [comment]
@IamPARANOID any luck with PRoot mounts?  You can find an example file in ~/arch/var/binds/.

**Comment by sdrausty** [comment]
@IamPARANOID any luck with using PRoot mounts instead of using `ln`?  You can find an example file in ~/arch/var/binds/:  
```
$ startarch c cat /var/binds/fbindexample.prs
# Hosting sdrausty.github.io/TermuxArch courtesy https://pages.github.com.
# https://sdrausty.github.io/TermuxArch/README has info about this project.
# https://sdrausty.github.io/TermuxArch/CONTRIBUTORS Thank you for your help.
# To regenerate the start script use `setupTermuxArch.sh re[fresh]`.  Add as many proot statements as you want; The init script will parse this file at refresh.  Examples are included for convenience.  Usage: PROOTSTMNT+="-b host_path:guest_path " The space before the last double quote is necessary.
################################################################################
# PROOTSTMNT+="-b /data/data/com.termux/files/home/arch/var/binds/fbindprocstat:/proc/stat "
# if [[ ! -r /dev/shm ]] ; then
#               PROOTSTMNT+="-b /data/data/com.termux/files/home/arch/tmp:/dev/shm "
# fi
```
Modify this file.  Then run `$ startarch`😀

**Comment by IamPARANOID** [comment]
@sdrausty Nope.

I tried multiple options, including the one you quoted, the one you quoted but to ``/dev/fd/1``, mounting each 'file' in ``/dev/fd``, or just mounting the entire directory.
None worked.
Some notes that may or may not be relevant:
- ``/proc/self/fd/3`` would not mount.
- /dev/fd/62 isn't actually a real "file or directory" in ``/dev/fd/`` even when symlinked, meaning it is some  "file or directory" in the symlinked ``/dev/fd`` that ``makepkg`` takes to mean ``/dev/fd/62``.
- The ``file`` command shows ``/dev/fd/1`` as a ``special character (136/0)``, where as when symlinked it just simply prints out the file name.
- ``/dev/stdout/`` exists by default.

File used was ``/var/bind/fd.prs``.

**Comment by sdrausty** [comment]
@IamPARANOID 🌺

`$ ls -al /dev/fd/{0..62}`
`$ ls -al /dev/pts/{0..62}`

Example diagnostics:
```
$ cat /var/bind/pts2.prs
 PROOTSTMNT+="-b /dev/pts/2:/dev/fd/62 "
```

Remember to login to Arch Linux for changes to take effect.  Try asking at https://gitter.im/termux and similar too.

**Comment by sdrausty** [comment]
>> Root access to Android is not required.

> It is required for creating the symlink for /dev/fd/62.

As the device is rooted/cracked your results will vary.

**Comment by sdrausty** [comment]
@IamPARANOID can you explain the motivation for using PRoot on a rooted device?

**Comment by IamPARANOID** [comment]
> @IamPARANOID can you explain the motivation for using PRoot on a rooted device?

I wanted to install PhantomJS (youtube-dl optional dep), as it was mentioned that it only worked on TermuxArch.  It appears to be dead/non-functional however, unless it is manually compiled, which can take days.

**Comment by SDRausty** [comment]
> wanted to install PhantomJS

The command `yay phantomjs` builds:
`6 aur/phantomjs-git 1:3.0.0dev+23+cb1b04bb5-1 (+0 0.00) (Installed: 1:3.0.0dev+31+0a0b0facb-1)`

> manually compiled, which can take days.

The package `phantomjs-git` compiled quickly.  To make the command `yay` you can use `makeyay`.
