### ISSUE TITLE
pip hangs after python package install

### ISSUE THREAD

**Issue by resolritter** [SDRausty/TermuxArch#172]
# steps
1. switch to root user with `su`
2. install some python package with pip. e.g. `pip install utt`
3. install succeeds, but hangs at the last step

![Screenshot_2019-06-11-07-44-41-034_com termux_1](https://user-images.githubusercontent.com/17429390/59266154-83457280-8c36-11e9-91d1-6533bf94a4bb.png)

# workaround
if you simply abort the last step with `control-c` (as you can see in the screenshot **KeyboardInterrupt**), no harm is done...

---

the exact problem is at the top of the stack trace!

**Comment by sdrausty** [comment]
What about python2?  The results should be better than python3;  Can you confirm this please?

**Comment by reaysawa** [comment]
@sdrausty I tried to install pip with python2 and had (what I assume is) the same problem

```
[root02:58no1user]$ python2 get-pip.py
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting pip
  Using cached https://files.pythonhosted.org/packages/5c/e0/be401c003291b56efc55aeba6a80ab790d3d4cece2778288d65323009420/pip-19.1.1-py2.py3-none-any.whl
Collecting wheel
  Using cached https://files.pythonhosted.org/packages/bb/10/44230dd6bf3563b8f227dbf344c908d412ad2ff48066476672f3a72e174e/wheel-0.33.4-py2.py3-none-any.whl
Installing collected packages: pip, wheel
Successfully installed pip-19.1.1 wheel-0.33.4
^CTraceback (most recent call last):
  File "get-pip.py", line 21492, in <module>
    main()
  File "get-pip.py", line 197, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 175, in bootstrap
    sys.exit(pip._internal.main(args))
  File "/tmp/tmpeKiEwk/pip.zip/pip/_internal/__init__.py", line 78, in main
  File "/tmp/tmpeKiEwk/pip.zip/pip/_internal/cli/base_command.py", line 230, in main
  File "/tmp/tmpeKiEwk/pip.zip/pip/_internal/utils/outdated.py", line 138, in pip_version_check
  File "/tmp/tmpeKiEwk/pip.zip/pip/_internal/utils/outdated.py", line 62, in save
  File "/tmp/tmpeKiEwk/pip.zip/pip/_vendor/lockfile/__init__.py", line 197
``` 

it hangs at the same point - tail end of the installation steps, while attempting to create the lock file

**Comment by reaysawa** [comment]
to chime in more, maybe this is obvious for you but running `sudo pip ...` does not work either (previously I was switching to root and executing the commands there directly)

**Comment by utzlol** [comment]
try with pypy or pypy3. That's work for me
