### ISSUE TITLE
Can't start TermuxArch, proot info: 1: terminated with signal 11

### ISSUE THREAD

**Issue by CecilRamza** [sdrausty/TermuxArch#174]
I already installed TermuxArch succesfully, but when run: `startarch` it says:

`proot info: vpid 1: terminated with signal 11`

I tried every way to start TermuxArch, the output is the same.

Device: Xiaomi Redmi 6,  MIUI ver. 10.3.2.0, Android ver. 8.1.0

**Comment by sdrausty** [comment]
@CecilRamza repost at https://github.com/termux/proot/issues
