### ISSUE TITLE
ps command fails 

### ISSUE THREAD

**Issue by tohitsugu** [SDRausty/TermuxArch#175]
ps fails with Error: /proc must be mounted

```

$ ps                                                         
PID TTY          TIME CMD                                
13675 pts/0    00:00:00  ps                                 15223 pts/0    00:00:04 bash                               25502 pts/0    00:00:00 python                             

$ startarch r ps                                                                                                          Welcome to Arch Linux in Termux!                           Install a package: pacman -S             

Error: /proc must be mounted
To mount /proc at boot you need an /etc/fstab line like:       
proc   /proc   proc    defaults                        

In the meantime, run "mount proc /proc -t proc"          
$startarch

[root23:16TermuxArchBloom]$ mount proc /proc -t proc       
mount: /proc: mount(2) system call failed: Function not implemented.
                                                  [root23:17TermuxArchBloom]$
```

**Comment by tohitsugu** [comment]
The only semi workaround I have found is to link the system directory with proot and use the/system/bin/ps command.

**Comment by sdrausty** [comment]
@tohitsugu can you please send the workaround:
```
[20:49~]$ cd arch/var/binds/
[20:50binds]$ p
/data/data/com.termux/files/home/arch/var/binds
[20:50binds]$ l
total 24
drwx------    2 u0_a146  u0_a146       4096 Jan 31 18:29 .
drwxr-xr-x   13 u0_a146  u0_a146       4096 Jun 13 12:04 ..
-rw-------    1 u0_a146  u0_a146        900 Jun 13 12:02 fbindexample.prs
-rw-------    1 u0_a146  u0_a146       2299 Jun 13 12:02 fbindprocstat
[20:50binds]$ cat fb
fbindexample.prs  fbindprocstat
[20:50binds]$ cat fbindexample.prs
# Copyright 2017-2018 by SDRausty. All rights reserved.  🌎 🌍 🌏 🌐 🗺
# Hosting sdrausty.github.io/TermuxArch courtesy https://pages.github.com.
# https://sdrausty.github.io/TermuxArch/README has info about this project.
# https://sdrausty.github.io/TermuxArch/CONTRIBUTORS Thank you for your help.
# To regenerate the start script use `setupTermuxArch.sh re[fresh]`.  Add as many proot statements as you want; The init script will parse this file at refresh.  Examples are included for convenience.  Usage: PROOTSTMNT+="-b host_path:guest_path " The space before the last double quote is necessary.
################################################################################
# PROOTSTMNT+="-b /data/data/com.termux/files/home/arch/var/binds/fbindprocstat:/proc/stat "
# if [[ ! -r /dev/shm ]] ; then
#               PROOTSTMNT+="-b /data/data/com.termux/files/home/arch/tmp:/dev/shm "
# fi
[20:50binds]$ ps
Error: /proc must be mounted
  To mount /proc at boot you need an /etc/fstab line like:
      proc   /proc   proc    defaults
  In the meantime, run "mount proc /proc -t proc"
```

**Comment by sdrausty** [comment]
PROOTSTMNT+=?

**Comment by tohitsugu** [comment]
Sure. I'm pretty sure it's not an actual workaround as it goes outside the proot jail. The fbindexample.prs is identical to yours. 

I can only get the command to run by launching the shell like so:

$  proot --kill-on-exit --link2symlink -0 -r /data/data/com.termux/files/home/arch -b /data/data/com.termux/files/home/arch/tmp:/dev/shm -b /data/data/com.termux/files/home/arch/var/binds/fbindprocstat:/proc/stat -b /proc/self/fd/1:/dev/stdout -b /proc/self/fd/2:/dev/stderr -b /data -b /dev/ -b /system/ -b /proc/ -b /sdcard -b /data/data/com.termux/files/home -b /proc/ -b /storage/ -b /sys/ -w /data/data/com.termux/files/home /usr/bin/env -i HOME=/root TERM=xterm-256color /bin/bash -l

**Comment by tohitsugu** [comment]
I add
 -b /system/ -b /proc/
and it seems to work. Not sure why mounting proc twice seems to help but earlier ps still failed when I did not

**Comment by tohitsugu** [comment]
Ah, wait I figured it out. By mounting system I'm able to use the android linker:

[root06:24home]$ /usr/bin/ps                               
Error: /proc must be mounted                                 
To mount /proc at boot you need an /etc/fstab line like:       
proc   /proc   proc    defaults                       
In the meantime, run "mount proc /proc -t proc"          

[root06:24home]$ /data/data/com.termux/files/usr/bin/ps  
PID TTY      STAT   TIME COMMAND

**Comment by SDRausty** [comment]
@tohitsugu mounting /proc twice isn't necessary.  After adding -b /system/ try:
```
startarch
cd bin
ln -s /system/bin/ps
logout
startarch
ps
```
The ps command produces desired output on aarch64, sdk 23.  As [Termux v0.63 deleted storage,](https://github.com/termux/termux-app/releases/tag/v0.63) this important feature may take a moment to automate.

**Comment by jschobben** [comment]
Faced this as well on my Nokia 8, running Android 9.
`strace ps` inside arch revealed that failing to read `/proc/uptime` was the cause.
So, another workaround is to create:
`~/arch/var/binds/fbindprocuptime.prs`
With contents:
`PROOTSTMNT+="-b /data/data/com.termux/files/home/arch/var/binds/fbindprocuptime:/proc/uptime "`
And of course create a fake `~/arch/var/binds/fbindprocuptime` too.
Then after a `setupTermuxArch.sh r`, the arch-native "ps" now also works for me!
