### ISSUE TITLE
error 403 

### ISSUE THREAD

**Issue by DannyKurniawan642** [sdrausty/TermuxArch#176]
core is up to date
error: failed retrieving file 'extra.db' from mirror.archlinuxarm.org : The requested URL returned error: 403                                                                     error: failed to update extra (unexpected error)
error: failed retrieving file 'community.db' from mirror.archlinuxarm.org : The requested URL returned error: 403                                                                 error: failed to update community (unexpected error)
error: failed retrieving file 'alarm.db' from mirror.archlinuxarm.org : The requested URL returned error: 403
error: failed to update alarm (unexpected error)
error: failed retrieving file 'aur.db' from mirror.archlinuxarm.org : Operation too slow. Less than 1 bytes/sec transferred the last 10 seconds
error: failed to update aur (download library error)                                     error: failed to synchronize all databases

**Comment by sdrausty** [comment]
Edit ~/arch/etc/pacman.d/mirrorlist and change your mirror to a faster one.

**Comment by sdrausty** [comment]
See if the [~/buildAPKs/scripts/build/build.github.bash](https://github.com/BuildAPKs) https://github.com/DannyKurniawan642 command can help you with resolving Android issues too
