### ISSUE TITLE
"WARNING sha512sum mismatch!" How can I solve this?

### ISSUE THREAD

**Issue by perrsona1234** [SDRausty/TermuxArch#177]
![Screenshot_20190727-113034_Termux](https://user-images.githubusercontent.com/20409397/61992841-b7001e80-b063-11e9-9667-a084f806901b.png)

I'm trying to install Arch, but I get this error. Waiting a while does not fixes it. Both curl and wget are not working.

What I tried:
-waiting a while 😂
-cleaning termux app data
-reinstalling termux
-using wget instead of curl

Commands I have executed:
pkg install proot wget
wget https://raw.githubusercontent.com/TermuxArch/TermuxArch/master/setupTermuxArch.sh
bash setupTermuxArch.sh

From earlier closed issues, I know that some wget versions were bugged. 
Could this be also the issue this time? 
Installing downgraded wget should work?

**Comment by DeadlyByNite** [comment]
Exact same issue here as well. Seems like dev might be on vacation or something and he will surely fix it soon.

**Comment by SDRausty** [comment]
@perrsona1234 do you have any idea why the sha512sum symlink is missing?  See https://github.com/SDRausty/termux-archlinux/issues/35 about a similar situation.  The simplest solution is to recreate the symlink.

**Comment by SDRausty** [comment]
@DeadlyByNite any idea why the symlink is missing on your system as well?

**Comment by SDRausty** [comment]
This symlink comes from busybox.  As this is a Termux package, busybox issues are https://github.com/termux/termux-packages/issues at this link.

**Comment by SDRausty** [comment]
> You can create sha512sum manually by symlinking to $PREFIX/bin/busybox:

```
cd $PREFIX/bin/applets/
ln -s ../busybox sha512sum
```

> Any idea why the symlink sha512sum is missing?  

This symlink comes from busybox.  As busybox is a Termux package, busybox issues are at https://github.com/termux/termux-packages/issues this link.

**Comment by DeadlyByNite** [comment]
@SDRausty, I have no idea why it's missing. I have reinstalled from f-droid and even the Play Store version and it's missing in both. I had to actually link 4 files that were missing (sha512sum, md5sum, uname, and tar. As well as use "bash setup setupTermuxArch.sh manual" to set the script to download with wget. I've heard of problems with the latest curl, but I haven't verified it yet. Maybe to prevent further incidents, you could symlink those 4 files at the beginning of the script? BTW I'm using a Samsung Galaxy S8 (SM-G950U) on Pie.

**Comment by SDRausty** [comment]
@DeadlyByNite @perrsona1234 what is the output of `ls $PREFIX/bin/applets/`?

**Comment by SDRausty** [comment]
Evidently backward comparability is being broken in Termux:
1. https://github.com/termux/termux-packages/issues/4123
2. https://github.com/termux/termux-packages/issues/4128
  * https://github.com/termux/termux-packages/issues/4128#issuecomment-516894201
  > Busybox is getting deprecated and will no longer provide symlinks. 

Breaking backward compatibility is something programmers should avoid, especially when distributing a stable release.  Please inform https://github.com/termux/termux-packages/issues/ of this fact.  As:
```
$ echo $PATH
/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
```
`bin` takes presidence over `bin/applets` there is NO VALID REASON to break comparability in Termux.

**Comment by SDRausty** [comment]
Evidently backward comparability is being broken in Termux:
1. https://github.com/termux/termux-packages/issues/4123
2. https://github.com/termux/termux-packages/issues/4128
  * https://github.com/termux/termux-packages/issues/4128#issuecomment-516894201
  > Busybox is getting deprecated and will no longer provide symlinks. 

Breaking backward compatibility is something programmers should avoid, especially when distributing a stable release.  Please inform https://github.com/termux/termux-packages/issues/ of this fact.  As:
```
$ echo $PATH
/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
```
`bin` takes presidence over `bin/applets` there is NO VALID REASON to break compatibility in Termux.

**Comment by DeadlyByNite** [comment]
I agree with you on breaking backward compatibility, but as a developer, as far as the link you sent me, states that's it's something that most devs hate, but is unfortunately inevitable. Termux is simply an android application just like any other apk that you can download from the Play Store. It's definitely not as they say "a whole Linux distribution" in one package. Far from it, but it's fun for some to tinker and play around with, and it definitely has some potential, but will probably never be perfect.
 Yeah, it sucks, but to continue to develop inside of Termux, a good developer will adapt and move along. Hopefully they won't continue to go the wrong direction, but all we can do is adapt to their standards and play along.
