### ISSUE TITLE
SHA512SUM mismatch!

### ISSUE THREAD

**Issue by ParseThisCode** [SDRausty/TermuxArch#179]
setupTermuxArch.sh: line 58: /data/data/com.termux/files/usr/bin/applets/sha512sum: No such file or directory

**Comment by SDRausty** [comment]
> You can create sha512sum manually by symlinking to $PREFIX/bin/busybox:

```
cd $PREFIX/bin/applets/
ln -s ../busybox sha512sum
```

> Any idea why the symlink sha512sum is missing?  

This symlink comes from busybox.  As busybox is a Termux package, busybox issues are at https://github.com/termux/termux-packages/issues this link.

**Comment by SDRausty** [comment]
You can create sha512sum manually by symlinking to $PREFIX/bin/busybox:

```
cd $PREFIX/bin/applets/
ln -s ../busybox sha512sum
```
Any idea why the symlink sha512sum is missing?  

This symlink comes from busybox.  As busybox is a Termux package, busybox issues are at https://github.com/termux/termux-packages/issues this link.

**Comment by SDRausty** [comment]
@ParseThisCode what is the output of `ls $PREFIX/bin/applets/`?

**Comment by ParseThisCode** [comment]
all needed symlinks (sha512sum, uname) exists in $PREFIX/bin and they binds to coreutils. Lol, did I miss something???

**Comment by SDRausty** [comment]
@ParseThisCode coreutils isn't a prerequisite as busybox should be sufficient. Here's the correct output:
```
$ ls $PREFIX/bin/applets/
ar                 fuser              pipe_progress      sv
arp                getopt             pkill              svlogd
awk                grep               pmap               sync
base64             gunzip             popmaildir         sysctl
basename           gzip               printenv           tac
bbconfig           hd                 printf             tail
bunzip2            head               ps                 tar
bzip2              hexdump            pscan              tcpsvd
cal                hostname           pstree             tee
cat                httpd              pwd                telnet
chattr             id                 pwdx               telnetd
chgrp              ifconfig           readlink           test
chmod              inotifyd           realpath           tftp
chown              install            reformime          tftpd
chpst              iostat             renice             time
chrt               ipcalc             reset              timeout
cksum              kill               resize             touch
clear              killall            rev                tr
cmp                less               rm                 true
comm               linux32            rmdir              tty
cp                 linux64            route              ttysize
cpio               ln                 run-parts          udpsvd
crond              ls                 runsv              uname
crontab            lsattr             runsvdir           uncompress
cut                lsof               rx                 unexpand
date               lsusb              script             uniq
dc                 lzma               scriptreplay       unix2dos
dd                 makemime           sed                unlink
diff               md5sum             sendmail           unlzma
dirname            mkdir              seq                unxz
dos2unix           mkfifo             setsid             unzip
du                 mknod              setuidgid          uptime
echo               mktemp             sha1sum            usleep
egrep              more               sha256sum          uudecode
env                mpstat             sha3sum            uuencode
envdir             mv                 sha512sum          vi
expand             nc                 shuf               watch
expr               netstat            sleep              wc
false              nice               smemcap            wget
find               nmeter             softlimit          which
fold               nohup              sort               whoami
free               nproc              split              whois
fsync              od                 start-stop-daemon  xargs
ftpd               patch              strings            xz
ftpget             pgrep              stty               yes
ftpput             pidof              sum
```
```
$ $PREFIX/bin/busybox --install
busybox: /bin/ar: No such file or directory
busybox: /sbin/arp: Permission denied
busybox: /bin/awk: No such file or directory
busybox: /bin/base64: No such file or directory
busybox: /bin/basename: No such file or directory
busybox: /bin/bbconfig: No such file or directory
busybox: /bin/bunzip2: No such file or directory
busybox: /bin/bzip2: No such file or directory
busybox: /bin/cal: No such file or directory
busybox: /bin/cat: No such file or directory
busybox: /bin/chattr: No such file or directory
.
.
.
```

The `busybox --install` feature appears to be broken.  Please let https://github.com/termux/termux-packages/issues know about these errors.  It also appears that linked libraries in Termux are broken at present too.

**Comment by SDRausty** [comment]
Evidently backward comparability is being broken in Termux:
1. https://github.com/termux/termux-packages/issues/4123
2. https://github.com/termux/termux-packages/issues/4128
  * https://github.com/termux/termux-packages/issues/4128#issuecomment-516894201
  > Busybox is getting deprecated and will no longer provide symlinks. 

Breaking backward compatibility is something programmers should avoid, especially when distributing a stable release.  Please inform https://github.com/termux/termux-packages/issues/ of this fact.  As:
```
$ echo $PATH
/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
```
`bin` takes presidence over `bin/applets` there is NO VALID REASON to break comparability in Termux.

**Comment by SDRausty** [comment]
Evidently backward comparability is being broken in Termux:
1. https://github.com/termux/termux-packages/issues/4123
2. https://github.com/termux/termux-packages/issues/4128
  * https://github.com/termux/termux-packages/issues/4128#issuecomment-516894201
  > Busybox is getting deprecated and will no longer provide symlinks. 

Breaking backward compatibility is something programmers should avoid, especially when distributing a stable release.  Please inform https://github.com/termux/termux-packages/issues/ of this fact.  As:
```
$ echo $PATH
/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets
```
`bin` takes presidence over `bin/applets` there is NO VALID REASON to break compatibility in Termux.

**Comment by ParseThisCode** [comment]
I found a workaround. Root is required.
Command: tsudo $PREFIX/bin/busybox --install $PREFIX/bin/appets

**Comment by SDRausty** [comment]
You can create sha512sum manually by symlinking to $PREFIX/bin/busybox:
```
cd $PREFIX/bin/applets/
ln -s ../busybox sha512sum
au bsdtar
```

These steps should resolve the issue for the time being.  If there are other 🚶 steps, please share.  

[au](https://sdrausty.github.io/au/)

**Comment by SDRausty** [comment]
@ParseThisCode you can create the symbolic links manually by symlinking to $PREFIX/bin/busybox:
```
cd $PREFIX/bin/applets/
ln -s ../busybox awk
ln -s ../busybox sha512sum
ln -s ../busybox rev
ln -s ../busybox tar
ln -s ../busybox uname
```
Run `setupTermuxArch.sh` again.
```
cd
bash setupTermuxArch.sh h # for more information
```

**Comment by SDRausty** [comment]
Is backwards compatiblity essential

**Comment by SDRausty** [comment]
To distribute, not at all

**Comment by SDRausty** [comment]
To use the code effectively

**Comment by SDRausty** [comment]
Please share https://www.google.com/search?q=ethiopian+trees

Integrate?

**Comment by SDRausty** [comment]
How to?

**Comment by ParseThisCode** [comment]
I think we can close this issue

**Comment by uetuluk** [comment]
@SDRausty Also received an error with m5sum after the download

**Comment by SDRausty** [comment]
See whether running [`sh init.sh`](https://raw.githubusercontent.com/TermuxArch/TermuxArch/master/init.sh) clears up the md5sum mismatch @uetuluk.

**Comment by uetuluk** [comment]
@SDRausty Yeah, I linked it myself. Saw you were missing it.

**Comment by SDRausty** [comment]
Thank you for confirming

**Comment by danieldjewell** [comment]
@SDRausty ultimately, I think the issue comes down to the hardcoded paths that look for the various utilities (i.e. tar, md5sum, sha512sum, etc.) in *only* the $PREFIX/bin/applets directory -- instead of either looking in $PATH directly or using something like "which sha512sum" to get the full path of sha512sum if installed. 

Alternatively, why hardcode the path at all? On my install, both usr/bin and usr/bin/applets are in $PATH... Why not just launch sha512sum (and the other utilities) without a path at all and let the system figure it out? (That way, it really wouldn't matter where they're located ... it's certainly not very ... portable ... to have to create symlinks in a less-than-typical path.) 

https://github.com/SDRausty/TermuxArch/blob/e792d9e5ca51af87ee1630cfb3e74a1ab8516031/setupTermuxArch.sh#L35

**Comment by SDRausty** [comment]
@danieldjewell thank you for the insight.  There was motivation for the hardcoding, but now it seems irrelevant since the busybox setup has been altered.  This commit https://github.com/TermuxArch/TermuxArch/commit/4406e856ce30af50d25ccb7f4c9a480a4c1293bf removes the hardcoded paths.  

 ##### -rwxrwx--- [setupTermuxArch.bash](https://TermuxArch.github.io/TermuxArch/setupTermuxArch.bash) 
##### -r--r--r-- [setupTermuxArch.bash](https://raw.githubusercontent.com/TermuxArch/TermuxArch/master/setupTermuxArch.bash)

If you get errors with `tar`, use `bsdtar`.
