### ISSUE TITLE
Ask of help. Thank you

### ISSUE THREAD

**Issue by boyzonecn** [SDRausty/TermuxArch#180]
proot warning: ptrace(PEEKDATA): I/O error
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so: Bad address
sudo: fatal error, unable to load plugins

**Comment by SDRausty** [comment]
@boyzonecn see whether https://github.com/SDRausty/termux-archlinux/issues/4#issuecomment-423579945 helps in getting this task on track.

**Comment by SDRausty** [comment]
https://github.com/sdrausty/Termux-archlinux/issues?q=is%3Aissue+sudo

**Comment by SDRausty** [comment]
@boyzonecn https://github.com/termux/proot/issues/70

> proot warning: ptrace(PEEKDATA): I/O error
