### ISSUE TITLE
Rfkill issue

### ISSUE THREAD

**Issue by nvixonimo** [SDRausty/TermuxArch#182]
I'm having huge mindflusks with rfkill. No matter what I do - "operation is not permitted". Always. Each time. 

I checked out a lot of pages on arch linux forum hoping to find a solution. And I've tried if not everything, then almost everything. And even though I'm logged in as root "operation is !still! not permitted".

I know Linux well - not "Arch" well, but "Debian-based" well. I'm only learning Arch, but already frustrated.

Is there maybe a broken link in directory tree? Maybe there is an issue in setup scripts? Because I'm trying to get my wifi adapter going and rfkill doesn't let me do anything. Not even a simple "rfkill list all".

Help would be appreciated

**Comment by SDRausty** [comment]
@nvixonimo see whether adding [proot binds](https://duckduckgo.com/?q="proot"+binds) to startarch helps.  File `/var/binds/fbindexample.prs` has more information.
