### ISSUE TITLE
espritfunctions.sh: line 62: ceds[$i]: unbound variable

### ISSUE THREAD

**Issue by FSpark** [SDRausty/TermuxArch#184]
An error occurs when configuring and updating Arch Linux. And command 'startarch' is still not found, though it can be found in ~/arch.
Termux 0.73 / Android 8.1
![Screenshot_2019-09-08-23-10-05-186_com termux](https://user-images.githubusercontent.com/20501721/64490441-62b9a280-d28f-11e9-9401-35a03587cc34.png)

**Comment by SDRausty** [comment]
@FSpark try `bash setupTermuxArch.sh refresh` to see whether this option helps in configuring and installing correctly.

**Comment by FSpark** [comment]
@SDRausty OK, It works well! And it's better to manually replace the mirror source in `~/arch/etc/pacman.d/mirrorlist` first.

**Comment by FSpark** [comment]
Another question... When running `startarch` with `tsudo`, Execv failed always comes up while installing any package, as described here https://github.com/sdrausty/termux-arch/issues/2. Why use `tsudo`?Because of this, the problem of top not working and the black screen of Firefox browser can be solved.😩

**Comment by SDRausty** [comment]
@FSpark information about `sudo` in TermuxArch is here:
 * https://github.com/SDRausty/termux-archlinux/issues?q=+is%3Aissue+sudo
   * https://github.com/SDRausty/termux-archlinux/issues/4#issuecomment-423579945

**Comment by SDRausty** [comment]
This commit https://github.com/TermuxArch/TermuxArch/commit/409b4beb959966015515f338366053147eda1744 should resolve `espritfunctions.sh: line 62: ceds[$i]: unbound variable`.  Thank you for bringing this to my attention @FSpark.

**Comment by SDRausty** [comment]
@FSpark this issue is also being discussed https://github.com/SDRausty/TermuxArch/issues/259 here.

**Comment by SDRausty** [comment]
The error `ceds[$i]: unbound variable` is resolved again.  This time this https://github.com/SDRausty/TermuxArch/commit/68631a280d11872dd35d02f3b808311cde74164f commit is the assisting commit, and comment, "[[16:29~]$ which editor](https://www.reddit.com/r/termux/comments/jfq7xi),” was one of the assisting discussions including this issue;  Thank you @FSpark very much.
