### ISSUE TITLE
startarch /bin/bash: No such file or directory

### ISSUE THREAD

**Issue by vxcvbzn** [SDRausty/TermuxArch#185]
I've encountered a weird issue with ``startarch`` script.
Regardless of what I have tried doing, it always throws me an error ``/usr/bin/env: '/bin/bash' : No such file of directory``.

Things I've tried:
* Installing ``termux-exec`` to fix the shebang,
* Editing the shebang in both files to the "correct" bash path (``usr/bin/bash``),
* Prefixing the commands with ``bash``,
* Symlinking ``${PREFIX}/bin/bash`` as ``${PREFIX}/../bin/bash``

What is weird is that bash is present in both termux directories and the arch ones.

**Comment by SDRausty** [comment]
This error appears on some armv7 and aarch64 devices.  The simplest way to confirm is by running `proot`.  The last line of output will show this error: `fatal error: see proot --help.`

See issue https://github.com/termux/proot/issues/76 for resolution of this error.

**Comment by SDRausty** [comment]
If you can add to https://github.com/termux/proot/issues/76 @vxcvbzn  this may help in finding a resolution sonner.

**Comment by SDRausty** [comment]
Issue https://github.com/termux/proot/issues/76 is also related.  Both issues are unresolved at present.  Providing `uname -m` infornation should be helpfull.

**Comment by umnikos** [comment]
Hello! I am having a very similar issue to this while trying to cross-compile C from x64 to arm and then run it with Termux and I feel the two may be related. I moved the executable to the home directory and made it executable with chmod, but it still won't run:
```
$ ./hello-arm
bash: ./hello-arm: No such file or directory
$ bash hello-arm
hello-arm: hello-arm: cannot execute binary file
```
The confirmation test SDRausty mentioned with `proot` gives fatal error.
The output of `uname -m` is `armv81`.

**Comment by SDRausty** [comment]
> first check whether you are using latest version of Termux

Reference https://github.com/termux/play-audio/issues/12
