### ISSUE TITLE
MD5 Checksum

### ISSUE THREAD

**Issue by KitsuneIDK** [SDRausty/TermuxArch#186]
Help me, how I can resolve problems with MD5 Checksum?

**Comment by SDRausty** [comment]
@KitsuneIDK see https://github.com/SDRausty/termux-archlinux/issues/35#issuecomment-517102110 

Running [init.sh](https://raw.githubusercontent.com/SDRausty/TermuxArch/master/init.sh) should fix this problem.

**Comment by KitsuneIDK** [comment]
@SDRausty Thanks!
