### ISSUE TITLE
PRoot command give error

### ISSUE THREAD

**Issue by KitsuneIDK** [SDRausty/TermuxArch#187]
When I use `startarch` the proot return the error `/usr/bin/env: '/bin/bash': No such file or directory`, you can test this using Android Oreo 8.1 Security Patch June 2019 (My phone model is a SM-G610M with a ARMv8 (Cortex A53) apparently 64 bits)

**Comment by SDRausty** [comment]
This error appears on some armv7 and aarch64 devices.  The simplest way to confirm is by running `proot`.  The last line of output will show this error: `fatal error: see `proot --help`.`

See issue https://github.com/termux/proot/issues/76 for resolution of this error.

**Comment by SDRausty** [comment]
If you can add to https://github.com/termux/proot/issues/76 @KitsuneIDK this may help in finding a resolution.

**Comment by SDRausty** [comment]
Issue https://github.com/termux/proot/issues/76 is also related.  Both issues are unresolved at present.  Providing `uname -m` infornation should be helpfull.
