### ISSUE TITLE
Add a method to properly remove TermuxArch from device

### ISSUE THREAD

**Issue by Harshiv-Patel** [sdrausty/TermuxArch#19]
I could have just did rm -rf but I feel that you should add little script that can remove TermuxArch from device in proper way, or add something in wiki section about how to do it in proper way.

**Comment by sdrausty** [comment]
@Harshiv-Patel https://github.com/sdrausty/TermuxArch/blob/master/scripts/debug/sraf.sh purges the install from device.

**Comment by sdrausty** [comment]
Another method has just been added with commit https://github.com/sdrausty/TermuxArch/commit/18ae6649ea2b8d39e24edefac3cf512473577fb4 Use `bash setupTermuxArch.sh uninstall` to purge your Arch Linux installation from device.  
![screenshot_20171124-141841](https://user-images.githubusercontent.com/27742457/33222084-6c3cc82a-d122-11e7-8721-e839cf17eba9.png)
