### ISSUE TITLE
User's group changes when `su`/`startarch`ing

### ISSUE THREAD

**Issue by milesand** [SDRausty/TermuxArch#192]
![Screenshot_20191024-134316](https://user-images.githubusercontent.com/14255227/67454355-de678700-f664-11e9-920a-990523f48663.jpg)

User `dummy_u`and Group `dummy_g` were just created with `addauser dummy_u` and `groupadd dummy_g`, and the user was added to the group via `usermod -aG dummy_g dummy_u`.

So as you can see, `id dummy_u` shows the expected set of groups, but `su`ing and then using `id` shows that
* `dummy_u` is *not* in `dummy_g`
* `dummy_u` is in a bunch of unnamed groups instead

The group change also happens on `startarch l dummy_u`.

User's new groups seem to be same as Termux user's groups:
![Screenshot_20191024-134428](https://user-images.githubusercontent.com/14255227/67454642-ed9b0480-f665-11e9-98e6-2047d5bb375a.jpg)

**Comment by SDRausty** [comment]
@milesand alas, userspace is simply userspace.  No groups allowed.

**Comment by milesand** [comment]
Hmm. Kinda disappointing, but okay.

**Comment by SDRausty** [comment]
@milesand some of my computer professors preached, "Computer science is created by humankind."  What is the rationel for groups in Android user?

**Comment by milesand** [comment]
Nah, it's nothing too serious. I was following some linux tutorial while away from my desktop, and the group behaviour was unexpected. It does seem that having groups woudn't be particularly useful, given the environment.
