### ISSUE TITLE
I want create Termux distro repo

### ISSUE THREAD

**Issue by KitsuneIDK** [SDRausty/TermuxArch#193]
I want create a Termux repository with all distro available and I want modify and add your script

**Comment by SDRausty** [comment]
@KitsuneIDK a discription of what is wanted is desired.  What's the goal?

**Comment by KitsuneIDK** [comment]
Gather all Termux compatible Linux in one place to make easily new users download hers

**Comment by SDRausty** [comment]
> new users download hers

?

**Comment by KitsuneIDK** [comment]
I only need of your permission do modify and reupload your setupTermuxArch.sh, I don't gonna use your messages, only links

**Comment by KitsuneIDK** [comment]
and I need permission to Slackware, I don't need everything only the proot command and download link permission to copy is for a repository and program to make installation and activation of Linux ditros on Termux more easily (So sorry my English I'm improvising)

**Comment by SDRausty** [comment]
See https://github.com/SDRausty/TermuxArch/blob/master/LICENSE for details.  If you want to install Slackware use `[systemimage.tar.gz [customdir]] Install directory argument is optional. A systemimage.tar.gz file can be substituted for network install.` from `bash setupTermuxArch.bash h`.  

SetupTermuxArch.bash doesn't configure Slackware at present.  It would be nice if it would.  If you want modify this script for Slackware, a peak with `grep -hl pacman *h` might be a good beginning.  Are you familiar with this https://github.com/gwenhael-le-moine/TermuxSlack project @KitsuneIDK?
