### ISSUE TITLE
Archlinux image is not downloaded

### ISSUE THREAD

**Issue by liuchang0920** [SDRausty/TermuxArch#194]
1. installation with command: 

```
$ bash TermuxArch/setupTermuxArch.sh wget
```

and following is the result, somehow the image is not able to download: 

 🕛 > 🕠 Checking download integrity with md5sum.  This may take a little while:

md5sum: archlinux-bootstrap-2017.03.01-i686.tar.gz: No such file or directory
md5sum: WARNING: 1 listed file could not be read

 🔆 WARNING md5sum mismatch! The download failed and was removed!  Run `bash setupTermuxArch.bash` again.  See `bash setupTermuxArch.bash help` to resolve md5sum errors.  This kind of error can go away, like magic.  Waiting before executing again is recommended.  There are numerous reasons for checksum errors.  Proxies are one explaination.  Mirroring and mirrors are another explaination for md5sum errors.  Interrupted download is one more reason.  If this keeps repeating, copy `knownconfigurations.bash` to `setupTermuxArchConfigs.bash` with preferred mirror.  After editing `setupTermuxArchConfigs.bash`, run `bash setupTermuxArch.bash` and `setupTermuxArchConfigs.bash` loads automaticaly from the same directory.  Change mirror to desired geographic location to resolve md5sum errors.

User configurable variables are in `setupTermuxArchConfigs.bash`.  Create this file from `kownconfigurations.bash` in the working directory.  Use `bash setupTermuxArch.bash manual` to create and edit `setupTermuxArchConfigs.bash`.

        Run `bash setupTermuxArch.bash` again…

setupTermuxArch.sh wget 2.0.12: DONE 🏁

2.  If manually copy the image file to arch/ folder, it will stuck in the following line:

```
🕛 > 🕡 Unpacking  into /data/data/com.termux/files/home/arch.  The option to create Arch Linux system users is available through addauser.  Arch Linux user login from Termux with startarch is now implemented.  See Ability for Scripts to Launch Commands for Arch Linux in Termux PRoot on Device https://github.com/sdrausty/TermuxArch/issues/54 for more information about these brand new options.

While waiting, you can use df, du -hs, htop, ps, top and watch in a new Termux session to watch the unpacking while the session completes.  Use info query and man query to learn more about your Linux system in the palm of your hand.  See The Linux Documentation Project http://tldp.org to learn more about Linux and CLI commands.  Unpacking  will take a long time; Be patient…

```

And it will stay in this state forever.

Could anyone help with this?

This is done on a Chromebook

Really appreciate it!

**Comment by SDRausty** [comment]
@liuchang0920 see if trying another download tool resolves this issue; `bash setupTermuxArch.bash h` shows all available download manager options.  Another way of seeking a solution is trying `bash setupTermuxArch.bash manual` with a different mirror adress.

**Comment by liuchang0920** [comment]
seems still doesn't work. Switched chromeos back to ubuntu again.. 

Thanks anyways, this is a really cool project
