### ISSUE TITLE
How to restart arch Linux in termux

### ISSUE THREAD

**Issue by rajuhax** [sdrausty/TermuxArch#20]
Sir after leaving arch Linux how can i restart arch Linux again please sir tell me is there any command to restart arch again in termux

**Comment by sdrausty** [comment]
Yes, you can restart Arch Linux in Termux any time you like after installing. Use `startarch` if you installed it to your `$PATH` or `~/arch/startarch` from your `$HOME` directory.

**Comment by sdrausty** [comment]
See https://github.com/sdrausty/TermuxArch/issues/25 for more options how to run Arch Linux in Termux.

**Comment by sdrausty** [comment]
Refences regarding this issue https://duckduckgo.com/?q=beginning+command+line+site%3Atldp.org at these links, about starting with the Linux CLI (Command Line Interface) in Termux on Android, Chromebook and Fire OS on device.
