### ISSUE TITLE
Keyring installation failed? 'error: no servers configured for repository: core.'

### ISSUE THREAD

**Issue by sudomain** [SDRausty/TermuxArch#200]
During installation, TermuxArch fails to configure the mirrors. Manually uncommenting mirrors in /etc/pacman.d/mirrorlist results in many packages failing to download

Here is the full transcript:

Welcome to Termux!

Wiki:            https://wiki.termux.com
Community forum: https://termux.com/community
Gitter chat:     https://gitter.im/termux/termux
IRC channel:     #termux on freenode

Working with packages:

 * Search packages:   pkg search <query>
 * Install a package: pkg install <package>
 * Upgrade packages:  pkg upgrade

Subscribing to additional repositories:

 * Root:     pkg install root-repo
 * Unstable: pkg install unstable-repo
 * X11:      pkg install x11-repo

Report issues at https://termux.com/issues

$ cd TermuxArch/
.git/                        espritfunctions.bash         pullTermuxArchSubmodules.sh
404.md                       gen/                         robots.txt
CHANGE.log                   getimagefunctions.bash       setupTermuxArch.bash
CONTRIBUTORS.md              gsa.bash                     setupTermuxArch.sh
LICENSE                      init.sh                      setupTermuxArch.sha512
NOTICE.md                    knownconfigurations.bash     setupTermuxArch.tar.gz
README.md                    maintenanceroutines.bash     sha512.sum
archlinuxconfig.bash         necessaryfunctions.bash      sitemap.txt
do.sums.bash                 printoutstatements.bash      tgen.bash
$ cd TermuxArch/
$ bash setupTermuxArch.bash

 🕛 > 🕛 ＴｅｒｍｕｘＡｒｃｈ /data/data/com.termux/files/home/arch shall attempt to install Linux in /data/data/com.termux/files/home/arch.  Arch Linux in Termux PRoot shall be
 available upon successful completion.  To run this BASH script again, use `!!`.  Ensure background data is not restricted.  Check the wireless connection if you do not see one 
o'clock 🕐 below.  If you get a '/usr/bin/env' not found error, please comment at issues https://github.com/termux/proot/issues/72 and 76 Checking prerequisites…

Found download tool `curl`: Continuing…

Using curl to manage downloads.

 🕛 > 🕧 Prerequisites: OK  Downloading TermuxArch…

Setting locales to: Language >> en_US << Region

 🕛 > 🕝 Detected armv7l Android operating system.

 🕛 > 🕒 Activating termux-wake-lock: DONE

 🕛 > 🕞 Contacting worldwide mirror https://os.archlinuxarm.org: DONE

 🕛 > 🕓 Downloading the checksum file and ArchLinuxARM-armv7-latest.tar.gz from the geographically local mirror http://il.us.mirror.archlinuxarm.org/.  If contact with the loca
l mirror is not successful, run bash setupTermuxArch.bash again.  Should the worldwide mirror not provide another geographically nearby server after a couple of attempts, use ba
sh setupTermuxArch.bash manual after locating a local mirror from the Internet; See bash setupTermuxArch.bash help for additional options.  Download of ArchLinuxARM-armv7-latest
.tar.gz pending Internet connection:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:17 --:--:--     0
  0     0    0     0    0     0      0      0 --:--:--  0:00:20 --:--:--     0^CTermuxArch WARNING:  Signal 130 received!
setupTermuxArch.bash  2.0.12: [Exit Signal 211] DONE 🏁

$ bash setupTermuxArch.bash

 🕛 > 🕛 ＴｅｒｍｕｘＡｒｃｈ /data/data/com.termux/files/home/arch shall attempt to install Linux in /data/data/com.termux/files/home/arch.  Arch Linux in Termux PRoot shall be
 available upon successful completion.  To run this BASH script again, use `!!`.  Ensure background data is not restricted.  Check the wireless connection if you do not see one 
o'clock 🕐 below.  If you get a '/usr/bin/env' not found error, please comment at issues https://github.com/termux/proot/issues/72 and 76 Checking prerequisites…

Found download tool `curl`: Continuing…

Using curl to manage downloads.

 🕛 > 🕧 Prerequisites: OK  Downloading TermuxArch…

Setting locales to: Language >> en_US << Region

 🕛 > 🕝 Detected armv7l Android operating system.

 🕛 > 🕒 Activating termux-wake-lock: DONE

 🕛 > 🕞 Contacting worldwide mirror https://os.archlinuxarm.org: DONE

 🕛 > 🕓 Downloading the checksum file and ArchLinuxARM-armv7-latest.tar.gz from the geographically local mirror http://fl.us.mirror.archlinuxarm.org/.  If contact with the loca
l mirror is not successful, run bash setupTermuxArch.bash again.  Should the worldwide mirror not provide another geographically nearby server after a couple of attempts, use ba
sh setupTermuxArch.bash manual after locating a local mirror from the Internet; See bash setupTermuxArch.bash help for additional options.  Download of ArchLinuxARM-armv7-latest
.tar.gz pending Internet connection:

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    67  100    67    0     0   1030      0 --:--:-- --:--:-- --:--:--  1030
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  415M  100  415M    0     0  4055k      0  0:01:44  0:01:44 --:--:-- 4202k

 🕛 > 🕠 Checking download integrity with md5sum.  This may take a little while:

 🕛 > 🕕 System image file download integrity: OK

 🕛 > 🕡 Unpacking ArchLinuxARM-armv7-latest.tar.gz into /data/data/com.termux/files/home/arch.  The option to create Arch Linux system users is available through addauser.  Arc
h Linux user login from Termux with startarch is now implemented.  See Ability for Scripts to Launch Commands for Arch Linux in Termux PRoot on Device https://github.com/sdraust
y/TermuxArch/issues/54 for more information about these brand new options.

While waiting, you can use df, du -hs, htop, ps, top and watch in a new Termux session to watch the unpacking while the session completes.  Use info query and man query to learn
 more about your Linux system in the palm of your hand.  See The Linux Documentation Project http://tldp.org to learn more about Linux and CLI commands.  Unpacking ArchLinuxARM-
armv7-latest.tar.gz will take a long time; Be patient…

 🕛 > 🕘 Cleaning up installation files: DONE

 🕛 > 🕤 Arch Linux in Termux PRoot is installed.  Configuring and updating Arch Linux  📲

To generate locales in a preferred language use Settings > Language & Keyboard > Language in Android; Then run setupTermuxArch.bash r for a quick system refresh; For full system
 refresh use setupTermuxArch.bash re[fresh].

==> Generating locales...
  en_US.UTF-8... done
Generation complete.

:: Removing redundant packages for Termux PRoot installation…
checking dependencies...
:: base optionally requires linux: bare metal support

Packages (2) linux-armv7-5.4.1-1  linux-firmware-20191022.2b016af-3

Total Removed Size:  554.48 MiB

:: Do you want to remove these packages? [Y/n]
:: Processing package changes...
(1/2) removing linux-armv7                           [############################] 100%
(2/2) removing linux-firmware                        [############################] 100%
:: Running post-transaction hooks...
(1/2) Arming ConditionNeedsUpdate...
(2/2) Updating module dependencies...

==> Running TermuxArch keys archlinux-keyring archlinuxarm-keyring ca-certificates-utils 2.0.12…

When gpg: Generating pacman keyring master key appears on the screen, the installation process can be accelerated.  The system desires a lot of entropy at this part of the insta
ll procedure.  To generate as much entropy as possible quickly, watch and listen to a file on your device.

The program pacman-key will want as much entropy as possible when generating keys.  Entropy is also created through tapping, sliding, one, two and more fingers tapping with shor
t and long taps.  When gpg: Generating pacman keyring master key appears on the screen, use any of these simple methods to accelerate the installation process if it is stalled. 
 Put even simpler, just do something on device.  Browsing files will create entropy on device.  Slowly swiveling the device in space and time will accelerate the installation pr
ocess.  This method alone might not generate enough entropy (a measure of randomness in a closed system) for the process to complete quickly.  Use bash ~/arch/bin/we in a new Te
rmux session to and watch entropy on device.

==> Running pacman-key --init…
gpg: /etc/pacman.d/gnupg/trustdb.gpg: trustdb created
gpg: no ultimately trusted keys found
awk: fatal: can't stat fd 0 (Operation not permitted)
gpg: starting migration from earlier GnuPG versions
gpg: porting secret keys from '/etc/pacman.d/gnupg/secring.gpg' to gpg-agent
gpg: migration succeeded
gpg: Generating pacman keyring master key...
gpg: key B7F15C7C8161727C marked as ultimately trusted
gpg: directory '/etc/pacman.d/gnupg/openpgp-revocs.d' created
gpg: revocation certificate stored as '/etc/pacman.d/gnupg/openpgp-revocs.d/55E4065292083D3855DA093BB7F15C7C8161727C.rev'
gpg: Done
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   0  trust: 0-, 0q, 0n, 0m, 0f, 1u
==> Appending keys from archlinuxarm.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signing key 69DD6C8FD314223E14362848BF7EEF7A9C6B5765...
  -> Locally signing key 02922214DE8981D14DC2ACABBC704E86B823CD25...
  -> Locally signing key 9D22B7BB678DC056B1F7723CB55C5315DCD9EE1A...
==> Importing owner trust values...
gpg: setting ownertrust to 4
gpg: inserting ownertrust of 4
gpg: setting ownertrust to 4
==> Updating trust database...
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   3  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   3  signed:   1  trust: 0-, 0q, 0n, 3m, 0f, 0u
gpg: depth: 2  valid:   1  signed:   0  trust: 1-, 0q, 0n, 0m, 0f, 0u

==> Running pacman -S archlinux-keyring archlinuxarm-keyring ca-certificates-utils --noconfirm --color=always…
warning: archlinuxarm-keyring-20140119-1 is up to date -- reinstalling
warning: ca-certificates-utils-20181109-2 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (3) archlinux-keyring-20191018-2  archlinuxarm-keyring-20140119-1
             ca-certificates-utils-20181109-2

Total Download Size:   0.88 MiB
Total Installed Size:  1.25 MiB
Net Upgrade Size:      1.21 MiB

:: Proceed with installation? [Y/n]
error: no servers configured for repository: core
error: failed to commit transaction (no servers configured for repository)
Errors occurred, no packages were upgraded.

When Appending keys from archlinux.gpg appears on the screen, the installation process can be accelerated.  The system desires a lot of entropy at this part of the install proce
dure.  To generate as much entropy as possible quickly, watch and listen to a file on your device.

The program pacman-key will want as much entropy as possible when generating keys.  Entropy is also created through tapping, sliding, one, two and more fingers tapping with shor
t and long taps.  When Appending keys from archlinux.gpg appears on the screen, use any of these simple methods to accelerate the installation process if it is stalled.  Put eve
n simpler, just do something on device.  Browsing files will create entropy on device.  Slowly swiveling the device in space and time will accelerate the installation process.  
This method alone might not generate enough entropy (a measure of randomness in a closed system) for the process to complete quickly.  Use bash ~/arch/bin/we in a new Termux ses
sion to watch entropy on device.

==> Running pacman-key --populate…
==> Appending keys from archlinuxarm.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signing key 69DD6C8FD314223E14362848BF7EEF7A9C6B5765...
  -> Locally signing key 02922214DE8981D14DC2ACABBC704E86B823CD25...
  -> Locally signing key 9D22B7BB678DC056B1F7723CB55C5315DCD9EE1A...
==> Importing owner trust values...
==> Updating trust database...
gpg: no need for a trustdb check

==> Running pacman -Ss keyring --color=always…
core/archlinux-keyring 20191018-2
    Arch Linux PGP keyring
core/archlinuxarm-keyring 20140119-1 [installed]
    Arch Linux ARM PGP keyring
extra/gnome-keyring 1:3.34.0-2 (gnome)
    Stores passwords and encryption keys
extra/libgnome-keyring 3.12.0+11+g3766bcc-1
    GNOME keyring client library
extra/python2-gnomekeyring 2.32.0-18
    Python bindings for libgnome-keyring
community/debian-archive-keyring 2019.1-1
    GnuPG archive keys of the Debian archive
community/jetring 0.27-1
    gpg keyring maintenance using changesets
community/python-keyring 19.2.0-3
    Store and access your passwords safely
community/python-keyrings-alt 1:3.1.1-3
    Alternate keyring implementations
community/ubuntu-keyring 2018.09.18.1-1
    GnuPG keys of the Ubuntu archive

TermuxArch keys archlinux-keyring archlinuxarm-keyring ca-certificates-utils 2.0.12: DONE 🏁

==> Running TermuxArch pci  2.0.12 …

:: Synchronizing package databases...
error: failed to update core (no servers configured for repository)
error: failed to update extra (no servers configured for repository)
error: failed to update community (no servers configured for repository)
error: failed to update alarm (no servers configured for repository)
error: failed to update aur (no servers configured for repository)
error: failed to synchronize all databases
error: no operation specified (use -h for help)

 TermuxArch WARNING:  Generated script signal 1 near or at line number 69 by !

TermuxArch pci  2.0.12: DONE 🏁

error: failed to update core (no servers configured for repository)
error: failed to update extra (no servers configured for repository)
error: failed to update community (no servers configured for repository)
error: failed to update alarm (no servers configured for repository)
error: failed to update aur (no servers configured for repository)
error: failed to synchronize all databases
error: no operation specified (use -h for help)

 TermuxArch WARNING:  Generated script signal 201 near or at line number 55 by
==> Running TermuxArch pci  2.0.12 …

:: Synchronizing package databases...

 TermuxArch WARNING:  Generated script signal 1 near or at line number 69 by !

TermuxArch pci  2.0.12: DONE 🏁

!

finishsetup.bash  2.0.12 [Exit Signal 201]: DONE  🏁

 🕛 > 🕙 Releasing termux-wake-lock: DONE

 🕛 > 🕥 Use startarch to launch Arch Linux in Termux PRoot.  Alternatively, run ~/arch/startarch in a BASH shell to start Arch Linux in Termux PRoot for future sessions.  See s
tartarch help for usage information.

 🕛 > 🕦 startarch copied to /data/data/com.termux/files/usr/bin.

 🕛 = 🕛 Information about "Starting Arch Linux from Termux?" at https://github.com/sdrausty/TermuxArch/issues/25.  Use tour to run a very short tour to get to know the new Arch
 Linux in Termux PRoot environment you just set up a little bit better.  If there was more than one error during the update procedure and you would like to refresh the installat
ion, use setupTermuxArch.bash refresh.  This will update and recreate the configuration provided.  The TermuxArch command keys helps install and generate Arch Linux keyring keys
.

Arch Linux in Termux PRoot is installed in /data/data/com.termux/files/home/arch.  This project is in active development.  Contributions to this project are welcome; See https:/
/sdrausty.github.io/TermuxArch/CONTRIBUTORS for information.  The documentation repository for TermuxArch https://sdrausty.github.io/TermuxArch/docs/ is a Termux Arch submodule 
that is located at https://github.com/sdrausty/docsTermuxArch.  Pull requests and contributions through the issues pages are open to improve the ux (user experience) and this Te
rmux PRoot installation script.

Use ~/arch/startarch and startarch in a BASH shell to launch Arch Linux in Termux PRoot for future sessions.  If you are new to *nix, http://tldp.org has *nix documentation.  Se
e https://wiki.archlinux.org/index.php/IRC_channel for available Arch Linux IRC channels.  If you get a '/usr/bin/env' not found error, please comment at issues https://github.c
om/termux/proot/issues/72 and 76

startarch help

startarch: Start Arch Linux as root.  This account is reserved for system administration.

startarch c[md] cmd: Run Arch Linux command from Termux as root user.

startarch u[ser]|l[ogin] user: Login as user.  Use startarch c addauser user first to create this user and user's home directory.

startarch r[aw]: Construct the startarch proot statement from exec.../bin/.  For example startarch r su will exec su in Arch Linux.

startarch s[u] user cmd: Login as user and execute command.  Use startarch c addauser user first to create this user and user's home directory.

startarch  2.0.12: DONE 🏁

Welcome to Arch Linux in Termux!
Install a package: pacman -S package
More  information: pacman -[D|F|Q|R|S|T|U]h
Search   packages: pacman -Ss query
Upgrade  packages: pacman -Syu

Chat: wiki.termux.com/wiki/Community
Help: info query and man query
IRC:  wiki.archlinux.org/index.php/IRC_channel

[root16:43arch]$

**Comment by SDRausty** [comment]
@sudomain ` vi /etc/pacman.d/mirrorlist ` will open the mirrorlist file in Arch Linux PRoot for editing.  Uncomment just one mirror for best results.

**Comment by SDRausty** [comment]
> Keyring installation failed? 'error: no servers configured for repository: core

Once the system is updated, the TermuxArch command ` keys ` should automatically configure the keyrings.

**Comment by sudomain** [comment]
I uncommented the global mirror and ran `keys` which fixed the issue. Thanks!

Is it intended behavior to have users enable a mirror and run `keys`? I don't remember this step from previous TermuxArch installs.

If it isn't intended behavior, then what caused this? I used the install method involving `git clone`

**Comment by imranido72773-stack** [comment]
termux proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/kali-arm64, cwd = /home/kali, $path=(null)) fatal error: see `proot --help`.

**Comment by imranido72773-stack** [comment]
termux proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/kali-arm64, cwd = /home/kali, $path=(null)) fatal error: see `proot --help`.
