### ISSUE TITLE
TermuxArch WARNING:  Generated script signal 100 near or at line number 615 by `trap`!

### ISSUE THREAD

**Issue by RaphaP3** [SDRausty/TermuxArch#202]
Error when running the setup Bash 

TermuxArch WARNING:  Generated script signal 100 near or at line number 615 by `trap`!

**Comment by Air1996** [comment]
Same problem, Check the Error message on the last line of this Error,  my Error was:
> E: unable to locate package **bsdtar**  

Execute the following command:
> apt update
> apt install **bsdtar**

Re-execute the script!It works!!

**Comment by SDRausty** [comment]
These latest https://github.com/TermuxArch/TermuxArch/commits/master commits have resolved this error.  If it still persists on your device please post here.
