### ISSUE TITLE
How to run setupTermuxArch without entering the proot afterward?

### ISSUE THREAD

**Issue by sudomain** [SDRausty/TermuxArch#206]
I'm writing a script that will:
1. Use this repo as a git submodule to install TermuxArch
2. Install packages inside the proot using pacman
3. Setup `~/.shortcuts` wrapper scripts to run programs in the proot

I notice that once installation of TermuxArch completes, the shell enters the proot and my scripts wont complete until the user exits. I'm writing my scripts with non-technical users in mind, so I don't expect them to know to type `exit` or `CTRL-D` to exit. Is there a way to install TermuxArch without it entering the proot after?

**Comment by SDRausty** [comment]
> Is there a way to install TermuxArch without it entering the proot after?

Comment out this line ["$INSTALLDIR/$STARTBIN"](https://github.com/TermuxArch/TermuxArch/blob/master/necessaryfunctions.bash#L150) in necessaryfunctions.bash to install TermuxArch without it entering proot. 

> I'm writing a script 

Share here when you have a working copy if you can.

**Comment by sudomain** [comment]
> Share here when you have a working copy if you can.
Sure thing. Should I share it as a PR to this project, a PR to the wiki/website, or some other format?

**Comment by SDRausty** [comment]
> Should I share it as a PR to this project, a PR to the wiki/website, or some other format?

All three are fine.  The issue pages can be another format.

**Comment by sudomain** [comment]
I got around to releasing  v0.0.1 of [my project](https://github.com/sudomain/AnkiTermuxArch). It uses TermuxArch as a submodule to install Arch. It then configures files for a VNC server and adds Termux shortcut scripts to launch gui programs in the proot.

Unfortunately, even after commenting out the line you mentioned, TermuxArch still enters the proot after installation. See [this commit](https://github.com/sudomain/TermuxArch/commit/7b6f7b5a8cad633fa62c75c071ddbf836477077d) of my fork of TermuxArch
