### ISSUE TITLE
Error running fakeroot

### ISSUE THREAD

**Issue by HitaloKun** [SDRausty/TermuxArch#208]
**I'm trying to compile yay but I get an error referring to fakeroot using makepkg**

![](https://i.imgur.com/83T5N4S.jpg)

**Comment by alissonlauffer** [comment]
Duplicate of #26

**Comment by HitaloKun** [comment]
Problem solved, fakeroot work from and yay installed.

**Comment by johndoehack** [comment]
got error 416 when self configufing mirrors
