### ISSUE TITLE
vi: command not found

### ISSUE THREAD

**Issue by smu** [sdrausty/TermuxArch#21]
It tried to install Termux Arch on a chrombook using the latest setupTermuxArch.sh from this git repository. During install the scipt asks whether to use vi or nano for file editing. When I choose vi, 
I get the following error message afterwards.

```
Would you like to run `locale-gen` to generate the en_US.UTF-8 locale or do you want to edit /etc/locale.gen specifying your preferred language before running `locale-gen`?  Answer run or edit [r|e].  e
/data/data/com.termux/files/home/arch/root/bin/finishsetup.sh: line 23: vi: command not found
```

vi, however, is installed in my termux environment.

```
$ which vi
/data/data/com.termux/files/usr/bin/vi
```

 I also tried to select nano, this results in a "nano: command not found". 

![screenshot 2017-11-21 at 20 09 17](https://user-images.githubusercontent.com/207880/33091773-5c455f94-cef8-11e7-869e-2551901c0c0e.png)

**Comment by smu** [comment]
OK, i understood that this part of the installation is already running inside of the PRoot, and that there is no [vi|nano] in /usr/bin of the arch installation.

**Comment by sdrausty** [comment]
@smu Thank you for opening this issue.  The script uses Arch components once installed since certain functions need to be performed inside Arch when it is running, like `locale-gen` and `pacman -Syu`. Both editors should reside in your Arch installation:

```
[root@localhost home]# which vi
/usr/bin/vi
[root@localhost home]# l /usr/bin/vi
lrwxrwxrwx 1 root 2 Sep 18  2015 /usr/bin/vi -> ex
[root@localhost home]# which nano
/usr/bin/nano
[root@localhost home]# l /usr/bin/nano
-rwxr-xr-x 1 root 254016 Nov 22 00:59 /usr/bin/nano
[root@localhost home]# ex
[root@localhost home]# vi
[root@localhost home]# nano
```
You can run Arch Linux in Termux by using `startarch` even though the system is not configured.  Please submit a screenshot of your Arch login with `ls -al`.

Without an i686 nor a Chromebook, there is still much we can do to help people with this device out. So if you can provide the following, this should help us out:
1  `uname -mo`
2  `getprop ro.product.cpu.abi`
3  `getprop ro.product.device`
4  `ls -al ~/arch`

Also login to Arch and see which editors are available.  **Important `setupTermuxArch.sh` was rewritten to improve Chromebook detection a couple of days age.  Are you using the latest version of  [`setupTermuxArch.sh`](https://sdrausty.github.io/TermuxArch/setupTermuxArch.sh)?**

**Comment by smu** [comment]
Thanks for your reply. Yes, I use a recent version of setupTermuxArch.sh from git  (06b7b7fc0ff0a743187ef4fac8759e3fa1bdd829). 

vi|nano are not installed within arch (see the attached screenshot). 

![screenshot 2017-11-22 at 19 31 16](https://user-images.githubusercontent.com/207880/33143980-e578330e-cfbb-11e7-8207-ff0ce8ef27b2.png)

Please find below the requested information:

```
$ uname -mo
i686 Android
$ getprop ro.product.cpu.abi
x86
$ getprop ro.product.device
cyan_cheets
$ ls -al ~/arch/
total 2036
drwx------ 18 u0_a39 u0_a39    4096 Nov 21 20:31 .
drwx------ 13 u0_a39 u0_a39    4096 Nov 21 20:59 ..
-rw-r--r--  1 u0_a39 u0_a39    1276 Mar  1  2017 README
lrwxrwxrwx  1 u0_a39 u0_a39      18 Dec  6  2016 bin -> usr/bin
drwxr-xr-x  2 u0_a39 u0_a39    4096 Dec  6  2016 boot
drwx------  3 u0_a39 u0_a39    4096 Nov 21 20:31 data
drwxr-xr-x  2 u0_a39 u0_a39    4096 Mar  1  2017 dev
drwxr-xr-x 27 u0_a39 u0_a39    4096 Nov 21 20:42 etc
drwxr-xr-x  2 u0_a39 u0_a39    4096 Dec  6  2016 home
lrwxrwxrwx  1 u0_a39 u0_a39      18 Dec  6  2016 lib -> usr/lib
drwxr-xr-x  2 u0_a39 u0_a39    4096 Dec  6  2016 mnt
drwxr-xr-x  2 u0_a39 u0_a39    4096 Dec  6  2016 opt
dr-xr-xr-x  2 u0_a39 u0_a39    4096 Mar  1  2017 proc
drwxr-x---  4 u0_a39 u0_a39    4096 Nov 21 20:14 root
drwxr-xr-x  2 u0_a39 u0_a39    4096 Mar  1  2017 run
lrwxrwxrwx  1 u0_a39 u0_a39      18 Dec  6  2016 sbin -> usr/bin
drwxr-xr-x  4 u0_a39 u0_a39    4096 Dec  6  2016 srv
-rwx------  1 u0_a39 u0_a39     387 Nov 21 20:08 startarch
d---------  2 u0_a39 u0_a39    4096 Nov 21 20:31 storage
dr-xr-xr-x  2 u0_a39 u0_a39    4096 Mar  1  2017 sys
drwxrwxrwt  2 u0_a39 u0_a39    4096 Nov 21 20:38 tmp
drwxr-xr-x  8 u0_a39 u0_a39    4096 Mar  1  2017 usr
drwxr-xr-x 12 u0_a39 u0_a39    4096 Mar  1  2017 var
-rwx------  1 u0_a39 u0_a39 1902580 Nov 21 20:19 vi
```

**Comment by sdrausty** [comment]
@smu Thank you for your time and quick reply. I have two questions which will hopefully resolve this matter:
1 Is the script still stating, "Detected i686 Android Operating System."? It should be stating, "Detected i686 Chromebook" on your device.
2 Which editors does `archlinux-bootstrap-2017.03.01-i686.tar.gz` install? Possibly a slightly older image is in order?  

A work around might be `pacman -S nano vi` and then running editors.  I would prefer to use the editor that comes with `archlinux-bootstrap-2017.03.01-i686.tar.gz`.

Also, where is your default `download` directory on your Chromebook? The default directory where your web browser downloads to on Chromebook.

**Comment by smu** [comment]
OK, I did a fresh installation with the current git version after deleting the existing arch/ directory. 

1. The installation still states "Detected i686 Android Operating System"

![screenshot 2017-11-22 at 20 31 21](https://user-images.githubusercontent.com/207880/33146506-ad8c5ad4-cfc4-11e7-8e6e-95e561269ed3.png)

2. As far as I can see, there is not a single editor available in the bootstrab archive. At least no one I know (there are about 600 programs under `/usr/bin`). The editor is not the only problem. For instance, `sed` is missing as well, therefore /bin/locale-gen also produces an error during installation. 

Regarding the work around. I think the problem is, that the mirrorlist needs to be configured first, before `pacman` can be used. I solved this by editing the mirrorlist from "outside" (i.e., before entering the PRoot). Still, the bootstrab archive seems to be very limited and I had a number of problems with the archive keys before the installation suceeded. 

I do not really now, where the default `download` directory exists. On a chromebook, there is a download directory in chrome os, which is available in Termux in `/data/data/com.termux/files/home/storage/downloads` after `termux-setup-storage` has been executed. 
This is the directory, where e.g. chrome running on chrome OS places the downloads. 
Moreover, there is a download directory in the home folder (`/data/data/com.termux/files/home/downloads`).

**Comment by sdrausty** [comment]
@smu awesome reply. 

1 Detection message wants refinement, both 
detectsystem2 () and detectsystem2p () in https://raw.githubusercontent.com/sdrausty/TermuxArch/master/scripts/files/necessaryfunctions.sh  
2 Editing i686 Arch setup scripts wants editing from within Termux, not Arch. This should migrate to general install.  Probably in finishsetup () in https://raw.githubusercontent.com/sdrausty/TermuxArch/master/scripts/files/archsystemconfigs.sh

Regarding downloads directory:
`ls -al ~/storage/` result from your Chromebook is requested for more information regarding simplification of https://sdrausty.github.io/TermuxArch/docs/install option #3.

**Comment by sdrausty** [comment]
1  This commit https://github.com/sdrausty/TermuxArch/commit/29d52df815c114407ff6b2f291ca9f76740bd1c1 fixes system detection for Chromebook. 
2  This commit https://github.com/sdrausty/TermuxArch/commit/b19c64f9eeced36639e81b1e3587480e648fdb3b finishes a series of commits that resolves this issue by relying on Termux for editing of Arch Linux configuration files instead of editors in the newly installed system.

If these modifications did not work for you @smu, please reopen this issue.

**Comment by sdrausty** [comment]
This commit https://github.com/sdrausty/TermuxArch/commit/d7e9de5dd7348adf4c9631fd3d161faa123e9ff4 fixes the system detection message for Chromebook.

**Comment by smu** [comment]
Thank you. Is tested the bugfix with the recent version from github and can confirm that vim is found now. However, I will report a new issue regarding `sed`.

**Comment by wulvyrn** [comment]
using the latest script as of a few hours ago.  vi isn't found.  i'm using a chromebook pixelbook.  any advice?

**Comment by sdrausty** [comment]
@wulvyrn You shouldn't need `vi` as it's available in busybox through Termux.  Where exactly does `vi` fail?  Can you post some output?  To install `vim` in Arch Linux use `pacman -S vim`.

**Comment by wulvyrn** [comment]
pacman doesn't work as it cannot update.  will try and fix that first.
