### ISSUE TITLE
Failure when running pacman -Syu

### ISSUE THREAD

**Issue by bscout9956** [SDRausty/TermuxArch#210]
Here's the following log of what happens after a clean installation of TermuxArch.

> [root20:44home]$ pacman -Syu
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 alarm is up to date
 aur is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (42) ca-certificates-20181109-3
              ca-certificates-mozilla-3.49.2-3
              ca-certificates-utils-20181109-3
              cryptsetup-2.3.0-1  curl-7.68.0-1
              dbus-1.12.16-5  device-mapper-2.02.186-5
              e2fsprogs-1.45.5-1  expat-2.2.9-3
              file-5.38-3  gcc-libs-9.2.0-4
              glib2-2.62.4-1  glibc-2.30-3
              gnupg-2.2.19-1  gnutls-3.6.12-1
              grep-3.4-1  iana-etc-20200117-1
              iproute2-5.5.0-1  iptables-1:1.8.4-1
              krb5-1.17.1-1  libarchive-3.4.1-1
              libcap-2.30-1  libedit-20191231_3.1-1
              libnftnl-1.1.5-1  libsecret-0.20.1-1
              libtasn1-4.16.0-1  libtirpc-1.2.5-1
              libutil-linux-2.35.1-1
              mkinitcpio-busybox-1.31.1-1  nano-4.7-1
              p11-kit-0.23.20-2  pacman-5.2.1-4
              pacman-mirrorlist-20200108-1
              pcre2-10.34-3  sed-4.8-1  shadow-4.8.1-1
              sqlite-3.31.1-1  systemd-244.2-1
              systemd-libs-244.2-1
              systemd-sysvcompat-244.2-1
              util-linux-2.35.1-1  zstd-1.4.4-1

Total Download Size:    63.69 MiB
Total Installed Size:  326.13 MiB
Net Upgrade Size:       47.05 MiB

:: Proceed with installation? [Y/n] Y
error: could not open file: /etc/mtab: No such file or directory
error: could not determine filesystem mount points
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
[root20:45home]$ cat /etc/mtab
cat: /etc/mtab: No such file or directory

I've looked up here and everywhere and couldn't find a solution

**Comment by mklan** [comment]
copy the file /proc/self/mounts to /proc/self/mounts inside your arch installation
