### ISSUE TITLE
Error when installing arch: getimagefunctions.bash: line 109: IFILE: unbound variable

### ISSUE THREAD

**Issue by TheFoppian** [SDRausty/TermuxArch#211]
I get this error when trying to install Arch on my chromebook using the Android app function. Note that my chromebook is a 32-bit system, if it's relevant. I apologize if this has already been raised.
![Screenshot 2020-02-19 at 3 28 14 PM](https://user-images.githubusercontent.com/38819438/74878358-c6f78c80-532c-11ea-8776-70e28df69e0e.png)

**Comment by lifers** [comment]
Mine too,
```
🕛 > 🕛 ＴｅｒｍｕｘＡｒｃｈ /data/data/com.termux/files/home/arch shall attempt to install Linux in /data/data/com.termux/files/home/arch.  Arch Linux in Termux PRoot shall be available upon successful completion.  To run this BASH script again, use `!!`.  Ensure background data is not restricted.  Check the wireless connection if you do not see one o'clock 🕐 below.  If you get a '/usr/bin/env' not found error, please comment at issues https://github.com/termux/proot/issues/72 and 76 Checking prerequisites…

Found download tool `curl`: Continuing…

Using curl to manage downloads.

 🕛 > 🕧 Prerequisites: OK  Downloading TermuxArch…

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   153  100   153    0     0    117      0  0:00:01  0:00:01 --:--:--   117
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 29965  100 29965    0     0  39427      0 --:--:-- --:--:-- --:--:-- 39375

 🕛 > 🕐 TermuxArch download: OK

 🕛 > 🕜 TermuxArch 2.0.12 integrity: OK

Setting locales to: Language >> en_GB << Region

 🕛 > 🕝 Detected i686 Chromebook.

 🕛 > 🕒 Activating termux-wake-lock: DONE


 🕛 > 🕞 Downloading checksum from http://archive.archlinux.org…

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   169  100   169    0     0    113      0  0:00:01  0:00:01 --:--:--   112
100   220  100   220    0     0     61      0  0:00:03  0:00:03 --:--:--   179
getimagefunctions.bash: line 109: IFILE: unbound variable

 TermuxArch WARNING:  Generated script signal 1 near or at line number 615 by `trap`!

setupTermuxArch.sh  2.0.12: [Exit Signal 201] DONE
```

this is my sysinfo log:
```
Begin TermuxArch 2.0.12 system information.

dpkg --print-architecture result:

i686

uname -a results:

Linux localhost 4.14.149-13636-g9eade7219710 #1 SMP PREEMPT Fri Jan 10 00:14:58 PST 2020 i686 Android

BASH_VERSINFO[0] = 5
BASH_VERSINFO[1] = 0
BASH_VERSINFO[2] = 16
BASH_VERSINFO[3] = 1
BASH_VERSINFO[4] = release
BASH_VERSINFO[5] = i686-pc-linux-android

cat /proc/cpuinfo results:

processor	: 0
vendor_id	: AuthenticAMD
cpu family	: 21
model		: 112
model name	: AMD A4-9120C RADEON R4, 5 COMPUTE CORES 2C+3G
stepping	: 0
microcode	: 0x6006705
cpu MHz		: 1775.678
cache size	: 1024 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 16
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good acc_power nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm perfctr_core perfctr_nb bpext ptsc mwaitx cpb hw_pstate ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 xsaveopt arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov
bugs		: fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 3194.37
TLB size	: 1536 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm 100mhzsteps hwpstate cpb eff_freq_ro acc_power [13]

processor	: 1
vendor_id	: AuthenticAMD
cpu family	: 21
model		: 112
model name	: AMD A4-9120C RADEON R4, 5 COMPUTE CORES 2C+3G
stepping	: 0
microcode	: 0x6006705
cpu MHz		: 1957.514
cache size	: 1024 KB
physical id	: 0
siblings	: 2
core id		: 1
cpu cores	: 2
apicid		: 17
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good acc_power nopl nonstop_tsc cpuid extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 movbe popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm perfctr_core perfctr_nb bpext ptsc mwaitx cpb hw_pstate ssbd ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 xsaveopt arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif overflow_recov
bugs		: fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
bogomips	: 3194.37
TLB size	: 1536 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 48 bits physical, 48 bits virtual
power management: ts ttp tm 100mhzsteps hwpstate cpb eff_freq_ro acc_power [13]


Download directory information results:

/sdcard/Download exists
/storage/emulated/0/Download exists
~/downloads not found
/data/data/com.termux/files/home/storage/downloads exists

Device information results:

/dev/ashmem exists
/dev/ashmem is readable
/dev/shm does not exist
/dev/shm is not readable
/proc/stat does not exit
/proc/stat is not readable

getprop results:

[getprop gsm.sim.operator.iso-country]: []
[getprop net.bt.name]: [Android]
[getprop net.dns1]: []
[getprop net.dns2]: []
[getprop net.dns3]: []
[getprop net.dns4]: []
[getprop persist.sys.locale]: [en-GB]
[getprop ro.build.target_country]: []
[getprop ro.build.version.release]: [9]
[getprop ro.build.version.preview_sdk]: [0]
[getprop ro.build.version.sdk]: [28]
[getprop ro.com.google.clientidbase]: []
[getprop ro.com.google.clientidbase.am]: []
[getprop ro.com.google.clientidbase.ms]: []
[getprop ro.product.device]: [grunt_cheets]
[getprop ro.product.cpu.abi]: [x86]
[getprop ro.product.first_api_level]: [28]
[getprop ro.product.locale]: []
[getprop ro.product.manufacturer]: [Google]
[getprop ro.product.model]: [grunt]

Disk report 3899056 on /data Fri Feb 28 14:20:59 +07 2020

df /data/data/com.termux/files/home/arch results:

Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/mmcblk1p1  21512696 16497800   3899048  81% /data

df results:

Filesystem                                                    1K-blocks     Used Available Use% Mounted on
/dev/loop1                                                       429312   429312         0 100% /
/dev/loop4                                                        23680    23680         0 100% /vendor
tmpfs                                                           1982392      328   1982064   1% /dev
tmpfs                                                           1982392        0   1982392   0% /dev/socket
tmpfs                                                           1982392        0   1982392   0% /dev/usb-ffs/adb
/dev/mmcblk1p1                                                 21512696 16497800   3899048  81% /data/dalvik-cache/x86
tmpfs                                                           1982392        0   1982392   0% /var/run/arc
tmpfs                                                           1982392        0   1982392   0% /var/run/arc/sdcard
/opt/google/containers/android/rootfs/android-data/data/media  21512696 16497800   3899048  81% /var/run/arc/sdcard/default/emulated
/opt/google/containers/android/rootfs/android-data/data/media  21512696 16497800   3899048  81% /var/run/arc/sdcard/read/emulated
/opt/google/containers/android/rootfs/android-data/data/media  21512696 16497800   3899048  81% /var/run/arc/sdcard/write/emulated
tmpfs                                                           1982392        0   1982392   0% /var/run/arc/obb
tmpfs                                                           1982392        0   1982392   0% /var/run/arc/media
passthrough                                                     1982392        0   1982392   0% /var/run/arc/media/removable
passthrough                                                    21512696 16497800   3899048  81% /var/run/arc/media/MyFiles
passthrough                                                     1982392        0   1982392   0% /var/run/arc/media/removable-write
passthrough                                                     1982392        0   1982392   0% /var/run/arc/media/removable-default
passthrough                                                    21512696 16497800   3899048  81% /var/run/arc/media/MyFiles-write
passthrough                                                    21512696 16497800   3899048  81% /var/run/arc/media/MyFiles-default
tmpfs                                                           1982392        0   1982392   0% /sys/kernel/debug
tmpfs                                                           1982392       12   1982380   1% /oem/etc
tmpfs                                                           1982392        0   1982392   0% /mnt

du -hs /data/data/com.termux/files/home/arch results:

676K	/data/data/com.termux/files/home/arch

ls -al /data/data/com.termux/files/home/arch results:

total 84
drwx------  8 u0_a64 u0_a64 4096 Feb 28 14:19 .
drwx------ 16 u0_a64 u0_a64 4096 Feb 28 14:20 ..
drwx------  2 u0_a64 u0_a64 4096 Feb 28 14:19 etc
-rw-------  1 u0_a64 u0_a64  220 Feb 28 14:19 md5sums.txt
drwx------  3 u0_a64 u0_a64 4096 Feb 28 14:19 root
drwx------  3 u0_a64 u0_a64 4096 Feb 28 14:19 run
-rwx------  1 u0_a64 u0_a64 7285 Feb 28 14:19 startarch
drwxrwxrwt  3 u0_a64 u0_a64 4096 Feb 28 14:20 tmp
drwx------  3 u0_a64 u0_a64 4096 Feb 28 14:19 usr
drwx------  3 u0_a64 u0_a64 4096 Feb 28 14:19 var

End `setupTermuxArchSysInfo92aa.log` 2.0.12 system information.
[0m
Share this information along with your issue at https://github.com/sdrausty/TermuxArch/issues; include input and output.  This file is found in `/data/data/com.termux/files/home/setupTermuxArchSysInfo92aa.log`.  If you think screenshots will help in a quicker resolution, include them in the post as well.  
```

**Comment by mazhe1988** [comment]
Mine too
Begin TermuxArch 2.0.12 system information.

dpkg --print-architecture result:

x86_64

uname -a results:

Linux localhost 4.9.214-android-x86_64-642290-g70b4ccb164a11-dirty #1 SMP PREEMPT Sat Apr 11 15:05:51 EDT 2020 x86_64 Android

BASH_VERSINFO[0] = 5
BASH_VERSINFO[1] = 0
BASH_VERSINFO[2] = 17
BASH_VERSINFO[3] = 1
BASH_VERSINFO[4] = release
BASH_VERSINFO[5] = x86_64-pc-linux-android

cat /proc/cpuinfo results:

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 94
model name	: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
stepping	: 3
microcode	: 0xa0
cpu MHz		: 1216.687
cache size	: 6144 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
bogomips	: 5184.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 94
model name	: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
stepping	: 3
microcode	: 0xa0
cpu MHz		: 1469.799
cache size	: 6144 KB
physical id	: 0
siblings	: 8
core id		: 1
cpu cores	: 4
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
bogomips	: 5184.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 94
model name	: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
stepping	: 3
microcode	: 0xa0
cpu MHz		: 1216.687
cache size	: 6144 KB
physical id	: 0
siblings	: 8
core id		: 2
cpu cores	: 4
apicid		: 4
initial apicid	: 4
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
bogomips	: 5184.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 94
model name	: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
stepping	: 3
microcode	: 0xa0
cpu MHz		: 1850.817
cache size	: 6144 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 4
apicid		: 6
initial apicid	: 6
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
bogomips	: 5184.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 4
vendor_id	: GenuineIntel
cpu family	: 6
model		: 94
model name	: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
stepping	: 3
microcode	: 0xa0
cpu MHz		: 1275.561
cache size	: 6144 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
bogomips	: 5184.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 5
vendor_id	: GenuineIntel
cpu family	: 6
model		: 94
model name	: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
stepping	: 3
microcode	: 0xa0
cpu MHz		: 1212.084
cache size	: 6144 KB
physical id	: 0
siblings	: 8
core id		: 1
cpu cores	: 4
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
bogomips	: 5184.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 6
vendor_id	: GenuineIntel
cpu family	: 6
model		: 94
model name	: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
stepping	: 3
microcode	: 0xa0
cpu MHz		: 1532.482
cache size	: 6144 KB
physical id	: 0
siblings	: 8
core id		: 2
cpu cores	: 4
apicid		: 5
initial apicid	: 5
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
bogomips	: 5184.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 7
vendor_id	: GenuineIntel
cpu family	: 6
model		: 94
model name	: Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
stepping	: 3
microcode	: 0xa0
cpu MHz		: 1200.024
cache size	: 6144 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 4
apicid		: 7
initial apicid	: 7
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb invpcid_single tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa itlb_multihit
bogomips	: 5184.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:


Download directory information results:

/sdcard/Download exists
/storage/emulated/0/Download exists
~/downloads not found
/data/data/com.termux/files/home/storage/downloads not found

Device information results:

/dev/ashmem exists
/dev/ashmem is readable
/dev/shm does not exist
/dev/shm is not readable
/proc/stat exits
/proc/stat is readable

getprop results:

[getprop gsm.sim.operator.iso-country]: []
[getprop net.bt.name]: [Android]
[getprop net.dns1]: [192.168.86.1]
[getprop net.dns2]: []
[getprop net.dns3]: []
[getprop net.dns4]: []
[getprop persist.sys.locale]: []
[getprop ro.build.target_country]: []
[getprop ro.build.version.release]: [9]
[getprop ro.build.version.preview_sdk]: [0]
[getprop ro.build.version.sdk]: [28]
[getprop ro.com.google.clientidbase]: [android-google]
[getprop ro.com.google.clientidbase.am]: []
[getprop ro.com.google.clientidbase.ms]: []
[getprop ro.product.device]: [x86_64]
[getprop ro.product.cpu.abi]: [x86_64]
[getprop ro.product.first_api_level]: [19]
[getprop ro.product.locale]: [en-US]
[getprop ro.product.manufacturer]: [Dell Inc.]
[getprop ro.product.model]: [Precision 3510]

Disk report 161192412 on /data Thu Apr 30 21:33:58 EDT 2020

df /data/data/com.termux/files/home/arch results:

Filesystem      1K-blocks     Used Available Use% Mounted on
/dev/block/sda3 186092444 15377408 161192400   9% /data

df results:

Filesystem       1K-blocks     Used Available Use% Mounted on
tmpfs             16390060     4776  16385284   1% /
/dev/loop0         3409848  2965592    427872  88% /system
/dev/block/loop1     41856    41856         0 100% /system/lib/arm
/dev/block/sda3  186092444 15377408 161192400   9% /data
tmpfs             16390060      340  16389720   1% /dev
tmpfs             16390060        0  16390060   0% /mnt
none              16390060        0  16390060   0% /cache
/data/media      186092444 15377408 161192400   9% /storage/emulated

du -hs /data/data/com.termux/files/home/arch results:

392K	/data/data/com.termux/files/home/arch

ls -al /data/data/com.termux/files/home/arch results:

total 44
drwx------ 8 u0_a193 u0_a193 4096 Apr 30 21:26 .
drwx------ 4 u0_a193 u0_a193 4096 Apr 30 21:33 ..
drwx------ 2 u0_a193 u0_a193 4096 Apr 30 21:26 etc
-rw------- 1 u0_a193 u0_a193  145 Apr 30 21:26 md5sums.txt
drwx------ 3 u0_a193 u0_a193 4096 Apr 30 21:26 root
drwx------ 3 u0_a193 u0_a193 4096 Apr 30 21:26 run
-rwx------ 1 u0_a193 u0_a193 6903 Apr 30 21:26 startarch
drwxrwxrwt 3 u0_a193 u0_a193 4096 Apr 30 21:33 tmp
drwx------ 3 u0_a193 u0_a193 4096 Apr 30 21:26 usr
drwx------ 3 u0_a193 u0_a193 4096 Apr 30 21:26 var

End `setupTermuxArchSysInfo7637.log` 2.0.12 system information.
[0m
Share this information along with your issue at https://github.com/sdrausty/TermuxArch/issues; include input and output.  This file is found in `/data/data/com.termux/files/home/setupTermuxArchSysInfo7637.log`.  If you think screenshots will help in a quicker resolution, include them in the post as well.

**Comment by SDRausty** [comment]
This https://github.com/TermuxArch/TermuxArch/commit/e323408b9b8d4bb64a609411b21e6ff26f5fe7ff commit rewrote image selection for Chromebooks. Image ArchLinuxARM-aarch64-chromebook-latest.tar.gz was added.
