### ISSUE TITLE
how to make startarch the default shell?

### ISSUE THREAD

**Issue by sudomain** [SDRausty/TermuxArch#212]
[The docs](https://sdrausty.github.io/docsTermuxArch/startingArch.html) report that you can 

>  Run chsh and change your login shell to startarch

I'm attempting to do this and running chsh interactively or doing `chsh -s startarch` results in this error when opening a new Termux session:

` /data/data/com.termux/files/usr/bin/login: 27: exec: /data/data/com.termux/files/usr/bin/startarch: not found

[Process completed (code 127) - press Enter] `

I checked that /data/data/com.termux/files/usr/bin/startarch actually exists and is executable. Also my $PREFIX/usr/bin/login  file has not been modified.

Adding `startarch` to bashrc technically does the trick, but seems really hacky especially since chsh is the method recommended by the docs

All help would be appreciated

**Comment by sudomain** [comment]
[Relavent section of the Termux wiki](https://wiki.termux.com/wiki/Recover_a_broken_environment) incase anyone attempts this and forgets to change their shell back with `chsh -s bash`

**Comment by SDRausty** [comment]
Search https://github.com/SDRausty/TermuxArch/issues?q=is%3Aissue+default+shell yields:
[Starting Arch Linux from Termux? #25](https://github.com/SDRausty/TermuxArch/issues/25)

**Comment by ReekyMarko** [comment]
Same issue here. If I go the extra mile and point to the startarch script absolutely, I get this
```
$ chsh -s /data/data/com.termux/files/home/arch/startarch

/data/data/com.termux/files/usr/bin//data/data/com.termux/files/home/arch/startarch is not an executable file!
```

**Comment by sudomain** [comment]
I guess the question is: does the `chsh` method work or not? It certainly doesn't work as it is written in the other issue or the [docs website page on the subject](https://termuxarch.github.io/docsTermuxArch/startingArch). The `chsh` method is the 3rd option mentioned, with the second no longer being relevant:

`1) Run ~/arch/startarch at the bash prompt. The bash shell interpreter is important!

2) Run startarch if you chose “copy to $PATH” during install. The bash shell interpreter is important!

3) Run chsh and change your login shell to startarch. Option 2 is required for this option to run correctly. When you open a session in Termux, it will login to Arch Linux. Important to undo this change and return to your Termux login, delete .termux/shell since chsh will be unavailable in Arch Linux to change your login shell.`

It seems that a few people have tried this method with different workarounds without success. If the `chsh` method is no longer viable I'll gladly be the one to submit a PR to the docs website that will remove references to the 2nd and 3rd methods.

**Comment by SDRausty** [comment]
> the question is: does the chsh method work or not

not 

> a few people have tried this method with different workarounds without

myself included

> PR to the docs website 

ok

**Comment by petkar** [comment]
It's probably safer to add `exec startarch` or `exec startarch u user` to the `.bashrc` file in termux if you want arch to start by default. chsh should be exclusively used to change login shells.

**Comment by xd003** [comment]
> It's probably safer to add `exec startarch` or `exec startarch u user` to the `.bashrc` file in termux if you want arch to start by default. chsh should be exclusively used to change login shells.

Isn't it ```exec startarch login user``` ?
exac startarch u user doesn't seem to work

**Comment by petkar** [comment]
> Isn't it exec startarch login user ?

AFIK, `startarch l user` and `startarch u user` (login and user options respectively) perform the same functions. Prefixing both of them `exec` with appears to work for me.


> exac startarch u user doesn't seem to work for me

There appears to be a typo. Could you try `exec` instead?


> Also its bash.bashrc file in data/data/com.termux/files/usr/etc if someone is wondering which exact file to edit

You could also make a `.bashrc` in `$HOME` using `touch ~/.bashrc` and edit that instead.
