### ISSUE TITLE
link to archlinuxarm.org rather than archlinux.org?

### ISSUE THREAD

**Issue by sudomain** [SDRausty/TermuxArch#214]
Correct me of I'm wrong: This project installs Arch Linux Arm which is a port of Arch Linux. Shouldn't this project therefor link to [Arch Linux Arm](https://archlinuxarm.org/about/contact) rather than archlinux.org in things like the `startarch` motd and other documentation? I ran into an issue a while ago which I sought help for in the irc channel that is currently linked to. I was told something along the lines that I technically wasn't running Arch, though they helped me anyway.

Linking to the [ArchLinuxArm packages forum](https://archlinuxarm.org/forum/viewforum.php?f=15) will likely reduce the number of GH issues opened regarding specific packages of the distro, which is out of scope for this project right?

**Comment by SDRausty** [comment]
> This project installs Arch Linux Arm which is a port of Arch Linux.

This project attempts to install and configure Arch Linux on device for these architectures:
[_DETECTSYSTEM_() {
	_PRINTDETECTEDSYSTEM_
	if [[ "$CPUABI" = "$CPUABI5" ]]
	then
		_ARMV5L_
	elif [[ "$CPUABI" = "$CPUABI7" ]]
	then
		_DETECTSYSTEM2_ 
	elif [[ "$CPUABI" = "$CPUABI8" ]]
	then
		_AARCH64_
	elif [[ "$CPUABI" = "$CPUABIX86" ]]
	then
		_I686_ 
	elif [[ "$CPUABI" = "$CPUABIX86_64" ]]
	then
		_X86_64_
	else
		_PRINTMISMATCH_ 
	fi
}](https://github.com/TermuxArch/TermuxArch/blob/master/necessaryfunctions.bash#L84&&#L104)

This https://github.com/TermuxArch/TermuxArch/commit/bc4ee47387f07c4a38adceecdfd52e4d960a5d63 commit adds arvhitecture support to `printoutstatements.bash`.  Thank you for the link @sudomain :fireworks:

**Comment by SDRausty** [comment]
This https://github.com/TermuxArch/TermuxArch/commit/663cd0e325736ce63d89089124d83879ee14a6ff commit adds device architecture support to `motd`.
