### ISSUE TITLE
Can't install using setupTermuxArch.sh

### ISSUE THREAD

**Issue by Parsepec** [SDRausty/TermuxArch#216]
I'm using a Huawei y9 2019 phone with an architecture of aarch64, I can't seem to be able to install using the script. It get stuck at the "Contacting worldwide mirror https://os.archlinuxarm.org:" 
And sometimes Outputs "printoutstatements.bash: line 149: -1: substring expression < 0"

**Comment by SDRausty** [comment]
>  printoutstatements.bash: line 149: -1: substring expression < 0"

The file [printoutstatements.bash](https://raw.githubusercontent.com/TermuxArch/TermuxArch/master/printoutstatements.bash) has been updated.  @Parsepec see if these latest commits have resolved the error on your device as I cannot reproduce it.

**Comment by SDRausty** [comment]
Continue comments in this closed issue; should you encounter install fail upon : telephone : type:
> Huawei y9 2019 phone with an architecture of aarch64
