### ISSUE TITLE
How to exit  from ssh with keeping the arch running?

### ISSUE THREAD

**Issue by Zonzely** [SDRausty/TermuxArch#219]
I launched the `sshd` and added `startarch` to the `.bashrc` on the `termux`, so when I ssh to the `termux` from my computer, I would get a shell of `arch`.
But when I quit from the shell on my computer,  the `arch` will also exit, and I need some programs to keep running on the `arch`.
 So how to exit from ssh with keeping the arch running. 
Thanks!

**Comment by lypanov** [comment]
My personal workaround to this has been to run the long living programs I need from .bashrc on termux startup. You can use something like "startarch c scripts/archinit.sh" and automate anything you always need running within this file.

I run this script based on the presence of the BOOTCLASSPATH environment variable as this only seems to be set in the case of direct termux session but not when sshing in.

**Comment by Zonzely** [comment]
I tried using `startarch s user cmd` and `tmux` on the `termux`, it did work well.
Thanks again!
