### ISSUE TITLE
Patch failure due to selinux errors when using AUR / makepkg

### ISSUE THREAD

**Issue by lypanov** [SDRausty/TermuxArch#220]
Good day!

I've spent a few hours this evening diving into getting k2pdfopt running in TermuxArch. It runs in Termux itself but I'd prefer to have everything in TermuxArch.

I'm running into the same issue i see mentioned a few times in other issues:
  patch: setting attribute security.selinux for security

Using strace I've narrowed this down to:
  lsetxattr("./CMakeLists.txt.oAQQFZ9", "security.selinux", "u:object_r:app_data_file:s0:c219"..., 48, 0 
  ...
  <... lsetxattr resumed>)    = -1 EACCES (Permission denied)

From what I can tell based on other issues in Termux itself I should be running this as root else some random selinux hacks don't kick in (really unsure of this but the idea I got).

Alas makepkg throws a fit if I attempt to run it under root and I'm yet to find a workaround.

Any ideas what I could do? I'm unsure why patch even needs to apply these extended attribute changes!

Thank you so much for any help / guidance,
Alex

**Comment by SDRausty** [comment]
Howdy,
`makepkg` and root do not mix; `sudo` might help.  Try these links for `makepkg` issues:

  * https://github.com/SDRausty/TermuxArch/issues?q=is%3Aissue+makepkg

  * https://github.com/SDRausty/termux-arch/issues?q=is%3Aissue+makepkg

  * https://github.com/SDRausty/termux-archlinux/issues?q=is%3Aissue+makepkg

  * https://github.com/TermuxArch/TermuxArch/issues?q=is%3Aissue+makepkg

You are welcome @lypanov, and thank you for taking part in these projects!  Share your progress here please.

**Comment by HoshiYamazaki** [comment]
I encountered the same issue while trying to build fakeroot-tcp from Arch, despite having bunch of acl errors due to probably that issue:
https://github.com/SDRausty/TermuxArch/issues/83

So I just assume that for now makepkg is not working either, and Arch heavily bases on that ;( I wanted to get working polybar and mesa with llvmpipe acceleration. Hope you will get it working in future @SDRausty

**Comment by SDRausty** [comment]
> for now makepkg is not working either, 

@HoshiYamazaki just in; `makepkg` is working again. 
> [The patch is now included in the root directory of the project](https://github.com/SDRausty/TermuxArch/issues/38#issuecomment-660610818)

> The command `setupTermuxArch.bash r` refreshes the installation quickly

**Comment by SDRausty** [comment]
This https://github.com/TermuxArch/TermuxArch/commit/161eaba60cedcd687f7d6282d5ee1a2a292e902d commit automates adding sudo users.

```
printf "%s\\n" "\$1 ALL=(ALL) ALL" >> /etc/sudoers
sed -i "s/\$1:x/\$1:/g" /etc/passwd
```
