### ISSUE TITLE
Cannot use makepkg on android

### ISSUE THREAD

**Issue by Josh012422** [SDRausty/TermuxArch#221]
Backstory

I installed TermuxArch yesterday, to use GitHub CLI, got some problems with pacman, solved It. But nos my problema is with makepkg, searched Google for solutions but there are not solutions.

My Problem

When i use the command:
`makepkg -si`

It gives me this error:
`/usr/bin/makepkg: line 1111: load_makepkg_config: command not found

/usr/bin/makepkg: line 111: error: command not found
User defined signal 1`

And if i start fakeroot:
`fakeroot, while creating message channels: Function not implemented
This may be due to a lack of SYSV IPC support.
fakeroot: error while starting the 'faked' daemon.
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]`

Specs

Acer Iconia One b1-780

uname -a (TermuxArch) output:
`Linux localhost 3.18.22 #1 SMP PREEMPT Thu May 18 09:49:57 CST 2017 aarch64 GNU/Linux`

uname -a ("Vanilla"Termux) output:

Linux localhost 3.18.22 #1 SMP PREEMPT Thu May 18 09:49:57 CST 2017 aarch64 Android

Thanks in advance!

P.D: btw, great work with TermuxArch

**Comment by SickBoy-Droid** [comment]
`pacman -S base-devel`

Directly press enter to select all.

**Comment by SickBoy-Droid** [comment]
I have downloaded that a hundered times, but still i am getting these weired errors!
