### ISSUE TITLE
(aapt error) Can't execute 'aapt' binary in Termux-Arch

### ISSUE THREAD

**Issue by SickBoy-Droid** [SDRausty/TermuxArch#223]
First of all thanks for such a great tool.
From last few days I was running Termux-Arch in termux. I explored most of the things but from last night a strange thing happened.

Actually I was trying to build android apps in termux-arch but I am unable to execute `aapt` binary that comes with android-sdk.

Below are some attempts that I hava done so far:
![Screenshot_2020-04-18-18-07-21-93_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/62709136/79637741-7cb15100-819f-11ea-971b-ea9e4fe5cfaf.jpg)

As you can see in above image I have tried every possible action but nothing helped. I gave all required permissions but that also didn't worked. Also not only `aapt` but also other binaries in this folder (android-sdk) are not running.

**Comment by OverPie** [comment]
binary file compiled for amd64 architecture, do your phone have it?

**Comment by Game-Of-Coding** [comment]
Thank you for repying!
Now how can i make them to run on my Arm64 device...?

**Comment by OverPie** [comment]
@Game-Of-Coding it's impossible

**Comment by Game-Of-Coding** [comment]
Really?
Then where the packages like 'aapt' came in Termux?
I think there should some sort of way to recompile the source code for arm64 devices...!

**Comment by SDRausty** [comment]
> Now how can i make them to run on my Arm64 device...?

See issue [CANNOT LINK EXECUTABLE "/data/data/com.termux/files/usr/bin/qemu-x86_64": library "libm.so" not found](https://github.com/termux/termux-packages/issues/5444) which has instructions how to modify `startarch` to use [qemu](https://github.com/qemu/qemu).

**Comment by SDRausty** [comment]
> modify `startarch`

Using something such as `cd ~/arch/startarch && cp startarch startarch.bkp` before editing is advised.  Here is a working example from `startarch+arch8664`; `exec proot -q /data/data/com.termux/files/usr/bin/qemu-x86_64 --kill-on-exit --link2symlink -0 -r /data/data/com.termux/files/home/arch8664 -b /system -b $PREFIX -b /data/data/com.termux/files/home/arch8664/tmp:/dev/shm -b /data/data/com.termux/files/home/arch8664/var/binds/fbindprocstat:/proc/stat -b /proc/self/fd/1:/dev/stdout -b /proc/self/fd/2:/dev/stderr -b "$ANDROID_DATA" -b /dev/ -b "$EXTERNAL_STORAGE" -b "$HOME" -b /proc/ -b /storage/ -b /sys/ -w "$PWD" /usr/bin/env -i HOME=/root TERM=xterm-256color  /bin/bash -l`.

> QEMU is a generic and open source machine emulator and virtualizer. 

https://www.qemu.org/
```
$ pkg list-installed | grep qemu
qemu-common/stable,now 1:4.1.1-5 arm [installed]
qemu-user-x86_64/stable,now 1:4.1.1-5 arm [installed]
qemu-utils/stable,now 1:4.1.1-5 arm [installed]
```
[`au`](https://wae.github.io/au/) can be used to install qemu in [Termux](https://github.com/termux).

**Comment by SDRausty** [comment]
> thanks for such a great tool.

My pleasure.  You are welcome.  Many plp are contributing.  I thank all of us too;)
