### ISSUE TITLE
Is libandroid-shmem working inside TermuxArch?

### ISSUE THREAD

**Issue by Root-voidX** [SDRausty/TermuxArch#226]
Dear SDRausty and everyone else,

I hope everyone is staying safe during these times. I would like to announce that I am back into the whole linux on android. I have used Linux On Dex, UserLAnd, and Anlinux. They all fail for my testing due to not being able to access shared memory. It fails to run an QNative apps. As well as cause segfaults for FreeCAD, Gmsh, Paraview and even for certain CFD apps too. I want to see how well linux on arm64 is for scientific/engineering computation. Anyway I am wondering if TermuxArch as it is current, support libandroid-shmem, make, and pulseaudio? Have the python issues from 2017 have been fixed?

Thanks

**Comment by HoshiYamazaki** [comment]
For me make and pulseaudio is working, libandroid-shmem probably not, and because of that `makepkg` and `fakeroot-tcp` fails causing whole AUR-system being useless for that moment.
