### ISSUE TITLE
Proot handles 32 bit program only

### ISSUE THREAD

**Issue by RavanNaimish** [SDRausty/TermuxArch#227]
I was trying to install nethunter rootless but got this error, please help me

$ nh
proot error: '/data/data/com.termux/files/home/kali-arm64/usr/bin/env' is a 64-bit program whereas this version of proot handles 32-bit programs only
proot info: vpid 1: terminated with signal 11

**Comment by HoshiYamazaki** [comment]
Do you use 32-bit ARM CPU? Because I don't quite get that. For me applications works fine.

Also you use KaliLinux, so what you want from Arch???
