### ISSUE TITLE
Lets discuss which shared memory .so library would be downloaded and stored in to resulting ArchlLinux container

### ISSUE THREAD

**Issue by JanuszChmiel** [SDRausty/TermuxArch#228]
Yes, It is here. I have spent many many hours while working with ArchLinux. It is really Linux distribution for vide range of users, advanced users, server admins and programmers. BUt There are many applications, which require shared memory. And even their developers have prepared its source code so it contain also alternative development techniques, which do not stricly depend on shared memory, if shared memory will not be available, apps will run slowly. SOme apps even refuse to run if shared memory is not supported.
We do not have to forget, that we must find universal shared memory library. Termux contain one. But it is not for Libc on regulalLinux distros. So there are two shared memory concepts, I do not know about others.
The most reliable and stable is Thepart of Debian no root source code.
It is little compiled .so library. I have intensively tested it with mate and many apps including PCManfm file manager and with Orca.
Sure. Very complex shared memory routines, when app allocate and free too much memory regions are not supported by this .so library. The good example of such app is x11vnc if somebody would try to run it without -noshm option.

Debian no root source is here and excellent .so libraryesto add shared memory support are The part of The source code.

Next shared memory technique is The part of Userland source code.
I do not know its extact name. When I have ttried shared memory library from Pelia it  really do its best to support shared memory operations as possible.
You can load this library in The case when some app will call it by adding The following line to /etc/profile or inside other Bash script.

If you want SHM extension to work in Linux chroot - download file libandroid-shmem.so from here:
https://github.com/pelya/cuntubuntu/tree/master/dist
copy it to chroot, set executable flag, and execute this in chroot before other commands:
export LD_PRELOAD=/path/to/libandroid-shmem.so

Hapy working with apps which need shared memory.

**Comment by SDRausty** [comment]
This commit https://github.com/SDRausty/TermuxArch/commit/a2e8c54b130b2c5d1cdf1e6b01856022cd1db98b @JanuszChmiel  and upstream may have resolved your issue.  You are welcome to comment here.

**Comment by SDRausty** [comment]
> find universal shared memory

This commit https://github.com/TermuxArch/TermuxArch/commit/19d112ef96ab846aa8c74245407d2e7b947d7a75 rewrote memory integration.  File [knownconfigurations.bash](https://github.com/TermuxArch/TermuxArch/blob/master/knownconfigurations.bash) has information regarding proot binds/mounts.  @JanuszChmiel could you try testing with `setupTermuxArch.bash re` to see if this resolves the issue?

**Comment by JanuszChmiel** [comment]
Dear Mr Rausty,
	Sure, i will be very glad to test and reinstall Arch Linux by using
latest setup script. Thank you very very much that you have invested The
time and that you have implemented new approach to shared memory.
Did you used android shared memory from Pelia on Github? Or did you find
other complex C native library? Or did you even have written new code from
scratch?
I know that I could observe it according to The script, but yours
professional answer will explain it to me.
Thank you again very very much. I will remove my archLinux installation and
I will begin from scratch.
I only do not know how to completely clean Arch data from Termux, because I
Am getting error when using
rm -rf arch
command. SO I willd o not have to pull Termux data or reinstall Termux.
Thank you very much for yours answer.

**Comment by JanuszChmiel** [comment]
I Am installing Termux and whole ArchLinux from scratch, it will be The best
ssolution. I will not be lazy, since you had to spend many hours to recode
The script. I will test if I will have to use android-shmem.so still, or if
you have made some magic that responsible .so library which is allready The
part of installed ArchLinux will try to do its best to implement shared
memory support.
I have compared Qemu with Proot. And unfortunately, really, Proot is much
more closer to be usable Linux executor on A top of Android kernel. I Am
helpless to root my phone, install Kqemu kernel module and then use Qemu
with accelerated virtualisation setting. And Termux provides robust sound
support thanks to its Pulseaudio implementation.
Advanced ArchLinux packagers have even stared to build Seamonkey more often.
I think, that my posts are bringing sweets fruids to many ArchLinux for
ANdroid users.

**Comment by JanuszChmiel** [comment]
I will test shared memory by The most difficult task available. Running
tigervnc without -extension MIT-SHM
command line option. X11vnc is also very intensive process which uses shared
memory very often.
But I know that it is too fast shared memory exchanges at a little time.
Yours script modiffication have no bad affect on installation process of
ArchLinux. I Am installing mate mate-extra tigervnc orca espeak-ng
speech-dispatcher pulseaudio-alsa

**Comment by SDRausty** [comment]
> reinstall Arch Linux 

There is no need to reinstall.  Refresh is  sufficient; `bash setupTermuxArch.bash re`.  `bash setupTermuxArch.bash h` has information. 

> getting error when using rm -rf arch command. 

You can use `bash setupTermuxArch.bash purge` to remove the installation. `bash setupTermuxArch.bash help` has information.

**Comment by JanuszChmiel** [comment]
Dear professional MR Rausty. I can confirm, that you have professionally
solved shared memory support on Arch Linux. And I Am sure that yours
revolutionar approach will be signed to various professional books for The
students of informatic sciences. Because with yours approach The stability
and speed of all Linux distros which are being executed by Proot from Termux
on A top of Android kernel will dramatically increase its quality.
I can even use tigervnc with no need to disable shared memory. Very well
done.
I AM only sad that I had a wrong assumption, that build in flash chips will
be too slow to replace RAM shared memory. But important is, that yours work
have brought next sweets fruids for many Arch Linux users.
Is it possible to extend Ubuntu Debian and other distros by using yours
approach? Or advanced user would had to install those distros and copy files
from /dev/shm when those distros have been installed by using normal
standalone AArch64 compatible device?

Really, excellent job and thank you for yours time, which you have invested
to this new feature.

**Comment by JanuszChmiel** [comment]
New shared memory feature work outstandingly. Tigervnc really work and I do
not have to disable build in shared memory support.
But why pcmanfm display The following error.

(pcmanfm:10165): Gdk-WARNING **: 14:04:19.915: shmget failed: error 38
(function not implemented)
It is only a little sosmetic think. But I would like to know, why GTK
library can not call shmget but other apps including xvnc process can
perfectly manipulate with shared memory.
I Am only curious, please do not think that I want to overload and bother
you too much. But I want to learn new thinks thanks to you.

**Comment by SDRausty** [comment]
> I can confirm, that you have professionally solved shared memory support on Arch Linux. And I Am sure that yours revolutionar approach will be signed to various professional books for The students of informatic sciences. 

Thank you; I am flattered.  It would be nice to see https://en.wikipedia.org/wiki/Special:Search?search=termux published too.  This page https://github.com/termux/termux-packages/issues/1930 is the deleted wikipedia Termux page.

Does this commit https://github.com/TermuxArch/TermuxArch/commit/93f2793f630e8bf664730c1beab0038a31ef3e25 resolves the Gdk-WARNING?  It adds `dev/shmget` support.  You can run `888` to quickly refresh the installation without reinstalling.

**Comment by SDRausty** [comment]
> Really, excellent job and thank you for yours time, which you have invested
to this new feature.

A thank you can also go to @sudomain who helped  catalyze this change with [pull requests](https://github.com/SDRausty/TermuxArch/pulls?q=is%3Apr+author%3Asudomain) that have also let [Termux:API](https://github.com/termux/termux-api) to function.

**Comment by SDRausty** [comment]
> Thank you again very very much.

You are welcome;  And I enjoy your assistance very much @JanuszChmiel too.

**Comment by JanuszChmiel** [comment]
Oh you are elite. Thank you very very much. If also this shared memory
function will work it will dramatically speed up Linux.
I can even rerun seamonkey when I terminate it at evening in The morning
without severe crash. When I have been forced to use android-shmem.so it
have caused Termucx processes crash when Seamonkey have been terminated ate
The evening and When I terminated Orca too. In the morning, when I have re
run orca and seamonkey, Before WSeamonkey have been activated, processes
crashed.
Very probably whole AArchLinux process tree or may be even all Termux sub
processes.
Thank you agin for yours help and for yours time.

**Comment by JanuszChmiel** [comment]
I AM very sorry, but even when I have executed yours setup script by typing
refresh
option, /dev/shmget
really exist inside /dev folders tree. But pcmanfm still report error shmget
function not implemented. I have exited arch Linux and restarted it twice,
but still The same. its look that it will be something very complex to
solve.

**Comment by JanuszChmiel** [comment]
There can be also other problem. May be, thatz Proot C code do not have The
chance to use so many file operations at The same time, so SHMget is
ignored, but I do not believe that, since Proot display debug run time
warnings in such cases.
Phone is also not very hod thanks to flash chips usage, Kernel of Android is
not becoming unstable so I think, that you are very near to The 100 % shared
memory solution. I will be patiently waiting for An future Scripts update.

**Comment by SDRausty** [comment]
This commit https://github.com/TermuxArch/TermuxArch/commit/d12e97497c37285d646b2e4860963612a2ac045e drops shmget support from the PRoot init statement.  @JanuszChmiel file [knownconfigurations.bash](https://github.com/TermuxArch/TermuxArch/blob/master/knownconfigurations.bash) has instructions how to construct the PRoot init statement.  Refresh the installation with `bash setupTermuxArch.bash re`.  There is no need to reinstall. Then run `startarch c mkdir /dev/shm/shmget` and check if this helped.

**Comment by JanuszChmiel** [comment]
Very strange, still do not work. Still The same error.
I have refreshed and I have run
startarch c mkdir /dev/shm/shmget
I have evidence, that  shared memory work also because /dev/shm contain more
than one files. But sub folder /dev/shm//shmget is still empty.
May be, that you had right firstly and that data must really reside in
/dev/shmget.
I AM very sorry if I have given you A wrong advice previously.

**Comment by JanuszChmiel** [comment]
/dev/shm have The following files available.
pulse-PKdhtXMmr18n  shmget  time-admin.pid

**Comment by JanuszChmiel** [comment]
Dear Mr Rausty and others.
Shared memory have dramatically changed The life of Orca screen readers
users like I Am. Flat review mode gets much more faster to be initialized.
System stability have been increased. No hangs, no processes crashes.
Even Tigervnc shared memory is working and it is very fast data exchange at
A time.
because mate-session and Xvnc exchange data between each others really very
fast.
RReally. Very well done. It is A real revolution in using non only X11 apps
in Termux.
I even think that postgresql and other Mysql database tools will work
perfectly thanks to this shared memory implementation.
GTK3 warning is not fatal. Since Pcmanfm C code has two codes for shared
memory and also for non shared.
To solve this, sombody would had to debate with GTK3 developers, because
they knows their complex and long C code very best.
The issue in such cases is, if .so library can detect if chroots from Termux
and Android are being executed so their new approach inside their complex C
code would work with this shared memory implementation.
Fact is, that shmget must work reliably because mate-session and tigervnc
must use this function very intensively and if shmget would not work, I do
not believe, that shared memory would work in such case.
So I Am very very happy.
I can write E-mail by using Seamonkey with Orca and Gradio is playing my
favourite 80S song in The background. My phone board is not getting hot even
if shared memory works.

**Comment by SDRausty** [comment]
> Sure, i will be very glad to test and reinstall Arch Linux 

@JanuszChmiel this request concerns https://github.com/SDRausty/TermuxArch/issues/237 Android API level 29 which is aka Andoid 10.   If your device is Google Android 10 and greater, do you see the same **critical error** upon fresh install?
```
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
```

**Comment by SDRausty** [comment]
This commit https://github.com/TermuxArch/TermuxArch/commit/9cd376d663616df1ea2c6367ea92c183117b013e resolves the pacman `Errors occurred, no packages were upgraded` error.

**Comment by JanuszChmiel** [comment]
I will refresh ArchLinux install. Unfortunately I have only devices with
Android 9.1.
No greaterversion.

**Comment by JanuszChmiel** [comment]
When shadow package is being upgraded I Am getting The following message:
Could not set capabilities on /usr/bin/newuidmap: Permission denied

**Comment by JanuszChmiel** [comment]
Shmget is really The severe problem.
Since also X11vnc can not communicate with Xorg which have been executed by
using xinit.
So other Shared memory functions are working except shmget.

shmget(scanline) failed.                                    
 16/07/2020 19:23:49 shmget: Function not implemented

**Comment by JanuszChmiel** [comment]
But X11vnc do not crash. And its VNC protocol work. So it is interesting
informatic phenomena.
Maz be, that in fact, shmget normallz work, but because Libc do not know
zours profi work around it states some error but data transfer in RAm work.
I think, that if shared memorz would not work at all, X11vnc would dsplaz
more crztical erro. I have tried it before zours patch and before I have
known libandroid/shmem.so
And if shared memorz have not been implemented at all, it have even stopped.
So thank zou again and manz users can be happz.

**Comment by JanuszChmiel** [comment]
aOh no. x11vnc process really terminate. I have read terminal bad.
So now, Tigervnc work really without disabling shared memory support with
The option.
-extension MIT-SHM
I will try to read some articles about shared memory in Linux, because The
situation is very strange.

**Comment by JanuszChmiel** [comment]
https://datacadamia.com/os/linux/shared_memory#about

**Comment by SDRausty** [comment]
@JanuszChmiel an important issue is semaphore support
> Its not possible.
The functions to implement Message Queues and Semaphore Arrays are not available before Nougat. So, this is not possible yet.
Maybe, when we make the minimum API Level 24.

From https://github.com/termux/termux-packages/issues/2427

**Comment by JanuszChmiel** [comment]
OK. Thank you for yours professional explanation. So now our attempt to
implement shared memory by using /dev/shm do not hurt anythink but do not
work if I have understood it correctly.

**Comment by SDRausty** [comment]
> shmget(scanline) failed.
 16/07/2020 19:23:49 shmget: Function not implemented

@JanuszChmiel this probably will not improve the error, but it might.  Can you run `bash setupTermuxArch.bash r` to quickly refresh the installation without having to reinstall it to see if the latest commits helped?

**Comment by SDRausty** [comment]
http://www.mouritzen.dk/aix-doc/en_US/a_doc_lib/files/aixfiles/shm.h.htm

**Comment by SDRausty** [comment]
@JanuszChmiel also can you share results from `setupTermuxArch.bash sysinfo`?

**Comment by JanuszChmiel** [comment]
Sure I will be glad to test yours newest ArchLinux setup scripts. I have
also found out, that when running Debian on 2,2 2 core CPU with 1 TB
harddisk with 900 GB partition or a little more, that loading whole Debian
Buster takes much time and that even Huavei contain strange kernel, which do
not like Proot very much, that even in those cyrcumstances it is possible to
load Mate and ArchLinux much more faster from chips.
I only know, that I will have to invest some money on future to buy other
phone moel, but it can not containbuild in encrypion, since also encryption
kernel driver slowdowns Proot operations.
I will debate with manufacturers such as Doogee about kernel and about its
Pokedata and partial file case insensitive file system.
Samsung contain too secure Android kernel and I Am afraid, that their kernel
will contain some block of Proot functions. May be, that I Am wrong, but I
do not know.

**Comment by petkar** [comment]
This may be relevant here. I installed a fresh copy from the TermuxArch/TermuxArch repo a while ago, set up xfce and Firefox doesn't work anymore. I get this error :
```
?? firefox --verbose
[19565, Main Thread] WARNING: failed to open shm: Permission denied: file /build/firefox/src/firefox-78.0.2/ipc/chromium/src/base/shared_memory_posix.cc, line 246
[1]    19565 segmentation fault  firefox --verbose

```
It used to work earlier. Any idea how I can fix this?

**Comment by SDRausty** [comment]
> It used to work earlier. Any idea how I can fix this?

It should be fixed now.  I was awaiting a reply.  Thank you for sharing @petkar.  Run `bash setupTermuxArch.bash r` to quickly refresh the installation without having to reinstall it.

**Comment by JanuszChmiel** [comment]
Mr Bednarski have Made A C library patch for special Android shared memory
library. It have been possible to run Postgresssql reliably thanks to it. I
have been even able to generate MySQL database for more than 5 hours and
database has more than 28 GB of data. No crash, no instability.
His patch is The part of The special script which generate The environment
to prepare MYSQL database with Openstreets maps data for specific country.

Patch is here.
https://gist.github.com/michalbednarski/6b0213e691f512573519cbd2b901a759?fbc
lid=IwAR0JixQsg4032jkRhk4d9s0Kh6AFTGnRkSRwFkBqICvj2O4w_p8MxifovjA
The change to C code of .so library is contained inside Bash script.

**Comment by petkar** [comment]
Amazing! It got resolved! Appreciate your work mate!

>  Run bash setupTermuxArch.bash r to quickly refresh the installation without having to reinstall it.

I'm aware of this. My previous installation had an error with xauth (not starting up at all).
```
xauth:  error in locking authority file /home/realzink/.Xauthority
Could not start Xvnc.

(EE)
Fatal server error:
(EE) Can't read lock file /tmp/.X2-lock

(EE)/usr/lib/Xorg.wrap: Only console users are allowed to run the X server
```
I installed many packages, was messing with makepkg, fakeroot-tcp and aur, and refreshed my install to keep up with the updates(on the previous installation). After many hours of looking up and checking conflicting packages/configs, I wasn't able to resolve it so I decided to go for the reinstallation.
Now, on this installation, It was clear that it was the refresh which was causing this issue.
Note that this does not affect the root user (which is why I was able to check if Firefox ran).
It only affected the standard user (Also, I'm able to install aur packages right after copying makepkg.diff because fakeroot was working. Great work!).
Then I tried again after creating a new user with addauser but get the same errors in it again.
```
[root10:29TermuxArch]$ addauser petkar
cp: cannot open '/root/.l2s..ICEauthority-n0001' for reading: Too many levels of symbolic links
cp: missing file operand
Try 'cp --help' for more information.

 TermuxArch WARNING:  Generated script signal 1 near or at line number 56 by !

addauser  2.0.118 [Exit Signal 201]: DONE
[root10:41TermuxArch]$ q
> startarch l petkar
[petkar10:33~]$ vncserver :3
xauth:  error in locking authority file /home/petkar/.Xauthority
Could not start Xvnc.

(EE)
Fatal server error:
(EE) Can't read lock file /tmp/.X3-lock
```
Assuming that it might be a problem with copying configs and desperate to keep the installation, I proceeded to create a user with the useradd command. 
Unfortunately, I got the same error on it too ('xauth:  error in locking authority file /home/deepit/.Xauthority`).
I don't want to reinstall arch again because setting up packages and my personal configurations take a lot of time. Any idea how I can fix this?

**Comment by JanuszChmiel** [comment]
I Am just installing everyting from scratch, I will check two server
initialisations. Running Xorg by using xinit or running Tigervnc XVNC server
by running vncserver command.
I will also experiment with asgmem.so patch from MR Bednarski, but I will
run it by using " and special command to test, if it support all shared
memory functions or if it have been pecifically patched for Debian and
Postgressql.
Now everything work fines, including ArchLinux upgrading process, I Am now
installing 
pacman -S mate mate-extra orca tigervnc espeak
I think, that shared memory will aprtially work thanks o C++ experts, who
will upgrade some .so libraryes. And Semaphores will allow to do that on
future. But it will not be easy debugging and development task.

**Comment by JanuszChmiel** [comment]
Tigervnc work ammazingly even after ArchLinux installation scripts upgrade.
If somebody want to run Xorg from non console session, it is necessary to
edit or create /etc/X11/Xorg.wrap
file. And add The following words finished by pressing Enter key.

allowed_users = anybody
In this case, you can run Xorg by using startx or by using Xinit.
If you want to use xinit you mast install xorg-xinit xorg xterm
Now it is possible to use Tigervnc or A combination with XVFB and x11vnc. Or
you can use Xinit and Xorg in combination with x11vnc.

**Comment by JanuszChmiel** [comment]
Dear MR Rausty,
Thank you for yours countinous programmers work Yours script really provides
The best possibility to run Linux distribution on Android devices thanks to
Termux and Proot. It is possible to run many many apps. And you are always
incorporating The most modern programmers trends so also modern Android
devices are supported.

You and yours cooperators have introduced /proc folder emulation, which is
very important. Because I can use Marco window manager. Openbox do not allow
Me to run Orca automatically at mate-session start, some focus freezes are
presented when user uses Openbox with some Mate apps.
So Marco window manager have its importance to be used with Mate. Thanks to
TCP stack I can even use special tool to build pkg packages on A isolated
environment.

When I Am sad I Am listening Gradio which is very accessible. I can even use
VLC and various GTK compatible file managers.
Thanks to Tigervnc I can use TAB and SHIFT+TAB appropriately without
confusements. Tigervnc is even very fast and do not produces memory leaks.
Seamonkey work excepts Czech dictionary, because even Pluma can not load
important .so libraryes. And I do not know why? If those .so libraryes are
using incompatible calls with Proot, I do not know.

**Comment by SDRausty** [comment]
> Tigervnc work ammazingly even after ArchLinux installation scripts upgrade.

You are welcome @JanuszChmiel and thank for sharing! Please consider submitting a pull request to this [`archlinuxconfig.bash`](https://github.com/TermuxArch/TermuxArch/blob/master/archlinuxconfig.bash) file and other files if you need too.

You might find this [information about pulse-audio](https://github.com/SDRausty/TermuxArch/issues/225) that @petkar just shared interesting too.

**Comment by JanuszChmiel** [comment]
Thanks to one very advanced C developer, Proot support some shared memory functions. May be that all of functions, which exist on special android-shmem.so library or may be even more.

Here is The link about This important new Proot feature.

https://github.com/termux/proot/issues/89

It is necessary to specifi
--sysvipc
to enable this new Proot feature. I will test it on very simple Bash scripts to install Ubuntu for example and I will try to find out if complex C and C++ apps which support shared memory will work without random crashes.

**Comment by SDRausty** [comment]
> --sysvipc

Thank you for sharing @JanuszChmiel; This is a really nice surprise!  This https://github.com/SDRausty/TermuxArch/commit/6e29c7129a15f81dca4d67d546a712b185f209b4 commit adds the `--sysvipc` option the the PRoot init statement for all user logins.
