### ISSUE TITLE
help me please :D 

### ISSUE THREAD

**Issue by cannabis09** [SDRausty/TermuxArch#230]
hello so i installed it inside termux , everything is fine but i cant correctly write or add paths to servers or to repo to download packeges and run it inside the archlinux a edited pacman.conf file but i think wrong.. can u give me some example or how its shoud look like ? :P thanks

**Comment by SDRausty** [comment]
> can u give me some example or how its shoud look like

1) Uncomment one mirror in this  `~/arch/etc/pacman.d/mirrorlist` file to choose a mirror:
`$ vim ~/arch/etc/pacman.d/mirrorlist`

2) Adjust PATH="$HOME/bin:$PATH" in this `~/arch/root/.bash_profile` file:
`$ vim ~/arch/root/.bash_profile`

3) To learn to use `vim` you can use `vimtutor`.
