### ISSUE TITLE
"Which repo should I use for X?"

### ISSUE THREAD

**Issue by sudomain** [SDRausty/TermuxArch#236]
All references to the TermuxArch project used to point to this repo, as is evident by the number of github stars. At a later point, URLs were then changed to the [TermuxArch/TermuxArch repo](https://github.com/TermuxArch/TermuxArch/). The two projects have different git histories the fact that SDRausty/TermuxArch has so many more stars  may cause users to think that SDRausty/TermuxArch is the main repo, when TermuxArch/TermuxArch actually is. In addition to the changed URLs, TermuxArch/TermuxArch has [a more up to date VERSIONID](https://github.com/TermuxArch/TermuxArch/blob/master/.conf/VERSIONID). The projects' different git histories has lead to atleast two inconsistencies that I know of, which I hope to fix soon.

To alleviate this confusing situation, I recommend that SDRausty/TermuxArch become archived and the README changed to point to TermuxArch/TermuxArch. Development can then occur on TermuxArch/TermuxArch in a more traditional Github/project forking workflow.

**Comment by SDRausty** [comment]
> Which repo should I use for X?" 

It does not matter;  All the projects should work.

> To alleviate this confusing situation

I am simply very happy that <bold>it works as intended</bold>, which has not always been the case.  The repository https://github.com/TermuxArch/TermuxArch is the HEAD.  It has mirrors;  Including this project.

**Comment by SDRausty** [comment]
> Which repo should I use for X?"

[This issue](https://github.com/SDRausty/TermuxArch/issues/59) has the most detailed information. It has forks, ie child issues.

**Comment by SDRausty** [comment]
> To alleviate this 

https://github.com/SDRausty/TermuxArch/commit/a33b480920f34c761b388637305a4690fed51be6 should help resolve this

**Comment by SDRausty** [comment]
> Development can then occur on TermuxArch/TermuxArch in a more traditional Github/project forking workflow.

This option is always available as long as we are online.  I am enjoying your branches and forks @sudomain and hope many of us are making good use of the recent merges you have bestowed upon us through your hard work.

> Which repo should I use

Many of these projects are inter-related.  For example https://github.com/BuildAPKs/buildAPKs/ which began here https://github.com/SDRausty/buildAPKs both now depend on https://github.com/shlibs and TermuxArch might too

This https://github.com/SDRausty/TermuxPRoot that is moving gradually here https://github.com/TermuxPRoot is also a good example.  Hopefully, it will give us more and easier self configuring options as far as variety of Linux systems.  This in turn can migrate back into this project.  

4Needless to say, some documentation falls out of date pursuing development and many mirror projects can use better updating too.

**Comment by sudomain** [comment]
> I am simply very happy that it works as intended, which has not always been the case. 

It's a great project that I use everyday to extend my Termux, to run desktop apps, and even [as an upstream/submodule](https://github.com/sudomain/AnkiTermuxArch). Thank you.

> All the projects should work.

> The repository https://github.com/TermuxArch/TermuxArch is the HEAD. It has mirrors; Including this project. 

I created this issue because I'm a very grateful user and concerned about the long-term maintainability of two repos with different git histories (which is not what I would call "mirrors" but I digress). Two repos with the same name, accomplishing the same goals, with (what seems like) 99% the same code base but different git histories seems like it would create twice the amount of work for whoever maintains the project(s). Additionally, as mentioned earlier, I know of two discrepancies between the two projects which I hope to fix soon. 

If you're happy with this system, then I'm happy with this system. I just hope (though I do believe) that this two repo/same name system will affect the long-term maintainability of the project, at least compared to the traditional one repo, many forks system. Thank you again for such a great project.

**Comment by SDRausty** [comment]
> comment at the same time

we did :smile:

**Comment by sudomain** [comment]
:) From now on I'll follow instructions and submit future PR's to TermuxArch/TermuxArch.

**Comment by SDRausty** [comment]
> whoever maintains the project

ai?  The `.scripts` directories have helper scripts that deserve documention.  Some of these scripts are in the `scripts` directories too.  This https://github.com/BuildAPKs/buildAPKs.github/blob/master/scripts/cp.g2d.sh one might be of interest you.  It rewrites one script into another.  This can be done with git repositories as well.  

> happy with this system

When systems work as intended;  Yes, this makes me happy, and I am humbled and proud that I can contribute.

> long-term maintainability

This is always a concern.  A self-maintaining system is a goal.  This https://github.com/BuildAPKs/buildAPKs.github/blob/master/.scripts/maintenance/upr.sh script assists in maintaining forks.  A copy will hopefully migrate to Termux Arch projects soon.

**Comment by sudomain** [comment]
> The .scripts directories have helper scripts that deserve documention. 

Funny you should mention this. I started [this file on a separate branch](https://github.com/sudomain/TermuxArch/blob/documentation/FILES.md) in order to better understand what is going on.

**Comment by SDRausty** [comment]
> started this file on a separate branch

You might want to merge this file into https://github.com/TermuxArch/docsTermuxArch

The file`setupTermuxArch.sh` is for backward compatability.  It was the original file name.
