### ISSUE TITLE
[Tip] Workaround to get systemctl commands working on TermuxArch

### ISSUE THREAD

**Issue by petkar** [SDRausty/TermuxArch#239]
The workaround was [this script](https://github.com/gdraheim/docker-systemctl-replacement) which replaces `/usr/bin/systemctl` and executes systemctl commands without systemd. It worked surprisingly well and got the job of starting and stopping services done, which is exactly what I wanted. The only requirement is python (`pacman -S --needed python3`)

Installation instructions:

```
mv /usr/bin/systemctl /usr/bin/systemctl.old
curl https://raw.githubusercontent.com/gdraheim/docker-systemctl-replacement/master/files/docker/systemctl3.py > /usr/bin/systemctl
chmod +x /usr/bin/systemctl
```
Although there were some issues I ran into, I think it's a neat a neat fix. I'm not aware of how compatible it is with proot or the issues that it could bring up.

**Comment by SDRausty** [comment]
Thank you for contributing @petkar I am impressed!

**Comment by SDRausty** [comment]
```
$ csystemctl.bash
Installing /usr/bin/systemctl replacement:
Already installed /usr/bin/systemctl replacement: DONE
```

I am testing this replacement version.   It is generated by [`_ADDcsystemctl_`](https://github.com/SDRausty/TermuxArch/blob/master/archlinuxconfig.bash#L197&&#L229).  Do you think this should be added to default setup @petkar?

**Comment by petkar** [comment]
One of the goals of the project appears to be to improve the usability of proot. It would indeed be a great default addition even if it's just a replacement script because decrease the general handicap that the proot imposes.

**Comment by SDRausty** [comment]
> be a great default addition even if it's just a replacement script because it decrease the general handicap that the proot imposes

Agreed;  updating and overwriting `csystemctl.bash`'s work is now abated.  It is currently set as default.  This is important, as upgrading the Arch Linux system can overwrite the `csystemctl.bash` refinement.  

How should this script behave in the long run?  How can it update itself?  Is `/etc/pacman.conf` rewritten correctly?
