### ISSUE TITLE
sed: command not found.

### ISSUE THREAD

**Issue by smu** [sdrausty/TermuxArch#24]
After issue #21 has been solved (thanks again) I still get a `command not found` error during installation.
 Is this case `sed` is missing, which is needed by `/bin/local-gen`.

![screenshot 2017-11-23 at 18 47 40](https://user-images.githubusercontent.com/207880/33184846-276114d4-d07f-11e7-9471-cb8f792c4e18.png)

Details on my system can be found in #21.

**Comment by smu** [comment]
The workaround is, of couse, to install sed in arch and run `/bin/locale-gen` after installation again.

**Comment by sdrausty** [comment]
@smu Thanks for opening this issue with extensive information.  When you login to Arch and run `locale-gen`, does it run correctly. Whether `sed` is present in Arch should not matter. The part where `sed` uncomments en_US.UTF-8 is with Termux's busybox version of `sed`.  Also, the last series of commits has moved localegen () about a bit in the script, further from Arch and closer to Termux.  If these recent commits do not resolve this issue, please confirm if `locale-gen` runs correctly in Arch.  Is it necessary to install `sed` in Arch i686 to run `locale-gen`?

**Comment by sdrausty** [comment]
@smu here is the resolution https://github.com/sdrausty/TermuxArch/commit/71321be7f87f94c259957f897a21f7d54a2b6d45 Let us know how it works on your Chromebook.
