### ISSUE TITLE
Can't use display because xauth not working after `setupTermuxArch r` refresh

### ISSUE THREAD

**Issue by petkar** [SDRausty/TermuxArch#241]
This should give some insight https://github.com/SDRausty/TermuxArch/issues/228#issuecomment-660830867
I'll expand it here : 
```
xauth:  error in locking authority file /home/realzink/.Xauthority
Could not start Xvnc.

(EE)
Fatal server error:
(EE) Can't read lock file /tmp/.X2-lock

(EE)/usr/lib/Xorg.wrap: Only console users are allowed to run the X server
```
I refreshed my install to keep up with the updates(on the previous installation). After many hours of looking up and checking conflicting packages/configs, I wasn't able to resolve it so I decided to go for the reinstallation.
Now, on this installation, the issue reappeared after refreshing and it was clear that it was the refresh which was causing this issue.
Note that this does not affect the root user (which is why I was able to check if Firefox ran).
It only affected the standard user (Also, I'm able to install aur packages right after copying makepkg.diff because fakeroot was working. Great work!).
Then I tried again after creating a new user with addauser but get the same errors in it again.
```
[root10:29TermuxArch]$ addauser petkar
cp: cannot open '/root/.l2s..ICEauthority-n0001' for reading: Too many levels of symbolic links
cp: missing file operand
Try 'cp --help' for more information.

 TermuxArch WARNING:  Generated script signal 1 near or at line number 56 by !

addauser  2.0.118 [Exit Signal 201]: DONE
[root10:41TermuxArch]$ q
> startarch l petkar
[petkar10:33~]$ vncserver :3
xauth:  error in locking authority file /home/petkar/.Xauthority
Could not start Xvnc.

(EE)
Fatal server error:
(EE) Can't read lock file /tmp/.X3-lock
```
Assuming that it might be a problem with copying configs and desperate to keep the installation, I proceeded to create a user with the useradd command. 
Unfortunately, I got the same error on it too (`xauth:  error in locking authority file /home/deepit/.Xauthority`).
I don't want to reinstall arch again because setting up packages and my personal configurations take a lot of time. Any idea how I can fix this?
This isn't an issue with vnc but xauth itself. `keys` or `pci` doesn't work in users anymore either.
A temporary work around to this issue is logging in using `startarch c su user` instead of `startarch l user`.
I thought this was due to zsh not loading `.profile` and `.bashrc` but it didn't fix it either.

After some searching, I figured that copying from root profile to user home profile messed up owners (even though It did show the user)
Running these commands successfully fixed the issue : 
```
GID=$(id -g)
startarch c "usermod -u $UID USER"
startarch c "groupmod -g $GID USER"
startaarch c "chown -R USER:USER /home/USER"
```
Lets discuss the consequences of this fix.

**Comment by petkar** [comment]
This https://github.com/TermuxArch/TermuxArch/pull/9 should probably fix the issue. After making all the files in the home directory of the user it's respective owner, xorg and xauth began to work flawlessly again.

**Comment by petkar** [comment]
Thanks! It's fixed now. Another very important thing to note is that the `--link2symlink` option must be enabled for user accounts for this to work. Why is it disabled for user accounts by default?

**Comment by SDRausty** [comment]
> Why is it disabled for user accounts by default?

Please see [Sudo is non functional #4](https://github.com/SDRausty/termux-archlinux/issues/4#issuecomment-423579945)

> Variable substitution in TermuxArch resolves sudo. Variable assignment PROOTSTMNTU="${PROOTSTMNT//--link2symlink }" drops --link2symlink from the user login proot statement. The option is necessary for root user to function properly.

**Comment by petkar** [comment]
I guess it can safely be considered necessary as disabling it breaks a lot of things.

**Comment by SDRausty** [comment]
> can safely be considered necessary

used to resolve:
> Please see [Sudo is non functional #4](https://github.com/SDRausty/termux-archlinux/issues/4#issuecomment-423579945)

It is amazing how this project is flux. Upstream and downstream and within the projects itself changes that at present seem to have this project working as expected;  Thsnk you once again🥇
