### ISSUE TITLE
TermuxArch install failed

### ISSUE THREAD

**Issue by sobaee** [SDRausty/TermuxArch#244]
After I cleared data of Termux apk on my mobile, and tried to install TermuxArch, this is what I get:

$ bash ~/storage/downloads/setupTermuxArch.sh

 🕛 > 🕛 ＴｅｒｍｕｘＡｒｃｈ 2.0.20 shall attempt to install Linux in /data/data/com.termux/files/home/arch.  Arch Linux in Termux PRoot shall be available upon successful completion.  To run this BASH script again, use `!!`.  Ensure background data is not restricted.  Check the wireless connection if you do not see one o'clock 🕐 below.  Checking prerequisites…

Found download tool `curl`: Continuing…

Using curl to manage downloads.

 🕛 > 🕧 Prerequisites: OK  Downloading TermuxArch…

[1/2]: https://raw.githubusercontent.com/TermuxArch/TermuxArch/master/setupTermuxArch.sha512 --> setupTermuxArch.sha512
--_curl_--https://raw.githubusercontent.com/TermuxArch/TermuxArch/master/setupTermuxArch.sha512
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- -  0     0    0     0    0     0      0      0 --:--:-- -100   153  100   153    0     0    128      0  0:00:01  0:00:01 --:--:--   128

[2/2]: https://raw.githubusercontent.com/TermuxArch/TermuxArch/master/setupTermuxArch.tar.gz --> setupTermuxArch.tar.gz
--_curl_--https://raw.githubusercontent.com/TermuxArch/TermuxArch/master/setupTermuxArch.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- - 86 33334   86 28791    0     0  43490      0 --:--:-- -100 33334  100 33334    0     0  50126      0 --:--:-- --:--:-- --:--:-- 50126

 🕛 > 🕐 TermuxArch download: OK

 🕛 > 🕜 TermuxArch 2.0.20 integrity: OK
knownconfigurations.bash: line 92: SYSVER: unbound variable
setupTermuxArch.sh  2.0.20: [Exit Signal 1] DONE 🏁

TermuxArch became an addiction!, I couldn't live without it.
Could you help me please?

**Comment by sobaee** [comment]
Solved
By using @isrgish method which advice to edit setupTermuxArch.sh file by adding "#" before "set -Eeuo pipefail"  to be like this "# set -Eeuo pipefail"

**Comment by SDRausty** [comment]
> Could you help me please?

This issue should be completely resolved with the latest https://github.com/SDRausty/TermuxArch/commit/a73e2bf0636f668a14db9d48fc7ed27b2fc6c602 commit.  Thank you @sobaee for creating this issue;  I will be looking into how the Termux in PRoot projects update.  Hopefully this kind of issue will stay resolved with future development.
