### ISSUE TITLE
root user login starts up arch proot without switching to /root directory 

### ISSUE THREAD

**Issue by xd003** [SDRausty/TermuxArch#245]
First of all being very new to this project , i wish i had found it earlier . Thanks to everyone who have contributed to this awesome project 

1) i have added a user , if i login as that user ```startarch login user``` it rightly takes me to the home directory ie /home/user
but in its default root user login , it should use ```/root``` directory as its startup working directory  ( ```echo $HOME``` rightly returns /root ) but it doesn't seem to work as intended . On startup after ```startarch``` is ran, it simply logs into arch proot being in the existing directory ie termux home . It should ideally switch to /root directory as its the default home dir .

2) Also can you please change the default location of bin folder and that systemctl file from home directory to somewhere else .It is better to have clean and only user generated files in home directory ( /root or /home/user ) . Maybe add it somwhere in the rootfs directory but not in home directory .That way those files would also be more safe and avoid getting deleted mistakenly while general usage

3) If i copy any folder from my device's sdcard to arch home directory using termux , i can access it properly
cp -a /sdcard/Download /home/user
But if i copy-paste the same folder using my device's file manager and try to cd to that directory in termux - it says operation not permitted .i tried changing folder permissions to 0755 but to no avail
If i wondering if there could a workaround to overcome this restriction , pasting content through file manager is definitely lot easier so would be good to have it working

**Comment by xd003** [comment]
i also wonder why there are so many repositories for very same project , its pretty confusing 
https://github.com/TermuxArch/TermuxArch
https://github.com/SDRausty/termux-arch
https://github.com/SDRausty/termux-archlinux
https://github.com/SDRausty/TermuxArch

@SDRausty am i supposed to report issues in other repos ?

**Comment by SDRausty** [comment]
Today's [commits](https://github.com/SDRausty/TermuxArch/commits/master) should fulfill the first of your requests for proot users to start up in their home directories.  Alll of them now do.

> i wish i had found it earlier . 

This project is under advertised.  @xd003  any good advertising is appreciated.  Some of the features features acquired this month are quite incredible: `yay` which gives access to aur repositories is probably the best of this months additions.   Do you agree?
