### ISSUE TITLE
can't open /proc/bus/pci/devices 

### ISSUE THREAD

**Issue by damionx7** [SDRausty/TermuxArch#247]
Hey there guys, thanks for this amazing script. i have been getting this error `cant open /proc/bus/pci/devices` when i try to run `anki`.  help me. 

![Screenshot_20200901-110418](https://user-images.githubusercontent.com/6530843/91798734-16404300-ec15-11ea-863a-11938059e257.jpg)

**Comment by SDRausty** [comment]
Can you `/proc/bus/pci/devices`?  Analogously:
```
cat /proc/bus/pci/*
cat /proc/bus/*
```
When you find something that is like `Is a directory`, What is in there? What is it?  Please share this information.  

This issue https://github.com/termux/proot/issues/97 @damionx7 appears to deal with an identical situation.   You do not have access to the PCI bus on Android.  Can you share what you are experiencing with your /proc/bus access?

**Comment by damionx7** [comment]
i am getting access denied. 

![Screenshot_20200902-061932](https://user-images.githubusercontent.com/6530843/91919669-37a53b80-ecb6-11ea-9ad4-d2ea580147b4.jpg)

**Comment by SDRausty** [comment]
Try `cat /proc/bus/*`; Notice there are no `cd`s in the example.

**Comment by SDRausty** [comment]
Thank you for sharing @damionx7.  This issue https://github.com/sdrausty/TermuxArch/issues/103 helped in getting `htop` up and running on Android 8.  We could not have got `htop` going if it were not for help from https://github.com/termux/proot/issues/32.  Possibly we can make similar progress with this issue...

**Comment by damionx7** [comment]
![Screenshot_20200902-075017](https://user-images.githubusercontent.com/6530843/91924667-df286b00-ecc2-11ea-9210-6cb636b38ee2.jpg)

**Comment by damionx7** [comment]
it fixes the issue, after create a fake bind to pci/devices

**Comment by SDRausty** [comment]
> it fixes the issue

Great news!  Can you share the snippet of code please?  Hopefully this can be incorperated into function [`_PR00TSTRING_`](https://github.com/SDRausty/TermuxArch/blob/master/knownconfigurations.bash#L69) and automated for users.

**Comment by damionx7** [comment]
i created an empty file `fbindprocpcidevices` in `~/arch/var/binds/` and added the command to `/usr/bin/startarch` `-b /data/data/com.termux/files/home/arch/var/binds/fbindprocpcidevices:/proc/bus/pci/devices`. 
after reading your comment, creating a .prs file would have been better.

**Comment by SDRausty** [comment]
> creating a .prs file would have been better.

Can you share a .prs file that works on your smartphone please?

**Comment by SDRausty** [comment]
I have looked at our work here, and I put in a little more effort.  @damionx7 does this commit https://github.com/SDRausty/TermuxArch/commit/ad78d9e59f1da0b035b5ccff8c87dbb39d32a233#diff-96e6fc14454e2d4bf496fc2de0323d87R295 automate the issue are working on?  Please backup your work before refreshing as I used the same file names you suggested.

Command `setupTermuxArch re`:
> [re [customdir]]  Refresh the Arch Linux in Termux PRoot scripts created by TermuxArch.  Useful for refreshing the root user's home directory and user home directories and the TermuxArch generated scripts to their newest version.

**Comment by damionx7** [comment]
yes indeed

**Comment by SDRausty** [comment]
Thank you 🍀

**Comment by SHINA774** [comment]
cat: /proc/bus/pci/devices: Permission denied
