### ISSUE TITLE
Starting arch linux from termux

### ISSUE THREAD

**Issue by dthboyd** [sdrausty/TermuxArch#25]
How do i start arch linux from termux

**Comment by sdrausty** [comment]
Thanks for posting. There are a number of ways you can start Arch Linux in Termux.  

1)  Run `~/arch/startarch` at the bash prompt.  The **bash shell interpreter is important!**
2)  Run `startarch` if you chose "copy to $PATH" during install.  
3)  Run `chsh` and change your login shell to `startarch`. **Important** to undo this change and return to your Termux login, delete `.termux/shell` since `chsh` will be unavailable in Arch Linux.

**Comment by dthboyd** [comment]
Thanks                                                                                                                                                                        Sent from my BlackBerry - the most secure mobile device - via the Rogers Network                                                                                                                                                                           From: notifications@github.comSent: November 23, 2017 5:49 PMTo: TermuxArch@noreply.github.comReply-to: reply@reply.github.comCc: dthboyd@gmail.com; author@noreply.github.comSubject: Re: [sdrausty/TermuxArch] Starting arch linux from termux (#25)  Thanks for posting. There are a number of ways you can start Arch Linux in Termux.
Run ~/arch/startarch at the bash prompt.  The bash shell interpreter is important!Run startarch if you chose "copy to $PATH" during install.Run chsh and change your login shell to startarch. Important to undo this change and return to your Termux login, delete .termux/shell since chsh will be unavailable in Arch Linux.

**Comment by sdrausty** [comment]
Refences regarding this issue https://duckduckgo.com/?q=beginning+command+line+site%3Atldp.org at these links about beginning with the Linux CLI (Command Line Interface) in Termux on Android, Chromebook and Fire OS.

**Comment by seanparsons** [comment]
@sdrausty Where is the "copy to $PATH" option? I don't remember being prompted for anything.

**Comment by seanparsons** [comment]
@sdrausty Using `chsh` doesn't seem to work, it seems like it's not available to the login script.

**Comment by sdrausty** [comment]
http://www.bing.com/search?q=ls%C2%A0pwd%C2%A0beginner%C2%A0site%3Atldp.org

**Comment by sdrausty** [comment]
Read, then try to understand...

Lear ditto

**Comment by seanparsons** [comment]
@sdrausty WTF?
