### ISSUE TITLE
diff https://github.com/TermuxArch/TermuxArch

### ISSUE THREAD

**Issue by mukhtharcm** [SDRausty/TermuxArch#250]
What is the difference between https://github.com/TermuxArch/TermuxArch repo and this one?

I see the other one has more recent commits.

**Comment by SDRausty** [comment]
> more recent commits.

This is not always the case. Sometimes they are up to date.

@mukhtharcm thank you for posting an interesting question.  If I may ask you some questions before answering in detail; What do you think the differences are?  How did these projects arise?  What is their purpose?

**Comment by mukhtharcm** [comment]
@SDRausty it is just a doubt 😊.
But I see that both of these repos are listed in your github profile.
## so my conclusion is that 
- this repo is kind of development repo.
- other one is just for stabilized versions.

As of purpose, I far as I understood, is to provide you with a full arch distro in your pocket.

But I really don't know how this arised, because I am new to this.

**Comment by SDRausty** [comment]
@mukhtharcm thank you for sharing your thoughts.  If you do not have any more questions, then please feel free to close this topic.

**Comment by mukhtharcm** [comment]
Thank you for your answers! :smile:
