### ISSUE TITLE
Issues with Libreoffice

### ISSUE THREAD

**Issue by WMCB-Tech** [SDRausty/TermuxArch#252]
Hey. I have an issues when installing Libreoffice. it says `/proc/version permission denied`

Is there a way to fix this? like fake `/proc/version` file

I have Android 9 with arm64 Architecture
with Arch Linux Installed In Termux. 

My device not rooted

**Comment by SDRausty** [comment]
> device not rooted

Using proot with a rooted device is not advised for many reasons.  @WMCB-Tech it would have been better for future use users if you had shared in aone of the closed issues after searching issues like so:

 [`https://github.com/SDRausty/TermuxArch/issues?q=is%3Aissue+libreoffice`](https://github.com/SDRausty/TermuxArch/issues?q=is%3Aissue+libreoffice)

Opening new issues about the same topic makes it more difficult for future open source users who will be searching for solutions when there are many issues pertaining to the same topic.  These two issues at this `git` repository have already mentioned libreoffice, and it would have been better had you shared in one of these:

1. [Applications like libreoffice that use /proc/version fail to run #242](https://github.com/SDRausty/TermuxArch/issues/242)
1. [Chromium, Firefox, Epiphany, Libreoffice, localectl, timedatectl... #68](https://github.com/SDRausty/TermuxArch/issues/68)

The error `/proc/version permission denied` was resolved as far as I know.  Obviously it is not resolved at present.  Thank you for bringing this to my attention. I will look into this to see if I can find a quick solution. I do not have the time right at this moment right now. In the meantime if you wish to see how `/proc/version` is supported in TermuxArch you can try these commands:
```
[14:26~]$ bash ~/storage/downloads/setupTermuxArch b
```
```
[14:26~]$ cd ~/TermuxArchBloom
[14:26TermuxArchBloom]$ f version *h|f -w proc
6:archlinuxconfig.bash:403:     # bind kernel information when /proc/version is accessed
7:archlinuxconfig.bash:404:     PROOTSTMNT+="-b $INSTALLDIR/var/binds/fbindprocversion:/proc/version "
```

If you happen to find a solution in the please share with a [PR](https://github.com/SDRausty/TermuxArch/pulls).

**Comment by WMCB-Tech** [comment]
So can you give me the script so I can try it

**Comment by WMCB-Tech** [comment]
Hey. @SDRausty Sorry to disturb you again. but how can I bind fake `/proc/version` in Arch Linux Environment. it seems when editing the `startarch` script. it's too complicated to edit it's configs. 

tried to run `bash setupTermuxArch b` but gives me. `Run it on native Termux Environment` Error.

**Comment by SDRausty** [comment]
> can you give me a link of fixed installer 
> Run it on native Termux Environment Error.

The link of fixed installer script is https://github.com/SDRausty/TermuxArch/commit/b833087a475aa9dacf15c33ff7689ce376e80ac9 and should it accomplish the goal you are seeking, please share this.

**Comment by WMCB-Tech** [comment]
So @SDRausty I should Download it?

**Comment by SDRausty** [comment]
> should Download it?

You can access the latest commit in a number of ways.  If you have cloned theis repository simply updating it with `git pull` should be enough to get the latest version.  If you are running the stand alone setup script `setupTermuxArch`, it should update itself automatically.  If it fails to update when run, executed it again.  Should that fail, download the newest copy from this website:
https://sdrausty.github.io/TermuxArch/.

**Comment by SDRausty** [comment]
> should I download it?

You can access the latest commit https://github.com/SDRausty/TermuxArch/commit/b833087a475aa9dacf15c33ff7689ce376e80ac9 in a number of ways.  A few suggestions are listed here.
1.  If you have cloned the repository, simply updating it with `git pull` should be enough to get the latest version.  
1. If you are running the standalone setup script `setupTermuxArch`, it should update itself automatically.  If it fails to selfupdate when run, execute it again.  I've noticed that with the recent changes sometimes it updates itself correctly, but fails to run. So the user will need to initiate the process requested again.  A couple of recent versions refuse to update completely.
1. Should the selfupdating process fail, you can download the newest copy from this website:
https://sdrausty.github.io/TermuxArch/.

Please share how this change affected your work @WMCB-Tech? Did it resolve the issue with Libreoffice? 

 If this change did not accomplish the desired result, please share the relevant diagnostic information so a resolution can be quickly found.

**Comment by SDRausty** [comment]
Retesting the install feature is requested as, ["Issues with Libreoffice #252"](https://github.com/SDRausty/TermuxArch/issues/252) was opened.  Should device space be an issue with your device smartphone, wearable, smartwatch and more, please run this command:
```
bash setupTermuxArch re
```
This will refresh the installation to the newest version for development, testing and the ux (user experience) should space on device NOT be an issue, please use the alternate directory install feature; `setupTermuxArch h` has more information about the alt directory install  feature; cocurrent Linux versions on smartphone and more with the `setupTermuxArch i` option are possible.  Please see option `setupTermuxArch h` for more information.

**Comment by SDRausty** [comment]
Retesting the install feature is requested as, ["Issues with Libreoffice #252"](https://github.com/SDRausty/TermuxArch/issues/252) was opened.  Should device space be an issue with your device smartphone, wearable, smartwatch and more, please run this command:
```
bash setupTermuxArch re
```
This command should refresh the installation to the newest version for development, testing and the ux (user experience) should space on device NOT be an issue.  Please use the alternate directory install feature; `setupTermuxArch h` has more information about the alt directory install feature it device space is unlimited for this project;  Cocurrent Linux versions on smartphone and more with the `setupTermuxArch i` option are possible.  Please see option `setupTermuxArch h` for more information.

**Comment by WMCB-Tech** [comment]
It worked @SDRausty I just need to execute `./setupTermuxArch re` and checked whether the `/proc/version` is readable. and it works. Thank you.

**Comment by SDRausty** [comment]
Thank you for confirming @WMCB-Tech Enjoy!

**Comment by SDRausty** [comment]
> Thank you.

You are welcome @WMCB-Tech.  Thank you for using this product.

**Comment by WMCB-Tech** [comment]
Actually @SDRausty. I have a PC. but it's a desktop computer. which it's not obviously portable to bring it everywhere. so I came up with a solution called TermuxArch. which it has more Functionality than Andronix and more Versatile. It has a great features such as fake proc Filesystem. Allows me to install packages with `AUR` and it has up-to-date packages. which is like a VM/Sandbox. I was so happy that I have a fully functional/stable Arch Linux system. in Andronix. you still have to patch stuff. but with this one. you can run Linux apps Unmodified.
