### ISSUE TITLE
Backup and restore

### ISSUE THREAD

**Issue by mukhtharcm** [SDRausty/TermuxArch#253]
Is there any way to backup and restore TermuxArch for resetting Android. 
So I don't have to setup all these again.

**Comment by SDRausty** [comment]
>  to backup and restore 

@mukhtharcm you try backing up the entire installation with `bsdtar`.  To backup the home directories just backup `/home`.

**Comment by SDRausty** [comment]
>  to backup and restore 

@mukhtharcm you can try backing up the entire installation with `bsdtar`.  To backup the home directories just backup `/home`:

1. https://www.gnu.org/software/tar/manual/
1. https://duckduckgo.com/?q=tar+site%3Atldp.org

**Comment by mukhtharcm** [comment]
How to restore then? @sdrausty
