### ISSUE TITLE
TigerVNC Xsession error in Arch Linux

### ISSUE THREAD

**Issue by WMCB-Tech** [SDRausty/TermuxArch#254]
So. I have installed TigerVNC on Arch. but when launching. it gives me an error:
`couldn't find suitable Xsession`. TigerVNC works before. now it seems it's broken in some ways. I could use XSDL. but it's buggy. is there a way to fix this?

**Comment by SDRausty** [comment]
This https://www.reddit.com/r/archlinux/comments/iqjds6/tigervnc_11102_update_fix/ just came up yesterday.

> Starting a vnc session results in tigervnc: Could not start a suitable Xsession

**Comment by SDRausty** [comment]
@WMCB-Tech is seems that @JanuszChmiel has found a workaround here https://github.com/TermuxArch/TermuxArch/issues/28#issuecomment-691035121_
