### ISSUE TITLE
[Error while installing]espritfunctions.bash: line20: ceds[$i]: unbound variable

### ISSUE THREAD

**Issue by nukemiko** [SDRausty/TermuxArch#256]
I run the command `bash setupTermuxArch.bash manual` in termux to install. I set the $CMIRROR is `mirrors.tuna.tsinghua.edu.cn`, and $RPATH is `/archlinuxarm/os/`.
While the unpack program done, the script is terminated and give me an error message:
```
🕛 > 🕤 Arch Linux in Termux PRoot is installed.  Configuring and updating Arch Linux 📲  espritfunctions.bash: line 20: ceds[$i]: unbound variable
setupTermuxArch manual 2.0.573: [Exit Signal 1] DONE 🏁
```
Is it an error? How I need to do after the error?

**Comment by SDRausty** [comment]
@nukemiko please try `bash setupTermuxArch.bash refresh` to see whether this helps with the error.

**Comment by SDRausty** [comment]
@nukemiko this issue is also being discussed https://github.com/SDRausty/TermuxArch/issues/259 here.

**Comment by SDRausty** [comment]
The error `ceds[$i]: unbound variable` is resolved again.  This time this https://github.com/SDRausty/TermuxArch/commit/68631a280d11872dd35d02f3b808311cde74164f commit is the assisting commit, and comment, "[[16:29~]$ which editor](https://www.reddit.com/r/termux/comments/jfq7xi),” was one of the assisting discussions including this issue;  Thank you @nukemiko very much.
