### ISSUE TITLE
Xfce4 Bug in Arch Linux

### ISSUE THREAD

**Issue by WMCB-Tech** [SDRausty/TermuxArch#257]
Hey @SDRausty sorry for disturbing you but today TigerVNC works. even with just executing `vncserver` command runs xfce4 flawlessly without any configurations. but now it seems There's a bug with it. Tried it with XSDL and TigerVNC and seems there's a bug:

![IMG_20201005_211158.jpg](https://user-images.githubusercontent.com/65075766/95084229-2d141100-0750-11eb-8422-17cdb195ac6d.jpg)
![IMG_20201005_211222.jpg](https://user-images.githubusercontent.com/65075766/95084247-3309f200-0750-11eb-936c-59bedeb1c53e.jpg)
![IMG_20201005_211445.jpg](https://user-images.githubusercontent.com/65075766/95084261-37360f80-0750-11eb-8488-2edee29585a3.jpg)

Not only xfce. i tried nautilus with Fluxbox and gives me invalid argument when opening `/` directory and GTK File Chooser Dialogs. idk if there's a bug with GTK.

**Comment by dockerformthedock** [comment]
same problem here
when you first give vncserver instead of asking to set the password and generate the config and the xstartup script
is asking for a display, if you give vncserver :1 or :2 or :3450 it starts of course but with no config

if you create the config and the xstartup script same problem it seams it doesnt read them

**Comment by SDRausty** [comment]
Does `vncserver -localhost -SecurityTypes none` help?

**Comment by WMCB-Tech** [comment]
No. there's a new update in Tigervnc, by simply typing:
`vncserver -localhost -SecurityTypes none`
It says:
`vncserver <DISPLAY>.

But with `vncpasswd` and `vncserver :1` it starts xfce4 automatically 

But the bug is XFCE and GTK Error about `/` invalid argument. even with XSDL and dbus-launch

**Comment by WMCB-Tech** [comment]
@SDRausty I'm closing this issue since proot has now fixed with statx () syscall [here](https://github.com/termux/proot/issues/122)

**Comment by SDRausty** [comment]
> proot has now fixed with statx() syscall

@WMCB-Tech thank you for helping to resolve this issue.
