### ISSUE TITLE
Can't use makepkg to build packages

### ISSUE THREAD

**Issue by muzz666** [sdrausty/TermuxArch#26]
Fakeroot is not working.
Shows this error:

fakeroot, while creating message channels: Function not implemented
This may be due to a lack of SYSV IPC support.
fakeroot: error while starting the `faked' daemon.

**Comment by sdrausty** [comment]
@muzz666  `setupTermuxArch.sh` now creates system information. Run `setupTermuxArch.sh sysinfo` and post this information along with your input and complete output.  If you think a screenshot will help us in resolving, include it in your post.

**Comment by xeffyr** [comment]
@muzz666, many of android devices have disabled SYSV IPC support. So only custom kernel with SYSV IPC.

**Comment by sdrausty** [comment]
Use `useradd username`.  Then `cp -r arch/root/ arch/username`.  Finally `su - username` and similar to login as user, not the root account of your Arch Linux in Termux installation.

**Comment by seanbud** [comment]
I'm having this issue - is there any solutions / workarounds ?

**Comment by sdrausty** [comment]
@xeffyr can you send an example of successfully using `makepkg`?
> Or force disable fakeroot in makepkg scripts

References
1) https://github.com/sdrausty/TermuxArch/issues/100
3) https://github.com/sdrausty/TermuxArch/issues/59
4) https://github.com/sdrausty/TermuxArch/issues/38
1) [is:issue makepkg](https://github.com/sdrausty/TermuxArch/issues?q=makepkg)

**Comment by sdrausty** [comment]
Accessing libandroid-shmem support is now possibly in TermuxArch, use **[`setupTermuxArch.sh r`](https://raw.githubusercontent.com/sdrausty/TermuxArch/master/scripts/files/stable/setupTermuxArch.sh)** for quick system refresh; libandroid-shmem support is added with this https://github.com/sdrausty/TermuxArch/commit/a25067274c341b73d1fc79b85eabbbbdf33680eb commit.  The current version of [TermuxArch](https://sdrausty.github.io/TermuxArch/) also sets locales from Android on the fly for Arch Linux in Termux PRoot to be in the language you wish!

**Comment by sdrausty** [comment]
> I'm having this issue - is there any solutions / workarounds ?

null / none

**Comment by sdrausty** [comment]
> I'm having this issue - is there any solutions / workarounds ?

Do you have some suggestions?

**Comment by sdrausty** [comment]
Variable substitution in TermuxArch resolves sudo.  Variable assignment [`PROOTSTMNTU="${PROOTSTMNT//--link2symlink }"`](https://github.com/sdrausty/TermuxArch/blob/master/knownconfigurations.sh#L88) drops --link2symlink from the user login proot statement.  The option is necessary for root user to function properly. This change modifies the proot statement for user login with this https://github.com/sdrausty/TermuxArch/commit/a0db0f130b3effba7eaa2dbe8061eaca2eab1058 commit.  

```
$ startarch l user
[user11:30~]$ sudo whoami

We trust you have received the usual lecture from the local System
Administrator. It usually boils down to these three things:

    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

[sudo] password for root:
root
[user11:30~]$ whoami
user
```

`setupTermuxArch.sh c addauser user` creates a user account.  As Arch Linux in Termux PRoot root user, use `visudo` to grant user permission to use sudo.

**Comment by hunar1997** [comment]
This solved the issue for me https://www.reddit.com/r/archlinux/comments/7rycmu/cannot_build_fakeroottcp_without_fakeroot/duhy47g

**Comment by sdrausty** [comment]
> This solved the issue for me https://www.reddit.com/r/archlinux/comments/7rycmu/cannot_build_fakeroottcp_without_fakeroot/duhy47g

Thank you @hunar1997
