### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by wtfdewuno** [SDRausty/TermuxArch#260]
How would i go about uninatalling...i had to cancel the install halfway with ctrl+c. Because of no room "memory"

**Comment by SDRausty** [comment]
Command `setupTermuxArch help` has the information you are seeking.

**Comment by SDRausty** [comment]
> Command `setupTermuxArch help` has the information you are seeking.

`PURGE    command 'setupTermuxArch purge' uninstalls Arch Linux in PRoot from Termux`
