### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by WMCB-Tech** [SDRausty/TermuxArch#261]
Hey sorry for the inconveniences, so while i install arch linux i got this error:
```
error: failed retrieving file 'archlinux-keyring-20200622-1-any.pkg.tar.xz' from tw.mirror.archlinuxarm.org : The requested URL returned error: 404
warning: failed to retrieve some files
 archlinuxarm-key...    12.2 KiB  0.00   B/s 00:00
 ca-certificates-...     7.9 KiB  0.00   B/s 00:00
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
/root/bin/keys: line 104: sudo: command not found

 TermuxArch WARNING:  Generated script signal 127 near or at line number 104 by '127'!


TermuxArch keys archlinux-keyring archlinuxarm-keyring ca-certificates-utils 2.0.724: DONE 📱 🏁


 TermuxArch WARNING:  Generated script signal 201 near or at line number 59 by '/root/bin/keys'!

finishsetup.bash  2.0.724 [Exit Signal 201]: DONE  🏁
```
It seems that there's a problem at the Installation about downloading pacman keys package. however doing `pacman -Syu` then `./setupTermuxArch refresh` fix it. but i think the problem is about `error while retriving X The requested url was not found` and the package databases isn't updated.

Here's the full log:
https://github.com/TermuxArch/docsTermuxArch/pull/5

(However isn't pulled yet)

**Comment by SDRausty** [comment]
> there's a problem at the Installation about downloading pacman keys package

This error arose from implementing Arch Linux 32.  Thank you for bringing it to my attention @WMCB-Tech
