### ISSUE TITLE
Getting resolve specifier error everytime i try to install something

### ISSUE THREAD

**Issue by dawnskullmega** [SDRausty/TermuxArch#262]
(1/1) installing sudo                              100%
:: Running post-transaction hooks...
(1/3) Reloading system manager configuration...
  Skipped: Current root is not booted.
(2/3) Creating temporary files...
/usr/lib/tmpfiles.d/journal-nocow.conf:26: Failed to resolve specifier: uninitialized /etc detected, skipping
All rules containing unresolvable specifiers will be skipped

I Get This Error Every time I Try To Install Something.

**Comment by SDRausty** [comment]
> I Get This Error Every time I Try To Install Something.

Does this error, `/usr/lib/tmpfiles.d/journal-nocow.conf:26: Failed to resolve specifier: uninitialized /etc detected, skipping
All rules containing unresolvable specifiers will be skipped` effect the programs that you install?

**Comment by SDRausty** [comment]
@dawnskullmega this https://github.com/SDRausty/TermuxArch/commit/d86c9feb63b4b164c372ca05df8295a46b552ed2 commit appears to resolve, `Failed to resolve specifier`.  The new version is read for testing.  You can close this issue as far as I see.
