### ISSUE TITLE
Where's all the scripts in ~/bin?

### ISSUE THREAD

**Issue by WMCB-Tech** [SDRausty/TermuxArch#264]
Hello i just did a clean install of Termux and TermuxArch, after clean straightforward Installation of TermuxArch, it seems all scripts (`makeyay` `makefakeroottcp` `tour` etc.) in `~/bin` is missing and only shows 2 Scripts:
![Screenshot_2020-12-05-13-42-24-77.jpg](https://user-images.githubusercontent.com/65075766/101235049-f6328b00-36ff-11eb-9c05-2abc3602d46c.jpg)

I tried refreshing it but the are still missing or moved?

**Comment by SDRausty** [comment]
Hello @WMCB-Tech 
> Where's all the scripts in ~/bin? 

Moved to ~/arch/usr/local/bin/;  Please use `which` to locate; `which tour`.
