### ISSUE TITLE
Display output method?

### ISSUE THREAD

**Issue by nathaneltitane** [SDRausty/TermuxArch#265]
Hello - I was wondering which display server/output method to android you were using to get the device to present the contents of your chroot onto the Android display.

[My project](https://github.com/nathaneltitane/dextop) currently relies on VNC output and was wondering if there was any way to enhave it to something a little more native.

Thanks

**Comment by SDRausty** [comment]
> get the device to present the contents of your chroot onto the Android display.

Hello,  I'm not sure if this answers your question completely.  If it doesn't please comment.  

> It's just a simple command to setup the exports.  For it to work, it must be sourced.  That's why the dot `.` and space are important.   Otherwise, it won't work right:
```
[19:36 ~ ]$ . exd
[19:36 ~ ]$ export
declare -x DISPLAY=":0"
declare -x PULSE_SERVER="tcp:127.0.0.1:4712"
```

_Originally posted by @SDRausty in https://github.com/SDRausty/TermuxArch/issues/59#issuecomment-381285151_

**Comment by nathaneltitane** [comment]
> > get the device to present the contents of your chroot onto the Android display.
> 
> Hello, I'm not sure if this answers your question completely. If it doesn't please comment.
> 
> > It's just a simple command to setup the exports.  For it to work, it must be sourced.  That's why the dot `.` and space are important.   Otherwise, it won't work right:
> 
> ```
> [19:36 ~ ]$ . exd
> [19:36 ~ ]$ export
> declare -x DISPLAY=":0"
> declare -x PULSE_SERVER="tcp:127.0.0.1:4712"
> ```
> 
> _Originally posted by @SDRausty in [#59 (comment)](https://github.com/SDRausty/TermuxArch/issues/59#issuecomment-381285151)_

Right, but what application or library or server do you use **on android** to get your display? Like what's on the screen capture for the project i guess...

**Comment by SDRausty** [comment]
> application or library or server do you use on android to get your display? 

Good question @nathaneltitane;   How can this topic be made easier for the new user?  Here are two answers to your question:

1. _Originally posted by @abicorios in https://github.com/SDRausty/TermuxArch/issues/27#issuecomment-350579775_

> Wow. It is work. After run **XServer XSDL**, just input in the TermuxArch console
```
export DISPLAY=:0 PULSE_SERVER=tcp:127.0.0.1:4712
```
> And after it, I can start some Gui soft from the TermuxArch console.

XServer XSDL link https://github.com/pelya/xserver-xsdl


2. _Originally posted by @iL3D in https://github.com/SDRausty/TermuxArch/issues/59#issuecomment-381350922_

> * How do I get software rendering so I can run gui app?

> @root-voidX, Using noVNC+tigervnc instead of XServer XSDL saves the need to install an external app. Access gui apps from any already-installed web browser.
```
#  lxde + fix, as before
pacman -S lxde
pacman -S ttf-dejavu

#  vnc server
pacman -S tigervnc
#  html5 vnc client 
curl -O https://github.com/novnc/noVNC/archive/v1.0.0.tar.gz
tar xvfz v1.0.0.tar.gz

#  run vnc. make sure display & vnc port match
export DISPLAY=:7
export VNC_PORT=5907
Xvnc --localhost --SecurityTypes=None $DISPLAY &
cd noVNC-1.0.0; ./utils/launch.sh --vnc localhost:$VNC_PORT &
 
startlxde
echo "To see the magic, point your favorite browser to http://127.0.0.1:6080/vnc.html"
```

Please share which method you prefer, and how this topic be made easier for the new user.

**Comment by nathaneltitane** [comment]
> > application or library or server do you use on android to get your display?
> 
> Good question @nathaneltitane; How can this topic be made easier for the new user? Here are two answers to your question:
> 
> 1. _Originally posted by @abicorios in [#27 (comment)](https://github.com/SDRausty/TermuxArch/issues/27#issuecomment-350579775)_
> 
> > Wow. It is work. After run **XServer XSDL**, just input in the TermuxArch console
> 
> ```
> export DISPLAY=:0 PULSE_SERVER=tcp:127.0.0.1:4712
> ```
> 
> > And after it, I can start some Gui soft from the TermuxArch console.
> 
> XServer XSDL link https://github.com/pelya/xserver-xsdl
> 
> 1. _Originally posted by @iL3D in [#59 (comment)](https://github.com/SDRausty/TermuxArch/issues/59#issuecomment-381350922)_
> 
> > * How do I get software rendering so I can run gui app?
> 
> > @Root-voidX, Using noVNC+tigervnc instead of XServer XSDL saves the need to install an external app. Access gui apps from any already-installed web browser.
> 
> ```
> #  lxde + fix, as before
> pacman -S lxde
> pacman -S ttf-dejavu
> 
> #  vnc server
> pacman -S tigervnc
> #  html5 vnc client 
> curl -O https://github.com/novnc/noVNC/archive/v1.0.0.tar.gz
> tar xvfz v1.0.0.tar.gz
> 
> #  run vnc. make sure display & vnc port match
> export DISPLAY=:7
> export VNC_PORT=5907
> Xvnc --localhost --SecurityTypes=None $DISPLAY &
> cd noVNC-1.0.0; ./utils/launch.sh --vnc localhost:$VNC_PORT &
>  
> startlxde
> echo "To see the magic, point your favorite browser to http://127.0.0.1:6080/vnc.html"
> ```
> 
> Please share which method you prefer, and how this topic be made easier for the new user.

I guess that answers my wuestion - using the same methods on my side :)

**Comment by SDRausty** [comment]
This link https://wiki.termux.com/wiki/Graphical_Environment should be useful for this issue too.
