### ISSUE TITLE
How to user general user to login arch

### ISSUE THREAD

**Issue by ilkl** [SDRausty/TermuxArch#267]
It is default user is root.How to use general username to login,that I can use aur helper as yay?

**Comment by WMCB-Tech** [comment]
`startarch u user`

**Comment by ilkl** [comment]
think you，how to login with password?

**Comment by SDRausty** [comment]
The commands `setupTermuxArch help` and `startarch help` have usage information.  Passwords are disabled in TermuxArch by default.  

> login with password

Why do you want to use a password @ilkl?
