### ISSUE TITLE
How to use Xorg in TermuxArch?

### ISSUE THREAD

**Issue by abicorios** [sdrausty/TermuxArch#27]
I need the Xorg for run my Java Gui code when I study the programming. I try my simple exercise https://github.com/abicorios/JavaGuiExercise by JDK, which I obtain by **pacman -S jdk9-openjdk**. As far as the error is **No X11 DISPLAY variable was set**, I use **pacman -S xorg** and **pacman -S xorg-init**. But **startx** produce errors too, and I cannot run my code. Also, how to connect the TermuxArch to the XServer XSDL? https://play.google.com/store/apps/details?id=x.org.server

**Comment by abicorios** [comment]
Wow. It is work. After run **XServer XSDL**, just input in the TermuxArch console
```
export DISPLAY=:0 PULSE_SERVER=tcp:127.0.0.1:4712
```
And after it, I can start some Gui soft from the TermuxArch console.

**Comment by Soph1a7** [comment]
Thanks for the input, I'm sure it will be useful for other people with the same question/issue.

**Comment by sdrausty** [comment]
@abicorios Thank you for posting this issue.  Can you provide a screenshot or two of your hard work on device regarding Xorg for this thread?

**Comment by abicorios** [comment]
Yes, these screens are made for you.

![screenshot_2017-12-20-05-48-09-886_com termux](https://user-images.githubusercontent.com/33332953/34190429-6ae675b2-e549-11e7-88cb-f34709656261.png)

![screenshot_2017-12-20-05-47-42-062_x org server](https://user-images.githubusercontent.com/33332953/34190447-7c42c360-e549-11e7-80d3-198239d6e471.png)

**Comment by sdrausty** [comment]
Thank you for sharing your experience and your work.

**Comment by tukusejssirs** [comment]
I tried to install and run `xfce4` with following commands:
```bash
    pacman -Syyu xfce4 xorg
    echo "exec startxfce4" > ~/.xinitrc
    export DISPLAY=:0 PULSE_SERVER=tcp:127.0.0.1:4712
```
but failed. Running `startx` outputs this:
```bash
[config] failed to pre-init udev                                                                                X.Org X Server 1.20.0                                   X Protocol Version 11, Revision 0                       Build Operating System: Linux Arch Linux                Current Operating System: Linux localhost 3.4.113-OmniBear-g6f9f4d3 #1 SMP PREEMPT Mon Dec 19 18:38:13 CET 2016 armv7l                                                  Build Date: 18 June 2018  07:03:09AM

Current version of pixman: 0.34.0                               Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,                                                      (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.                                         (==) Log file: "/var/log/Xorg.0.log", Time: Wed Jun 20 23:33:27 2018
(==) Using system config directory "/usr/share/X11/xorg.conf.d"                                                 (EE)
Fatal server error:                                     (EE) parse_vt_settings: Cannot open /dev/tty0 (No such file or directory)                                       (EE)
(EE)
Please consult the The X.Org Foundation support                  at http://wiki.x.org                            for help.                                              (EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.                        (EE)                                                    (EE) Server terminated with error (1). Closing log file.

xinit: giving up                                        xinit: unable to connect to X server: Connection refusedxinit: server error
Couldn't get a file descriptor referring to the console
```

I am probably missing something, probably it’s just the port number – how can I get that number?

**Comment by abicorios** [comment]
You can see port nuber by 'XServer XSDL' app. Install it from [https://play.google.com/store/apps/details?id=x.org.server](https://play.google.com/store/apps/details?id=x.org.server)
