### ISSUE TITLE
Pulse audio aun no funciona

### ISSUE THREAD

**Issue by Yisus7u7** [SDRausty/TermuxArch#275]
ya lidie con todos los bugs que encontre, pero hay uno que no logro solucionar, el de pulse audio, no sirve, o estoy haciendo algo mal?
![Screenshot_20210322-135040](https://user-images.githubusercontent.com/64093255/112042724-d6d83600-8b15-11eb-8fe0-50c719a0e108.png)
![Screenshot_20210322-135045](https://user-images.githubusercontent.com/64093255/112042733-db045380-8b15-11eb-81a6-7cd217e803ec.png)

**Comment by SDRausty** [comment]
No estoy seguro de si esto te ayudará; ¿Ha utilizado el comando de TermuxArch 'orcaconf'?

**Comment by SDRausty** [comment]
He actualizado las `setupTermuxArch visualorca` opciones  que configuran PulseAudio en Termux.  Use el comando de Termuxarch 'orcaconf' una vez instalado Arch Linux en Termux PRoot para completar la configuración.

**Comment by Yisus7u7** [comment]
Listo, ahora ahora que debo hacer ?

**Comment by Yisus7u7** [comment]
Lo canceoe, esto usando xfce4, no tengo muchos espacio, orcaconf iba a instalar el escritorio de mate, para que voy a querer ese escritorio?

**Comment by SDRausty** [comment]
Si:
```
[user17:54~]$ cat $(which orcaconf)
.
.
.
espeak-ng mate mate-extra orca pulseaudio-alsa tigervnc
.
.
.
```

**Comment by Yisus7u7** [comment]
mejor me quedo sin audio con tal de mantener xfce4

**Comment by SDRausty** [comment]
> para que voy a querer ese escritorio?

Por favor pregúntale a @JanuszChmiel como él ayudó al pionero de visualorca que usa mate. Si el espacio es un problema, sugiero [`play-audio`](https://github.com/termux/play-audio) en programa informático nativo Termux.

> mejor me quedo sin audio con tal de mantener xfce4

Sigue este tema en sentido ascendente y aquí.

https://groups.io/g/termux/message/561
> why it is not possible to release pulseaudio which will support recording from microphone

https://github.com/termux/termux-packages/issues?q=is%3Aissue+pulseaudio
