### ISSUE TITLE
Strange job of fakeroot.

### ISSUE THREAD

**Issue by Maxython** [SDRausty/TermuxArch#276]
Hello everyone, I noticed fakeroot was working strangely when installing the AUR package.
### Briefly:  
If you run arch from a specific user (`startarch u user`), then fakeroot does not work and refers to the problem #83 .  
If you run arch in the usual way (`startarch`), then fakeroot works.  
___
Are there any suggestions why this is happening?

**Comment by Ther-Test** [comment]
Start Arch
`startarch`

install fakeroot
`pacman -S fakeroot`

create a sh script
`touch fr.sh`
then copy↓
`pacman -R --noconfirm fakeroot
for i in make automake autoconf gcc libtool po4a; do
	[[ $(command -v ${i}) ]] || pacman -Syu --noconfirm ${i}
done
[[ $(command -v whereis) ]] || pacman -Sy --noconfirm util-linux

FAKEROOT_SRC_REPO='https://mirrors.bfsu.edu.cn/debian/pool/main/f/fakeroot/'
FAKEROOT_SRC_VERSION=$(curl -L ${FAKEROOT_SRC_REPO} | grep \.orig\.tar | tail -n 1 | awk -F '<a href=' '{print $2}' | cut -d '"' -f 2)
FAKEROOT_SRC_URL="${FAKEROOT_SRC_REPO}${FAKEROOT_SRC_VERSION}"
FAKEROOT_SRC_FILE=$(printf "%s\n" ${FAKEROOT_SRC_VERSION} | sed 's@fakeroot_@fakeroot-@g')
cd /tmp
curl -Lv -o ${FAKEROOT_SRC_FILE} ${FAKEROOT_SRC_URL}
tar -xvf ${FAKEROOT_SRC_FILE}
cd ${FAKEROOT_SRC_FILE%.*.*.*}
./bootstrap
./configure --prefix=/usr --libdir=/usr/lib/libfakeroot --with-ipc=tcp --disable-static
make -j4
cd doc
po4a -k 0 --rm-backups --variable "srcdir=../doc/" po4a/po4a.cfg
cd ..
make install`

ago 
`nano fr.sh`

Long press, then paste
Ctrl+x
y
enter


then 
`sh fr.sh`

**Comment by Ther-Test** [comment]
Start Arch
`startarch`

install fakeroot
`pacman -S fakeroot`

create a sh script
`touch fr.sh`

then copy↓
`pacman -R --noconfirm fakeroot
for i in make automake autoconf gcc libtool po4a; do
	[[ $(command -v ${i}) ]] || pacman -Syu --noconfirm ${i}
done
[[ $(command -v whereis) ]] || pacman -Sy --noconfirm util-linux

FAKEROOT_SRC_REPO='https://mirrors.bfsu.edu.cn/debian/pool/main/f/fakeroot/'
FAKEROOT_SRC_VERSION=$(curl -L ${FAKEROOT_SRC_REPO} | grep \.orig\.tar | tail -n 1 | awk -F '<a href=' '{print $2}' | cut -d '"' -f 2)
FAKEROOT_SRC_URL="${FAKEROOT_SRC_REPO}${FAKEROOT_SRC_VERSION}"
FAKEROOT_SRC_FILE=$(printf "%s\n" ${FAKEROOT_SRC_VERSION} | sed 's@fakeroot_@fakeroot-@g')
cd /tmp
curl -Lv -o ${FAKEROOT_SRC_FILE} ${FAKEROOT_SRC_URL}
tar -xvf ${FAKEROOT_SRC_FILE}
cd ${FAKEROOT_SRC_FILE%.*.*.*}
./bootstrap
./configure --prefix=/usr --libdir=/usr/lib/libfakeroot --with-ipc=tcp --disable-static
make -j4
cd doc
po4a -k 0 --rm-backups --variable "srcdir=../doc/" po4a/po4a.cfg
cd ..
make install`

ago 
`nano fr.sh`

Long press, then paste
Ctrl+x
y
enter


then 
`sh fr.sh`

Wait a while

**Comment by SDRausty** [comment]
This commit https://github.com/SDRausty/TermuxArch/commit/744e3a3eefc58aa227ce04612415d5ef1a40ea1e enables the `--sysvipc` PRoot option for user accounts. Creating `fakeroot-tcp` is no longer required.
