### ISSUE TITLE
Using pacman on fails on i686 machine (Chromebook)

### ISSUE THREAD

**Issue by bambooeater** [sdrausty/TermuxArch#28]
I successfully installed ArchLinux in Termux with your script on my Chromebook. However, pacman cannot make a connection to any of the servers that I uncomment in /etc/pacman.d/mirrorlist. Adding archstrike and/or blackarch in pacman.conf also does not help.

In Termux itself I am connected and can install stuff with apt.

Here my system information (I am using the latest install script):
1 uname -mo
i686 Android ("i686 GNU/Linux" from within the Arch environment)
2 getprop ro.product.cpu.abi
x86
3 getprop ro.product.device
relm_cheets
4 ls -al ~/arch
see screenshot

Any ideas? Looking forward to use Arch in Termux...

![screenshot 2017-12-14 at 1 52 48 am](https://user-images.githubusercontent.com/3826096/33970136-a0fe1be6-e071-11e7-81ef-4eee980d2adf.png)

**Comment by Soph1a7** [comment]
On a stock TermuxArch install, without uncommenting your prefered hosts, can you update(or have any kind of network acess such as ping)?
If no, do `cat /etc/resolv.conf` and give us the output.
Thanks

**Comment by bambooeater** [comment]
No, network at all on stock TermuxArch install, also no response on ping.

I will post later my resolv.conf when I am back at the Chromebook. Thanks!


On Dec 14, 2017 15:08, "Sofia" <notifications@github.com> wrote:

On a stock TermuxArch install, without uncommenting your prefered hosts,
can you update(or have any kind of network acess such as ping)?
If no, do cat /etc/resolv.conf and give us the output.
Thanks

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sdrausty/TermuxArch/issues/28#issuecomment-351720356>,
or mute the thread

**Comment by bambooeater** [comment]
The resolv.conf contains the Google DNS nameservers:
`nameserver 8.8.8.8
nameserver 8.8.4.4`

Actually I cannot even ping, as the ping command is not found. Also vi is not installed. The machine is a brand new Acer Chromebook, should be nothing special about it.

Calling `pacman -Syu` fails both for no servers uncommented and some servers uncommented. Problem seems to be indeed the network itself.

Hope to get it running! Thank you for your support!

**Comment by sdrausty** [comment]
@bambooeater what is the output from `which ping` in Arch Linux in Termux PRoot?  Check `.profile`, `.bash_profile ` and `.bashrc` for specific network configurations.  Do you have any such entries in these files in Termux $HOME that should be migrated to Arch $HOME?  

Try with just `Server = http://mirror.archlinuxarm.org/$arch/$repo` this line uncommented in /etc/pacman.d/mirrorlist and do not set ArchStrike or BlackArch up until you are finished setting up Arch Linux in Termux.  Setting Arch Linux up including updating is a prerequisite to either of the other two versions.

**Comment by bambooeater** [comment]
I don't even have a `which` command in ArchLinux in PRoot. There are also no config files (`.profile`, `.bash_profile`, `.bashrc`) at all.  It is a fresh installation of termux and basically the first thing I did then was to install PRoot with ArchLinux (I tried to install via wget and via git, same effect). Networks works in termux, not in PRoot.

**Comment by bambooeater** [comment]
BTW it is a Acer N7 Chromebook, with an Intel processor. Does PRoot only work with ARM, possibly?

**Comment by sdrausty** [comment]
What is the output on your machine when you do this?
```
$ startarch
Welcome to Arch Linux in Termux!  Enjoy!

Chat:    https://gitter.im/termux/termux/
Help:    info <query> and man <query>
Portal:  https://wiki.termux.com/wiki/Community

Install a package: pacman -S <package>
More  information: pacman [-D|F|Q|R|S|T|U] --help
Search   packages: pacman -Ss <query>
Upgrade  packages: pacman -Syu
[23:22 home ]$ cd
[23:22 ~ ]$ ls -al
total 32
drwxr-x---  4 root root 4096 Dec 11 07:57 .
drwx------ 18 root root 4096 Dec 14 23:22 ..
-rw-------  1 root root    2 Dec 11 07:57 .bash_history
-rw-------  1 root root  215 Dec 11 04:16 .bash_profile
-rw-------  1 root root  517 Dec 11 04:16 .bashrc
drwx------  2 root root 4096 Dec 11 04:47 bin
drwx------  3 root root 4096 Dec  3 18:39 .gnupg
-rw-------  1 root root   22 Dec 11 04:16 .profile
```

Is your result similar?

**Comment by bambooeater** [comment]
Yeah, my `/root` folder looks the same. My `.bash_profile` is smaller (only 80 Bytes), containing:
`
. $HOME/.bashrc
PS1="[\A\[\033[0;32m\] \W \[\033[0m\]]\$ "
`

BTW, how do I copy and paste in Termux (I retyped the .bash_profile, as I didnt know how to c/p)?

**Comment by sdrausty** [comment]
@bambooeater This http://www.tldp.org/LDP/intro-linux/html/sect_02_02.html should make interesting reading from http://www.tldp.org/LDP/intro-linux/html/index.html See section 3.3.2.2.3. 'Copying files' for answers to your copy and paste question.

1) Output from `setupTermuxArch.sh --sysinfo` and `ip route` in Termux is requested.  
2) `ip route` output from Arch Linux in Termux PRoot is wanted too.

**Comment by bambooeater** [comment]
Thanks for the link. Actually I know how to copy files in linux. I just do not know how to use a clipboard from within termux (to paste here). I can store for example the output of `setupTermuxArch.sh --sysinfo` in a file, but don't know how to paste it here.

`$ ip route`
`100.115.92.0/30 dev arc0  proto kernel  scope link  src 100.115.92.2`

In PRoot I do not have the ip command.

**Comment by Soph1a7** [comment]
Try reinstalling the arch chroot and tell us if that fixes it

**Comment by bambooeater** [comment]
Tried already. Flashed the Chromebook by enabling the developer more and
reinstalled Termux and TermuxArch. Exactly the same happened, no network
access in PRoot.

**Comment by EsdrasTarsis** [comment]
Arch Linux does not support i686 architecture in repositories, but it has a project that supports this architecture and you can use the mirrors of that project by placing them in the mirrorlist

https://archlinux32.org/

I use i686 architecture on my smartphone and pacman is working with these mirrors

**Comment by bambooeater** [comment]
Great hint, EsdrasTarsis. Using one of the archlinux32 servers brings me one step further, pacman can retrieve data.

However, I cannot install the package `pacman -Syy archlinux32-keyring-transition` as described on https://archlinux32.org/download/
I am getting the error message:
`could not change the root directory (Function not implemented)`
`error: command failed to execute correctly`

**Comment by EsdrasTarsis** [comment]
Try to run these commands to see if it works
```pacman -Syuu```

```rm -r arch/etc/pacman.d/gnupg```

```pacman -S gnupg archlinux32-keyring```

```pacman-key --init```

```pacman-key --populate archlinux32```

```pacman-key --refresh-keys```

```pacman -Sc```

**Comment by sdrausty** [comment]
@EsdrasTarsis @Soph1a7 Thank you for assistance with this important i686 matter.

**Comment by EsdrasTarsis** [comment]
If the arch linux 32 project had a bootstrap in the mirrors of the isos, we could put it in the script, so no one would have problems with the arch in the i686 architecture

**Comment by bambooeater** [comment]
It would be nice to make it easier, I agree. My Arch installation is now running. @EsdrasTarsis latest commands didn't help me to solve the issue. I could work myself around, by setting ignoring the key requirement in `/etc/pacman.conf`(by changing the SigLevel line to `SigLevel = Never`). Of course, this is not the optimal solution. If I do not disable this option I get the `invalid or corrupted package (PGP signature)` error message. Another issue is that `pacman-key --populate archlinux32` hangs forever (`pacman-key --init` runs fine).

Also without key requirement, I also do get error messages with pacman: `could not change the root directory (Function not implemented)`

Did a test install on my Android ARM phone, everything works out of the box like a charm. Maybe we should reopen this issue using a better title, as i686 Chromebooks definitely still have issues with ArchTermux.

**Comment by sdrausty** [comment]
Function i686 in https://github.com/sdrausty/TermuxArch/blob/master/scripts/files/stable/knownconfigurations.sh  wants updating to https://archive.archlinux.org/iso/2017.12.01/ and archlinux-bootstrap-2017.12.01-x86_64.tar.gz with on device testing.  It seems i686 is currently unfrozen!  Your assistance is welcome.

**Comment by bambooeater** [comment]
Thank you @sdrausty. Using current archlinux32 as suggested by @EsdrasTarsis is probably the best idea. I am afraid I won't find the time to test things out thoroughly in near future.

After switching to archlinux32 `gnupg` complained for a version mismatch with `libassuan`, so mixing the frozen version and modules from the archlinux32 repo should be probably avoided. 

Thanks all for your helpful comments and your work on this project.

**Comment by EsdrasTarsis** [comment]
@sdrausty If the arch linux 32 mirrors have the arch bootstrap I will do a pull request

**Comment by sdrausty** [comment]
@EsdrasTarsis Great! Using scripts/maintenance/makedownload.sh in scripts/files/stable will generate setupTermuxArch.tar.gz and setupTermuxArch.md5 after modifying knownconfigurations.sh.

**Comment by sdrausty** [comment]
"vi: command not found"   https://github.com/sdrausty/TermuxArch/issues/21and sed similar seem related.  @Soph1a7 has pushed beautiful code regarding self update to newest online boot image download for similar architecture.   Hopefully it will be useful in i686 necessary functions.

**Comment by sdrausty** [comment]
> It seems i686 is currently unfrozen! 

Wishful thinking which might be possible.  

"as there is still some interest in keeping i686 alive, we would like to encourage the community to make it happen with our guidance. The arch-ports mailing list and #archlinux-ports IRC channel on Freenode will be used for further coordination.  " 

https://www.archlinux.org/news/phasing-out-i686-support/ has details.

**Comment by sdrausty** [comment]
Here is "Community maintained repos.  i686"   https://archlinux32.org/ another link which might make boot images possible.

**Comment by sdrausty** [comment]
> My Arch installation is now running.  

Thanks for the update 🔆🌅🌑🎼

**Comment by sdrausty** [comment]
Issue https://github.com/termux/proot/issues/10, "`pacman -S archlinux-keyring` Hangs in Arch Linux Termux PRoot" is now open regarding this matter.

**Comment by sdrausty** [comment]
@bambooeater @EsdrasTarsis `pacman-key --populate archlinux` hangs on arm; Any suggestions?
```
pacman-key --populate archlinux
==> Appending keys from archlinux.gpg...
==> Locally signing trusted keys in keyring...
  -> Locally signing key DDB867B92AA789C165EEFA799B729B06A680C281...
  -> Locally signing key 684148BB25B49E986A4944C55184252D824B18E8...
```

**Comment by sdrausty** [comment]
Upstream has resolved this issue https://github.com/termux/proot/issues/10#issuecomment-370161621 after working on this topic afaict, @michalbednarski has found:
```
pacman-key --init
echo disable-scdaemon > /etc/pacman.d/gnupg/gpg-agent.conf
pacman-key --populate
```
Use this code to resolve `pacman-key --populate archlinux` issues with Arch Linux in Termux PRoot.  Before using `pacman-key --populate archlinux`,  run `pacman -S archlinux-keyring` first.  

Arch x86 and x86_64 results are requested, arm results as well pertaining to `finishsetup.sh` and `pacman-key`.  If a post setup autoconfiguration with update script is deemed wanted for `setupTermuxArch.sh` regarding `pacman-key`, this can be done on a per architecture basis.

**Comment by sdrausty** [comment]
Commit https://github.com/sdrausty/TermuxArch/commit/f16c27d4336ff6e38e1338e7846adc8843b9c0fc adds Arch Linux IRC channel upstream contact information to the TermuxArch motd and logout.  
> See https://wiki.archlinux.org/index.php/IRC_channel for available Arch Linux IRC channels.
