### ISSUE TITLE
A little question

### ISSUE THREAD

**Issue by GitHubNeko** [SDRausty/TermuxArch#280]
Is this proot container a lite version？Whether it is a custom Arch ？;-)

**Comment by SDRausty** [comment]
>Is this proot container a lite version？

No, it's a full distro.

>Whether it is a custom Arch ？;-)

It is customized for Termux PRoot installation.

**Comment by GitHubNeko** [comment]
> > 这个 proot 容器是精简版吗？
> 
> 不，这是一个完整的发行版。
> 
> > 是不是定制的 Arch ？;-)
> 
> 它是为 Termux PRoot 安装定制的。

Very good, exactly what i need :,-)
