### ISSUE TITLE
Error While Installing Packages

### ISSUE THREAD

**Issue by Teeskid** [SDRausty/TermuxArch#289]
When I install new package, an error ocuurs with Arming ConditionNeedsUpdate. Then things like nodejs doesn't work, npm not in directory.

**Comment by Teeskid** [comment]
Ok Sir, Thank you

**Comment by SDRausty** [comment]
>Arming ConditionNeedsUpdate

I cannot reproduce this error at present; @Teeskid is this error still still present on your device?
