### ISSUE TITLE
ssh-agent >> PRNG is not seeded

### ISSUE THREAD

**Issue by ZaxonXP** [sdrausty/TermuxArch#29]
I installed the TermuxArch and I want to use it as my default shell, so I am migrating my settings from the termux as much as possible.

One of the thngs I want to use is the ssh-agent, so I do not have to type the password each time I do remote ssh or scp. However when I do the:

`ssh-agent`

I got the:

`PRNG is not seeded`

Any ideas?

Regards,
Piotr

**Comment by Soph1a7** [comment]
Can you acess `/dev/random` or `/dev/urandom`?  (`cat` them)
PRNG cannot be seeded if the chroot directory doesn't have acess to the /dev  pseudofilesystem.

**Comment by ZaxonXP** [comment]
Yes, they both producing some random characters when I cat tchem.

**Comment by Soph1a7** [comment]
try this 
 ```mknod -m 0644 /dev/random c 1 8
mknod -m 0644 /dev/urandom c 1 9```  and retry the ssh command.

**Comment by ZaxonXP** [comment]
It says `mknod: /dev/urandom: File exists` and `mknod: /dev/random: File exists`

**Comment by ZaxonXP** [comment]
Any ideas?

**Comment by sdrausty** [comment]
Thank you for your comments and consideration regarding this matter.  Random, this is a very interesting issue!   Use

`[04:31 home ]$ random="$(dd if=/dev/urandom bs=3 count=1)"
1+0 records in
1+0 records out
3 bytes copied, 0.000339479 s, 8.8 kB/s
[05:04 home ]$ random="$(dd if=/dev/random bs=3 count=1)"
1+0 records in
1+0 records out
3 bytes copied, 0.000463229 s, 6.5 kB/s`

To read as this is a quieter alternative to reading  from these files.  

As regular Termux user, Arch Linux in Termux PRoot user, `su` and `sulogin` `rm` commands all yield `rm: cannot remove '/dev/random': Permission denied`.  Information about deleting and recreating these system files is welcome at this thread.

**Comment by sdrausty** [comment]
`[05:26 home ]$ dd if=/dev/urandom bs=3 count=1
��1+0 records in
1+0 records out
3 bytes copied, 0.000247031 s, 12.1 kB/s
[05:27 home ]$ dd if=/dev/urandom bs=3 count=1 of=ra
1+0 records in
1+0 records out
3 bytes copied, 0.00605912 s, 0.5 kB/s
[05:27 home ]$ !ca
cat ra
h��[05:27 home ]$ dd if=/dev/urandom bs=3 count=1 of=ra |cat ra
h��1+0 records in
1+0 records out
3 bytes copied, 0.00385885 s, 0.8 kB/s
[05:27 home ]$`

**Comment by ZaxonXP** [comment]
@sdrausty: What is your point with the dd code? I did the test using cat and the random devices were producing random output. But still I cannot use ssh-agent due to the `PRNG is not seeded` error. How can I fix this?

**Comment by sdrausty** [comment]
@ZaxonXP have you explained your topic at https://wiki.archlinux.org/index.php/IRC_Channel and similar discussion groups?

**Comment by ZaxonXP** [comment]
@sdrausty: No, I did not. Yesterday I gave up the TermuxArch because of this and some other issues. Maybe I give another try some day.

**Comment by sdrausty** [comment]
@ZaxonXP Are the randon devices producing random output?

> the random devices were producing random output.  

How did you reseed?

**Comment by ZaxonXP** [comment]
@sdrausty: when I did `cat /dev/urandom` and `cat /dev/random` they printed random characters (also not ASCII) on the terminal. What do you mean by "how did you reseed"?

**Comment by sdrausty** [comment]
@ZaxonXP Reseeding and random are related to entropy (A measure of the disorder or randomness in a closed system).  It appears that the root Arch Linux user cannot access this due to  Android permission selinux.

**Comment by sdrausty** [comment]
These links https://duckduckgo.com/html?q=reseed%20random%20device%20site%3Atldp.org are here for our future scrutiny.

**Comment by sdrausty** [comment]
It seems like the random devices are working fine on aarch64.  See https://github.com/sdrausty/TermuxArch/commit/9aea551b7bbcfd1c1718d7b7642afa55e2301f9e for newely added bash scripts to test these devices.  @ZaxonXP scripts/frags/rnd/9.16.sh has examples of reseeding random.  Another method of reseeding is to use`date`.

**Comment by sdrausty** [comment]
This issue is closed since it does not concern [`setupTermuxArch.sh`](https://raw.githubusercontent.com/sdrausty/TermuxArch/master/scripts/files/stable/setupTermuxArch.sh) itself.

**Comment by Gold3nboy** [comment]
@sdrausty you closed this issue, but even reading the links and the other related issues it's not so clear how to overcome this problem. Can you please give some detailed hints about how to use ssh-agent ?

**Comment by arno01** [comment]
That was the ``proot`` issue https://github.com/termux/proot/issues/62#issue-445846475 which has been fixed in this commit https://github.com/termux/proot/commit/3ea655b1ae40bfa2ee612d45bf1e7ad97c4559f8
