### ISSUE TITLE
Building xrdp from AUR fails mentioning selinux

### ISSUE THREAD

**Issue by lupo-on-github** [SDRausty/TermuxArch#293]
Building xrdp from AUR fails with
(German localization)

```
==> Beginne prepare()...  
patching file instfiles/xrdp.service.in
patch: setting attribute security.selinux for security.selinux: Permission denied
```

Any suggestions?

(Are these lines sufficient to evaluate the problem?)

**Comment by SDRausty** [comment]
>Any suggestions?

Try editing the PKGBUILD file, and then run `makepkg -firs --noconfirm`.

> security.selinux: Permission denied

This topic is very extensive.  See whether reaching out through the [community channels](https://wiki.termux.com/wiki/Community) and [github discussions](https://github.com/termux/termux-packages/discussions) helps in resolving this build issue if you cannot solve it easily; Good luck!

**Comment by SDRausty** [comment]
@lupo-on-github I have taken a closer look at this issue and opened a new issue [patch: setting attribute security.selinux for security.selinux: Permission denied #220](https://github.com/termux/proot/issues/220) regarding this issue here.  Please feel free to join the new discussion.

**Comment by SDRausty** [comment]
An open disscussion is at [patch: setting attribute security.selinux for security.selinux: Permission denied #182](https://github.com/termux/proot/issues/182).

**Comment by SDRausty** [comment]
Thank you for opening this issue @lupo-on-github;  While I was attempting to fix [`makeaurhelpers`](https://github.com/SDRausty/TermuxArch/blob/master/archlinuxconfig.bash#L650) with commands:

`cd /usr/local/bin/`

`for i in $(ls --color=never makeaur*) ; do $i ; done` this issue began ringing in my mind as I was studying the output from the [`makeaur*`](https://github.com/SDRausty/TermuxArch/blob/master/archlinuxconfig.bash#L650&&L856) commands.  Hopefully a resolution for the `patch` command in Termux PRoot environment will be found soon.

**Comment by SDRausty** [comment]
>resolution for the patch command 

Fortunately, the Termux `patch` command works in TermuxArch.  Please link the `patch` command into the `/usr/local/bin` directory, and the packages that you are trying to make should build as expected.

**Comment by SDRausty** [comment]
This command `ln -s /data/data/com.termux/files/home/bin/patch /data/data/com.termux/files/home/arch/usr/local/bin/patch` run in a native Termux shell might resolve a `patch: setting attribute security.selinux for security.selinux: Permission denied` error.  Issues “Building xrdp from AUR fails mentioning selinux #293” at https://github.com/SDRausty/TermuxArch/issues/293 and “patch: setting attribute security.selinux for security.selinux: Permission denied #182” at https://github.com/termux/proot/issues/182 have more information about this error.
