### ISSUE TITLE
Installation not successful 

### ISSUE THREAD

**Issue by Rockysri** [SDRausty/TermuxArch#294]
I installed today when i run , startarch it gives me $startarch
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/arch, cwd = /root, $PATH=(null))
fatal error: see `proot --help`.

**Comment by SDRausty** [comment]
>proot error:

Please attempt refreshing the Arch Linux in Termux PRoot system after finding out more why the install failed;  Command `setupTermuxArch sysinfo` can help.

I cannot reproduce this error;  Is the system that you are using [up to date with packages](https://github.com/WAE/au) and [app](https://github.com/termux/termux-app/releases) and Android?

What is your device architecture `uname -m`?
