### ISSUE TITLE
command makeyay not found

### ISSUE THREAD

**Issue by UnsuitableFollower** [SDRausty/TermuxArch#296]
I previously installed arch but I deleted it, And a few days later I installed arch again, And I did makeyay, but command not found, How to fix it
![Screenshot_20220517-122703_Termux](https://user-images.githubusercontent.com/88485719/168735585-3ae644cf-4072-49b3-8cf4-8c8604e8d088.png)

**Comment by SDRausty** [comment]
Commit https://github.com/SDRausty/TermuxArch/commit/434f7a795fae06a42c7c7fa5525465d32dfe173c improves `makeyay` support.

**Comment by SDRausty** [comment]
Commit https://github.com/SDRausty/TermuxArch/commit/434f7a795fae06a42c7c7fa5525465d32dfe173c seems to have improved support for the `makeyay` command.  If you have comments and/or questions, please share them in this issue here.
