### ISSUE TITLE
Having problems with the installation

### ISSUE THREAD

**Issue by 0uros** [SDRausty/TermuxArch#306]
Hello, I make this proposal because I have doubts regarding the installation of Arch Linux, when I do the installation termux closes, leaving me with the files _finishsetup.bin_ and _setupbin.bash_

I am not very knowledgeable about Linux, I have done this following the guide on the page, but i'm stuck

**Comment by MasterInfinite** [comment]
How do I install it.

**Comment by 0uros** [comment]
First I installed git in termux:
`pkg install git`

Then I downloaded and installed arch arm
`cd && git clone https://github.com/sdrausty/TermuxArch`
`bash TermuxArch/setupTermuxArch.sh`

After that, he didn't get any further.
