### ISSUE TITLE
Automatic x86_64 download from evowise no longer works

### ISSUE THREAD

**Issue by dmayle** [sdrausty/TermuxArch#32]
The setup script assumes that a wget from will automatically download the correct file, but now it just downloads an index.html file, and so the script halts

**Comment by dmayle** [comment]
I'm happy to help...  Why isn't x86_64 just using the equivalent bootstrap image?

**Comment by dmayle** [comment]
`< 🕛 Activating termux-wake-lock.  Now downloading  and the corresponding checksum.  This may take a long time depending on your Internet connection.

--2018-01-10 14:16:15--  http://mirrors.evowise.com/archlinux/iso/latest/
Resolving mirrors.evowise.com... 2400:cb00:2048:1::6813:874b, 2400:cb00:2048:1::6813:894b, 2400:cb00:2048:1::6813:8b4b, ...
Connecting to mirrors.evowise.com|2400:cb00:2048:1::6813:874b|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html.tmp’

index.html.tmp                                             [ <=>                                                                                                                       ]   1.12K  --.-KB/s    in 0s

Last-modified header missing -- time-stamps turned off.
2018-01-10 14:16:15 (11.2 MB/s) - ‘index.html.tmp’ saved [3202]

Loading robots.txt; please ignore errors.
--2018-01-10 14:16:15--  http://mirrors.evowise.com/robots.txt
Reusing existing connection to [mirrors.evowise.com]:80.
HTTP request sent, awaiting response... 404 Not Found
2018-01-10 14:16:15 ERROR 404: Not Found.

Removing index.html.tmp since it should be rejected.

--2018-01-10 14:16:15--  http://mirrors.evowise.com/archlinux/iso/latest/arch/
Reusing existing connection to [mirrors.evowise.com]:80.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html.tmp’

index.html.tmp                                             [ <=>                                                                                                                       ]    1008  --.-KB/s    in 0.001s

Last-modified header missing -- time-stamps turned off.
2018-01-10 14:16:15 (894 KB/s) - ‘index.html.tmp’ saved [2369]

Removing index.html.tmp since it should be rejected.

--2018-01-10 14:16:15--  http://mirrors.evowise.com/archlinux/iso/latest/archlinux-bootstrap-2018.01.01-x86_64.tar.gz
Reusing existing connection to [mirrors.evowise.com]:80.
HTTP request sent, awaiting response... 200 OK
Length: 134175315 (128M) [application/octet-stream]
Saving to: ‘archlinux-bootstrap-2018.01.01-x86_64.tar.gz’

archlinux-bootstrap-2018.01.01-x86_64.tar.gz           100%[==========================================================================================================================>] 127.96M  8.92MB/s    in 12s

2018-01-10 14:16:27 (10.4 MB/s) - ‘archlinux-bootstrap-2018.01.01-x86_64.tar.gz’ saved [134175315/134175315]

--2018-01-10 14:16:27--  http://mirrors.evowise.com/archlinux/iso/latest/arch/boot/
Reusing existing connection to [mirrors.evowise.com]:80.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html.tmp’

index.html.tmp                                             [ <=>                                                                                                                       ]   1.05K  --.-KB/s    in 0.004s

Last-modified header missing -- time-stamps turned off.
2018-01-10 14:16:27 (260 KB/s) - ‘index.html.tmp’ saved [2642]

Removing index.html.tmp since it should be rejected.

--2018-01-10 14:16:27--  http://mirrors.evowise.com/archlinux/iso/latest/arch/x86_64/
Reusing existing connection to [mirrors.evowise.com]:80.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html.tmp’

index.html.tmp                                             [ <=>                                                                                                                       ]   1.02K  --.-KB/s    in 0s

Last-modified header missing -- time-stamps turned off.`

**Comment by dmayle** [comment]
```
--2018-01-10 14:16:27--  http://mirrors.evowise.com/archlinux/iso/latest/arch/x86_64/
Reusing existing connection to [mirrors.evowise.com]:80.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html.tmp’

index.html.tmp                                             [ <=>                                                                                                                       ]   1.02K  --.-KB/s    in 0s

Last-modified header missing -- time-stamps turned off.
2018-01-10 14:16:28 (5.04 MB/s) - ‘index.html.tmp’ saved [2519]

Removing index.html.tmp since it should be rejected.

--2018-01-10 14:16:28--  http://mirrors.evowise.com/archlinux/iso/latest/arch/boot/x86_64/
Reusing existing connection to [mirrors.evowise.com]:80.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘index.html.tmp’

index.html.tmp                                             [ <=>                                                                                                                       ]   1.04K  --.-KB/s    in 0.01s

Last-modified header missing -- time-stamps turned off.
2018-01-10 14:16:28 (108 KB/s) - ‘index.html.tmp’ saved [2645]

Removing index.html.tmp since it should be rejected.

FINISHED --2018-01-10 14:16:28--
Total wall clock time: 13s
Downloaded: 6 files, 128M in 12s (10.4 MB/s)
md5sums.txt                                                [ <=>                                                                                                                       ]     126  --.-KB/s    in 0s

 🕠 < 🕛 Checking download integrity with md5sum.  This may take a little while.

md5sum: .md5: No such file or directory

 🔆 ERROR md5sum mismatch! The download was corrupt! Removing failed download.  Run setupTermuxArch.sh again!  See https://sdrausty.github.io/TermuxArchPlus/md5sums for more information.  This kind of error can go away, sort of like magic.  Waiting a few minutes before executing again is recommended. There are many reasons that generate checksum errors.  Proxies are one reason.  Mirroring and mirrors are another explaination for md5sum errors.  Either way it means this download was corrupt.  If this keeps repeating, please change your mirror with an editor like vi in knownconfigurations.sh.  See https://sdrausty.github.io/TermuxArchPlus/mirrors for more information.

        Run setupTermuxArch.sh again. Exiting...
$
```

**Comment by sdrausty** [comment]
In the meantime simply edit [setupTermuxArch.sh](https://raw.githubusercontent.com/sdrausty/TermuxArch/master/scripts/files/stable/setupTermuxArch.sh) locally after setting it aside in its own directory.  `git clone https://github.com/sdrausty/TermuxArch` should do this gracefully.  Remove the checksum and download function calls from  [setupTermuxArch.sh](https://raw.githubusercontent.com/sdrausty/TermuxArch/master/scripts/files/stable/setupTermuxArch.sh)  and  [necessaryfunctions.sh](https://raw.githubusercontent.com/sdrausty/TermuxArch/master/scripts/files/stable/necessaryfunctions.sh) .  Edit [knownconfigurations.sh](https://raw.githubusercontent.com/sdrausty/TermuxArch/master/scripts/files/stable/knownconfigurations.sh) and x86_64 download should be back up and running locally on your device.  

*Important* **pull request** *information:*   https://raw.githubusercontent.com/sdrausty/TermuxArch/master/scripts/maintenance/makedownload.sh in https://github.com/sdrausty/TermuxArch/tree/master/scripts/files/stable generate setupTermuxArch.tar.gz and setupTermuxArch.md5 after modifying https://raw.githubusercontent.com/sdrausty/TermuxArch/master/scripts/files/stable/knownconfigurations.sh and similar.

**Comment by ardoi** [comment]
This is not an issue with the arch bootstrap file failing the md5 check. As you can see from the error message (`md5sum: .md5: No such file or directory`), the script is looking for a file called `.md5`. The problem is in the `makesystem` function in `necessaryfunctions.sh`. It assumes that `$file` variable contains the file name, but this is not set for x86_64 systems (as per `knowconfigurations.sh`). Adding a line with `file=$filename` in the `adjustmd5file` function in `necessaryfunctions.sh` should make it work. Coincidentally had been trying to figure this out myself today and that gets the installation going.

**Comment by sdrausty** [comment]
@ardoi Thank you for the update.  
> Remove the wget, checksum and download calls from 
Remove the checksum function calls from the download setup script.  Leave the downloaded image file checksums checks in place.  It is great to see that you have a handle on the script.

**Comment by sdrausty** [comment]
Automatic x86_64 download from evowise no longer works https://github.com/sdrausty/TermuxArch/issues/32 
How to solve this error?  https://github.com/sdrausty/TermuxArch/issues/35
Latest `wget` 1.19.3 produces errors https://github.com/termux/termux-packages/issues/2052
**All three(3) of these may be related, including this topic.**  

Can you check by downgrading your `wget`?  Here are the instructions:
At present the simplest solution is to downgrade wget in Termux. Use `apt remove wget` to downgrade your wget to https://sdrausty.github.io/TermuxArch/scripts/files/wget_1.19.2-1_aarch64.deb this version. dpkg --install wget_1.19.2-1_aarch64.deb, then `bash setupTermuxArch.sh` may resolve this issue as it has two other issues. Let us know your outcome.

For **armv7** users: 
https://sdrausty.github.io/TermuxArch/scripts/files/wget_1.19.2_arm.deb https://sdrausty.github.io/TermuxArch/scripts/files/libuuid_1.0.3-1_arm.deb  
https://sdrausty.github.io/TermuxArch/scripts/files/libunistring_0.9.7_arm.deb  
https://sdrausty.github.io/TermuxArch/scripts/files/pcre_8.41-1_arm.deb 

Use `apt remove wget libunistring` followed by `dpkg --install libunistring_0.9.7_arm.deb wget_1.19.2_arm.deb` as a possible temporary solution to this  x86_64 and ERROR md5sum mismatch topic.

**Comment by sdrausty** [comment]
@dmayle can you check your version of `wget`?  If it  is version 1.19.3 which has known issues, try using 

https://sdrausty.github.io/repoX86_64/dists/termux/extras/binary-x86_64/wget_1.19.1_x86_64.deb

https://sdrausty.github.io/repoX86_64/dists/termux/extras/binary-x86_64/libunistring_0.9.7_x86_64.deb might be wanted as well.  

From https://sdrausty.github.io/repoX86_64/ hosted at https://github.com/sdrausty/repoX86_64

**Comment by sdrausty** [comment]
@dmayle I just checked your architecture with the latest version of `wget`.  Use [`apt update`](https://termux.com/package-management.html) or [`au`](https://sdrausty.github.io/au/) to update the Termux system.  [Latest `wget` 1.19.3 produces errors](https://github.com/termux/termux-packages/issues/2052) is now closed with this pull request [wget: Update from 1.19.3 to 1.19.4](https://github.com/termux/termux-packages/commit/fd1350e42710a44ff6de1c0fd9914f4b0543710b) which was causing the error you were getiing.
