### ISSUE TITLE
Arch kernel and Android kernel compatibility

### ISSUE THREAD

**Issue by Atavic** [sdrausty/TermuxArch#34]
Please explain it to me:

Arch is currently on kernel 4.14.13 while Android 8.0 Oreo has kernel 4.10
Do different versions work together or may I find errors?

Also, previous Android are on older versions: 7.0 Nougat  has kernel 4.4.1
Are older versions stil usable with a bleeding edge OS as Arch or Fedora?

**Comment by sdrausty** [comment]
@Atavic Have you installed Arch Linux on your smartphone in Termux?

**Comment by Atavic** [comment]
No. I have an old version 5.1.1

**Comment by sdrausty** [comment]
> I have an old version 5.1.1

Termux Arch Linux fine in Android 5.  

Try it and see if you like it.  You might want to get [**a free new smartphone when you switch**](https://duckduckgo.com/?q=a+free+new+smartphone+when+you+switch&atb=v98-6_g&ia=web) to have more space and power on device and more fun with Arch Linux in [Termux PRoot](https://github.com/termux/proot) on Android, Chromebook and Fire OS.
