### ISSUE TITLE
How to solve this error?

### ISSUE THREAD

**Issue by r0om3** [sdrausty/TermuxArch#35]
ERROR md5sum mismatch!  Setup initialization mismatch!  Update your copy of setupTermuxArch.sh.  If you have updated it, this kind of error can go away, sort of like magic.  Waiting a few minutes before executing again is recommended, especially if you are using a new copy from https://raw.githubusercontent.com/sdrausty/TermuxArch/master/setupTermuxArch.sh on your system.  There are many reasons that generate checksum errors.  Proxies are one reason.  Mirroring and mirrors are another explanation for md5sum errors.  Either way this means,  "Try again, initialization was not successful."  See https://sdrausty.github.io/TermuxArchPlus/md5sums for more information.

        Run setupTermuxArch.sh again. Exiting...

![screenshot_2018-01-21-11-25-04-337_com termux](https://user-images.githubusercontent.com/35037886/35195740-3d0f6ea0-fe9e-11e7-9430-c2bacf92588b.png)

**Comment by sdrausty** [comment]
Thank you for posting this issue.  At present the simplest solution is to downgrade wget in Termux.  Use `apt remove wget` to downgrade your wget to https://sdrausty.github.io/TermuxArch/scripts/files/wget_1.19.2-1_aarch64.deb this version.  `dpkg --install wget_1.19.2-1_aarch64.deb`, then `bash setupTermuxArch.sh` should resolve this issue for the time being.  Let us know your outcome.

**Comment by sdrausty** [comment]
For armv7 users https://sdrausty.github.io/TermuxArch/scripts/files/wget_1.19.2_arm.deb

**Comment by sdrausty** [comment]
https://github.com/sdrausty/TermuxArch/issues/32#issuecomment-359306018 `wget` might be producing other maladies as well with version 1.19.3.  

>  Automatic x86_64 download from evowise no longer works https://github.com/sdrausty/TermuxArch/issues/32 
How to solve this error?  https://github.com/sdrausty/TermuxArch/issues/35
Latest `wget` 1.19.3 produces errors https://github.com/termux/termux-packages/issues/2052
**All three(3) of these may be related, including this topic.**  

**All three(3) of these may be related, including this topic to wget 1.19.3 and libunistring.**  

> if [ $(getprop ro.product.cpu.abi) = x86_64 ];then
		wget -A tar.gz -m -nd -np http://$mirror$path

*From https://raw.githubusercontent.com/sdrausty/TermuxArch/master/scripts/files/stable/necessaryfunctions.sh*

**Comment by r0om3** [comment]
thanks for the solution I think this is running

![screenshot_2018-01-21-22-22-21-956_com termux](https://user-images.githubusercontent.com/35037886/35202624-28eb1bc0-fefa-11e7-8b0f-f14d880db632.png)

**Comment by sdrausty** [comment]
Thank you for sharing!
