### ISSUE TITLE
Succesfully Modified Stock 'makepkg'...

### ISSUE THREAD

**Issue by markfelt** [SDRausty/TermuxArch#38]
...To work on stock TermuxArch. I have built and installed the 'aur/cylon' package on a Samsung S8+.

I basically commented out lines so that 'su' instead of 'sudo' is used, and 'fakeroot' isn't used.

**Comment by markfelt** [comment]
Here's the diff from the current (as of this posting) stock 'makepkg' to a version that'll work on Android:
[makepkg.zip](https://github.com/sdrausty/TermuxArch/files/1666976/makepkg.zip)

**Comment by sdrausty** [comment]
Thank you for sharing your success with us!      Can you outline a few steps how to use it with aur?

**Comment by markfelt** [comment]
The basic scenario:
After installing Termux and TermuxArch on the Android device, do this:
Have the 'makepkg.diff' file in a location it can be accessed (in the following example, it's located in the normal 'home' directory).

Then run this command:
patch -n -i makepkg.diff -o makepkg /bin/makepkg
(This creates an updated 'makepkg' in the 'home' directory.)

Next, copy the updated 'makepkg' over the original 'makepkg' by running this command:
cp makepkg /bin

Now you're ready to use aur packages...

For example, do these commands to install and run 'aur/cylon' while starting in the 'home' directory:
pacman -S cower
cower -d cylon
cd cylon
makepkg -i
cylon

**Comment by markfelt** [comment]
Your mileage may vary based on the Android device used. I wasn't able to build 'cylon' on one device due to a problem with '/dev' and another device won't allow the direct patching of '/bin/makepkg' (which is why I gave the patching steps listed above).

**Comment by markfelt** [comment]
Also, the '/dev' problem relates to how redirection is handled in the shell:
https://unix.stackexchange.com/questions/367849/why-is-there-a-dev-fd-63-in-the-output-of-echo-123-cat

In this case, these are the 'makepkg' errors when running on certain devices:
/usr/share/makepkg/util/pkgbuild.sh: line 69: /dev/fd/62: No such file or directory
/usr/share/makepkg/source/file.sh: line 44: /dev/fd/62: No such file or directory

**Comment by Raywarioba** [comment]
how can you install arch linux desktop on chromebook, i successful installed the arch linux environment on my chromebook but the problem is i dont know how to install desktop environment

**Comment by sdrausty** [comment]
@Raywarioba your question is off topic for this thread.  "How to use Xorg in TermuxArch?" has information regarding your question.  Post more information about Linux desktop topic at #27, or open a new issue.  #27 can be reopened at any time when requested.  Posting information output from `bash setupTermuxArch.sh sysinfo` is requested.

**Comment by sdrausty** [comment]
This [TermuxArch v0.9](https://github.com/sdrausty/TermuxArch/releases/tag/0.9) release adds user functionality to Termux for Arch Linux PRoot users:

* `addauser` creates an Arch Linux user and user $HOME directory. 
* `addauserps` creates an Arch Linux user, user $HOME directory and Arch Linux user `startarch` login from Termux.

**Comment by sdrausty** [comment]
@markfelt this [TermuxArch v1.1](https://github.com/sdrausty/TermuxArch/releases/tag/1.1) release adds [the patch](https://github.com/sdrausty/TermuxArch/blob/master/necessaryfunctions.sh#L203&L205).  However:
```
makepkg -i
/usr/share/makepkg/util/pkgbuild.sh: line 69: /dev/fd/62: No such file or directory
.
.
.
/usr/share/makepkg/util/pkgbuild.sh: line 69: /dev/fd/62: No such file or directory
==> Making package: cylon 5.2-4 (Fri Mar  9 12:49:44 UTC 2018)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
/usr/share/makepkg/source/file.sh: line 44: /dev/fd/62: No such file or directory
```
 This error happens on all devices tested, including aarch64 and armv7.

**Comment by markfelt** [comment]
That's because you're using an old(?) Kernel (or Bash) which doesn't do
shell file redirection correctly. If you look at the lines mentioned in the
error(s), you'll notice at the location of one of them, the output of a
subshell command is being redirected directly into the input of a while
loop (I'm not sure (at this moment) how to pipe (or otherwise get) the
command results into the while loop.) Try using a later version of 64bit
Android to test, my 7.0 device works, my 6.0? device shows the same error
mentioned.

**Comment by sdrausty** [comment]
@markfelt as the patch does not work on Android 6 the patching process has been dropped at present.

> an old(?) Kernel (or Bash)

This patch was applied in the latest versions of Arch Linux in armv7 and aarch64.  How could this be an old version issue?  Making aur repositories accessible is important.  Do you have any idea why it works on Android 7, but not on Android 6?  

This question, "Everthing Goes Well, Except for These Three Errors https://github.com/sdrausty/TermuxArch/issues/51," might be related since both threads have a common denominator, /dev errors.  Why does `makepkg` need access to /dev?  This sounds unreasonable just to build a package, doesn't it?  Is there a simple way to have `makepkg` drop all requests to /dev?

**Comment by sdrausty** [comment]
@markfelt after testing in  Android 7: fakeroot error.  There doesn't appear to be anything `setupTermuxArch.sh` can do about this at present.  Is your device rooted?  What architecture is the Android 7 mentioned?

**Comment by markfelt** [comment]
Device isn't rooted, which is why I'm using TermuxArch. System Info is attached:
[setupTermuxArchDebug.log](https://github.com/sdrausty/TermuxArch/files/1811710/setupTermuxArchDebug.log)

**Comment by sdrausty** [comment]
> Device isn't rooted

Awesome; compiling as root is a no no.  Compiling on a rooted device is a no^no no^no; unless seeing the device fail, and how it failed is the goal.  Can this be one of the reasons `makepkg` refuses to run when envoked as root user?  If you cannot envoke it, then it is not possible to observe it in action.

> System Info is attached:

Cannot open the provided link; @markfelt can you repost it into this thread.  Also, recently posted, [A few questions about Arch Linux in Termux PRoot #59](https://github.com/sdrausty/TermuxArch/issues/59) has a few questions that you might be able to answer easily.

**Comment by markfelt** [comment]
Begin setupTermuxArch debug information.

Wed Mar 14 08:02:30 PDT 2018
BASH_VERSINFO[0] = 4
BASH_VERSINFO[1] = 4
BASH_VERSINFO[2] = 19
BASH_VERSINFO[3] = 1
BASH_VERSINFO[4] = release
BASH_VERSINFO[5] = aarch64-unknown-linux-android

cat /proc/cpuinfo results:

Processor	: AArch64 Processor rev 4 (aarch64)
processor	: 0
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x51
CPU architecture: 8
CPU variant	: 0xa
CPU part	: 0x801
CPU revision	: 4

processor	: 1
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x51
CPU architecture: 8
CPU variant	: 0xa
CPU part	: 0x801
CPU revision	: 4

processor	: 2
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x51
CPU architecture: 8
CPU variant	: 0xa
CPU part	: 0x801
CPU revision	: 4

processor	: 3
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x51
CPU architecture: 8
CPU variant	: 0xa
CPU part	: 0x801
CPU revision	: 4

processor	: 4
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x51
CPU architecture: 8
CPU variant	: 0xa
CPU part	: 0x800
CPU revision	: 1

processor	: 5
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x51
CPU architecture: 8
CPU variant	: 0xa
CPU part	: 0x800
CPU revision	: 1

processor	: 6
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x51
CPU architecture: 8
CPU variant	: 0xa
CPU part	: 0x800
CPU revision	: 1

processor	: 7
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32
CPU implementer	: 0x51
CPU architecture: 8
CPU variant	: 0xa
CPU part	: 0x800
CPU revision	: 1

Hardware	: Qualcomm Technologies, Inc MSM8998

dpkg --print-architecture result:

aarch64

getprop ro.product.cpu.abi result:

arm64-v8a

getprop ro.product.device result:

dream2qltesq

Download directory information results.

lrwxrwxrwx 1 u0_a335 u0_a335 28 Jan 15 05:56 /data/data/com.termux/files/home/storage/downloads -> /storage/emulated/0/Download
ls: cannot access '/data/data/com.termux/files/home/downloads': No such file or directory
/sdcard/Download exists
/storage/emulated/0/Download exists

uname -mo results:

aarch64 Android

End setupTermuxArch debug information.

Post this information along with information regarding your issue at https://github.com/sdrausty/TermuxArch/issues.  This debugging information is found in /data/data/com.termux/files/home/setupTermuxArchDebug.log.  If you think screenshots will help in resolving this matter better, include them in your post please.

**Comment by jansenmtan** [comment]
Makepkg was updated recently. This diff reflects those changes: [makepkg.zip](https://github.com/sdrausty/TermuxArch/files/2051997/makepkg.zip)

**Comment by sdrausty** [comment]
> Sudo is now working for me. 
According to the AUR description, it's "a small bash script that fakes sudo using su", similar (I think) to how the modified makepkg works.

Referencing issue: https://github.com/sdrausty/termux-archlinux/issues/4

**Comment by sdrausty** [comment]
Accessing libandroid-shmem support is now possibly in TermuxArch, use **[`setupTermuxArch.sh r`](https://raw.githubusercontent.com/sdrausty/TermuxArch/master/scripts/files/stable/setupTermuxArch.sh)** for quick system refresh; libandroid-shmem support is added with this https://github.com/sdrausty/TermuxArch/commit/a25067274c341b73d1fc79b85eabbbbdf33680eb commit.  The current version of [TermuxArch](https://sdrausty.github.io/TermuxArch/) also sets locales from Android on the fly for Arch Linux in Termux PRoot to be in the language you wish.

**Comment by aiisuika** [comment]
`makepkg` uses `su` if `sudo` isn't found, as root, you can do:
```bash
pacman -R sudo
```
Though you'll get this warning:
```bash
makepkg
==> WARNING: Cannot find the sudo binary. Will use su to acquire root privileges.
```

If you want to remove the warning, delete at 992:
```diff
- 992: 	if (( DEP_BIN || RMDEPS || INSTALL )); then
- 993: 		if ! type -p sudo >/dev/null; then
- 994: 			warning "$(gettext "Cannot find the %s binary. Will use %s to acquire root privileges.")" "sudo" "su"
- 995: 		fi
- 996: 	fi
```
If you wanna run `makepkg` as root, it'll refuse, if you want, you may remove the lines at 1412:

```diff
- 1412: if (( ! INFAKEROOT )); then
- 1413: 	if (( EUID == 0 )); then
- 1414:		error "$(gettext "Running %s as root is not allowed as it can cause permanent,\n\
- 1415: catastrophic damage to your system.")" "makepkg"
- 1416: 		exit $E_ROOT
- 1417:	fi
- 1418: else
+ 1412: if (( INFAKEROOT )); then
```

`fakeroot` doesn't work due to Android not having sysvipc, there is [aur/fakeroot-tcp](https://aur.archlinux.org/packages/fakeroot-tcp), but to build it, we gotta use makepkg which uses fakeroot, so we have to [manually build it](https://www.reddit.com/r/archlinux/comments/7rycmu/cannot_build_fakeroottcp_without_fakeroot). The source http://ftp.debian.org/debian/pool/main/f/fakeroot/fakeroot_1.22.orig.tar.bz2 is now a 404. So:
```bash
git clone https://github.com/aiisuika/fakeroot-tcp
cd fakeroot-tcp
./build_tcp
```
Which will install to `/opt/fakeroot`. Simply uninstall fakeroot, then symlink this one.
```bash
pacman -R fakeroot
cd /bin
ln -s /opt/fakeroot/bin/fakeroot
```
You may get **a lot** of warnings when using `fakeroot`, but it works, so eh. Now we can build *most* aur packages.
For aur packages that require `patch` like [aur/fakeroot](https://aur.archlinux.org/packages/fakeroot-tcp) itself,  we need patch built with the `--disable-xattr ` flag:
```bash
git clone https://github.com/aiisuika/patch
cd patch
./build
```
This'll install to `/opt/patch` like fakeroot, uninstall patch, symlink this one. I may turn these into packages to simply install...
Here's `makepkg` without the root check & sudo: https://gist.github.com/aiisuika/f988f27c84dda8c4c9aa6b0b6cf17dc6

**Comment by sdrausty** [comment]
```
startarch u[ser]|l[ogin] user: Login as user.  Use startarch addauser user first to create this user and user's home directory.

startarch s[u] user cmd: Login as user and execute command.  Use startarch addauser user first to create this user and user's home directory.
```

These two options were modified a few days ago and should enable a functional `sudo`.

**Comment by Victor-UA** [comment]
It doesn't work in my case. Could you help me please?
![screenshot_2018-10-09-22-47-06-156_com termux](https://user-images.githubusercontent.com/24568162/46694409-6c68ff00-cc15-11e8-8cdc-6f9809feb42e.png)

**Comment by markfelt** [comment]
@Victor-UA, it's 'startarch c addauser user'. 'startarch' needed the 'c' option to tell it to run a command. Which is why it displayed its help text.

**Comment by sdrausty** [comment]
I am preparing a push to fix this issue in `startarch h[elp]`.

**Comment by sdrausty** [comment]
Thanks for pointing it out 😙

**Comment by Victor-UA** [comment]
Thank you for help, but I have problems again )
![screenshot_2018-10-11-18-13-04-420_com termux](https://user-images.githubusercontent.com/24568162/46814780-1fef0200-cd82-11e8-8ea0-55c71004d548.png)

![screenshot_2018-10-11-18-13-10-954_com termux](https://user-images.githubusercontent.com/24568162/46814763-12d21300-cd82-11e8-9955-be1e1c228f25.png)

**Comment by sdrausty** [comment]
@Victor-UA use `setupTermuxArch.sh re` to update your version.  If working with the repository, update it too before running `setupTermuxArch.sh re` to update the installation to the most recent version.

**Comment by markfelt** [comment]
@Victor-UA: You are having a security issue in trying to create the user 'user' as root. 'PAM' is blocking 'root' for some reason (invalid password, etc.).

If you are just starting out with TermuxArch and don't care about your current TermuxArch setup then reset everything by running 'setupTermuxArch.sh purge' to remove everything and then 'setupTermuxArch.sh' again to reinstall TermuxArch again. Now run 'startarch c addauser user' to add the  user 'user' to your new TermuxArch installation. (I had to do this purge and reinstall so I could test the ''startarch c addauser user' command.)

**Comment by sdrausty** [comment]
@markfelt I was tinckering with the user feature and the version @Victor-UA is using creates TermuxArch root as proot.  Editing `/etc/passwd` and renaming proot to root and /proot to /proot should resolve the issue too.  Refreshing the system should work as well.

**Comment by Victor-UA** [comment]
![screenshot_2018-10-11-21-39-35-428_com termux](https://user-images.githubusercontent.com/24568162/46826248-2ee3ad80-cd9e-11e8-8449-0fd8d44842a7.png)

**Comment by sdrausty** [comment]
@Victor-UA this is a BASH shell script.  Why are you using sh?

**Comment by Victor-UA** [comment]
Sorry, I'm very new in Linux
![screenshot_2018-10-12-17-11-14-352_com termux](https://user-images.githubusercontent.com/24568162/46874533-09a87b00-ce42-11e8-986c-5f79520c05b6.png)

**Comment by sdrausty** [comment]
The current version is TermuxArch v1.6.7.id5677.  Update manually, since the version you have is not self-updating correctly.

**Comment by sdrausty** [comment]
> I'm very new in Linux

Have you read any of these https://duckduckgo.com/?q=basic+commands+site%3Atldp.org articles?

**Comment by markfelt** [comment]
@Victor-UA, if you need a place online where you can practice with using Linux, this webpage lists 6 different online places to practice: https://geekflare.com/run-linux-from-a-web-browser/

(Some of the listed places allow you to practice with items in the software field other than Linux.)

**Comment by markfelt** [comment]
The TermuxArch installer script isn't self-updating, just manually get a copy of it from GitHub again.

**Comment by 86423355844265459587182778** [comment]
@SDRausty @markfelt 

To solve the `/dev/fd/62: No such file or directory` issue, re-compile Arch Linux ARM's bash package and add the `bash_cv_dev_fd=whacky` option when configuring:
```
  ./configure --prefix=/usr --with-curses --enable-readline \
    --without-bash-malloc --with-installed-readline \
    bash_cv_dev_fd=whacky
```
(Reference: termux/termux-packages@ab41f5b)

On an x86_64 machine, one can use [qemu-arm-static<sup>AUR</sup>](https://aur.archlinux.org/packages/qemu-arm-static) to run an ALARM chroot for re-compiling the package (the build process can be quite slow, and using distcc to redirect the compilation to the phone may help speed up a bit).

**Comment by SDRausty** [comment]
> To solve the /dev/fd/62: No such file or directory 

This is now resolved with the latest commits.  The command `setupTermuxArch.bash r` refreshes the installation quickly and resolves `No such file or directory` when using `makepkg`.

**Comment by SDRausty** [comment]
This updated diff is current (as of this posting) and was tested on armv7h Android:
[makepkg.zip](https://github.com/SDRausty/TermuxArch/files/4943430/makepkg.zip)

**Comment by SDRausty** [comment]
The patch is now included in the root directory of the project, but an error persists.  The best result with `makepkg` at present is:
```
==> Starting prepare()...
patching file libfakeroot.c
patch: setting attribute security.selinux for security.selinux: Permission denied
==> ERROR: A failure occurred in prepare().
    Aborting...
```
Thank you to those who have contributed.   More contributions are welcome.

**Comment by SDRausty** [comment]
Using `makepkg` with the `--noprepare`

**Comment by petkar** [comment]
I can't thank you enough! I'm really happy that I'm able to install packages from the aur.

**Comment by SDRausty** [comment]
The aur repository is now partly automated with functions `_ADDmakefakeroot-tcp_` and `_ADDmakeyay_` and `_ADDpatchmakepkg_` added to [archlinuxconfig.bash](https://github.com/TermuxArch/TermuxArch/blob/master/archlinuxconfig.bash#L499&&#L534) to help easily enable aur.  These functions add these `makefakeroot-tcp.bash`, `makeyay.bash` and `patchmakepkg.bash` commands.

**Comment by SDRausty** [comment]
@petkar you are very welcome.  Thank you for contributing to this project.

**Comment by phoenix183** [comment]
Why my pacman doesn't install the cower package?
pacman -S cower
Output: error: target not found: cower
