### ISSUE TITLE
Warnings during installation

### ISSUE THREAD

**Issue by MarkoM2** [sdrausty/TermuxArch#39]
Great work btw
I used the setupTermuxArch.sh script and it worked. Arch is running and programs can be installed. There were some warnings during installation however (see transcrip attached, line 160ff).  

The device is a "Vernee Thor E"

[180125_termux transcript aarch.txt](https://github.com/sdrausty/TermuxArch/files/1666903/180125_termux.transcript.aarch.txt)

**Comment by tomty89** [comment]
They are harmless as the initramfs images and the kernel are of no use when we aren't actually booting a system. You can even do `pacman -Rs linux-aarch64`.

**Comment by MarkoM2** [comment]
Ok thanks, good to know :)
