### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by mjskoneg** [sdrausty/TermuxArch#4]
[root@localhost home]# apt-get update && apt-get upgrade
bash: apt-get: command not found
[root@localhost home]#

**Comment by Soph1a7** [comment]
arch does not use dpkg, therefore it doesn't utilize apt.

**Comment by sdrausty** [comment]
Thank you for your time and input. It was very helpful in modifying [setupTermuxArch.sh](https://raw.githubusercontent.com/sdrausty/TermuxArch/master/setupTermuxArch.sh) accordingly.

**Comment by sdrausty** [comment]
https://github.com/sdrausty/TermuxArch/commit/c2b945f92d0ad54a511f5bbdf6a17edbf5c672fa
