### ISSUE TITLE
How to change the default shell?

### ISSUE THREAD

**Issue by neo-expert** [sdrausty/TermuxArch#41]
I've replaced /bin/bash with /bin/zsh in startarch file, but it starts still the bash shell.

**Comment by sdrausty** [comment]
@neo-expert Is `zsh` installed in Arch Linux Termux PRoot?  Use `pacman -S zsh` to install it if it is not installed.

**Comment by neo-expert** [comment]
Yes i can Start zsh from command line (even the glorious ".oh-my-zsh". But how to run it automatically on startarch command?
