### ISSUE TITLE
error:

### ISSUE THREAD

**Issue by yuanchuyouzuoshan** [sdrausty/TermuxArch#45]
🕒 < 🕛 Activated termux-wake-lock.  Contacting mirror http://os.archlinuxarm.org/.  Downloading ArchLinuxARM-aarch64-latest.tar.gz and the corresponding checksum from http://sg.m.  This may take a long time pending the Internet connection.

curl: (3) Illegal characters found in URL
curl: (3) Illegal characters found in URL

**Comment by sdrausty** [comment]
Thanks for sharing.  Use `setupTermuxArch.sh --help` for instructions how to set the mirror manually.  Evidently http://os.archlinuxarm.org/ is handing off an inactive mirror in your geographic location.  Running  the script again hoping you will get a better mirror next time is also a possible solution.

**Comment by JoshuaWebb** [comment]
I also encountered this issue, from multiple attempts I ended up with the following invalid URIs in the output:

Downloading ArchLinuxARM-aarch64-latest.tar.gz from [http://au.mirror.archlinuxarm.](#).
Downloading ArchLinuxARM-aarch64-latest.tar.gz from [http://sg.mirror.archlinuxarm.](#).
Downloading ArchLinuxARM-aarch64-latest.tar.gz from [.archlinuxarm.org/](#).

I can't tell at which stage the URI is getting mangled, but when I run
```bash
curl -v "http://os.archlinuxarm.org/"
```
The `Location` header seems to be okay on multiple separate attempts.
e.g.
< Location: http://au.mirror.archlinuxarm.org/
< Location: http://sg.mirror.archlinuxarm.org/

Using the http://au.mirror.archlinuxarm.org/ as the mirror in `setupTermuxArchConfigs.sh` resulted in a successful installation.

**Comment by sdrausty** [comment]
@JoshuaWebb Thanks for the update.  Glad to hear that you found a mirror that works.  Some of the mirrors near me are more reliable than others.  I guess that's what mirrors are for.  See https://archlinuxarm.org/about/mirrors for contact information.
