### ISSUE TITLE
TermuxArch setup scripts has some error in Android x86_64(RemixOS 2.0.513) in Termux

### ISSUE THREAD

**Issue by codimiracle** [sdrausty/TermuxArch#46]
i try to install TermuxArch v0.8 (using method 2) in My Android x86_64, but i meet the problem...
```
🕠 < 🕛 Checking download integrity with md5sum.  This may take a little while.

archlinux-bootstrap-2018.02.01-x86_64.tar.gz: OK

 🕕 < 🕛 System image file download integrity: OK

 🕡 < 🕛 Uncompressing .  This will take a long time.  Be patient.
bsdtar: Error opening archive: Failed to open '--strip-components'
rm: can't remove '*.tar.gz.md5': No such file or directory

 🕙 < 🕛 Arch Linux in Termux is installed.  Answer the following questions to complete the Arch Linux configuration.

archsystemconfigs.sh: line 143: etc/motd: No such file or directory
archsystemconfigs.sh: line 170: etc/resolv.conf: No such file or directory
necessaryfunctions.sh: line 156: etc/locale.gen: No such file or directory

```
i download the image and mv it to arch/ArchLinuxARM-x86_64-latest.tar.gz...
it wil be happen...
```
🕠 < 🕛 Checking download integrity with md5sum.  This may take a little while.

archlinux-bootstrap-2018.02.01-x86_64.tar.gz: OK

 🕕 < 🕛 System image file download integrity: OK

 🕡 < 🕛 Uncompressing .  This will take a long time.  Be patient.
necessaryfunctions.sh: line 139: [: too many arguments


Download Exception!  Exiting...
```
now, i have no idea to deal with the problem.

**Comment by sdrausty** [comment]
@Codimiracle Sorry to hear that you are having problems.  Thank you for sharing.   Can you check if https://github.com/sdrausty/TermuxArch/commit/940c40ad74ee9a0dc1e24c3fe90e1760f56d42b1 update v0.8 id330015623 works for you out-of-box?

**Comment by Codimiracle** [comment]
necessaryfunctions.sh line 139
```
 if [ $(du ~/arch/*z | awk 

> {'print $1}'

) -gt 112233 ];then
```
should be
```
if [ $(du ~/arch/*z | awk 

> {'print $1'}

) -gt 112233 ];then
```

**Comment by Codimiracle** [comment]
knownconfigurations.sh
```
x86_64 ()
{
        # x86_64 downloads the latest file automatically.  $file is unnecessary for download.
        mirror=mirrors.evowise.com
        path=/archlinux/iso/latest/
        makesystem
}
```
but i need to rerun setupTermuxArch.sh(do not uninstall) using command as follows:
```
export file=archlinux-bootstrap-2018.02.01-x86_64.tar.gz
bash setupTermuxArch.sh

```
and then i install TermuxArch successfully.

**Comment by sdrausty** [comment]
Thanks for the update.  gen.v0.8 id447049456 is currently available for testing.  To access gen versions, activate line line 182 in setupTermuxArch.sh `dfl=/gen`.

**Comment by sdrausty** [comment]
Update; this gen version 086259509 requests testing. https://github.com/sdrausty/TermuxArch/commit/f977c17265004edfdcc6713481dfc4aae2cf80ea#diff-a8f27a760a6efd68e7e20b3deb5354df  Access is already updated via 182.

**Comment by Codimiracle** [comment]
necessaryfunctions.sh line 141
```
proot --link2symlink -O bsdtar -xpf $file --strip-components 1 
```
O is not zero.
should be
```
proot --link2symlink -0 bsdtar -xpf $file --strip-components 1 
```
take it easy!

**Comment by sdrausty** [comment]
Looks good for a stable candidate https://github.com/sdrausty/TermuxArch/commit/756c251447da5463f5ab1f546297b4e2d4329a5e#diff-a8f27a760a6efd68e7e20b3deb5354df  663274271

**Comment by sdrausty** [comment]
This stable release https://github.com/sdrausty/TermuxArch/commit/78156303b6fa9abcc5386f5b34396058e77387dd#diff-f38f8ed8605d40e475f567d0a126c647 id558937627 should resolve this thread.  Thank you for your time, interest and input @Codimiracle

**Comment by Codimiracle** [comment]
getimagefunctions.sh
Oh...
line 51 nmirror=$(grep Location gmirror | awk {'print $3       }   '     )
line 59 nmirror=$(grep Location gmirror | awk {'print $3       }   '     )

**Comment by Codimiracle** [comment]
id558937627 TEST:
```
🕠 < 🕛 Checking download integrity with md5sum.  This may take a little while.

archlinux-bootstrap-2018.02.01-x86_64.tar.gz: OK

 🕕 < 🕛 System image file download integrity: OK

 🕡 < 🕛 Uncompressing .  This will take a long time.  Be patient.
bsdtar: Error opening archive: Failed to open '--strip-components'
rm: can't remove '*.tar.gz.md5': No such file or directory

 🕙 < 🕛 Arch Linux in Termux is installed.  Answer the following questions to complete the Arch Linux configuration.

archsystemconfigs.sh: line 143: etc/motd: No such file or directory
archsystemconfigs.sh: line 170: etc/resolv.conf: No such file or directory
necessaryfunctions.sh: line 156: etc/locale.gen: No such file or directory
```

**Comment by sdrausty** [comment]
Thanks for the update.  The code had a logical error which https://github.com/sdrausty/TermuxArch/commit/481321becd26b792e6fd0e1690031889226f14c7 this commit resolves.  Does it resolve this matter too @Codimiracle?

**Comment by sdrausty** [comment]
These two https://github.com/sdrausty/TermuxArch/commit/1d97713b9e7cba49fe73ebb0a2a428e04b77c2cf and https://github.com/sdrausty/TermuxArch/commit/ff64863ba6e1f2feaeee3545ded9c2cd853bb269 commits should resolve this matter.  Thank you for your suggestions.

**Comment by sdrausty** [comment]
It looks like both `curl` and `wget` change the md5sum.txt file structure from http://mirrors.evowise.com/archlinux/iso/latest/md5sums.txt This is strange.  

From
```
9ef8f8df6134961966e38de4b9bd7174  archlinux-2018.02.01-x86_64.iso
2f3fab72a10e915e9394c6e6a7880255  archlinux-bootstrap-2018.02.01-x86_64.tar.gz
```
To
```
[10:54 ~ ]$ wget http://mirrors.evowise.com/archlinux/iso/latest/md5sums.txt
--2018-02-14 11:38:05--  http://mirrors.evowise.com/archlinux/iso/latest/md5sums.txt
Connecting to 192.168.0.6:5680... connected.
Proxy request sent, awaiting response... 200 OK
Length: 127 [text/plain]
Saving to: ‘md5sums.txt’

md5sums.txt          100%[=====================>]     127  --.-KB/s    in 0s

2018-02-14 11:38:07 (2.28 MB/s) - ‘md5sums.txt’ saved [127/127]

[11:38 ~ ]$ cat md5sums.txt
� �
  �{��A�����L0m��T�HQ��5��k�J�"������̹$Ha������9��Y c�����
                                                         f��䪯�����=�%Y�uȭ�}t��\C�y��?uه3�[11:38 ~ ]$
```

**Comment by Codimiracle** [comment]
thanks for update
i intall TermuxArch successfully.
but scripts running command `pacman -Syu` geting some errors(x86_64 only, it works in aarch64.).
I suggest running these two commands before the command
```
pacman-key --init
pacman-key --populate
```
error is:
```
warning: Public keyring not found; have you run 'pacman-key --init'?
downloading required keys...
error: key "EEEEE2EEEE2EEEEE" could not be looked up remotely
error: key "3C1C876030B65FE2" could not be looked up remotely
error: key "4A1AFC345EBE18F8" could not be looked up remotely
error: key "BBE43771487328A9" could not be looked up remotely
error: key "94657AB20F2A092B" could not be looked up remotely
error: key "FC1B547C8D8172C8" could not be looked up remotely
error: key "A6234074498E9CEE" could not be looked up remotely
error: key "426991CD8406FFF3" could not be looked up remotely
error: key "A5E9288C4FA415FA" could not be looked up remotely
error: key "6D1655C14CE1C13E" could not be looked up remotely
error: key "786C63F330D7CB92" could not be looked up remotely
error: required key missing from keyring
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
```
reason(maybe):
```
[03:03 home ]$ date
Thu Feb 15 03:03:23 UTC 2018
```
but real time is 
```
$ date
Thu Feb 15 11:05:03 CST 2018
```
and then.
another error is:
```
Generating locales...
/bin/locale-gen: line 33: sed: command not found
  .UTF-8/bin/locale-gen: line 35: sed: command not found
.../bin/locale-gen: line 38: sed: command not found
```

**Comment by sdrausty** [comment]
@codimiracle this https://github.com/sdrausty/TermuxArch/releases/tag/0.8.1 release addreses the issues discussed in this thread except for:
```
pacman-key --init
pacman-key --populate
```
See https://github.com/sdrausty/TermuxArch/issues/33 for further details about entropy.  Thank you for your time and information with diagnostics.  It appears that functionality for two important architectures is regained and that setupTermuxArch has more options thanks to this issue too.  

* Use `tzselect` to setup your local time zone.  
* After successfully updating a new system, `sed` should be available https://github.com/sdrausty/TermuxArch/blob/master/scripts/files/stable/v0.8.1.id502434699/archsystemconfigs.sh#L236&L240 in all architectures:
```
if [ $(getprop ro.product.cpu.abi) = x86 ] || [ $(getprop ro.product.cpu.abi) = x86_64 ];then
		pacman -Syu sed --noconfirm 
	else
		pacman -Syu --noconfirm 
	fi
```
Hence `locale-gen` should not have problems finding`sed`.  Update the system and install `sed` manually with `pacman -Syu sed`, then use `locale-gen` again.

**Comment by wulvyrn** [comment]
where in the script could this be added before it gets and install packages ?
rng-tools needs to be installed first
```
rngd -r /dev/urandom
```
then pacman-key --init etc should work.

**Comment by sdrausty** [comment]
@wulvyrn added with https://github.com/sdrausty/TermuxArch/commit/16517a8f6e4421e469c9475be5421219e4df137c this commit; Thank you for this solution  🎼🏄🐬💦

**Comment by sdrausty** [comment]
I got what appeared as success @wulvyrn at first, but now:
```
$ rngd -r /dev/urandom
unable to adjust write_wakeup_threshold: Permission denied
$ rngd
Unable to open file: /dev/tpm0
can't open any entropy source
Maybe RNG device modules are not loaded
```
What exactly is wrong with the random devices?  Is because they are devices?

**Comment by wulvyrn** [comment]
i don't know.  this rabbit hole seems pretty deep!  i'll do more digging as i cloned the repo and can test before throwing more dirt out the hole.

**Comment by wulvyrn** [comment]
dumb question:  i can't find where it is calling pacman -Syu to update all the packages before it fails.
would it be possible to put this before that command ?
```
pacman-key --init
pacman-key --autopopulate archlinux
```

**Comment by sdrausty** [comment]
>  cloned the repo and can test 

Are you familiar with the bloom option?  It is designed for testing script modifications locally on device.  First run `bash setupTermuxArch.sh --bloom`.  Modify TermuxArch components in `$HOME/TermuxArchBloom` as desired.  Then use `bash setupTermuxArch.sh --run` to run the entire script locally on device.  Good luck.

> is there a rng-tools package for termux? 

Thank you for opening https://github.com/termux/termux-packages/issues/2180.  Let's stay on topic with these issues.  `pacman-key --populate archlinux hangs` https://github.com/sdrausty/TermuxArch/issues/33 is now reopened seeking resolution.  Thank you @wulvyrn et al

**Comment by wulvyrn** [comment]
i found those option buried in some of the comments of other issues.  i must have missed them on the webpages somehow.

**Comment by sdrausty** [comment]
@wulvyrn options bloom, run and rootdir have been in the making for months.  All three are recent commits that appeared just a little while ago.  They are not fully implemented.  Comments in the code for all options are upcoming.  Most are already listed in `bash setupTermuxArch.sh --help`.

> missed them on the webpages somehow.

The webpages want better documentation.  Pull requests welcome at https://github.com/sdrausty/docsTermuxArch/pulls regarding documentation. Suggestions welcome as well.

**Comment by sdrausty** [comment]
Comments to the [options section](https://github.com/sdrausty/TermuxArch/blob/master/setupTermuxArch.sh#L546&L599) in [`setupTermuxArch.sh`](https://raw.githubusercontent.com/sdrausty/TermuxArch/master/setupTermuxArch.sh) are now present with this https://github.com/sdrausty/TermuxArch/commit/4cf83155058e8422622f08d3fe5e93bcbc6c1866 commit.  This will assist current and future users and developers alike.  Thanks for sharing your thoughts about usage @wulvyrn

**Comment by sdrausty** [comment]
Issue https://github.com/termux/proot/issues/10, "`pacman -S archlinux-keyring` Hangs in Arch Linux Termux PRoot" is now open regarding `pacman-key` hangs.

**Comment by sdrausty** [comment]
Upstream has resolved this issue https://github.com/termux/proot/issues/10#issuecomment-370161621 after working on this topic afaict, @michalbednarski has found:
```
pacman-key --init
echo disable-scdaemon > /etc/pacman.d/gnupg/gpg-agent.conf
pacman-key --populate
```
Use this code to resolve `pacman-key --populate archlinux` issues with Arch Linux in Termux PRoot.  Before using `pacman-key --populate archlinux`,  run `pacman -S archlinux-keyring` first.  

Arch x86 and x86_64 results are requested, arm results as well pertaining to `finishsetup.sh` and `pacman-key`.  If a post setup autoconfiguration with update script is deemed wanted for `setupTermuxArch.sh` regarding `pacman-key`, this can be done on a per architecture basis.

**Comment by khairiGuiri123** [comment]
![Screenshot_20190726_085114_com termux](https://user-images.githubusercontent.com/35901818/61935526-9ad88080-af82-11e9-8ec4-f8b9acc6d13e.jpg)
are you here pleze help me

**Comment by SDRausty** [comment]
@khairiGuiri123 try again.  If it doesn't work try the following:
![Screenshot_20190726-110727](https://user-images.githubusercontent.com/27742457/61961669-dcbef200-af95-11e9-95ce-bc0c233d46f2.png)
