### ISSUE TITLE
every mirror returning 404

### ISSUE THREAD

**Issue by AccountsDept** [sdrausty/TermuxArch#49]
![image](https://user-images.githubusercontent.com/34864881/36347220-cafc661e-141f-11e8-9c0c-e7bd87f04b3d.png)

Not sure why this is happening. I enabled a whole bunch of mirrors, and it's clear something is wrong with the internet connection during the install. Help?

**Comment by sdrausty** [comment]
@AccountsDept You are only supposed to enable one mirror that is the closest to you geographically.  Choose a nearby mirror and use only one.

**Comment by AccountsDept** [comment]
i'll try it again when i get home, but that's exactly what i did the first time and it still threw a 404

**Comment by sdrausty** [comment]
See if you can access the mirror manually using a web browser to confirm the 404.

**Comment by sdrausty** [comment]
Most mirrors are working fine.  See `bash setupTermuxArch.sh --help` for more information.  

>  enable one mirror that is the closest to you geographically. Choose a nearby mirror and use only one.
