### ISSUE TITLE
Error Please Help me

### ISSUE THREAD

**Issue by mjskoneg** [sdrausty/TermuxArch#5]
[root@localhost home]# pacman -Syu
:: Synchronizing package databases...
error: failed retrieving file 'core.db' from mirror.archlinuxarm.org : Could not resolve host: mirror.archlinuxarm.org
error: failed to update core (download library error)
error: failed retrieving file 'extra.db' from mirror.archlinuxarm.org : Could not resolve host: mirror.archlinuxarm.org
error: failed to update extra (download library error)
error: failed retrieving file 'community.db' from mirror.archlinuxarm.org : Could not resolve host: mirror.archlinuxarm.org
error: failed to update community (download library error)
error: failed retrieving file 'alarm.db' from mirror.archlinuxarm.org : Could not resolve host: mirror.archlinuxarm.org
error: failed to update alarm (download library error)
error: failed retrieving file 'aur.db' from mirror.archlinuxarm.org : Could not resolve host: mirror.archlinuxarm.org
error: failed to update aur (download library error)
error: failed to synchronize any databases
error: failed to init transaction (download library error)
[root@localhost home]#

**Comment by sdrausty** [comment]
+mjskoneg thanks for your time. Your input is very helpful.  Please adjust your `/etc/pacman.d/mirrorlist` file according 🌎 to your geographic location. Also, how do websites render in text-based browsers from Arch Linux on Termux?

![screenshot_20171015-161003](https://user-images.githubusercontent.com/27742457/31588670-7b1665a0-b1c3-11e7-99e0-bee76b50388f.png)

**Comment by Soph1a7** [comment]
@mjskoneg I solved that issue by creating a resolv.conf file on /etc with the following configuration:
```
nameserver 8.8.8.8
nameserver 8.8.4.4
```
it should work afterwards.

**Comment by sdrausty** [comment]
Thanks for your time and consideration. It was very helpful in modifying [setupTermuxArch.sh](https://raw.githubusercontent.com/sdrausty/TermuxArch/master/setupTermuxArch.sh) accordingly.
