### ISSUE TITLE
Sudo not working 

### ISSUE THREAD

**Issue by thomasswan5547** [sdrausty/TermuxArch#50]
Hi there,  i just installed TermuxArch, and i've noticed that the Sudo command doesn't work, when i ran it, i got this error... 

`sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: unable to load /usr/lib/sudo/sudoers.so: /usr/lib/sudo/sudoers.so: cannot stat shared object: Bad file descriptor`    
                        
`sudo: fatal error, unable to load plugins`

I'm not really sure whats causing the issue, Any help would be great, if you need anymore information just ask, Thanks :)

**Comment by sdrausty** [comment]
resolved: https://github.com/sdrausty/TermuxArch/commit/a0db0f130b3effba7eaa2dbe8061eaca2eab1058

**Comment by SDRausty** [comment]
This https://github.com/TermuxArch/TermuxArch/commit/161eaba60cedcd687f7d6282d5ee1a2a292e902d commit automates adding sudo users.

```
printf "%s\\n" "\$1 ALL=(ALL) ALL" >> /etc/sudoers
sed -i "s/\$1:x/\$1:/g" /etc/passwd
```
