### ISSUE TITLE
Everthing gone well accept for these 3 errors

### ISSUE THREAD

**Issue by barre121** [sdrausty/TermuxArch#51]
Are these fatal errors or just minor ones.
How do solve them?
I need step by step guide  to solve these three errors since i am a newbie
I don't know but it seems arch is up and working.
i don't even know how termuxarch works lool.
These are the errors i encountered along the way.

1....  warning: could not get file information for boot/Image
2...  warning: could not get file information for usr/lib/modules/4.15.1-1-ARCH/build/vmlinux
...................
......................
3.... ==> ERROR: /dev must be mounted!
error: command failed to execute correctly.
.........
....................
Here it is.
......
like to run `locale-gen` to generate the en_US.UTF-8 locale, or would you like to edit `/etc/locale.gen` specifying your preferred language(s) before running `locale-gen`?  Answer run or edit [R|e]. run
:: Synchronizing package databases...
 core                     186.9 KiB   112K/s 00:02 100%
 extra                      2.3 MiB   141K/s 00:16 100%
 community                  4.0 MiB   154K/s 00:26 100%
 alarm                     46.5 KiB  73.8K/s 00:01 100%
 aur is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (24) bash-4.4.019-1  bzip2-1.0.6-7
              dbus-1.12.4-1  dhcpcd-7.0.1-1
              e2fsprogs-1.43.9-1  gnutls-3.5.18-1
              iana-etc-20180205-1  iptables-1.6.2-2
              less-530-1  libnghttp2-1.30.0-1
              libsystemd-237.64-1  libtirpc-1.0.2-3
              linux-aarch64-4.15.6-1  lz4-1:1.8.1.2-1
              man-db-2.8.1-1  man-pages-4.15-1
              mpfr-4.0.1-1  ncurses-6.1-3
              net-tools-1.60.20180212git-1
              pcre2-10.31-1  procps-ng-3.3.12-3
              s-nail-14.9.7-1  systemd-237.64-1
              systemd-sysvcompat-237.64-1

Total Download Size:    78.44 MiB
Total Installed Size:  167.49 MiB
Net Upgrade Size:        3.99 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
 iana-etc-20180205-1-any  361.9 KiB   142K/s 00:03 100%
 ncurses-6.1-3-aarch64   1089.4 KiB   167K/s 00:07 100%
 bash-4.4.019-1-aarch64  1394.6 KiB   149K/s 00:09 100%
 bzip2-1.0.6-7-aarch64     49.9 KiB  83.2K/s 00:01 100%
 lz4-1:1.8.1.2-1-aarch64   75.1 KiB  32.2K/s 00:02 100%
 libsystemd-237.64-1...   312.3 KiB   124K/s 00:03 100%
 dbus-1.12.4-1-aarch64    266.6 KiB   162K/s 00:02 100%
 iptables-1.6.2-2-aa...   304.0 KiB   145K/s 00:02 100%
 pcre2-10.31-1-aarch64    882.2 KiB   197K/s 00:04 100%
 e2fsprogs-1.43.9-1-...   949.0 KiB   209K/s 00:05 100%
 libtirpc-1.0.2-3-aa...   168.2 KiB  87.2K/s 00:02 100%
 systemd-237.64-1-aa...     4.0 MiB   198K/s 00:21 100%
 dhcpcd-7.0.1-1-aarch64   147.1 KiB   144K/s 00:01 100%
 gnutls-3.5.18-1-aarch64    2.2 MiB   179K/s 00:12 100%
 less-530-1-aarch64        91.2 KiB   134K/s 00:01 100%
 libnghttp2-1.30.0-1...    77.8 KiB   210K/s 00:00 100%
 mpfr-4.0.1-1-aarch64     283.3 KiB   211K/s 00:01 100%
 linux-aarch64-4.15....    58.5 MiB   192K/s 05:12 100%
 man-db-2.8.1-1-aarch64   873.2 KiB   155K/s 00:06 100%
 man-pages-4.15-1-any       5.7 MiB   184K/s 00:32 100%
 net-tools-1.60.2018...   120.2 KiB  94.7K/s 00:01 100%
 procps-ng-3.3.12-3-...   291.1 KiB   140K/s 00:02 100%
 s-nail-14.9.7-1-aarch64  427.1 KiB   166K/s 00:03 100%
 systemd-sysvcompat-...     6.7 KiB  0.00B/s 00:00 100%
(24/24) checking keys in keyring                   100%
(24/24) checking package integrity                 100%
(24/24) loading package files                      100%
(24/24) checking for file conflicts                100%
(24/24) checking available disk space              100%
warning: could not get file information for boot/Image
warning: could not get file information for usr/lib/modules/4.15.1-1-ARCH/build/vmlinux
:: Processing package changes...
( 1/24) upgrading iana-etc                         100%
( 2/24) upgrading ncurses                          100%
( 3/24) upgrading bash                             100%
( 4/24) upgrading bzip2                            100%
( 5/24) upgrading lz4                              100%
( 6/24) upgrading libsystemd                       100%
( 7/24) upgrading dbus                             100%
( 8/24) upgrading iptables                         100%
( 9/24) installing pcre2                           100%
(10/24) upgrading e2fsprogs                        100%
(11/24) upgrading libtirpc                         100%
(12/24) upgrading systemd                          100%
(13/24) upgrading dhcpcd                           100%
(14/24) upgrading gnutls                           100%
(15/24) upgrading less                             100%
(16/24) upgrading libnghttp2                       100%
(17/24) upgrading mpfr                             100%
(18/24) upgrading linux-aarch64                    100%
>>> Updating module dependencies. Please wait ...
(19/24) upgrading man-db                           100%
(20/24) upgrading man-pages                        100%
(21/24) upgrading net-tools                        100%
(22/24) upgrading procps-ng                        100%
(23/24) upgrading s-nail                           100%
(24/24) upgrading systemd-sysvcompat               100%
:: Running post-transaction hooks...
(1/6) Updating linux-aarch64 initcpios
==> ERROR: /dev must be mounted!
error: command failed to execute correctly
(2/6) Updating udev hardware database...
(3/6) Updating system user accounts...
(4/6) Creating temporary files...
(5/6) Arming ConditionNeedsUpdate...
(6/6) Updating the info directory file...
Generating locales...
  en_US.UTF-8... done
Generation complete.

Help me plese!
Bad english, sorry!

**Comment by sdrausty** [comment]
@barre121 provide information using `bash setupTermuxArch.sh --sysinfo` to help this project grow.

> Help me plese!

These pages https://duckduckgo.com/?q=warning+error+exemption+difference+stdout+site%3Atldp.org have information about warnings.  

>  or just minor ones.

How is Arch Linux working on your device?  Are you impressed?

**Comment by barre121** [comment]
Working great!

It looks i am impressed!

I really don't know it's specs and how it's different from other distros, like i told you, i am some kinda what they call "newbie". I will keep using it and learning more about it, though.

can get some link to it's docs?
I wanna learn more.

Thanks for everything.

**Comment by barre121** [comment]
I forgot to tell you that 
I removed the file....

....setupTermuxArch.sh

Sorry!
 
Should i download it again and do that?

**Comment by sdrausty** [comment]
> Working great!

You are welcome @barre121
