### ISSUE TITLE
seriously

### ISSUE THREAD

**Issue by lukeeey** [sdrausty/TermuxArch#52]
it really pisses me off how whenever someone asks for a package in termux you just direct them here to your own project. why dont you actually try and contribute to termux?

**Comment by sdrausty** [comment]
@lukeeey seriously, would you prefer Termux users not to know what is available on device?  

>  why dont you actually try and contribute to termux?

What is this project then @lukeeey?  Can you use it outside Termux?  How about these other projects to name a few:
* https://github.com/sdrausty/au
* https://github.com/sdrausty/buildAPKs
* https://github.com/sdrausty/TermuxPovray

These were open issues at Termux for a very long time.  Technically, now they are resolved.  A thank you might have been appropriate…

> really pisses me off 

**The only one that can control your emotions is you yourself.**  See if a better diet can help you in this endeavor.  It's more than a one day afair.  **Good food + excercise = a healthy emotionally stable mind.**  Do you drink soda pop and eat candy, chips and fast food @lukeeey?

**Comment by sdrausty** [comment]
@lukeeey you had enough energy to vent your emotions; Do you have enough energy to reply?

**Comment by lukeeey** [comment]
Imagine this as a game server: if i am making plugins for it, am i contributing to the software? No. I am simply providing an alternative, unoffical way of doing things, when it could be implemented in the software itself. (For example, a Minecraft server software which did not have entity AI and i made a plugin to implement it - i could have made a PR to the software so everyone gets to enjoy it because they might not knkw about my plugin (or TermuxArch) and therefore might give up on Termux for not having the features they want)

**Comment by sdrausty** [comment]
> could have made a PR 

I wish I were better at PRs.  Hopefully, I will find the time and gain the knowledge to submit successful PRs directly to Termux as suggested.  At present we must settle with what we have and know.

**Comment by sdrausty** [comment]
> could have made a PR 

I wish I were better at PRs.  Hopefully, I will find the time and gain the knowledge to submit successful PRs directly to Termux as suggested.  At present we must settle with what we have and know.

>  not having the features 

This is why TermuxArch was created.  Think of it as a work around until we have these features directly in Termux.  Also the fact that many things now do work device, as opposed to not working on device just a few months ago should accelerate Termux package development too.

Screenshot from an Android smartphone.
[![screenshot_20180413-172406](https://user-images.githubusercontent.com/27742457/38758637-ec0ff0dc-3f3f-11e8-802c-82bc511cde88.png)](https://github.com/sdrausty/TermuxArch/issues/59)
