### ISSUE TITLE
Can't install TermuxArch

### ISSUE THREAD

**Issue by Adalrikus** [sdrausty/TermuxArch#53]
It gives me this error during installation:
TermuxArch download: OK

 🕛 > 🕜 TermuxArch v1.1 integrity: OK

 🕛 > 🕝 Detected aarch64 Android operating system.

 🕛 > 🕒 Activating termux-wake-lock: CANNOT LINK EXECUTABLE "/system/bin/app_process": cannot locate symbol "__xlog_buf_printf" referenced by "/system/lib64/libdpframework.so"...
Aborterd
I guess this is due to the fact that I have android 7. A similar error occured when I ran tsu.

**Comment by sdrausty** [comment]
Open an issue at https://github.com/termux/termux-app/search?q=termux-wake-lock&type=Issues  This is possibly an error with `termux-wake-lock`, or something else, not in `setupTermuxArch.sh`.  Probably, it is an error with the device being rooted, not Android 7, from the information you provided.  Use `setupTermuxArch.sh --sysinfo` to provide additional information about your device.

**Comment by cherryleafroad** [comment]
I have nougat, and TermuxArch installed perfectly.
