### ISSUE TITLE
WebKit Browsers Showing Nothing instead of Web Content

### ISSUE THREAD

**Issue by jansenmtan** [SDRausty/TermuxArch#55]
I have installed Arch Linux and LXDE successfully, and they run pretty well (nothing short of amazing).

However, WebKit browsers, although drawing the UI, are not displaying websites.
When I run them on the terminal, they output hundreds of errors that look like  `Failed to create shared memory file /WK2SharedMemory.##########: Permission denied`
Apparently, the issue comes from /dev/shm (or its nonexistence) : https://bugzilla.redhat.com/show_bug.cgi?id=1347436

So far, I've been using NetSurf, which works.

**Comment by sdrausty** [comment]
> they run pretty well (nothing short of amazing).

Thank you for your praise.  Countless hours and iterations have created what we praise.  This is an upstream issue.  Which upstream, I am not sure.  The more upstream knows about it, the faster it may be solved.

**Comment by sdrausty** [comment]
This https://github.com/sdrausty/TermuxArch/commit/f16c27d4336ff6e38e1338e7846adc8843b9c0fc commit adds Arch Linux IRC channel upstream contact information to the TermuxArch motd and logout.  
> See https://wiki.archlinux.org/index.php/IRC_channel for available Arch Linux IRC channels.

**Comment by robsmith11** [comment]
Has this issue been identified or reported anywhere upstream?
I believe Firefox experiences a similar problem.

**Comment by sdrausty** [comment]
@robsmith11 if you believe that TermuxArch can influence shmem in some way, please enlighten us.  I see nothing that a BASH script working within the confines of Android can do for shmem and similar issues.  If I am mistaken, this issue can be reopened at anytime.
> Has this issue been identified or reported anywhere upstream?

If it has not been reported yet, hopefully it will be reported upstream soon.  This is why upstream links are posted throughout this website.

**Comment by robsmith11** [comment]
@sdrausty Well shmem system calls can be fixed by using LD_PRELOAD with an ashmem wrapper like this:
https://github.com/pelya/android-shmem

As for programs that want to write to /dev/shm, the easiest way to get them working would be to just create an empty, writeable directory there, but that might not be so great for performance.  I'm not sure if there's an easy way to get it pointing to a tmpfs filesystem without root.  Is there any writeable tmpfs in android?  A symlink could point to there if so.

**Comment by sdrausty** [comment]
@robsmith11 
> fixed by using LD_PRELOAD

```
$ egrep LD_PRELOAD *
archsystemconfigs.sh:   unset LD_PRELOAD
archsystemconfigs.sh:   unset LD_PRELOAD
archsystemconfigs.sh:   unset LD_PRELOAD
necessaryfunctions.sh:  unset LD_PRELOAD
necessaryfunctions.sh:  unset LD_PRELOAD
```

There doesn't seem to be any place more that this can be used in TermuxArch as far as I know.  
>  an ashmem wrapper like this:
https://github.com/pelya/android-shmem

TermuxArch is a BASH shell script.  Your example is written in C.  
> write to /dev/shm

/dev is mounted from Android along with the permissions.  **If the apps we are discussing could use shared memory as an option, there would be no issues.** 

> How can I change the cache folder (to tmpfs)?
On Linux and BSD, you can set XDG_CACHE_HOME for all applications, or just Midori. Midori saves icons and cache files in that location. The default is ~/.cache.

> export XDG_CACHE_HOME=/dev/shm

*From http://midori-browser.org/faqs/*


##### Here are some links where repeating the shm topic should be worth the effort and time:
https://github.com/eustasy/midori-browser.org/issues
https://github.com/archlinuxarm 
https://github.com/ArchStrike/ArchStrike 
https://wiki.archlinux.org/index.php/IRC_channel
Email : termux+subscribe@groups.io
Github : https://github.com/termux/
Gitter : https://gitter.im/termux/termux
Termux Community : https://plus.google.com/communities/101692629528551299417

**Comment by sdrausty** [comment]
This https://github.com/termux/libandroid-shmem repository may give us the functionality we are seeking in this issue and these ones:

1) https://github.com/sdrausty/termux-archlinux/issues/4
1) https://github.com/sdrausty/TermuxArch/issues/38
4) https://github.com/sdrausty/TermuxArch/issues/68

**Comment by sdrausty** [comment]
@robsmith11 To access libandroid-shmem support in TermuxArch use `setupTermuxArch.sb r` for a quick system refresh; libandroid-shmem support is added with this https://github.com/sdrausty/TermuxArch/commit/a25067274c341b73d1fc79b85eabbbbdf33680eb commit.

**Comment by sudomain** [comment]
This was broken for a while but Firefox appears normally now

![Screenshot_2020-04-29-17-41-14](https://user-images.githubusercontent.com/30786326/80650129-6332c380-8a41-11ea-8fa3-b097e3a1c15c.png)

**Comment by SDRausty** [comment]
> This was broken for a while but Firefox appears normally now

Good news;  Thank you for sharing @sudomain

**Comment by SDRausty** [comment]
This commit https://github.com/SDRausty/TermuxArch/commit/a2e8c54b130b2c5d1cdf1e6b01856022cd1db98b @jansenmtan and upstream may have resolved your issuu.  You are welcome to comment here.
