### ISSUE TITLE
TimeZone selection in setup doesn't effective.

### ISSUE THREAD

**Issue by xqdoo00o** [sdrausty/TermuxArch#56]
After I select asia time in the install setup, it seems not effective when I `startarch`. 
or I have to `cp` the code which setup shows    manually to modify TZ?

**Comment by sdrausty** [comment]
The output code from `tzselect`  should be added to `.bash_profile` so the time is set correctly for future sessions.

**Comment by xqdoo00o** [comment]
OK, I would like to `cp /usr/share/zoneinfo/**/** /etc/localtime` directly.

**Comment by sdrausty** [comment]
It would be great to simply copy this value from Android into Arch.
