### ISSUE TITLE
Replace `vi` with `vim`.

### ISSUE THREAD

**Issue by xqdoo00o** [sdrausty/TermuxArch#57]
Consider that most Linux distro use `vim` instead of `vi`. and each debian-based distro use symbol link `vi` => `vim`

**Comment by sdrausty** [comment]
If the user's interface shows `Answer nano or vi [n|V]?` this means that the only editor installed is `busybox` which provides `vi`.  Function editors in [setupTermuxArch.sh](https://raw.githubusercontent.com/sdrausty/TermuxArch/master/scripts/files/stable/setupTermuxArch.sh) checks from all available editors in Termux to see if any are installed and chooses the first available editor from this array `aeds=("zile" "nano" "nvim" "vi" "emacs" "joe" "jupp" "micro" "ne" "applets/vi")`.

Function edqaquestion can be reimplemented to ask the user to install an editor of choice.  String construction for cedst wants refinement before this can be implemented.  **The prerequisites part should be as lean as possible for fastest install.**  `vi` along with the other editors can be added as a user interactive question once cedst constructs properly.  The intended construct is, "Editors x, y and z are present.  Choose one or install one."  String construction wants the word 'and' to be added to cedst when two or more editors are present.  

Help is also wanted in editor instructions.  Function editfiles in [necessaryfunctions.sh](https://raw.githubusercontent.com/sdrausty/TermuxArch/master/scripts/files/stable/necessaryfunctions.sh) edits and inserts new user TermuxArch instructions into the locale.gen and mirrorlist files.  At present editfiles adds:
```
# # # # # # # # # # # # # # # # # # # # # # # # #
# TermuxArch vi instructions:   CTR+r is redo.
# Use the hjkl keys to navigate. <h down j up k l>
# Numbers are multipliers.  The u is undelete/undo.
# 17j then i opens edit mode for the Geo-IP mirror.
# Enter the # hash/num/pounds symbol to comment it out:
# Server = http://mirror.archlinuxarm.org/$arch/$repo.
# Long tap KEYBOARD in the side pane to see ESC, CTR...
# Tap ESC to return to command mode in vi.
# CTRL+d and CTRL+b to find your local mirror.
# / for search, N and n for next match.
# Tap x to delete # to uncomment your local mirror.
# Choose only one mirror.  Use :x to save your work.
# Comment out the Geo-IP mirror end G   top gg
# # # # # # # # # # # # # # # # # # # # # # # # # # #
```
These instructions are added to mirrorlist when `vi` is used.  New user instructions for nvim and vim are also present when these one of these editors is chosen.  When any of the remaining editors are empolyed, instructions are lacking.  Post new user instructions for the other editors you know how to use from this array, `aeds=("zile" "nano" "nvim" "vi" "emacs" "joe" "jupp" "micro" "ne" "applets/vi")`.

For this enchancment to happen string construction wants refinement appears to be a prerequisite.
