### ISSUE TITLE
Hush motd on login when using -c command

### ISSUE THREAD

**Issue by cherryleafroad** [sdrausty/TermuxArch#58]
It would be best to ignore the displaying of motd when (and only when) using the -c command.

I believe this can be best accomplished by modifying the .bashrc `. /etc/motd` to the following. This disables motd if we have a .hushlogin (this one is for the user to make if they want to permanently disable it) or .chushlogin file. The .chushlogin is only temporarily used to hush the motd when we run commands from startarch (it's removed after)
```
if [ ! -e ~/.hushlogin ] && [ ! -e ~/.chushlogin ]; then
    . /etc/motd
fi
if [ -e ~/.chushlogin ]; then
    rm ~/.chushlogin
fi
```

And in the startarch script, when using -c, simply create the temporary file first
```
touch $HOME/arch/root/.chushlogin
exec proot ...
```

This is the best solution I found to this question. Hopefully it's elegant enough haha

**Comment by sdrausty** [comment]
@cherryleafroad the feature you requested is implemented.  Test and see if it is to your liking.  Thanks for sharing and improving this project.  Do not hesitate if you still see room for improvement :drum: :loud_sound:

**Comment by cherryleafroad** [comment]
Works perfect, just one thing.

Regarding this code in `startarch`:
```
if [[ $1 = [Cc]* ]] || [[ $1 = -[Cc]* ]] || [[ $1 = --[Cc]* ]];then
touch /data/data/com.termux/files/home/arch/root/.chushlogin
exec proot --kill-on-exit --link2symlink -0 -r /data/data/com.termux/files/home/arch -b /dev/ -b $ANDROID_DATA -b $EXTERNAL_STORAGE -b /proc/ -w "$PWD" /bin/env -i HOME=/root TERM=$TERM /bin/bash -lc "${@:2}"
rm /data/data/com.termux/files/home/arch/root/.chushlogin
```

These commands shouldn't be there after the `exec proot`. Because `exec` replaces the entire shell, no commands will be run after it, so the `rm` commands will never get run (and will give us false security in the future too). That's why we had to implement the `rm` inside `.nashrc`
`rm /data/data/com.termux/files/home/arch/root/.chushlogin`

**Comment by cherryleafroad** [comment]
And one more important note, in the user login section, you left it touching the root users home directory instead of the user the person is trying to login to, which means that `. /etc/motd` will still get run. And it's likely that the person wanted to use a different user than root if they're using the login command. You'll need to somehow extract the current user from the command given, then touch it inside the users home directory.

```
elif [[ $1 = [Ll]* ]] || [[ $1 = -[Ll]* ]] || [[ $1 = --[Ll]* ]] ;then
# extract user from command here
touch /data/data/com.termux/files/home/arch/$user/.chushlogin
```

**Comment by cherryleafroad** [comment]
And one more important note, in the user login section, you left it touching the root users home directory instead of the user the person is trying to login to, which means that `. /etc/motd` will still get run. And it's likely that the person wanted to use a different user than root if they're using the login command. You'll need to somehow extract the current user from the command given, then touch it inside the users home directory.

```
elif [[ $1 = [Ll]* ]] || [[ $1 = -[Ll]* ]] || [[ $1 = --[Ll]* ]] ;then
# extract user from command here
touch /data/data/com.termux/files/home/arch/$user/.chushlogin
```
