### ISSUE TITLE
Declare error: value too great for base (error token is: 08)

### ISSUE THREAD

**Issue by Kitsumi** [sdrausty/TermuxArch#60]
On line 91, I get an error, see title.
Used the master branch today, on termux.
Ran the setup-storage script and everything.

**Comment by greenfork** [comment]
I have the same issue with error token "09":

...
TermuxArch v1.3 integrity: OK
necessaryfunctions.sh: line 91: declare: 09: value too great for base (error token is "09")

I run termux on SM-G800H with Android v6.0.1

**Comment by sdrausty** [comment]
> necessaryfunctions.sh: line 91: declare: 09: value too great for base (error token is "09")

Commit https://github.com/sdrausty/TermuxArch/commit/ba1585ff9a8276620355a9c9756a8e76d04c312a has resolved this error.  Suprisingly it is unreproducable on any of the devices devoted to TermuxArch testing at my disposal.  Can you post `bash setupTermuxArch.sh sysinfo` output here please?  I am curious why, and the system information you provide may answer this question @Kitsumi @greenfork

**Comment by greenfork** [comment]
Sure

`termux-info` results:

Updatable packages:
All packages up to date
System information:
Linux localhost 3.4.0-9750041 #1 SMP PREEMPT Wed Nov 9 14:29:44 KST 2016 armv7l Android
Termux-packages arch:
arm
Android version:
6.0.1
Device manufacturer:
samsung
Device model:
SM-G800H

Disk report 3.8G on /data Sat Mar 17 03:51:14 MSK 2018

BASH_VERSINFO[0] = 4
BASH_VERSINFO[1] = 4
BASH_VERSINFO[2] = 19
BASH_VERSINFO[3] = 1
BASH_VERSINFO[4] = release
BASH_VERSINFO[5] = arm-unknown-linux-androideabi

cat /proc/cpuinfo results:

Processor       : ARMv7 Processor rev 3 (v7l)
processor       : 0
BogoMIPS        : 38.40

processor       : 1
BogoMIPS        : 38.40

processor       : 2
BogoMIPS        : 38.40

processor       : 3
BogoMIPS        : 38.40

Features        : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xc07
CPU revision    : 3

Hardware        : Qualcomm MSM8228
Revision        : 0004
Serial          : 00000000116fe8cf

dpkg --print-architecture result:

arm

getprop ro.product.cpu.abi result:

armeabi-v7a

getprop ro.product.device result:

kmini3g

Download directory information results.

/sdcard/Download exists
/storage/emulated/0/Download exists

du -hs /data/data/com.termux/files/home/arch results:


ls -al /data/data/com.termux/files/home/arch results:


uname -a results:

Linux localhost 3.4.0-9750041 #1 SMP PREEMPT Wed Nov 9 14:29:44 KST 2016 armv7l Android

End `setupTermuxArchDebug7867.log` debug information.

**Comment by Kitsumi** [comment]
```
$bash setupTermuxArch.sh sysinfo
 🕛 > 🕛 setupTermuxArch v1.3 will create a system information file.  Ensure background data is not restricted.  Run bash setupTermuxArch.sh help for additional information.  Check the wireless connection if you do not see one o'clock 🕐 below.  Checking prerequisites…

 🕛 > 🕧 Prerequisites: OK  Downloading TermuxArch…

      setupT   0%       0  --.-KB/s              setupTermuxA 100%     153  --.-KB/s    in 0s
      setupT   0%       0  --.-KB/s              setupTermuxA 100%  17.33K  --.-KB/s    in 0.04s

 🕛 > 🕐 TermuxArch download: OK

 🕛 > 🕜 TermuxArch v1.3 integrity: OK

Begin setupTermuxArch debug information.

`termux-info` results:

Updatable packages:
All packages up to date
System information:
Linux localhost 3.4.0-8025411 #1 SMP PREEMPT Thu Dec 7 18:35:47 KST 2017 armv7l Android
Termux-packages arch:
arm
Android version:
6.0.1
Device manufacturer:
samsung
Device model:
SM-G900V

Disk report 3.8G on /data Fri Mar 16 19:07:03 MDT 2018

BASH_VERSINFO[0] = 4
BASH_VERSINFO[1] = 4
BASH_VERSINFO[2] = 19
BASH_VERSINFO[3] = 1
BASH_VERSINFO[4] = release
BASH_VERSINFO[5] = arm-unknown-linux-androideabi

cat /proc/cpuinfo results:

Processor       : ARMv7 Processor rev 1 (v7l)
processor       : 0
BogoMIPS        : 38.40

processor       : 1
BogoMIPS        : 38.40

processor       : 2
BogoMIPS        : 38.40

processor       : 3
BogoMIPS        : 38.40

Features        : swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt
CPU implementer : 0x51
CPU architecture: 7
CPU variant     : 0x2
CPU part        : 0x06f
CPU revision    : 1

Hardware        : Qualcomm MSM8974PRO-AC
Revision        : 000e
Serial          : 000021db00000ace

dpkg --print-architecture result:

arm

getprop ro.product.cpu.abi result:

armeabi-v7a

getprop ro.product.device result:

kltevzw

Download directory information results.

lrwxrwxrwx    1 u0_a247  u0_a247         28 Mar 15 17:55 /data/data/com.termux/files/home/storage/downloads -> /storage/emulated/0/Download
/sdcard/Download exists
/storage/emulated/0/Download exists

du -hs /data/data/com.termux/files/home/arch results:


ls -al /data/data/com.termux/files/home/arch results:


uname -a results:

Linux localhost 3.4.0-8025411 #1 SMP PREEMPT Thu Dec 7 18:35:47 KST 2017 armv7l Android

End `setupTermuxArchDebug8820.log` debug information.

Post this information along with information regarding your issue at https://github.com/sdrausty/TermuxArch/issues.  Include information about input and output.  This debugging information is found in /data/data/com.termux/files/home/storage/arch/setupTermuxArchDebug8820.log.  If you think screenshots will help in resolving this matter better, include them in your post as well.

Submit this information if you plan to open up an issue at https://github.com/sdrausty/TermuxArch/issues to improve this installation script along with a screenshot of your topic.  Include information about input and output.

Thank you for using setupTermuxArch.sh v1.3 🏁
```

**Comment by greenfork** [comment]
Now everything works fine!

**Comment by sdrausty** [comment]
The reason this error was only coming up on certain devices had to do with $MINOR_REVISION -eq 0.  When [`declare -- MINOR_REVISION=$(echo ${tmp:0:3} |sed 's/[^0-9]*//g')`](https://github.com/sdrausty/TermuxArch/blob/master/necessaryfunctions.sh#L84&&L105) was declared an integer and it did actually equal zero, that is when the error occurred.  Thank you for helping out @Kitsumi and @greenfork in developing TermuxArch and the Linux experience in our the palm of our hand with Termux PRoot :sunflower: :musical_score: :musical_score:
