### ISSUE TITLE
Error running script.

### ISSUE THREAD

**Issue by Jezwin** [sdrausty/TermuxArch#66]
![screenshot_20180330-175025](https://user-images.githubusercontent.com/16209021/38137553-eb8cea82-3442-11e8-98bd-34be77650511.png)
![screenshot_20180330-175028](https://user-images.githubusercontent.com/16209021/38137561-f6351478-3442-11e8-83a8-470aca9ea0e4.png)

**Comment by sdrausty** [comment]
Closed https://github.com/sdrausty/TermuxArch/commit/88ac6b5c88fecef07c2bc6eadacce64463c3b229 with this commit.
