### ISSUE TITLE
Chromium, Firefox, Epiphany, Libreoffice, localectl, timedatectl...

### ISSUE THREAD

**Issue by pantumaca** [SDRausty/TermuxArch#68]
I am having problems with:
 
- Chromium -> SUID is present but not configured. Check /chromium.conf (it seems ok)
- Firefox -> Black screen with any web
- Epiphany -> White screen with any web
- Libreoffice -> prod is not mounted
- Localectl and timedatectl -> command not found

Anybody can work with those app/commands?

Thanks!

**Comment by sdrausty** [comment]
The Firefox issue has progressed a little bit:
[![screenshot_20180514-192546](https://user-images.githubusercontent.com/27742457/40029184-194e4402-57b1-11e8-850f-a8d105705901.png)](https://github.com/termux/libandroid-shmem/issues/3)

**Comment by sdrausty** [comment]
Accessing libandroid-shmem support is now possibly in TermuxArch, use **[`setupTermuxArch.sh r`](https://raw.githubusercontent.com/sdrausty/TermuxArch/master/scripts/files/stable/setupTermuxArch.sh)** for quick system refresh; libandroid-shmem support is added with this https://github.com/sdrausty/TermuxArch/commit/a25067274c341b73d1fc79b85eabbbbdf33680eb commit.  The current version of [TermuxArch](https://sdrausty.github.io/TermuxArch/) also sets locales from Android on the fly for Arch Linux in Termux PRoot to be in the language you wish.

**Comment by SDRausty** [comment]
Retesting install feature is requested as [Issues with Libreoffice #252](https://github.com/SDRausty/TermuxArch/issues/252) was opened.  Should device space be an issue and your device smartphone, wearable, smartwatch and more, please run this command:
```
bash setupTermuxArch re
```
This will refresh the installation to the newest version for development, testing and the ux (user experience) should space on device be an issue, please use the alternate directory install feature; `setupTermuxArch h` has more information about the alt directory install  feature .
