### ISSUE TITLE
Chromebook question

### ISSUE THREAD

**Issue by xroot25** [sdrausty/TermuxArch#69]
I am running a Samsung Chromebook 3, which can not run any distro outside gallium :-(
Can I use chromebrew for needed dependencies like wget and whatnot, in conjunction with your project as the main attraction, OUTSIDE of Termux? Or are there unbendable barriers requiring me to use only Termux? I am dying to replace chrome on, and NOT with Debian derivates.

**Comment by xroot25** [comment]
I meant to say can I use it inside of dev-enabled Crosh?

**Comment by sdrausty** [comment]
TermuxArch is designed to work in Termux.

> are there unbendable barriers requiring me to use only Termux? 

Yes, [Termux PRoot](https://github.com/termux/proot) is required.

**Comment by sdrausty** [comment]
@xroot25 I been giving this issue considerable though in passing:

1) This idea is a tremendous idea on many levels,
2) The answer from a few days ago is valid, provided you don't have unlimited resources to accomplish this goal.  The solution itself might even be fairly simple with the proper knowledge.

Reason one (1) and what a few of my mentors shared, "Nothing is impossible in computer science.  The entire real is man-made."  The potential is an operating system independent installation script.  That's quite a feat.  If you succeed in any way, this includes unsuccessful installation with errors, I'll help as much as possible.
