### ISSUE TITLE
Bad system call

### ISSUE THREAD

**Issue by BearChavez** [sdrausty/TermuxArch#7]
In Termux, on a fresh install of Arch proot I got this

[root@localhost home]# pacman -Syu
Bad system call 
[root@localhost home]# 

I'm running Android Oreo, stock Pixel²ROM, no root and stock kernel for Pixel²ROM

**Comment by sdrausty** [comment]
@BearChavez thanks for commenting. What is your `uname -m`? You might want to check https://github.com/termux/proot/issues out.

**Comment by sdrausty** [comment]
This issue is being closed since this issue concerns PRoot's behavior in Oreo Android, not `setupTermuxArch.sh`. Please repost at https://github.com/termux/proot/issues/5

**Comment by sdrausty** [comment]
This afaik resolved issue involves termux-exec also, not just PRoot and all should be behaving well with this commit https://github.com/sdrausty/TermuxArch/commit/71f2b4fa72a45c51d812e7598856d1ab6a2d531b. See https://github.com/termux/termux-exec
