### ISSUE TITLE
The TermuxArch Keyring Command keys : Generating Keys

### ISSUE THREAD

**Issue by sdrausty** [sdrausty/TermuxArch#72]
This issue is forked from https://github.com/sdrausty/TermuxArch/issues/59 A few questions about Arch Linux in Termux PRoot on 20180418

@Root-voidX screenshot from aarch64 Android 6 fresh install:

![screenshot_20180417-213348](https://user-images.githubusercontent.com/27742457/38906930-53c71d96-4287-11e8-8402-3c708f614292.png)

Ditto armv7:

![screenshot_2018-04-17-23-38-18](https://user-images.githubusercontent.com/27742457/38911301-387c3a70-429c-11e8-9c80-b2e68fb1312d.png)

More information about installing keys at:

https://github.com/termux/proot/issues/10
https://github.com/sdrausty/TermuxArch/issues/28
https://github.com/sdrausty/TermuxArch/issues/33
https://github.com/sdrausty/TermuxArch/issues/46
 
##### Here are some links:
https://github.com/archlinuxarm 
https://github.com/ArchStrike/ArchStrike 
https://wiki.archlinux.org/index.php/IRC_channel
Email : termux+subscribe@groups.io
Github : https://github.com/termux/
Gitter : https://gitter.im/termux/termux
Termux Community : https://plus.google.com/communities/101692629528551299417

**Comment by Root-voidX** [comment]
I actually think it's an issue with android 8.0 itself. Maybe something to do with device entropy? Because my s7e on nougat was also an armv8h so it can't be an armv8 issue
