### ISSUE TITLE
Several TermuxArch repositories

### ISSUE THREAD

**Issue by abicorios** [sdrausty/TermuxArch#75]
Hi. I see https://github.com/sdrausty/TermuxArch, https://github.com/sdrausty/termux-arch, https://github.com/sdrausty/termux-archlinux.
And when I read the Readme files, I am not see about differences of this versions. What are differences?

**Comment by sdrausty** [comment]
https://sdrausty.github.io/TermuxArch/NOTICE has more information; no 404s...
