### ISSUE TITLE
Error when extracting the archive

### ISSUE THREAD

**Issue by iantothecore** [sdrausty/TermuxArch#8]
Dunno why when extracting arch image somehow its always end up with some error. Try to manually extracting the image, same result

**Comment by developer787** [comment]
Hi, can you paste here a screenshot of the error?

**Comment by sdrausty** [comment]
Thank you for your time and input. It was very helpful in modifying [setupTermuxArch.sh](https://raw.githubusercontent.com/sdrausty/TermuxArch/master/setupTermuxArch.sh) accordingly; Error suppression and md5sum checks were added.

**Comment by iantothecore** [comment]
Thanks man ... Its fixed now 👍
