### ISSUE TITLE
Arm build error 

### ISSUE THREAD

**Issue by Root-voidX** [sdrausty/TermuxArch#81]
Hello all,

I have a new error popping up when I run termux arch on my s9+ running android 8.0 on the newest kernal.

```
(40/40) checking keys in keyring                   [#######] 100%
(40/40) checking package integrity                 [#######] 100%
error: git: signature from "Arch Linux ARM Build System <builder@archlinuxarm.org>" is unknown trust
:: File /var/cache/pacman/pkg/git-2.17.1-1-aarch64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: libdaemon: signature from "Arch Linux ARM Build System <builder@archlinuxarm.org>" is unknown trust
:: File /var/cache/pacman/pkg/libdaemon-0.14-4-aarch64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: libxinerama: signature from "Arch Linux ARM Build System <builder@archlinuxarm.org>" is unknown trust
:: File /var/cache/pacman/pkg/libxinerama-1.1.3-3-aarch64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: libxkbfile: signature from "Arch Linux ARM Build System <builder@archlinuxarm.org>" is unknown trust
:: File /var/cache/pacman/pkg/libxkbfile-1.0.9-2-aarch64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: libxt: signature from "Arch Linux ARM Build System <builder@archlinuxarm.org>" is unknown trust
:: File /var/cache/pacman/pkg/libxt-1.1.5-2-aarch64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: libxmu: signature from "Arch Linux ARM Build System <builder@archlinuxarm.org>" is unknown trust
:: File /var/cache/pacman/pkg/libxmu-1.1.2-2-aarch64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: libxss: signature from "Arch Linux ARM Build System <builder@archlinuxarm.org>" is unknown trust
:: File /var/cache/pacman/pkg/libxss-1.2.2-3-aarch64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: libxxf86dga: signature from "Arch Linux ARM Build System <builder@archlinuxarm.org>" is unknown trust
:: File /var/cache/pacman/pkg/libxxf86dga-1.1.4-2-aarch64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: libxxf86vm: signature from "Arch Linux ARM Build System <builder@archlinuxarm.org>" is unknown trust
:: File /var/cache/pacman/pkg/libxxf86vm-1.1.4-2-aarch64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: linux-aarch64: signature from "Arch Linux ARM Build System <builder@archlinuxarm.org>" is unknown trust
:: File /var/cache/pacman/pkg/linux-aarch64-4.16.13-1-aarch64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: pkgconf: signature from "Arch Linux ARM....
```

**Comment by tukusejssirs** [comment]
It happened to me too, while I tried to install `xfce4` or `lxde`.

This was on OnePlus One with custom rom (Omnia based on Marshmallow); `uname -a`:

`Linux localhost 3.4.113-OmniBear-g6f9f4d3 #1 SMP PREEMPT Mon Dec 19 18:38:13 CET 2016 armv7l GNU/Linux`

**Comment by tukusejssirs** [comment]
According to [this](https://www.reddit.com/r/archlinux/comments/77p5j0/upgrade_issues_signature_has_unknown_trust/) site, it’s a problem of expired/duplicate signatures, but I couldn’t fix it with `pacman-key --refresh-keys`.

```bash
$ pacman-key --refresh-keys
gpg: refreshing 5 keys from hkps://hkps.pool.sks-keyservers.net
gpg: key BF7EEF7A9C6B5765: "Michael Brown (ArchLinux ARM Master Key) <mbrown@master-key.archlinuxarm.org>" 2 new signatures
gpg: key BC704E86B823CD25: "Kevin Mihelich (Arch Linux ARM Master Key) <kevin@master-key.archlinuxarm.org>" 2 new signatures
gpg: key B55C5315DCD9EE1A: "Jason Plum (Arch Linux ARM Master Key) <jplum@master-key.archlinuxarm.org>" 2 new signatures
gpg: key 77193F152BDBE6A6: 1 duplicate signature removed
gpg: key 77193F152BDBE6A6: 2 signatures not checked due to missing keys
gpg: key 77193F152BDBE6A6: "Arch Linux ARM Build System <builder@archlinuxarm.org>" not changed
gpg: Total number processed: 4
gpg:              unchanged: 1
gpg:         new signatures: 6
gpg: marginals needed: 3  completes needed: 1  trust model: pgp
gpg: depth: 0  valid:   1  signed:   3  trust: 0-, 0q, 0n, 0m, 0f, 1u
gpg: depth: 1  valid:   3  signed:   1  trust: 0-, 0q, 0n, 3m, 0f, 0u
gpg: depth: 2  valid:   1  signed:   0  trust: 1-, 0q, 0n, 0m, 0f, 0u

$ pacman-key --list-keys builder@archlinuxarm.org
pub   rsa4096 2014-01-18 [SC]
      68B3537F39A313B3E574D06777193F152BDBE6A6
uid           [  full  ] Arch Linux ARM Build System <builder@archlinuxarm.org>
sub   rsa4096 2014-01-18 [E]
```

**Comment by Root-voidX** [comment]
I did a full purge and it fixed the issue, still haven't reinstalled git yet though. 

Try that?

**Comment by Root-voidX** [comment]
Actually the issue resurfaced again!

[00:35 home ]$ pacman -Syu
:: Synchronizing package databases...
 core                     189.9 KiB  1899K/s 00:00 [#######] 100%
 extra                      2.2 MiB  3.57M/s 00:01 [#######] 100%
 community                  4.1 MiB  2.95M/s 00:01 [#######] 100%
 alarm                     46.2 KiB  0.00B/s 00:00 [#######] 100%
 aur is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (2) libsystemd-238.133-1  vi-1:070224-3

Total Download Size:   0.50 MiB
Total Installed Size:  2.36 MiB
Net Upgrade Size:      0.29 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 libsystemd-238.133-...   354.3 KiB  3.46M/s 00:00 [#######] 100%
 vi-1:070224-3-aarch64    157.2 KiB  3.84M/s 00:00 [#######] 100%
(2/2) checking keys in keyring                     [#######] 100%
warning: Public keyring not found; have you run 'pacman-key --init'?
downloading required keys...
error: key "77193F152BDBE6A6" could not be looked up remotely
error: required key missing from keyring
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.

**Comment by sdrausty** [comment]
@Root-voidX @tukusejssirs [Android 5 results;](https://github.com/sdrausty/TermuxArch/issues/72) Doesn't using [`keys`](https://github.com/sdrausty/TermuxArch/issues/72) resolve keyring issues?

I'm also wondering about the title of our issue here; How is this topic related to building?

**Comment by Root-voidX** [comment]
@sdrausty

No running keys doent fix the issue. I can purge and get back to a clean install but once pacman starts updating the issue comes back. Also as per the title, my original post showed error codes for a arm builder so that's why I wrote that is a title. I dont know why there was an error for an arm build when I was just originally just getting updates via pacman.

**Comment by tukusejssirs** [comment]
I think the problem lays in the key expiry/renewal of `builder@archlinuxarm.org`, therefore it might not be (directly/fully) resolved from `termuxarch`.

**Comment by sdrausty** [comment]
Does purging `archlinuxarm-keyring` help this issue?

**Comment by sdrausty** [comment]
Does purging `archlinuxarm-keyring` help this issue?
```
$ pacman -Rc archlinuxarm-keyring
checking dependencies...
warning: pacman is designated as a HoldPkg.
:: HoldPkg was found in target list. Do you want to continue? [y/N]
```
Removes `pacman` too; I'll try too update TermuxArch today so `keys` uses only `archlinux-keyring` by default which should help out future users.

**Comment by sdrausty** [comment]
This https://github.com/sdrausty/TermuxArch/commit/0b405c41a7843ffca1e5e8cff07a5fddc8c6f906 commit depreciates `archlinuxarm-keyring` from the default install `keys` uses.  Does this resolve the error for the devices you are using @Root-voidX @tukusejssirs as far as default configurations?

**Comment by Root-voidX** [comment]
@sdrausty

I did a purge and redownload and the keys stil expire.

**Comment by sdrausty** [comment]
Show us your output @Root-voidX

**Comment by Root-voidX** [comment]
@sdrausty here is the output. It keeps looping the error for me.

'''
aur is up to date
:: Starting full system upgrade...
resolving dependencies...
looking for conflicting packages...

Packages (11) bash-4.4.023-1  ca-certificates-mozilla-3.37.3-1
              db-5.3.28-4  keyutils-1.5.10-2  libarchive-3.3.2-2
              libunistring-0.9.10-1  mkinitcpio-busybox-1.28.4-1
              nano-2.9.8-1  procps-ng-3.3.15-1
              readline-7.0.005-1  sqlite-3.24.0-1

Total Download Size:    3.03 MiB
Total Installed Size:  31.81 MiB
Net Upgrade Size:       2.04 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 db-5.3.28-4-aarch64     1059.4 KiB  3.57M/s 00:00 [#######] 100%
 ca-certificates-moz...   326.0 KiB  3.98M/s 00:00 [#######] 100%
 nano-2.9.8-1-aarch64     436.6 KiB  3.88M/s 00:00 [#######] 100%
 sqlite-3.24.0-1-aarch64 1281.5 KiB  3.48M/s 00:00 [#######] 100%
(11/11) checking keys in keyring                   [#######] 100%
downloading required keys...
:: Import PGP key 4096R/68B3537F39A313B3E574D06777193F152BDBE6A6, "Arch Linux ARM Build System <builder@archlinuxarm.org>", created: 2014-01-18? [Y/n] y
(11/11) checking package integrity                 [#######] 100%
error: readline: signature from "Arch Linux ARM Build System <builder@archlinuxarm.org>" is unknown trust
:: File /var/cache/pacman/pkg/readline-7.0.005-1-aarch64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: bash: signature from "Arch Linux ARM Build System <builder@archlinuxarm.org>" is unknown trust
:: File /var/cache/pacman/pkg/bash-4.4.023-1-aarch64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: db: signature from "Arch Linux ARM Build System <builder@archlinuxarm.org>" is unknown trust
:: File /var/cache/pacman/pkg/db-5.3.28-4-aarch64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: ca-certificates-mozilla: signature from "Arch Linux ARM Build System <builder@archlinuxarm.org>" is unknown trust
:: File /var/cache/pacman/pkg/ca-certificates-mozilla-3.37.3-1-aarch64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: keyutils: signature from "Arch Linux ARM Build System <builder@archlinuxarm.org>" is unknown trust
:: File /var/cache/pacman/pkg/keyutils-1.5.10-2-aarch64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: libarchive: signature from "Arch Linux ARM Build System <builder@archlinuxarm.org>" is unknown trust
:: File /var/cache/pacman/pkg/libarchive-3.3.2-2-aarch64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: libunistring: signature from "Arch Linux ARM Build System <builder@archlinuxarm.org>" is unknown trust
:: File /var/cache/pacman/pkg/libunistring-0.9.10-1-aarch64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] y
error: mkinitcpio-busybox: signature from "Arch Linux ARM Build....
'''

**Comment by sdrausty** [comment]
Why is your system:
`:: Import PGP key 4096R/68B3537F39A313B3E574D06777193F152BDBE6A6, "Arch Linux ARM Build System <builder@archlinuxarm.org>", created: ` using arm?  Arm is no longer default.

**Comment by tukusejssirs** [comment]
@sdrausty, probably because we use `termuxarch` on an ARM device—this is at least my case. :)

**Comment by Root-voidX** [comment]
@sdrausty I am on arm64 also known as aarch64. The issue here is that arch created the key but it cannot read it. No doubt a permission issue with android 8.0. Arch works fine with my s7 edge. I have so far no issues yet with ubuntu on termux besides annoying warnings, which is also due to permissions. I dont know if the current state can allow you give termux proot elevated access safely without root or tripping selinux.

**Comment by Zach-15803** [comment]
I had the same issue, and I made a post about it, it was resolved

https://github.com/sdrausty/TermuxArch/issues/86

**Comment by tukusejssirs** [comment]
Indeed, I can confirm that @FreshMosh’s [comment](https://github.com/sdrausty/TermuxArch/issues/86#issuecomment-398335208) solved this issue. You need to run the following two commands:
```bash
pacman-key --init
pacman-key --populate archlinuxarm
```

**Comment by Root-voidX** [comment]
@Zach-15803 Do you know why that is the case? Shouldn't arch auto populate? This did fix the issue at the moment

**Comment by FreshMosh** [comment]
Populating is not done by Arch itself. 
And the [current script](https://github.com/sdrausty/TermuxArch/blob/master/scripts/files/stable/necessaryfunctions.sh) does seem to lack the pacman-key part from the [previous versions](https://github.com/sdrausty/TermuxArch/blob/master/scripts/files/stable/v1.4/necessaryfunctions.sh).  

Right now I am not sure if it is handled elsewhere now, but it seems to me that the current script just does not initilize the keyring. 

-------
necessaryfunctions-v1.5.sh
```
	printf "\033[0;34mWhen \033[0;37mgpg: Generating pacman keyring master key\033[0;34m appears on the screen, the installation process can be accelerated.  The system desires a lot of entropy at this part of the install procedure.  To generate as much entropy as possible quickly, watch and listen to a file on your device.  \n\nThe program \033[1;32mpacman-key\033[0;34m will want as much entropy as possible when generating keys.  Entropy is also created through tapping, sliding, one, two and more fingers tapping with short and long taps.  When \033[0;37mgpg: Generating pacman keyring master key\033[0;34m appears on the screen, use any of these simple methods to accelerate the installation process if it is stalled.  Put even simpler, just do something on device.  Browsing files will create entropy on device.  Slowly swiveling the device in space and time will accelerate the installation process.  This method alone might not generate enough entropy (a measure of randomness in a closed system) for the process to complete quickly.  Use \033[1;32mbash ~${darch}/bin/we \033[0;34min a new Termux session to and watch entropy on device.\n\n\033[m"
	pacman-key --init ||: 
	printf "\n\033[0;34mWhen \033[1;37mAppending keys from archlinux.gpg\033[0;34m appears on the screen, the installation process can be accelerated.  The system desires a lot of entropy at this part of the install procedure.  To generate as much entropy as possible quickly, watch and listen to a file on your device.  \n\nThe program \033[1;32mpacman-key\033[0;34m will want as much entropy as possible when generating keys.  Entropy is also created through tapping, sliding, one, two and more fingers tapping with short and long taps.  When \033[1;37mAppending keys from archlinux.gpg\033[0;34m appears on the screen, use any of these simple methods to accelerate the installation process if it is stalled.  Put even simpler, just do something on device.  Browsing files will create entropy on device.  Slowly swiveling the device in space and time will accelerate the installation process.  This method alone might not generate enough entropy (a measure of randomness in a closed system) for the process to complete quickly.  Use \033[1;32mbash ~${darch}/bin/we \033[0;34min a new Termux session to watch entropy on device.\n\n"
	pacman-key --populate archlinux ||: 
```
missing in the current necessaryfunctions.sh

**Comment by carlosal1015** [comment]
> Indeed, I can confirm that @FreshMosh’s [comment](https://github.com/sdrausty/TermuxArch/issues/86#issuecomment-398335208) solved this issue. You need to run the following two commands:
> 
> ```shell
> pacman-key --init
> pacman-key --populate archlinuxarm
> ```
It works yes!
