### ISSUE TITLE
pacman -Syu Error

### ISSUE THREAD

**Issue by technicalsonuindia** [sdrausty/TermuxArch#82]
Synchronizing package databases...
error: failed to update core (unable to lock database)
error: failed to update extra (unable to lock database)
error: failed to update community (unable to lock database)
error: failed to update alarm (unable to lock database)
error: failed to update aur (unable to lock database)
error: failed to update blackarch (unable to lock database)
error: failed to synchronize all databases

**Comment by sdrausty** [comment]
http://www.bing.com/search?q=error%3A+failed+to+update+core+%28unable+to+lock+database
