### ISSUE TITLE
Fakeroot giving IPC error

### ISSUE THREAD

**Issue by Xieyt** [SDRausty/TermuxArch#83]
Any workaround for this ?? I was installing pacaur..

**Comment by sdrausty** [comment]
Accessing libandroid-shmem support is now possibly in TermuxArch, use **[`setupTermuxArch.sh r`](https://raw.githubusercontent.com/sdrausty/TermuxArch/master/scripts/files/stable/setupTermuxArch.sh)** for quick system refresh; libandroid-shmem support is added with this https://github.com/sdrausty/TermuxArch/commit/a25067274c341b73d1fc79b85eabbbbdf33680eb commit.  The current version of [TermuxArch](https://sdrausty.github.io/TermuxArch/) also sets locales from Android on the fly for Arch Linux in Termux PRoot to be in the language you wish.

**Comment by sdrausty** [comment]
>  I managed to install fakeroot-tcp in arch-termux. 

Can you share the details of how you accomplished this please?

**Comment by sdrausty** [comment]
> has been done before 

https://github.com/sdrausty/TermuxArch/issues?g=fakeroot

> give out a few errors but it's only cosmetic

Possibly.  Probably not.
```
fakeroot
dlsym(acl_get_fd): /opt/fakeroot/libs/libfakeroot.so: undefined symbol: acl_get_fd
dlsym(acl_get_file): /opt/fakeroot/libs/libfakeroot.so: undefined symbol: acl_get_file
dlsym(acl_set_fd): /opt/fakeroot/libs/libfakeroot.so: undefined symbol: acl_set_fd
dlsym(acl_set_file): /opt/fakeroot/libs/libfakeroot.so: undefined symbol: acl_set_file
[root@localhost fakeroot-1.23]#
```

> sudo make install

[This installs without sudo in proot.](https://raw.githubusercontent.com/sdrausty/docsTermuxArch/master/fakeroot/makeinstall.md)  

> managed to install yay, trizen, gcalcli from the aur.

Can you outline the steps that you used to install these from aur?

**Comment by sdrausty** [comment]
> has been done before 

https://github.com/sdrausty/TermuxArch/issues?q=fakeroot

> give out a few errors but it's only cosmetic

Possibly;  Probably not.
```
[user09:14fakeroot-1.23]$ fakeroot
dlsym(acl_get_fd): /opt/fakeroot/libs/libfakeroot.so: undefined symbol: acl_get_fd
dlsym(acl_get_file): /opt/fakeroot/libs/libfakeroot.so: undefined symbol: acl_get_file
dlsym(acl_set_fd): /opt/fakeroot/libs/libfakeroot.so: undefined symbol: acl_set_fd
dlsym(acl_set_file): /opt/fakeroot/libs/libfakeroot.so: undefined symbol: acl_set_file
[root@localhost fakeroot-1.23]#
```

> sudo make install

[This installs without sudo in proot.](https://raw.githubusercontent.com/sdrausty/docsTermuxArch/master/fakeroot/makeinstall.md)  

> managed to install yay, trizen, gcalcli from the aur.

Can you outline the steps that you used to install these from aur?

**Comment by paranoid7** [comment]
We for yay I followed the standard procedure:
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
Fakeroot did give the undefined symbol error but yay installed alright
After that I install trizen and gcalcli from yay itself without any issues (apart from fakeroot undefined symbol error)

**Comment by sdrausty** [comment]
@paranoid7 did you get this error?

```
$ startarch+archer c pc go
.
.
.
ldconfig: /usr/lib/libfakeroot-0.so is not a symbolic link
```

`$ ln -s libfakeroot-1.23.so libfakeroot-0.so` resolves it☀️⏳

There are screenfulls of:
```
$ makepkg -si
.
.
.
dlsym(acl_get_fd): /opt/fakeroot/libs/libfakeroot.so: undefined symbol: acl_get_fd
dlsym(acl_get_file): /opt/fakeroot/libs/libfakeroot.so: undefined symbol: acl_get_file
dlsym(acl_set_fd): /opt/fakeroot/libs/libfakeroot.so: undefined symbol: acl_set_fd
dlsym(acl_set_file): /opt/fakeroot/libs/libfakeroot.so: undefined symbol: acl_set_file
dlsym(acl_get_fd): /opt/fakeroot/libs/libfakeroot.so: undefined symbol: acl_get_fd
dlsym(acl_get_file): /opt/fakeroot/libs/libfakeroot.so: undefined symbol: acl_get_file
Thanks$ ==> Leaving fakeroot environment.
==> Finished making: yay 9.0.1-3 (Fri 04 Jan 2019 04:56:19 AM EST)
==> Installing package yay with pacman -U...
[sudo] password for root:
Sorry, try again.
[sudo] password for root:
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) yay-9.0.1-3

Total Installed Size:  4.84 MiB

:: Proceed with installation? [Y/n]
(1/1) checking keys in keyring                     [#########################] 100%
(1/1) checking package integrity                   [#########################] 100%
(1/1) loading package files                        [#########################] 100%
(1/1) checking for file conflicts                  [#########################] 100%
(1/1) checking available disk space                [#########################] 100%
:: Processing package changes...
(1/1) installing yay                               [#########################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
[user09:57yay]$ yay --version
yay v9.0.1 - libalpm v11.0.1
```

Can you give a little information about which choices to choose from these menus?
```
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> A
:: Deleting (1/1): /home/e/.cache/yay/gcalcli
:: Downloaded PKGBUILD (1/1): gcalcli
  1 gcalcli                                  (Build Files Exist)
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> Diffs to show?
```

**Comment by sdrausty** [comment]
@paranoid7 did you get this error?

```
[user09:56tmp]$ startarch+archer c pc go
.
.
.
ldconfig: /usr/lib/libfakeroot-0.so is not a symbolic link
```

`$ ln -s libfakeroot-1.23.so libfakeroot-0.so` resolves it☀️⏳

There are screenfulls of:
```
$ makepkg -si
.
.
.
dlsym(acl_get_fd): /opt/fakeroot/libs/libfakeroot.so: undefined symbol: acl_get_fd
dlsym(acl_get_file): /opt/fakeroot/libs/libfakeroot.so: undefined symbol: acl_get_file
dlsym(acl_set_fd): /opt/fakeroot/libs/libfakeroot.so: undefined symbol: acl_set_fd
dlsym(acl_set_file): /opt/fakeroot/libs/libfakeroot.so: undefined symbol: acl_set_file
dlsym(acl_get_fd): /opt/fakeroot/libs/libfakeroot.so: undefined symbol: acl_get_fd
dlsym(acl_get_file): /opt/fakeroot/libs/libfakeroot.so: undefined symbol: acl_get_file
Thanks$ ==> Leaving fakeroot environment.
==> Finished making: yay 9.0.1-3 (Fri 04 Jan 2019 04:56:19 AM EST)
==> Installing package yay with pacman -U...
[sudo] password for root:
Sorry, try again.
[sudo] password for root:
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) yay-9.0.1-3

Total Installed Size:  4.84 MiB

:: Proceed with installation? [Y/n]
(1/1) checking keys in keyring                     [#########################] 100%
(1/1) checking package integrity                   [#########################] 100%
(1/1) loading package files                        [#########################] 100%
(1/1) checking for file conflicts                  [#########################] 100%
(1/1) checking available disk space                [#########################] 100%
:: Processing package changes...
(1/1) installing yay                               [#########################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
[user09:57yay]$ yay --version
yay v9.0.1 - libalpm v11.0.1
```

Can you give a little information about which choices to choose from these menus?
```
[user10:06tmp]$ yay -S gcalcli
:: Checking for conflicts...
:: Checking for inner conflicts...
[Repo: 18]  python-oauth2client-4.1.3-1  python-httplib2-0.12.0-1  python-pyasn1-0.4.5-1  python-pyasn1-modules-0.2.3-1  python-pyopenssl-18.0.0-2  python-cryptography-2.4.2-1  python-cffi-1.11.5-2  python-pycparser-2.19-1  python-ply-3.11-2  python-idna-2.8-1  python-asn1crypto-0.24.0-2  python-rsa-4.0-1  python-dateutil-2.7.5-1  python-google-api-python-client-1.7.7-1  python-google-auth-httplib2-0.0.3-2  python-google-auth-1.6.2-1  python-cachetools-3.0.0-1  python-uritemplate-3.0.0-3
[Aur: 1]  gcalcli-4.0.0a4-1

  1 gcalcli                                  (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> A
:: Deleting (1/1): /home/e/.cache/yay/gcalcli
:: Downloaded PKGBUILD (1/1): gcalcli
  1 gcalcli                                  (Build Files Exist)
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> Diffs to show?
```

**Comment by paranoid7** [comment]
I am sorry I am pretty new to yay myself so I can't help you much. For the menu questions I just pressed enter and it sorta worked (I know I am dumb) .
I was talking about this error: 

dlsym(acl_get_fd): /opt/fakeroot/libs/libfakeroot.so: undefined symbol: acl_get_fd
Have tried to fix but can't do it (still a newbie to Linux in general).

**Comment by paranoid7** [comment]
Also can't install fakeroot-tcp from yay (gives a permission denied error). Care to take a look into it?

**Comment by sdrausty** [comment]
When something like this appears:
```
[sudo] password for root:
resolving dependencies...
looking for conflicting packages...

Packages (1) po4a-0.55-1

Total Download Size:   1.43 MiB
Total Installed Size:  3.00 MiB

:: Proceed with installation? [Y/n] n
Error installing repo packages
```
Choose no.  Use a new session.  In this example, `startarch c pc po4a` will satisfy the dependency.  Afterwards, return to the previous session.  `$ yay -S fakeroot-tcp` should be run twice in this example.  Which choice?  Any idea @paranoid7?
```
[e05:19tmp]$ yay -S fakeroot-tcp
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur: 1]  fakeroot-tcp-1.23-1

  1 fakeroot-tcp                             (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==>
.
.
.
patching file libfakeroot.c
patch: setting attribute security.selinux for security.selinux: Permission denied
==> ERROR: A failure occurred in prepare().
    Aborting...
Error making: fakeroot-tcp
```

![](https://sdrausty.github.io/imgsTermuxArch/fakeroot/3wLv5jY.jpg)

> Also can't install fakeroot-tcp from yay (gives a permission denied error). Care to take a look into it?

Sure;  That is what we are doing.

**Comment by sdrausty** [comment]
This https://github.com/sdrausty/libandroid-shmem should run correctly to resolve many of the errors we have encountered.  Feel free to take up this challenge with us.  I will help out in any way I can.

**Comment by sdrausty** [comment]
A couple of references regarding this topic: https://github.com/termux/termux-packages/issues?q=is%3Aissue+libshmem and https://github.com/termux/libandroid-shmem/issues?q=is%3Aissue+proot

**Comment by paranoid7** [comment]
I didn't really under what you mean by 
"$ yay -S fakeroot-tcp should be run twice in this example. Which choice? Any idea @paranoid7?"

I will try my utmost to help with this issues however.

**Comment by sdrausty** [comment]
https://github.com/sdrausty/TermuxArch/issues?q=is%3Aissue+label%3Ashmem

**Comment by sdrausty** [comment]
https://github.com/sdrausty/libandroid-shmem

**Comment by sdrausty** [comment]
> will try my utmost to help with these issues however.

@paranoid7 here is an out line:
a) Clone https://github.com/sdrausty/libandroid-shmem which should build on device correctly.
b) Configure and run tests...

**Comment by HoshiYamazaki** [comment]
I have the same issue as I tried to `makepkg` some AUR and own packages, and fakeroot-tcp gives me this error.

Gonna try libandroid-shmem soon, I suppose I need to compile it at Arch side? I have it installed under Termux though.

**Comment by Xwang1976** [comment]
Trying to compile from websockify from AUR I have got the following error:
"fakeroot, while creating message channels: Function not implemented
This may be due to a lack of SYSV IPC support.
fakeroot: error while starting the 'faked' daemon"

So I exited the arch environment, I installed libandroid-shmem in termux using  "pkg install libandroid-shmem", then I ran  "setupTermuxArch.sh r", but still I'm getting the same error.

Should I do something else to solve the problem?

**Comment by SDRausty** [comment]
> Should I do something else to solve the problem?

Please try the the command [`makefakeroottcp`](https://github.com/SDRausty/TermuxArch/issues?q=is%3Aissue+makefakeroottcp) which should build and install `fakeroot-tcp`.

**Comment by WMCB-Tech** [comment]
Actually, with the `--sysvipc` option allows you to emulate ipc and run fakeroot without needing to use tcp version

Although Android 5/6 users won't be able to use this so probably that Commands is for compatibility reasons

**Comment by Xwang1976** [comment]
> > Should I do something else to solve the problem?
> 
> Please try the the command [`makefakeroottcp`](https://github.com/SDRausty/TermuxArch/issues?q=is%3Aissue+makefakeroottcp) which should build and install `fakeroot-tcp`.

I just did it and it solved the problem. Thanks a lot!!!

**Comment by SDRausty** [comment]
You are welcome and thank you for confirming @Xwang1976 🎵 🎶

**Comment by SDRausty** [comment]
> Any workaround for this ??

This commit https://github.com/SDRausty/TermuxArch/commit/744e3a3eefc58aa227ce04612415d5ef1a40ea1e enables the `--sysvipc` PRoot option for user accounts. Creating `fakeroot-tcp` is no longer required.
