### ISSUE TITLE
unable to run "pacman -Syu"

### ISSUE THREAD

**Issue by Zach-15803** [sdrausty/TermuxArch#86]
I cant update or install, i have gereated a public keyring thingy, this is what happens when i try to run "pacman -Syu" after a fresh reinstall

https://pastebin.com/VbiBsteU

**Comment by Zach-15803** [comment]
Alright, i sorta fixed this by manually installing the files in /var/cache/pacman/pkg with "pacman -U ./*"

**Comment by ReekyMarko** [comment]
Thanks a lot, works now!

**Comment by Zach-15803** [comment]
That works

**Comment by Zach-15803** [comment]
And can an ADMIN close this?

**Comment by ReekyMarko** [comment]
Why don't you close it yourself?

**Comment by Zach-15803** [comment]
Because i dont know how

**Comment by Zach-15803** [comment]
resolved #86

**Comment by tuxr** [comment]
Thank you FreshMosh, I just installed and was running into the same issue. This resolved for me as well.

**Comment by sstt011** [comment]
@Zach-15803 next to the comment button, there is a close button

**Comment by abicorios** [comment]
It is not work for me

**Comment by FreshMosh** [comment]
@abicorios what exactly is not working for you?

**Comment by abicorios** [comment]
Now I understand. Working case in Termux is next:
```
pkg install git
cd && git clone https://github.com/sdrausty/TermuxArch
bash TermuxArch/setupTermuxArch.sh
pacman-key --init
pacman-key --populate archlinuxarm
pacman -Syu
```
My mistake was next:
```
pkg install git
cd && git clone https://github.com/sdrausty/TermuxArch
bash TermuxArch/setupTermuxArch.sh
pacman -Syu
```
And it was answer
```
Proceed with installation? [Y/n]
warning: Public keyring not found; have you run 'pacman-key --init'?
```
So I run:
```
pacman-key --init
pacman -Syu 
```
And it was next:
```
error: gcc-libs: signature from "Arch Linux ARM Build System <builder@archlinuxarm.org>" is unknown trust
:: File /var/cache/pacman/pkg/gcc-libs-8.1.1+20180531-1-aarch64.pkg.tar.xz is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n]
```
And I such 
```
y
```
So I deleted all packages and TermuxArch was broken by my hands. Cool story. Yeah?

**Comment by abicorios** [comment]
Okay, okay. But you can run `keys` twice by install-script automaticaly. Why no?

**Comment by sdrausty** [comment]
@abicorios this install Arch Linux, then cannot install Arch Linux in Termux PRoot because of keyrings is **a recently acquired behavior** of Arch Linux in Termux PRoot that was not present earlier.  I am fairly sure that the keyring shouldn't be required for users.  As far as being an option for users...

**Comment by abicorios** [comment]
Ok.
1. I install TermuxArch by setupTermuxArch.sh
2. I have option `keys`.
But if I do not run `keys` so `pacman -Syu` produce errors. If `keys` is option, so how can I run `pacman -Syu` without `keys` and without errors? What is another option case? Is it disabling of key-check in some configs?

**Comment by jlmess77** [comment]
The fix is to add the SigLevel like this:

`[archstrike]
Server = https://mirror.archstrike.org/$arch/$repo

[blackarch]
Server = http://blackarch.org/blackarch/$repo/os/$arch
SigLevel = Never`

**Comment by sdrausty** [comment]
This https://github.com/sdrausty/TermuxArch/commit/6c9c119c00c5601bd37c07a2e231c305d4966168 commit should resolve the keyring issue.

**Comment by abicorios** [comment]
```
[20:01 arch ]$ pacman -Syu
error: GPGME error: No data
error: GPGME error: No data
error: GPGME error: No data
error: GPGME error: No data
error: GPGME error: No data
:: Synchronizing package databases...
 core                     188.5 KiB   236K/s 00:01
 core.sig                   8.7 KiB   145K/s 00:00
error: GPGME error: No data
error: failed to update core (invalid or corrupted database (PGP signature))
 extra                      2.2 MiB   524K/s 00:04
 extra.sig                  8.7 KiB  0.00B/s 00:00
error: GPGME error: No data
error: failed to update extra (invalid or corrupted database (PGP signature))
 community                  4.1 MiB   686K/s 00:06
 community.sig              8.7 KiB   871K/s 00:00
error: GPGME error: No data
error: failed to update community (invalid or corrupted database (PGP signature))
 alarm                     46.2 KiB   171K/s 00:00
 alarm.sig                  8.7 KiB   290K/s 00:00
error: GPGME error: No data
error: failed to update alarm (invalid or corrupted database (PGP signature))
 aur                        4.4 KiB   44
 aur.sig                    8.7 KiB   290K/s 00:00
error: GPGME error: No data
error: failed to update aur (invalid or corrupted database (PGP signature))
error: failed to synchronize all databases
```
Is it because I have aarch64?

**Comment by FreshMosh** [comment]
@abicorios Run ```keys``` first in order to use pacman. Vor reinstall TermuxArch entirely.

**Comment by sdrausty** [comment]
@abicorios try `setupTermuxArch.sh refresh` before reinstalling.

**Comment by abicorios** [comment]
keys
```
...
==> Running pacman -Ss keyring --color=always…
error: GPGME error: No data
error: GPGME error: No data
error: GPGME error: No data
error: GPGME error: No data
error: database 'core' is not valid (invalid or corrupted database (PGP signature))
error: database 'extra' is not valid (invalid or corrupted database (PGP signature))
error: database 'community' is not valid (invalid or corrupted database (PGP signature))
error: database 'alarm' is not valid (invalid or corrupted database (PGP signature))


TermuxArch Keys: DONE
```

**Comment by FreshMosh** [comment]
@abicorios Please try sdrasty's solution and run in your Termux ```setupTermuxArch.sh refresh``` to refresh your TermuxArch installation.

**Comment by sdrausty** [comment]
This snippet should be useful too: `$ startarch c pacman -Syyuu`

**Comment by sdrausty** [comment]
How'd your databases get messed up @abicorios?

**Comment by abicorios** [comment]
"How'd your databases get messed up @abicorios?"
I do not know. I installed Termux Arch, and run keys. May be it depends on a mirror.

**Comment by abicorios** [comment]
It was better before fix commit. Last fix broke Arch for me.

**Comment by abicorios** [comment]
Which mirror is working for you? Maybe. I need nice mirror to exclude database error.

**Comment by FreshMosh** [comment]
@abicorios
Have you already tried the provided solutions? 
If so, what was the output
If not, please try sdrausty's newly provided ```refresh```-switch like
setupTermuxArch.sh refresh```
Of course you may need to update your setupTermuxArch.sh-script in beforehand. 


Or, if anything else fails, please completely delete the install directory of Arch in Termux and run the up-to-date setupTermuxArch.sh.

**Comment by abicorios** [comment]
Yes, I already tried **all** provided solutions.
```
keys
```
```
bash TermuxArch/setupTermuxArch.sh refresh
```
```
startarch c pacman -Syyuu
```
Updating -S to read -Syyuu in keys was not help.
```
rm -rf TermuxArch
git clone https://github.com/sdrausty/TermuxArch
bash TermuxArch/setupTermuxArch.sh 
```
And I have same result:
```
error: GPGME error: No data
error: GPGME error: No data
error: GPGME error: No data
error: GPGME error: No data
error: GPGME error: No data
error: database 'core' is not valid (invalid or corrupted database (PGP signature))
error: database 'extra' is not valid (invalid or corrupted database (PGP signature))
error: database 'community' is not valid (invalid or corrupted database (PGP signature))
error: database 'alarm' is not valid (invalid or corrupted database (PGP signature))
error: database 'aur' is not valid (invalid or corrupted database (PGP signature))
```

**Comment by sdrausty** [comment]
@abicrios what does `bash setupTermuxArch.sh debug` say?

**Comment by sdrausty** [comment]
@abicorios what does `bash setupTermuxArch.sh debug` say?

It also appears that you misinterpreted what @FreshMosh said:
> please completely delete the install directory of Arch in Termux

Use `git pull` to update the git repository.  Deleting and recloning the repository was unnecessary:
```
rm -rf TermuxArch
git clone https://github.com/sdrausty/TermuxArch
bash TermuxArch/setupTermuxArch.sh 
```

There shouldn't be any reason to delete it.  More information about working with git repositories at this link: [**Instructional GitHub and Git Foundations Videos Can Be Downloaded for Viewing at Your Leisure.**](https://sdrausty.github.io/pages/ggf)

When `setupTermuxArch.sh` asks: 
```
$ bash setupTermuxArch.sh                                                       
TermuxArch: DIRECTORY WARNING!  /data/data/com.termux/files/home/arch/ directory detected.  Termux Arch installation shall continue.  If in doubt, answer yes.                                                                                  Uninstall /data/data/com.termux/files/home/arch? [Y|n]
Uninstall /data/data/com.termux/files/home/arch? [Y|n]
```
Simply tap for yes.  https://sdrausty.github.io/TermuxArch/docs/outputarmv720180729debugrefresh.txt

**Comment by abicorios** [comment]
No, I made `bash SetupTermuxArch.sh uninstall` 
[setupTermuxArchDebug9718.log](https://github.com/sdrausty/TermuxArch/files/2247049/setupTermuxArchDebug9718.log)

**Comment by abicorios** [comment]
I reinstall Termux, and it is not help me.
