### ISSUE TITLE
Unable to SSH into TermuxArch

### ISSUE THREAD

**Issue by Zach-15803** [sdrausty/TermuxArch#87]
How would one do this? i have my SSHD_config file set to look like this 
https://pastebin.com/bVHGtjdC

im trying to have it set for 9922 as the SSH port, but everytime i try, i get a "Connection Refused" error, even from localhost

**Comment by FreshMosh** [comment]
As I understand this setup, Arch is executet in some dort of unprivileged container via proot.
So to connect to your arch installed via termix->proot just do the following:
In Termux, installiert OpenSSH and place your SSH-Keyfile (Termux does not support Passwort auth(?)). 
Now run sshd in Termux which will Start the SSH-Server. 
Now xou can SSH into your Termux and run archstart from there. 

Note: I am 100% not sure about this and this is just an resemblance oft what I figured out when I tried it a couple weeks ago.

**Comment by sdrausty** [comment]
> Since Termux is a single-user system you may connect as any user - regardless of your specified username you will login as the only Termux user available.

> The Termux sshd binary does not support password logins, so a key needs to be authorized in ~/.ssh/authorized_keys before connecting. Use ssh-keygen to generate a new one if desired.

From https://termux.com/ssh.html
