### ISSUE TITLE
Question:Metasploit in Termux-Arch

### ISSUE THREAD

**Issue by T4P4N** [sdrausty/TermuxArch#89]
Can we use this https://Auxilus.github.io/metasploit.sh script in termux arch?. As much i know metasploit in not available in arch via pacman. So Is there any way to install it in termux arch?

**Comment by Hax4us** [comment]
`pacman -S metasploit`

**Comment by T4P4N** [comment]
I said [As much i know metasploit in not available in arch via pacman]

**Comment by T4P4N** [comment]
I also don't want to install metasploit from blackarch or archstrike. I want that from arch user repository

**Comment by sdrausty** [comment]
@T4P4N https://github.com/Hax4us/Metasploit_termux

**Comment by sdrausty** [comment]
> So Is there any way to install it in termux arch?

Why?   Share your thoughts.
