### ISSUE TITLE
How to make full backup of my arch folder? 

### ISSUE THREAD

**Issue by peterwilli** [sdrausty/TermuxArch#90]
Hi there,

I like your tool and am using it a lot. I'd like to make a full backup in the sense that I can fully restore it when my installation is broken. 

It happened to me quite a lot that I accidentally break everything and have to completely reinstall and install my favorite tools.

Is this possible? Couldn't find anything about it. For now I just tar.gz'ed my arch folder but it gave me some errors about permission denied.

I'm typing this on my phone right now so I can't really give much more details, thanks!

**Comment by sdrausty** [comment]
```
arch/usr/lib/initcpio/hooks/lvm2
arch/usr/lib/initcpio/hooks/udev
arch/usr/lib/initcpio/hooks/mdadm
arch/usr/lib/initcpio/hooks/encrypt
arch/usr/lib/initcpio/install/
arch/usr/lib/initcpio/install/lvm2
arch/usr/lib/initcpio/install/sd-lvm2
arch/usr/lib/initcpio/install/systemd
arch/usr/lib/initcpio/install/udev
arch/usr/lib/initcpio/install/mdadm
arch/usr/lib/initcpio/install/mdadm_udev
arch/usr/lib/initcpio/install/sd-encrypt
arch/usr/lib/initcpio/install/encrypt
arch/usr/lib/libkrb5support.so.0.1
arch/usr/lib/liblber.so.2
arch/usr/lib/libz.a
arch/usr/lib/libkrb5support.so
arch/usr/lib/coreutils/
arch/usr/lib/coreutils/libstdbuf.so
arch/usr/lib/libfdisk.so.1.1.0
arch/usr/lib/libext2fs.so.2.4
arch/usr/lib/libstdc++.so
arch/usr/lib/libgmp.so.10
arch/usr/lib/libmenuw.so
arch/usr/lib/libstdc++.so.6.0.25
^C
$ tar -czvf arch.tar.gz arch/
```
`tar -czvf arch.tar.gz arch/` should do what you want well.
