### ISSUE TITLE
Cannot use systemctl

### ISSUE THREAD

**Issue by life2015** [sdrausty/TermuxArch#91]
[11:04 etc ]$ systemctl
bash: systemctl: command not found

**Comment by sdrausty** [comment]
The systemd package is removed by default because it is redundant since Arch Linux works in Termux PRoot.  If it is installed, you get the following message:
```
$ startarch s user systemctl
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
$
```

**Comment by mateuszlewko** [comment]
@SDRausty  So how to run services (like docker) without using systemctl?

**Comment by SDRausty** [comment]
@mateuszlewko as [computer programming is a man-made environment ](https://duckduckgo.com/?q="computer+programming"+"man-made+environment"+site%3A.edu) docker should not be an issue on our devices, but it is:

   * https://github.com/SDRausty/TermuxArch/issues?q=is%3Aissue+docker

   * https://github.com/termux/termux-packages/issues?q=is%3Aissue+docker

**Comment by SDRausty** [comment]
@mateuszlewko see whether adding [proot binds](https://duckduckgo.com/?q="proot"+binds) to startarch helps.  File `/var/binds/fbindexample.prs` has more information.

**Comment by SDRausty** [comment]
The TermuxArch command `csystemctl` installs a `systemctl` replacement that appear to work as expected.

**Comment by SDRausty** [comment]
>docker should not be an issue on our devices

[`udocker` is available;  A basic user tool to execute simple docker containers in batch or interactive systems without root privileges.](https://github.com/indigo-dc/udocker)
