### ISSUE TITLE
Network-tools problems(fping,nmap) 

### ISSUE THREAD

**Issue by thunderbirdtr** [sdrausty/TermuxArch#92]
Hello o/ 

I made a clean **termux arch** install and  made updates also had some minor issue with a pacman/key problem but I get over via this repo "issues" list and archlinux forums(basically google) and I was trying to make some scripts but looks like I cannot use nmap or fping or any other network tool require "interface" because It basically said "there is no interface or If I select and show  wlan0) It still going to no where but when I do via "termux-terminal" It just works and giving me the result we all expected.

![screenshot_20180706-180421_termux](https://user-images.githubusercontent.com/1688848/42386300-cee38a1a-8147-11e8-86e7-e5431a595eb1.jpg)

Still I'm not sure It is a bug based on nmap or problem because of "proot" but it is the case right now

Thank you. 
PS: when I run "ifconfig" It shows wlan0 and other interfaces.

**Comment by sdrausty** [comment]
I don't see any problem with nmap.  It seems to work as expected:
```
$ startarch s user nmap -sV 192.168.1.1
Starting Nmap 7.70 ( https://nmap.org ) at 2018-07-22 12:50 EDT
Nmap scan report for 192.168.1.1
Host is up (0.011s latency).
Not shown: 999 closed ports
PORT   STATE SERVICE VERSION
53/tcp open  domain  dnsmasq 2.51

Service detection performed. Please report any incorrect results at https://nmap.org/submit/ .
Nmap done: 1 IP address (1 host up) scanned in 25.01 seconds
$ 
```
