### ISSUE TITLE
Low performance of openJDK

### ISSUE THREAD

**Issue by PlatonShubin** [sdrausty/TermuxArch#93]
Hello, I successfully managed to install everything including openJDK java 8 and ran a jar-file using it. But performance is extra slow. My phone hardware is quite new and fast but considering multiple stages of arch functioning inside Termux inside Android this is not very surprising.

Maybe I can somehow configure either Termux, arch or JDK to get more of my hardware?

**Comment by sdrausty** [comment]
Can you please send timing information?

**Comment by sdrausty** [comment]
> this is not very surprising.

[Faster than vanilla Termux? Yes, faster by ~0.5s! See 0m8.320s above. Termux PRoot is about 6% faster than Termux. This is statistically significant. How is this possible?](https://github.com/termux/termux-app/issues/603#issuecomment-370002564)

**Comment by Yisus7u7** [comment]
Me a pasado tambien, debe instalar la version mas reciente de java, si instala una, version como java 8 o 9 le ira lento, le sugiero la 10 en adelante
