### ISSUE TITLE
Installation errors | Missing files

### ISSUE THREAD

**Issue by bensh4** [sdrausty/TermuxArch#94]
Tried installing 4 times but throwing the same error all time.

![](https://i.imgur.com/k4mp4m7.png)

![](https://i.imgur.com/xlYLPxA.png)

![](https://i.imgur.com/wjqRNXe.png)

**Comment by FreshMosh** [comment]
Signaturen is unknown trust.
To solve this run "keys" which is a script located in "/root/bin".
It will initialize the pacman keyring and therefor solve such problems.

**Comment by bensh4** [comment]
You mean this command?
`pacman-key --init
pacman-key --populate archlinuxarm`

**Comment by bensh4** [comment]
Yes. We need to --populate key. Then it will work. Anyway it would be nice if you also add this patch to the repo. Then there wouldn't be any feature issues like this. 
Thanks!

**Comment by sdrausty** [comment]
Hopefully https://sdrausty.github.io/TermuxArch/docs/outputarmv720180722.txt shall be of use; Running keys twice resolved armv7 errors.

**Comment by sdrausty** [comment]
This https://github.com/sdrausty/TermuxArch/commit/6c9c119c00c5601bd37c07a2e231c305d4966168 commit should resolve the keyring issue.

**Comment by sdrausty** [comment]
https://sdrausty.github.io/TermuxArch/docs/outputarmv720180724.txt

**Comment by bensh4** [comment]
@FreshMosh we could also do
` pacman-key --init 
 pacman-key --populate archlinuxarm`

**Comment by sdrausty** [comment]
@bensh4 likewise, "Good work!"

https://sdrausty.github.io/TermuxArch/docs/outputarmv720180725.txt 

How can this error be resolved upstream?

**Comment by defendre** [comment]
keys if u yes
