### ISSUE TITLE
glxinfo error

### ISSUE THREAD

**Issue by seanbud** [sdrausty/TermuxArch#96]
I'm new to arch, but trying to learn. I can't seem to get glxgears running. I'm using my android phone which has an aarch64 instruction set. I'm using i3wm, and displaying with the XServer XSDL app from the play store. 

when i run glxgears, or glxinfo i get the same error, 

```
[19:28 ~]$ glxinfo 
name of display: :0 
Error: couldn't find RGB GLX visual or fbconfig 

```
I've read that others have gotten the glxgears working, any idea how i can diagnose / fix this? Can anyone point me in the right direction?
Thanks!

**Comment by sdrausty** [comment]
https://github.com/sdrausty/TermuxArch/issues?q=is%3Aissue+label%3Asocket
