### ISSUE TITLE
utime function not implemented. Need to start systemd?

### ISSUE THREAD

**Issue by jlmess77** [sdrausty/TermuxArch#98]
I am having an issue with yarn that tries to extract files from tar file and got error, wget complains about no utime and probably other tools. I have searched and it looks like it needs to start systemd when runs startarch? I am not sure how to do it? Use systemd-nspawn? Although I have no idea if get systemd running would solve it.

> $ yarn
> yarn install v1.7.0
> [1/5] Validating package.json...
> [2/5] Resolving packages...
> [3/5] Fetching packages...
> error An unexpected error occurred: "https://registry.yarnpkg.com/@types/chai-as-promised/-/chai-as-promised-0.0.31.tgz: ENOSYS: function not implemented, utime '/usr/local/share/.cache/yarn/v1/npm-@types/chai-as-promised-0.0.31-e1e905ea6d971dafcad36560c8f1f7a7d690c5e5/LICENSE'".
> info If you think this is a bug, please open a bug report with the information provided in "/root/theia/yarn-error.log".
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

> $ wget https://registry.yarnpkg.com/@types/tough-cookie/-/tough-cookie-2.3.3.tgz
> --2018-07-23 18:17:26--  https://registry.yarnpkg.com/@types/tough-cookie/-/tough-cookie-2.3.3.tgz
> Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
> Resolving registry.yarnpkg.com (registry.yarnpkg.com)... 2400:cb00:2048:1::6810:1823, 2400:cb00:2048:1::6810:1323, 2400:cb00:2048:1::6810:1a23, ...
> Connecting to registry.yarnpkg.com (registry.yarnpkg.com)|2400:cb00:2048:1::6810:1823|:443... connected.
> HTTP request sent, awaiting response... 200 OK                                         Length: 3451 (3.4K) [application/octet-stream]
> Saving to: ‘tough-cookie-2.3.3.tgz.1’
> 
> tough-cookie-2.3.3.tg 100%[========================>]   3.37K  --.-KB/s    in 0s
> 
> utime(tough-cookie-2.3.3.tgz.1): Function not implemented
> 2018-07-23 18:17:26 (8.27 MB/s) - ‘tough-cookie-2.3.3.tgz.1’ saved [3451/3451]

> $ timedatectl list-timezones
> System has not been booted with systemd as init system (PID 1). Can't operate.
> Failed to create bus connection: Host is down

**Comment by sdrausty** [comment]
`systemd` is removed by default.  If you reinstall it with `pacman -Syu systemd` does this error persist?

**Comment by sdrausty** [comment]
This is an issue with running a Linux distribution in a PRoot environment in Android (eg. SELinux).  If you can get systemd stuff to work in this environment, please post your findings here.

**Comment by sdrausty** [comment]
https://sdrausty.github.io/TermuxArch/docs/outputarmv720180724.txt

**Comment by jlmess77** [comment]
It has been solved in the latest version of proot apt. @michalbednarski added utime workaround https://github.com/termux/proot/commit/0e449b9e46ec849d603b48130a2e7d9181aa3f5a .
